#+title:      R&D-based economic growth in a supermultiplier model
#+date:       [2021-10-25 seg 00:00]
#+filetags:   :bib:
#+identifier: 20211025T000000
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl
#+reference:  nomaler_2021_rdbased



* Backlinks

[[denote:20250202T120807][Innovation bubble ABM]]

[[denote:20250203T184155][Supermultiplier Models]]

[[denote:20240707T182500][Demand-led growth models]]

[[denote:20240708T155455][Schumpeterian growth models]]

[[denote:20250202T120740][Innovation-led growth models]]

[[denote:20250204T193239][Structural Change and Economic Dynamics]]

[[denote:20230628T172800][PhD Dissertation Discussions]]

* FISH-5SS

|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| *Background*                                  | It is argued that SSM only ensure a stable path for both capacity utilization and employment rate if autonomous expenditures and productivity grow at the same pace.                                                                                                                                                                                                                                                                                                                                     |
| *Supporting Ideas*                            | There is no secular instability regarding both capacity utilization and employment rate. They endogenize autonomous consumption using [cite:/t@brochier_2018_Supermultiplier] procedure in which autonomous consumption depends on accumulated wealth. R&D and innovation depends on accumulated knowledge ($R$).                                                                                                                                                                                        |
| *Purpose*                                     | Append the supply-side/Schumpeterian discussion in to SSM and evaluate the consequences for employment rate stability.                                                                                                                                                                                                                                                                                                                                                                                   |
| *Originality/value (Contribution)*            | Include an stable path for both capacity utilization and employment rate in the SSM model by means of R&D. The smooth-consumption mechanism implies a wealth-financed consumption increase whenever actual employment rate is bellow the "satisfactory" level since labour income will decrease as a consequence. Thus, households need to use their wealth to finance its consumption.                                                                                                                  |
| *Relevance*                                   | Provides some discussion about the role of R&D and innovation in the SSM agenda.                                                                                                                                                                                                                                                                                                                                                                                                                         |
| *Design/methodology/approach*                 | Both numerical and analytical solve with stability analysis.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| *Results*                                     | Model is governed by supply-side variables in which demand-side elements provide the stability conditions. These results are virtually the same if the autonomous consumption come from private or government sector. The consumption adjustment mechanism are crucial for model stability.                                                                                                                                                                                                              |
| *(Interesting) Findings*                      | No empirical finding or any results at odds with the debated literature.                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Research limitations/implications (Critics)* | Autonomous expenditures (consumption in this case) play no role and the model is determined by supply-side variables. Besides the mathematical validity of the results, it is not consistent with the demand-led growth agenda. No further discussion about "satisfactory" employment rate. The no-public debt assumption impose a lot of restrictions to the model while generates an (unintend) crowding-out effect (since tax increase to finance government consumption reduce private consumption). |
| *Uncategorized stuff*                         | Provide some interesting stability check using Mathlab. Regarding this stability analysis, adjustment parameter in investment share ($\gamma$) and consumption smoot ($\iota$) play a crucial role.                                                                                                                                                                                                                                                                                                               |
| *5SS*                                         | The authors propose a R&D-led SSM model in which autonomous expenditures play no active role while consumption smooth mechanism provides the stability for the model.                                                                                                                                                                                                                                                                                                                                    |
|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|


** Abstract

#+BEGIN_ABSTRACT
We investigate how economic growth in a demand-driven economy with semi-endogenous productivity growth can be compatible with a stable employment path. Our model uses a Sraffian supermultiplier (SSM), and we endogenize the growth rate of autonomous demand, and semi-endogenize productivity growth. The basic model has a steady state that is consistent with a stable employment rate, and in which the growth rate is determined by R&D expenditures. Consumption smoothing (between periods of high and low employment) by workers is the mechanism that ensures that demand keeps up with productivity growth and that the growing economy is stable. We also introduce a version of the model where the burden for stabilization falls upon government fiscal policy. This also yields a stable growth path, although the parameter restrictions for stability are more demanding in this case.
#+END_ABSTRACT



* Specifics comments
:PROPERTIES:
:NOTER_DOCUMENT: /HDD/PDFs/Nomaler_et_al_2021_R&D-based.pdf
:END:


** Notes extraction

"Consumption smoothing (between periods of high and low employment) by workers is the mechanism that ensures that demand keeps up with productivity growth and that the growing economy is stable." (Nomaler et al 2021:1)

"These bounds imply sizeable shortto medium-run fluctuations, but not secular instability. Hence a dynamic theory of demand and growth must reflect this relative stability." (Nomaler et al 2021:2)

"The choice for the supermultiplier model is primarily a convenience choice: the SSM model already generates a stable growth path for the rate of capacity utilization" (Nomaler et al 2021:3)

"SSM model can only generate a stable employment rate if the exogenous rates of growth of labour productivity and of autonomous spending are equal to each other" (Nomaler et al 2021:3)

"Usually, they simply assume that output is equal to capacity output, which, implicitly, calls Say's Law to working" (Nomaler et al 2021:3)

"magnitude of the growth rate is determined by supply-side parameters related to R&D and technical change" (Nomaler et al 2021:3)

"Brochier & Silva (2019) link autonomous consumption to the accumulated wealth of the workers, which is an approach that we will follow." (Nomaler et al 2021:5)

"Palley (2019) assumes that productivity is sensitive to the employment rate. When the employment rate increases, productivity growth increases, because of learning effects, and when the employment rate falls, the productivity growth rate falls accordingly." (Nomaler et al 2021:5)

"These R&D-based models, including the model we will present below, are rooted in the neo-Schumpeterian evolutionary tradition, which mainly looks at technology as a supply phenomenon (something that it shares with the mainstream growth theory)." (Nomaler et al 2021:5)

"The inclusion of productivity growth is also often done by adding a Kaldor-Verdoorn learning effect (Allain, 2019; Brochier, 2020; Deleidi & Mazzucato, 2019; Nah and Lavoie, 2019b), in which, because of learning by doing, productivity growth depends (positively) on the capital accumulation rate or on the growth rate of output" (Nomaler et al 2021:6)

"Finally, the supply of labour has also been proposed as endogenous. Fazzari et al. (2020) and Nah & Lavoie (2019a) argue that labour supply growth reacts to the employment rate, with high (low) employment rates causing faster (slower) growth of the labour force" (Nomaler et al 2021:6)

"(8)" (Nomaler et al 2021:8)

"푍ith both of 퐾 푍ady state with both capital utilization and employment constant (and positive)." (Nomaler et al 2021:9)

"Productivity change depends on the accumulated knowledge stock (not just on current R&D activities), and hence we introduce an R&D-capital stock (denoted by R). We follow the empirical literature that addresses the relation between R&D and productivity (see, e.g., Hall et al., 2010) in assuming that R evolves as a stock in the same way as fixed capital" (Nomaler et al 2021:9)

[Important] R&D depends on knowledge stock (R&D Capital stock) (note on p.9)
"Finally, we again follow the empirical literature in assuming that productivity growth results from R&D intensity (in our case intensity relative to the capital stock), more specifically," (Nomaler et al 2021:10)

[HYPOTHESIS] Labour productivity depends on R&D intensity. (note on p.10)
"that the magnitude of the growth rate will become dependent on the R&D parameters (which are all supply side). However, demand will still play an important role in the model because without demand adjustment, the growth path cannot be stable." (Nomaler et al 2021:10)

[RESULT] This is a supply-side SSM in which demand-side is argue to have a stabilizing effetct. (note on p.10)
"푔푍 is that private autonomous consumption depends on accumulated wealth." (Nomaler et al 2021:10)

gZ in endogenized as in Brochier and Silva. (note on p.10)
"푤 푊 depreciation of wealth. This arises from the specific setup of the model, explained in more detail in the appendix, in which total accumulated wealth in the economy is equal to the sum of the productive capital stocks (both R&D capital R and fixed capital K)." (Nomaler et al 2021:11)

See: Why the need for an wealth depreciation. It seems required for R&D and capital depreciation rate are the same. (note on p.11)
"Here 휁푤 is a new variable that represents the (marginal) propensity to consume out of accumulated workers' savings, and similarly 휁푝 is a parameter that represents the marginal propensity to consume out of profit earners' assets." (Nomaler et al 2021:11)

Following Brochier and Silva, autonomous consumption depends on a share of households wealth. (note on p.11)
"Our assumption is also that the variable 휁푤 is a behavioural variable that serves to smooth (autonomous)" (Nomaler et al 2021:11)

Next, they endogenize this consumption parameter that will smooth consumption according to changes in employment rate. (note on p.11)
"Here 휄 and 퐸 are parameters (both >0). 퐸 specifies a neutral rate of employment at which current wage income is considered satisfactory. When the employment rate drops below 퐸, current labour income also falls below the satisfactory level (remember we assume a fixed real wage rate), and workers have to "compensate" by drawing to a larger extent on their accumulated wealth for consumption." (Nomaler et al 2021:12)

Them, they employ an adjustment procedure simular to h (replacing u for E) and stablish thatn when employment rate is lower, consumption will be more financed out of wealth since real wages will fall as a consequence; increasing the consumption out of wealth (in relative terms). (note on p.12)
"We adopt the 푤 Kim et al., 2014) for the idea specified by equation (13), which is a key mechanism in our model that proves to provide stability to the growth path in terms of ensuring a stable employment rate." (Nomaler et al 2021:12)

This behaviour smooth-consumption mechanism is what proved stability to the model. (note on p.12)
"It is easy to see how equation (13) has the potential to stabilize the economy. If employment falls below the neutral value (퐸), autonomous consumption will tend to increase (푊푤 will be fixed initially, while 휁푤 increases), and ceteris paribus the multiplier, GDP will increase, bringing the employment back towards the neutral rate 퐸. Note that such stabilization works exclusively through quantity adjustment" (Nomaler et al 2021:12)

[EXAMPLE] How this mechanism provides stability: E < normal E -> Z increase -> multiplier change -> Y increase -> ... -> stability. (note on p.12)
"Demand-side parameters, such as 푐푤, 퐸 or even 휎 do not enter the expression for the long-run growth rate of the economy. What happens is that 푔푍 (the demand side) adjusts to the growth rate of productivity. This also implies that the endogenization of the demand side (푔푍) is crucial for the existence and stability of a steady state. In fact, we could keep the rate of productivity growth completely exogenous (e.g., 휑 = 0), and, as long as we keep the endogenization of 푔푍, the steady state of the model would still exist." (Nomaler et al 2021:15)

[RESULT] The model is stable, however, gZ is endogenized towards growth rate of productivity. (note on p.15)
"Inspection of the results of the grid search suggests that the parameters 휄 and 훾 play a crucial role in stability. In particular, we need a minimum value of the ratio 휄 훾 for the steady state to be stable." (Nomaler et al 2021:17)

[RESULT] h and E adjustment parameter play a crucial role. (note on p.17)
"The marginal propensities to consume (or save) for workers and profit earners are applied to total income, i.e., to the shares of GDP as specified in the previous paragraph." (Nomaler et al 2021:19)

Now on, the consumption function changes. Marginal propensity to consume is applied to the total income. (note on p.19)
"In order to consider the model with a government, we will make one major simplification to the model as considered so far: we will no longer distinguish between workers and profit earners in the private sector." (Nomaler et al 2021:21)

Now on, private sector is aggregated and smooth consumption parameter is considerd fixed. (note on p.21)
"First, we assume that government spending is proportional (by 휁퐺) to the private wealth variable W:" (Nomaler et al 2021:22)

As before, autonomous consumption is a share of total wealth while the martinal propensity to (autonomous) consume is reuled by discrepancies in desired and effective employment rate. However, this smooth mechanism is now regarded as a stabilation mission by the government. (note on p.22)
"In what follows, we will set 퐷 government aims to have no debt in the long run (the model that we analyze is a balanced budget supermultiplier model)." (Nomaler et al 2021:22)

The authors impose that government intend to have no debt, so it is a balanced budget supermultiplier model. (note on p.22)
"Thus, any positive effects on GDP and employment from increasing 휁퐺 will be offset by an increasing tax rate. If the tax effect is immediate, fiscal policy will become ineffective in stabilizing the economy." (Nomaler et al 2021:24)

Since government will have no debt, there is a crowding-out effect as a result of tax increase in order to finance govern consumption increase. (note on p.24)
"overnment stabilization using fiscal policy is harder than with the private consumption smoothing stabilizer in the previous sections" (Nomaler et al 2021:24)

[RESULT] Fiscal policy mechanism is less stable than private smoothing channel. (note on p.24)
"where the government runs a temporary deficit (surplus) if the unemployment rate is high (low) and raises taxes to keep its long-run debt within bounds." (Nomaler et al 2021:27)

The version with government spending have a temporarily defict/surplus followed by and increase/decrease of tax rate in order to stabilize government debt. (note on p.27)
"Thus, while we considered R&D investment as a fraction of GDP as a fixed parameter, there is scope to consider it as an endogenous variable. This could be done both by making R&D dependent on other macroeconomic variables, such as (expected) profits (as in the endogenous growth literature, e.g., Aghion & Howitt, 1992), or by a behavioral approach that considers R&D at the firm level as resulting from imitation and behavioral mutation (as in Silverberg and Verspagen, 1994)." (Nomaler et al 2021:28)

[WRITING] THey suggest that R&D expenditures could be endogenized as in neo-Schumpeterian literature. This could be a friendly way to cite them. (note on p.28)
"On the other hand, the introduction of a more detailed way of modelling the financial sector would also enhance the degree of realism of the model. This would not only allow the modelling of the (de-)stabilizing effects of finance, but also the inclusion of monetary policy by the government." (Nomaler et al 2021:28)

[WRITING] Other way to improve in provide a fully SFC model. (note on p.28)

** Relevant equations

#+BEGIN_latex
\begin{equation}
g_{E} = g_{Z} + \frac{\Delta h}{1 - c - h} - \rho
\end{equation}
#+END_latex
in which $g_{E}$ is employment growth rate while $\rho$ is productivity growth rate.
When $g_{Z} \neq \rho$, there is no stable path for both capacity utilization and employment rate.

R&D is defined as a share of GDP:
#+BEGIN_latex
\begin{equation}
\Theta = \tau\cdot Y
\end{equation}
#+END_latex

Latter, the authors present an innovation function that depends both on a exogenous parameter and R&D:
#+BEGIN_latex
\begin{equation}
\rho = \overline \rho + \phi\cdot\Theta
\end{equation}
#+END_latex

The consumption smooth mechanism is proposed as follows:
#+BEGIN_latex
\begin{equation}
Z = \zeta W
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
\Delta \zeta = \iota\zeta(\overline{E} - E)
\end{equation}
#+END_latex

* Bibliography


#+print_bibliography:
