:mtime:    20211202152742 20211013082514
:ctime:    20211013082514
:END:
#+TITLE: lavoie_2020_Was: Was Hyman Minsky a post-Keynesian economist? (2020, Review of Evolutionary Political Economy)
#+OPTIONS: toc:nil num:nil
#+filetags: High_Impact Financial_Instability_Hypothesis Finance Housing Minsky
Time-stamp: 2021-03-02


* Backlinks


[[denote:20230216T235200][Minskian theory]]

[[denote:20230216T235201][Investimento, fluxo de caixa e dinâmica da alavancagem: regime minskiano ou paradoxo da dívida?]]


* FISH-5SS


|---------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                                    |
| *Background*                                  | HIF; Loanable funds approach; Endogenous money debate; SFC; MMT                                                                                                                                                         |
| *Supporting Ideas*                            | Real estate and household debt seems to be more relevant than usually attributed; Leverage is not pro-cyclical; Inflation is not a result of excess demand; Loanable funds theory is at odds Effective Demand Principle |
| *Purpose*                                     | Present both Minsky's contributions and its flaws in order to prevent researchers to repeat them                                                                                                                        |
| *Originality/value (Contribution)*            | Summarizes Minsky's proposition and its limitations                                                                                                                                                                     |
| *Relevance*                                   | Include references to some debates in the frontier                                                                                                                                                                      |
| *Design/methodology/approach*                 | Review of literature                                                                                                                                                                                                    |
| *Results*                                     | Besides some controvertial, Minsky *Is* a PK author who had contributed to a long range of topics                                                                                                                         |
| *(Interesting) Findings*                      | The author indicates McCulley (2009) work in which Minskian typology is applied to mortgage finance                                                                                                                     |
| *Research limitations/implications (Critics)* |                                                                                                                                                                                                                         |
| *Uncategorized stuff*                         | There are some sentences of Minsky about a long range of topics.                                                                                                                                                        |
| *5SS*                                         |                                                                                                                                                                                                                         |
|---------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: lavoie_2020_Was
 :AUTHOR: Lavoie, M.
 :JOURNAL: Review of Evolutionary Political Economy
 :YEAR: 2020
 :DOI:  http://dx.doi.org/10.1007/s43253-020-00002-7
 :URL: https://doi.org/10.1007/s43253-020-00002-7
 :END:


The most relevant finding in this paper is the following quote about textcite:mcculley_2010_Shadow (note on p. 7):

#+begin_quote
McCulley (2009), a former managing director at PIMCO, defined standard mortgages, amortized over at a fixed interest rate over a long period as hedge finance.
He defined interest-only mortgages, with borrowers not paying back the principal, as speculative finance.
Mortgages with negative amortization mortgages—the so-called 2/28 mortgages—are equivalent to Ponzi finance.
#+end_quote


* Extracted Annotations (02/03/2021 15:23:16)
:PROPERTIES:
 :NOTER_DOCUMENT: ~/Zotero/storage/433GLTV6/Lavoie - 2020 - Was Hyman Minsky a post-Keynesian economist.pdf
:NOTER_PAGE: 1
 :END:

"a number of authors have shown the similar visions of Minsky and Schumpeter, with both seeing capitalism as an evolutionary process, associated with disequilibria rather than equilibrium, and with bank credit playing a fundamental role (Ülgen 2014). According to O'Hara (2007)" (Lavoie 2020:2)

[REF] Similarities between Minsky and Schumpeter (note on p.2)

"My ambition in this paper is to show that while Minsky is an unavoidable reference for all those who associate themselves with a political economy approach, from the standpoint of contemporary post-Keynesian economics there are some weaknesses in his works. These must be recognized, in the hope that newcomers to heterodox or postKeynesian economics will avoid these oversights rather than repeat them." (Lavoie 2020:3)

[PURP] Purpose of the paper (note on p.3)

** The bright side of Minsky

*** General features

"The difference between Keynes and Minsky is that for the former, disequilibria push economic activity downward, whereas the latter argued that "we are dealing with a system that is inherently unstable, and the fundamental instability is upward" (Minsky 1975, p. 165)." (Lavoie 2020:4)

Some discrepancies between Minsky and Keynes. (note on p.4)

"One implication of this insight is that as soon as an economic unit runs into financial difficulties and must sell some of its assets in an attempt to avoid financial distress and default on its payments, this will have feedback effects on the organizations whose financial assets are the liabilities of this distressed economic unit. There thus can be a cumulative tide of financial problems, leading to a general debt deflation." (Lavoie 2020:4)

Implications of SFC side of Minsky. (note on p.4)
*** Specific features

"Minsky (1986a, p. 117) when he argued that in the context where "speculative and conjectural elements are powerful, the principle of substitution does not always apply." As a consequence, "a rise in the relative prices of some set of financial instruments or capital assets may very well increase the quantity demanded of such financial or capital assets."" (Lavoie 2020:5)

Positively sloped curve of financial asset and its prices. (note on p.5)

"There are a few additional gems that can be extracted from Minsky's books. Minsky (1986a, pp. 174-5) makes the distinction between direct labor and overhead labor." (Lavoie 2020:5)

Other Minskians colaborations: difference between direct and overhead labor. (note on p.5)

"Associated with Wall Street capitalism, as noted by others, Minsky (1986b, 1987, 1991a) identified very early on the potential development and dangers of securitizing bank loans. Minsky saw securitization as an innovation reducing reserve requirements, thus enhancing the impotence of central banking, and mostly as an innovation that drastically cuts down on the need for bank capital." (Lavoie 2020:5)

Some antecipations regarding securitization and financial inovation -> reducing capital requiriments. (note on p.5)

"The most explicit description of the dangers of securitization is to be found in Minsky (1986b, p. 14), with the integrity of the new originate and distribute banking model being dependent "upon the wisdom and integrity" of all the involved institutions. Minsky (ibid) feared that "fraud and incompetence will intrude in the long chain of securitization," in which case contagion reactions on a significant scale could occur, with the lender of last resort being "exposed to greater risk."" (Lavoie 2020:5)

[REF] Minsky about securitization. (note on p.5)

"On Minsky's financial instability hypothesis, I will only recall some of his most clever quotes on the topic. The crux of the hypothesis is the paradox of tranquility, which can be summarized as stability is destabilizing." (Lavoie 2020:5)

[TOPIC] HIF and paradox of tranquility (note on p.5)

"Minsky (1975, p. 166) also expressed what today we would call ecological concerns. He saw the potential conflict between the goal of full employment and that of sustainable growth. He objected to "the scheme of perpetual waste and want" and to the "fruitless inflationary treadmill, accompanied by what is taken to be deterioration in the biological and social environment." He called for "a state of disciplined wants, a stable population, and a lifting of the burdens of war," realizing however that the "disciplined-wants requirement is furthest from sight" (ibid, p. 155), as it has been observed until now with the resistance with which many consumers tend to oppose carbon taxes." (Lavoie 2020:6)

[REF; TOPIC] Minsky on ecological issues (note on p.6)

** The dark side of Minsky

*** The FIH deals with firms: what about households?

"The first issue is directly related to the financial instability hypothesis. Minsky focused on banks and firms, as did nearly all his followers until the subprime financial crisis. Households do not enter the picture in his two major books, although Minsky notes that households also face cash flow constraints. There is substantial evidence that real estate investment is the key driver of business cycles, at least in the USA (Fiebiger 2018)." (Lavoie 2020:6)

FIH is mainly about firms and banks; households were out until the GFC (note on p.6)

"First in his 1964 American Economic Review article, Minsky (1964b, p. 328) draws a 2- dimensional graph where instability depends on both the business and household debt to income ratio. Second, as Jan Kregel pointed out to me, Minsky (1964b, pp. 180-181) did refer to events that look like those of the subprime financial crisis: "At present real estate assets seem to be a more important source of financial distress than stock exchange assets...real assets are collateral for an extensive amount of debt, both of households and of business firms, owned by financial institutions.... If the price or real estate should fall very sharply, not only will the net worth of households and business firms be affected, but also defaults, repossessions, and losses by financial intermediaries would occur." Third, when Minsky (1984) explains the events that led to the Great Depression, he does mention household debt, and especially household mortgages, and the fact that at the time mortgages had to be periodically refinanced." (Lavoie 2020:7)

[REF] Minsky about household debt and real estate. (note on p.7)

"McCulley (2009), a former managing director at PIMCO, defined standard mortgages, amortized over at a fixed interest rate over a long period as hedge finance. He defined interest-only mortgages, with borrowers not paying back the principal, as speculative finance. Mortgages with negative amortization mortgages—the so-called 2/28 mortgages—are equivalent to Ponzi finance." (Lavoie 2020:7)

[REF] Minsky tipology extended to mortgage:

- Standard mortgage with fixed interest rate <-> hedge
- Interest-only <-> Speculative
- Negative amortizat\ion mortgages (2\28) <-> Ponzi finance (note on p.7)

*** A missing macroeconomic link?

"Under the strict assumption of a given level of internal funds, the higher investment that would be associated with more optimistic entrepreneurial expectations must inevitably result in higher debt and leverage ratios. These particular analytics of the financing unit are then largely generalized to the overall economy without, unfortunately, a careful consideration of the link between his micro and macro frameworks of analysis." (Lavoie 2020:7)

Minsky composition fallacy (note on p.7)
*** Rising interest rates before the crisis?

"Minsky's explanation of financial crises also relies on rising interest rates. One can easily grant that interest rates could be rising in the boom because the central bank fears inflation and wishes to slow down the economy, thus taking the policy decision to raise interest rates. But, Minsky believes that rising interest rates is a natural phenomenon, which happens independently of the behavior of the central bank." (Lavoie 2020:8)

Minskian turning point depends on increase in interest rate as a result of an economic (not political) mechanism. (note on p.8)

"Minsky's past reliance on a loanable funds approach appears most clearly when he claimed in 1957 that "the excess of ex ante saving over induced investment will be utilized to reduce bank debt" (Minsky 1982, p. 243). This assertion is reproduced by the balance sheets used by Minsky (1982, fn. 18) in the case of a downswing. In the Kalecki-Keynes framework, any excess of saving over investment will lead to unsold production—the Marxian profit realization problem—and hence to increases in debt for producers." (Lavoie 2020:9)

Minsky rely on loanable funds approach. (note on p.9)
*** Endogenous money: financial innovation versus reverse causation

"Minsky has an approach to endogenous money that relies essentially on banking and financial innovations and a variable velocity of money. The supply of reserves by the central bank is seen as the main constraint to loan creation. Authors backing Minsky's financial instability hypothesis have usually also endorsed his view of endogenous money based on financial innovations." (Lavoie 2020:9)

Minskian monetary view depends on financial innovations, variable velocity of money while reserves are the main constraint to loan creation. (note on p.9)
*** Inflation and cost theory

"Minsky makes the same mistake as Augusto Graziani, the leader of the Italian school of circuit theory. They both use the same equations that assume that production, and hence capacity utilization, in the consumption good sector is a given and cannot be increased. Hence any increase in the share of employment of the investment sector or of the government sector must necessarily lead to an increase in the rate of inflation of consumer prices according to Graziani and Minsky (1986a, p. 285)" (Lavoie 2020:10)

Inflation is excess of demand according to Minsky since production is given. (note on p.10)

*** A new controversy

"It is indeed puzzling to read Minsky on this issue. On the one hand, Minsky (1986a, p. 39) argues vehemently that "government debt is free of default risk; whatever the government debt contract says will be forthcoming will, in fact, be forthcoming." MMT authors usually recall that this claim is valid as long as the debt of the government is issued in its own domestic currency. On the other hand, in a later paper, Minsky (1991b, p. 166) seems to take an entirely different position: "There is nothing in principle nor in the facts of an economy with debts that says that the United States cannot become an Argentinaa country whose debts, whether denominated in its own or in foreign currency, are not marketable."" (Lavoie 2020:11)

Minsky MMT dualism: somethines functional finance, in others, sound finance. (note on p.11)
** Post-Keynesian or not?

*** Feelings

"All of this is rather puzzling for those able to take a step back. Both Minsky and Davidson have attached great importance to radical uncertainty, both have been critical of other post-Keynesians for having omitted monetary and financial considerations, as well as liquidity problems, both made use of Marshallian U-shaped cost curves, and both independently designed an investment theory that showed a large degree of affinity with Tobin's q-theory." (Lavoie 2020:12)

Similarities between Minsky and Davidson, besides the latter stated that the former is not a PK economist. (note on p.12)

*** Facts
"The key elements of post-Keynesian economics as he describes are money really matters; financial flows and debt validation; expectations; the Kaleckian profit equation; complex system dynamics (multi-dimensional, non-linear, time-dependent business cycles). These are all elements that modern post-Keynesians would approve of." (Lavoie 2020:13)

Elements of PK school according to Minsky. (note on p.13)
