:mtime:    20211202152743 20211013082514
:ctime:    20211013082514
:END:
#+TITLE: internationalmonetaryfund.reseachdept._2008_changing: The changing housing cycle and the implications for monetary policy (2008)
#+OPTIONS: toc:nil num:nil
#+filetags: Business_cycle Monetary_Policy Institucions QCA Data
Time-stamp: 2021-02-23
- tags ::


* Backlinks

[[denote:20210210T185414][QCA Data]]
[[denote:20210210T191246][Panel Data]]
[[denote:20210216T121647][QCA Theoretical Economics Foundations]]

* FISH-5SS

|---------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| *Background*                                  | Recent GFC housing boom episode. Theoretical background: some scholars stated that housing relevance has weakened due to household smooth consumption as a decorence of easier credit access. Deregulation had promoted more credit access due to the removal of interest rate ceilings and quantitative limits.                                                                                                                                                                                                                            |
| *Supporting Ideas*                            | The is an implicit mechanism from increasing competition in mortgage markets and easing credit lending policies (more access to mortgage): increasing diversity of funding sources; lender types and loan products. The spill-over mechanism from housing sector to the economy is due to consumption spending related to wealth effects. Housing is both a source of volatility and transmits monetary shocks.                                                                                                                             |
| *Purpose*                                     | Examined how innovation in *housing finance* affected the role of housing sector in the business cycles and monetary transmission mechanism.                                                                                                                                                                                                                                                                                                                                                                                                  |
| *Originality/value (Contribution)*            | Evaluate whether institutional elements explain how housing finance changes generated a higher spill-over effect from housing sector to overall economy.                                                                                                                                                                                                                                                                                                                                                                                    |
| *Relevance*                                   | Establishes the links between housing finance and business sector (Panel). Presents some institutional particularities in housing sector that are still resilience (QCA). Create an index that summarizes the characteristics of cross-country differences (the higher, more household access to mortgage debt).                                                                                                                                                                                                                            |
| *Design/methodology/approach*                 | Var for Real house prices; residential investment and other key macroeconomic and monetary policy variables                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Sample*:                                     | 18 developed countries (1970-2006)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| *Results*                                   | The link between housing section and overall economy was strainted by the increasing use of housing as collateral, increasing consumption after house price increase (financial accelerator effect). Monetary policy transmitions affects occurs throught house prices and not more by residential investment changes. Do not propose a change of how monetary policy should work, but advocate for more flexibility.                                                                                                                       |
| *(Interesting) Findings*                    | Present a way to estimate housing bubbles measured in terms of gap between actual prices and fundamentals (box 3.1, p. 113-116). The link between housing sector and business cycle is greater the more developed mortgage market is (note on p.123)                                                                                                                                                                                                                                                                                        |
| *Research limitations/implications (Critics)* | Estimations based on qualitative date with quantitative-only method. Additionally, the proposed index has a small role in the analysis (almost only correlations).                                                                                                                                                                                                                                                                                                                                                                          |
| *Uncategorized stuff*                         | Presents the timing and background of deregulation in some countries. The deregulation analysis may support the idea of convergence in housing finance sector. This paper provided an temporary hypothesis (QCA): the higher access to mortgage debt, the higher mortgaging value will be. Presents some stylized facts (Panel). The housing cycles has becoming more unusual: more volatile with higher amplitude. House price increases have a direct redistributive effect (between households) and an indirect aggregate demand effect. |
| *5SS*                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|---------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: internationalmonetaryfund.reseachdept._2008_changing
 :AUTHOR: Dept., I. M. F. R.
 :JOURNAL:
 :YEAR: 2008
 :DOI:
 :URL: https://www.elibrary.imf.org/view/IMF081/07980-9781589067196/07980-9781589067196/ch03.xml?lang=en&redirect=true
 :END:


#+CAPTION: Directional expectations
|-----------------------+------------------------------------------------------------+----------------------------------|
| Variable              | Expectations                                               | Representation                   |
|-----------------------+------------------------------------------------------------+----------------------------------|
| LTV ratio             | The higher, more access to mortgage debt                   | LTV -> Mortgaging                |
| Repayment-terms       | Keep debt-service-to-income more affordable                | REPAY -> Mortgaging              |
| Home equity withdraw  | More capacity to borrow                                    | WITHDRAW -> HHDebt -> Mortgaging |
| Early payment         | Refinance mortgage debt in the event interest rate decline | EARLY -> Access -> Mortgaging    |
| Secondary Market Loan | Easier to funding via capital markets                      | SECOND -> Access -> Mortgaging   |
|-----------------------+------------------------------------------------------------+----------------------------------|


#+CAPTION: Table 3.1 - Institutional Differences in National Mortagage Markets and the Mortgage Market Index
|----------------+--------------------------+-------------+-----------------------------+------------------------------+---------------------+---------------------------------+-----------------------|
| Country        | Mortgage Equity Withdraw | Refinancing | Typical Loan-to-Value ratio | Average typical term (years) | Covered Bond issues | Mortgage-backed security issues | Mortgage Market Index |
| <10>           | <10>                     | <10>        |                        <10> |                         <10> |                <10> |                            <10> |                  <20> |
|----------------+--------------------------+-------------+-----------------------------+------------------------------+---------------------+---------------------------------+-----------------------|
| Australia      | Yes                      | Limited     |                          80 |                           25 |                   - |                             7.9 |                  0.69 |
| Austria        | No                       | No          |                          60 |                           25 |                 2.2 |                               - |                  0.31 |
| Belgium        | No                       | No          |                          83 |                           20 |                   - |                             1.9 |                  0.34 |
| Canada         | Yes                      | No          |                          75 |                           25 |                   - |                             3.6 |                  0.57 |
| Denmark        | Yes                      | Yes         |                          80 |                           30 |                58.5 |                             0.1 |                  0.82 |
| Finland        | Yes                      | No          |                          75 |                           17 |                 2.6 |                               - |                  0.49 |
| France         | No                       | No          |                          75 |                           15 |                 1.6 |                             1.0 |                  0.23 |
| Germany        | No                       | No          |                          70 |                           25 |                 3.6 |                             0.2 |                  0.28 |
| Greece         | No                       | No          |                          75 |                           17 |                   - |                             6.2 |                  0.35 |
| Ireland        | Limited                  | No          |                          70 |                           20 |                 4.0 |                             6.6 |                  0.39 |
| Italy          | No                       | No          |                          50 |                           15 |                   - |                             4.7 |                  0.26 |
| Japan          | No                       | No          |                          80 |                           25 |                   - |                             4.7 |                  0.39 |
| Netherlands    | Yes                      | Yes         |                          90 |                           30 |                 0.7 |                             4.6 |                  0.71 |
| Norway         | Yes                      | No          |                          70 |                           17 |                   - |                               - |                  0.59 |
| Spain          | Limited                  | No          |                          70 |                           20 |                11.1 |                             5.7 |                  0.40 |
| Sweden         | Yes                      | Yes         |                          80 |                           25 |                10.1 |                             0.9 |                  0.66 |
| United Kingdom | Yes                      | Limited     |                          75 |                           25 |                 0.9 |                             6.4 |                  0.58 |
| United States  | Yes                      | Yes         |                          80 |                           30 |                   - |                            20.1 |                 0.98  |
|----------------+--------------------------+-------------+-----------------------------+------------------------------+---------------------+---------------------------------+-----------------------|

* Extracted Annotations (23/02/2021 12:08:11)
:PROPERTIES:
:NOTER_DOCUMENT: ../../PDFs/international_monetary_fund._reseach_dept._2008_the_changing.pdf
:NOTER_PAGE: 146
 :END:
monetary policy transmission mechanism." (International Monetary Fund. Reseach Dept. 2008:122)

Purpose of the chapter: inovations in housing finance -> new role of housing -> business sector (note on p.122)




"concludes that these changes have broadened the spillovers from the housing sector to the rest of the economy and have amplified their impact by strengthening the role of housing as collateral." (International Monetary Fund. Reseach Dept. 2008:122)

Main result: broaden the housing spillover <- housing as colateral (note on p.122)




"he recent booms in house prices and residential investment in many advanced economies," (International Monetary Fund. Reseach Dept. 2008:122)

Background: recent GFC (note on p.122)




"Some authors advanced the hypothesis that these changes have weakened the link between housing and the business cycle—for example, easier access to credit allows households to better smooth temporary downturns in income (Dynan, Elmendorf, and Sichel, 2006)." (International Monetary Fund. Reseach Dept. 2008:122)

Some scholars states that these changes have weakened the links between housing sector and business cycle. (note on p.122)




"explores the implications for the conduct of monetary policy." (International Monetary Fund. Reseach Dept. 2008:122)

Contribution: explore its implications for monetary policy (note on p.122)




"Has there been a change in the housing sector's contribution to the business cycle in advanced economies over the past two decades? Are crosscountry differences in the role of the housing sector in the business cycle related to the institutional characteristics of national mortgage markets?" (International Monetary Fund. Reseach Dept. 2008:122)

Questions adressed.
The 2nd is more relevant for QCA chapter: does institutional particularities affects theses changes? (note on p.122)




"uses a methodology that formally identifi es the housing sector as both a source of volatility and a channel through which other shocks are transmitted to the broader economy." (International Monetary Fund. Reseach Dept. 2008:123)

Methodology: broad cross-country comparison; housing sector is a source of both *volatility* and a *transmission channel* (note on p.123)




"First, the increased use of homes as collateral has amplifi ed the impact of housing sector activity on the rest of the economy by strengthening the positive effect of rising house prices on consumption via increased household borrowing—the "fi nancial accelerator" effect." (International Monetary Fund. Reseach Dept. 2008:123)

How changes affects 1: financial accelerator effect - houses as colateral -> increasing household borrowing <- house prices effects (note on p.123)




"Second, monetary policy is now transmitted more through the price of homes than through residential investment." (International Monetary Fund. Reseach Dept. 2008:123)

How it affects 2: Monetary policy transmission is through house prices and not residential investment (note on p.123)




"First, because its impact is greater in economies with more developed mortgage markets, monetary policy may need to be more aggressively responsive to unexpected developments in the housing sector and mortgage markets in these economies." (International Monetary Fund. Reseach Dept. 2008:123)

Interesting findings: the effect is greater the more developed mortgage market is (note on p.123)




"Paying increased attention to house price developments does not require any change to the formal mandates of major central banks, but rather could be achieved by interpreting existing mandates in a fl exible manner, for instance by extending the time horizon for infl ation and output targets." (International Monetary Fund. Reseach Dept. 2008:123)

Policy recomendation: more flexible act rather than house prices been the main goal of monetary policy (note on p.123)




"Regulations set interest rate ceilings and quantitative limits on mortgage credit and repayment periods. These regulations resulted in chronic or temporary credit rationing in the mortgage market and made it diffi cult for households to access mortgage credit (Girouard and Blöndal, 2001)." (International Monetary Fund. Reseach Dept. 2008:123)

Implications of regulations in the 80s: credit rationing.
How they acted? interest rate ceilings, quantitative limits, repayment periods. (note on p.123)




"The process of deregulation, however, took different forms in various countries (Diamond and Lea, 1992)." (International Monetary Fund. Reseach Dept. 2008:123)

Further reference to how the deregulation occured in different countries. (note on p.123)




"interest rate controls under Regulation Q in the early 1980s (Green and Wachter, 2007)." (International Monetary Fund. Reseach Dept. 2008:124)

In the US, coincided with Regulation Q. (note on p.124)




"At the same time, the development of a secondary mortgage market greatly facilitated the funding of mortgage lending via capital markets" (International Monetary Fund. Reseach Dept. 2008:124)

Additionally, development of secondary mortgage market -> funding <- capital markets (note on p.124)




"United Kingdom, deregulation occurred mainly through the abolition of credit controls ("the corset" was abolished in 1980)" (International Monetary Fund. Reseach Dept. 2008:124)

In the UK, abolition of credit controls. (note on p.124)




"In Canada, Australia, and the Nordic countries, deregulation of housing fi nancial markets was also relatively rapid and almost completed by the mid-1980s." (International Monetary Fund. Reseach Dept. 2008:124)

In these countries, the deregulation was fast. (note on p.124)




"By contrast, in some continental European countries and in Japan, the reform process was slower and/or less comprehensive." (International Monetary Fund. Reseach Dept. 2008:124)

The deregulation process in this countries was slower. (note on p.124)




"However, public sector fi nancial institutions continued to dominate the residential mortgage market in these countries, and this constrained the forces of competition" (International Monetary Fund. Reseach Dept. 2008:124)

Additionally, the presence of public sector in this countries still were high. (note on p.124)




"Countries that experienced faster and deeper innovations in mortgage markets (the United States, the United Kingdom, Canada, Australia, and the Nordic countries) tend to have higher shares of household loans from nonbank financial institutions and a higher stock of mortgage debt as a ratio to GDP." (International Monetary Fund. Reseach Dept. 2008:124)

Figure 3.1 (note on p.124)




"Following the deregulation of mortgage markets, advanced economies all moved toward more competitive housing fi nance models—in which households have easier access to housingrelated credit, thanks to the increased diversity of funding sources, lender types, and loan products." (International Monetary Fund. Reseach Dept. 2008:125)

Which instruments and changes allowed for higher mortgage access. (note on p.125)




"High LTV ratios allow borrowers to take out more debt, whereas longer repayment terms keep debt-service-to-income ratios affordable." (International Monetary Fund. Reseach Dept. 2008:125)

Rationale of LTV and length of mortgage loans:

1. LTV: debt level
2. Length: affordability (note on p.125)




"The ability to make home equity withdrawals and to prepay mortgages without fees: The capacity to borrow against accumulated home equity allows households to tap their housing wealth directly and to borrow more when house prices increase. Early repayment fees constrain households' ability to refinance their mortgage debt in the event interest rates decline." (International Monetary Fund. Reseach Dept. 2008:125)

Equity withdraws -> tap their housing wealth -> borrow more when house prices increases. (note on p.125)




"ary markets for mortgage loans, the easier it should be for lenders to tap funding via capital markets and, all else being equal, to provide credit to households." (International Monetary Fund. Reseach Dept. 2008:125)

The existence of secondary mortgage market may allow to increase funding via capital markets -> credit to households (note on p.125)




"The index lies between 0 and 1, with higher values indicating easier household access to mortgage credit." (International Monetary Fund. Reseach Dept. 2008:125)

Index interpretation: the higher, more access to mortgage debt (note on p.125)




"(see BIS, 2006)" (International Monetary Fund. Reseach Dept. 2008:125)

Further reference for securitized mortgage data. (note on p.125)




"ources: European Central Bank (2003); Catte and others (2004); Calza, Monacelli, and Stracca (2007). 2003-06. Sources: European Mortgage Federation, Hypostat 2006; Bond Market Association and Federal Reserve for the United States; Dominion Bond Rating Services and Statistics Canada for Canada; Australia Securitization Forum and Reserve Bank of Australia for Australia; FinanceAsia.com and Bank of Japan for Japan." (International Monetary Fund. Reseach Dept. 2008:126)

References for construction mortgage market index. (note on p.126)




"Movements in real house prices have been closely correlated with the economic cycle." (International Monetary Fund. Reseach Dept. 2008:126)

Stylized fact: house prices ~ business cycle (note on p.126)




"See, among others, Case (2000); Girouard and Blöndal (2001); Catte and others (2004); European Commission (2005); European Central Bank (2003); and April 2003 and September 2004 World Economic Outlook." (International Monetary Fund. Reseach Dept. 2008:126)

Further references for housing stylyzed facts. (note on p.126)




"First, residential investment has led the business cycle in several countries, with some exceptions in the euro area (Germany, Italy, and Finland) and the Nordic countries (Sweden and Norway) (see Figure 3.2)" (International Monetary Fund. Reseach Dept. 2008:126)

Residential investment leads the cycle with some exceptions. (note on p.126)




"Some studies note, however, that the link between the housing sector and the business cycle appears to have weakened over the past decade." (International Monetary Fund. Reseach Dept. 2008:127)

Some scholars have pointed out that the links between housing sector and business cycle had weakened. (note on p.127)




"First, recent housing cycles have been unusual in several respects, including in their duration and amplitude." (International Monetary Fund. Reseach Dept. 2008:127)

The previous weaken does not mean that housing is less important.
1. The housing cycles are more unsual -> more longer and stronger (duration and amplitude) (note on p.127)




"developments in the housing sector have differed considerably across the set of countries here." (International Monetary Fund. Reseach Dept. 2008:127)

Additionally, development in hosuing sector is different across countries. (note on p.127)




"For example, in countries with more fl exible labor markets and more labor-intensive construction sectors, changes in demand can lead to stronger responses in both housing supply and construction employment, and ultimately can have a larger effect on economic activity." (International Monetary Fund. Reseach Dept. 2008:128)

The authors explain some of countries distinctiveness due to flexibility in labor market. (note on p.128)




"The characteristics and structure of mortgage markets also play a key role in forging links between housing markets and the business cycle. Indeed, some authors argue that fi nancial deepening over the past two decades may have led to a decoupling of the housing sector from both investment and consumer spending (see Dynan, Elmendorf, and Sichel, 2006; and Campbell and Hercowitz, 2005). Others note that the increased integration of housing fi nance with capital markets has reduced the interest rate elasticity of residential investment." (International Monetary Fund. Reseach Dept. 2008:128)

Further references for both financial deepening and interest-rate sensitivity. (note on p.128)




"The importance of home values as a share of household total wealth suggests that fl uctuations in house prices may affect consumer spending through wealth effects." (International Monetary Fund. Reseach Dept. 2008:129)

Supporting theoretical ideal: house values affects household wealth -> consumer spending <- wealth effetcs. (note on p.129)




"an increase in house prices redistributes wealth within the household sector, rather than boosting net aggregate wealth." (International Monetary Fund. Reseach Dept. 2008:129)

Interesting finding: house prices redistributes income within housold sector instead to increase net aggregate demand directlu. (note on p.129)




"increases in house prices may raise the value of the collateral available to households, loosen borrowing constraints," (International Monetary Fund. Reseach Dept. 2008:129)

Additionally, house price increase may loose borrowing constraints. (note on p.129)




"In principle, however, the resulting impact on consumption and output volatility is ambiguous, because two countervailing effects may be at work." (International Monetary Fund. Reseach Dept. 2008:130)

Ambigous effetcs: smooth consumption; volatility amplified by variations in collateral constrainsts. (note on p.130)




"Although the potential for housing fi nance to smooth consumption is relevant, it may not fully apply to all households (Dynan and Kohn, 2007). Many households that experience income shortfalls will be unable to borrow to smooth" (International Monetary Fund. Reseach Dept. 2008:130)

ABM related: the smooth comsuption may not be relevant for all households. (note on p.130)




"To examine these questions more systematically, a vector autoregression (VAR) model for real house prices, residential investment, and other key macroeconomic and monetary policy variables is estimated separately for 18 countries, using quarterly data for the period from 1970 (or the fi rst year for which data are available)" (International Monetary Fund. Reseach Dept. 2008:131)

Econometric methodology. (note on p.131)




"In this box, the vulnerability to a housing market correction is assessed based on two different indicators: fi rst, the extent to which the increase in house prices in recent years cannot be explained by fundamentals, and second, the size of the increase in the residential investment-to-GDP ratio experienced during the past 10 years." (International Monetary Fund. Reseach Dept. 2008:132)

Indicatior for vulnerability of housing market: prices > fundamental; residential investment-to-GDP ratio (note on p.132)




"This suggests that the housing sector tends to have its own distinct dynamics (see also Zhu, 2005)." (International Monetary Fund. Reseach Dept. 2008:135)

Housing has its own distinct dynamics.
Further reference to justify residential investment as an autonomous expenditure. (note on p.135)




"The extent to which housing demand shocks explain fluctuations in the aggregate economy varies significantly across countries and over time (Figure 3.5)." (International Monetary Fund. Reseach Dept. 2008:135)

There is also an cross-country variability regarding fluctiations in aggregate demand.
(note on p.135)




"Changes in interest rates affect domestic demand both directly, by affecting residential construction and household spending plans through the change in cost and availability of credit, and indirectly, by moving house prices." (International Monetary Fund. Reseach Dept. 2008:136)

Changes in interest rates -> residential investment and household spending; house prices (indirectly) (note on p.136)




"Share of Output Variation Explained by Housing Demand Shocks1" (International Monetary Fund. Reseach Dept. 2008:136)

Panel plot: FEVD for all countries in two subsamples. (note on p.136)




"Therefore, increases in policy interest rates would trigger an outfl ow of such savings deposits and squeeze mortgage fi nance institutions' net incomes—both of which would result in reduced credit availability." (International Monetary Fund. Reseach Dept. 2008:137)

Interest rate effects prior to the deregulation of mortgage markets: squeeze availability out of savings depositis (note on p.137)




"monetary policy transmission. First, with increased competition in housing fi nance, mortgage retailers may adjust interest rates more rapidly in response to policy rates. Second, because households and fi rms have access to a wider array of credit products, residential investment and consumer durable expenditure may respond more strongly to changes in interest rates.17 Third, greater access to mortgage credit may make house prices more responsive to interest rates, thereby" (International Monetary Fund. Reseach Dept. 2008:137)

Monetary policy transmission channels:

1. Higher competition -> adjust fast to change in interest rates
2. More acces to a wider arry of credit products
3. House prices are more responsive to interest rates (note on p.137)




"The results confi rm that there are noticeable differences between the two periods. Monetary policy shocks had a smaller impact on both residential investment and output in the second period, but their effect lasted much longer (Figure 3.9). House prices reacted more slowly during the second period, but their decrease was more persistent and eventually stronger— reaching their maximum decline after about four years, compared with two years during the fi rst period." (International Monetary Fund. Reseach Dept. 2008:138)

The auhtors found differences between the subsample: house prices more persistent (note on p.138)




"Such normalization suggests that the elasticity of residential investment to monetary policy shocks in the United States has declined only modestly during the second period, whereas the elasticity of house prices and output has increased (Figure 3.10).2" (International Monetary Fund. Reseach Dept. 2008:139)

After some normalization procedures, the authors found that the residential investment elasticity decreased a little; while house price elasticity increased. (note on p.139)




"Comparing these counterfactuals with the actual path of housing variables suggests that the unusually low level of interest rates in the United States between 2001 and 2003 contributed somewhat to the elevated rate of expansion in the housing market, in terms of both housing investment and the run-up in house prices up to mid-2005 (Figure 3.12), as has been argued by Taylor (2007).24" (International Monetary Fund. Reseach Dept. 2008:140)

Counterfactuals estimates conclude that low level o interest rate in the US have increased the expansion of housing market. (note on p.140)




"For Ireland, which has a less-fl exible market, the analysis does not indicate that a tighter monetary policy would have resulted in signifi cantly different housing market outcomes. In the Netherlands, however, the analysis suggests that tighter monetary policy during this period might have contained the housing dynamics, especially with regard to house prices." (International Monetary Fund. Reseach Dept. 2008:141)

The results of counterfactuals are different in countries with lower (Ireland) and higher (Netherlands) mortgage market index. (note on p.141)




"However, there is much less consensus on how best to respond to rising asset prices." (International Monetary Fund. Reseach Dept. 2008:141)

This discussion is too much off-topic. (note on p.141)




"The diffi culties of identifying bubbles in asset prices and the uncertainty over the impact of monetary policy on asset prices are the main arguments against responding to asset price changes over and above the response warranted by their implications for infl ation and output." (International Monetary Fund. Reseach Dept. 2008:141)

Some arguments against the focus on asset-price policy making. (note on p.141)




"The reason could be that the greater "liquidity" of housing equity in these economies has amplifi ed the fi nancial accelerator effect from endogenous variations in the collateral constraint tied to the value of homes." (International Monetary Fund. Reseach Dept. 2008:145)

Summary of the argument: the more liquidity, more amplified financial accelerator effect is <- endogenous variations in collateral constraint. (note on p.145)




"At the same time, the evidence about the responsiveness of residential investment to monetary policy is mixed." (International Monetary Fund. Reseach Dept. 2008:146)

Panel related: interest rate -> residential investment is mixed. (note on p.146)




"Such attention to house price developments need not require a change in the formal mandates of major central banks, but could be achieved by interpreting existing mandates more fl exibly, for instance, by extending the horizon for infl ation and output targets." (International Monetary Fund. Reseach Dept. 2008:146)

Summary of policy making recommendation (note on p.146)
