:mtime:    20211202152744 20211013082514
:ctime:    20211013082514
:END:
#+TITLE: baccaroRethinkingComparativePolitical2016: Rethinking Comparative Political Economy: The Growth Model Perspective (2016, Politics \& Society)
#+OPTIONS: toc:nil num:nil
Time-stamp: 2021-02-17
- tags ::


* Backlinks


[[denote:20230216T235157][Varieties of Capitalisms]]

* FISH-5SS


|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                     |
| *Background*                                  | Both CPE and VoC literature is based on supply side; emphasize the resilience of country-particularity and; do not pay attention to distributional effects.                                              |
| *Supporting Ideas*                            | Both CME and LME exibit an increase in inequelity while VoC literature attributes this results mainly to LME while CPE is explained by other factors.                                                    |
| *Purpose*                                     | Include both demand-side and distribution elements in CPE literature based on a Neo-Kaleckian growth model framework. Additionally, intends to enlarge the ideal typology.                               |
| *Originality/value (Contribution)*            | Connects demand-side variables to an comparative framework proposed by prior VoC literature.                                                                                                             |
| *Relevance*                                   | Review the CPE literature and point out its flaws, consensus, emphasis and neglations.                                                                                                                   |
| *Design/methodology/approach*                 | Review of empirical literature and analysis of time-series data (no econometric)                                                                                                                         |
| *Sample:*                                     | Germany,  Italy,  Sweden  and  the  UK over  the  pre-crisis  period  1994-2007                                                                                                                          |
| *Results*                                     | Since there is an broad PK literature dedicated to it, this results is not relevant.                                                                                                                     |
| *(Interesting) Findings*                      | According to VoC literature, globalization implies divergence due to trial to achieve comparative advantages based on institutional particularities. Points out that VoC literature is too firm-centric. |
| *Research limitations/implications (Critics)* | Empirical proposal is null and based on out-dated PK literature. Does not explain how institutions could generates those growth regimes.                                                                 |
| *Uncategorized stuff*                         | Ideia: QCA chapter proposes an demand-led alternative to include institutional particularities in a comparative manner.                                                                                  |
| *5SS*                                         | Embeds neo-Kaleckion growth model proposition in CPE literature and points outs its limitations                                                                                                          |
|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: baccaroRethinkingComparativePolitical2016
 :AUTHOR: Baccaro, L., & Pontusson, J.
 :JOURNAL: Politics \& Society
 :YEAR: 2016
 :DOI:  http://dx.doi.org/10.1177/0032329216638053
 :URL: https://doi.org/10.1177/0032329216638053
 :END:


* Extracted Annotations (17/02/2021 12:48:42)
:PROPERTIES:
 :NOTER_DOCUMENT: /home/gpetrini/Zotero/storage/HVK7ARXX/Baccaro e Pontusson - 2016 - Rethinking Comparative Political Economy The Grow.pdf
 :END:


"have  refracted  political  and  economic  responses  common  economic  shocks  or opportunities." (Baccaro and Pontusson 2016:177)

Institucionalities -> how economies reacts to some shocks and opportunities. (note on p.177)




"nto  two  camps:  on  one  side,  those  who  emphasize  the  common,  socially-­‐regressive,  trajectory of  capitalism  from  the  1970s  onwards  and,  on  the  other  side,  those  who  continue  to  underscore the  resilience  of  national  models  or,  in  other  words,  cross-­‐national  diversity" (Baccaro and Pontusson 2016:177)

Break in the consensus due to the GFC.

1. Socially-regressive trajectories -> explain better
2. Resilience of cross-national diversity (note on p.177)




"Our  main  theoretical  innovation  is  to  return  to  Keynesian  and  Kaleckian insights  neglected  by  CPE  scholars" (Baccaro and Pontusson 2016:177)

Contribution: plugs neo-kaleckian model to CPE and VoC literature (note on p.177)




"we  do  not  conceive  this  diversity  in  terms  of  institutional equilibria  that  predate  the  crisis  of  Fordism  in  the  1970s." (Baccaro and Pontusson 2016:177)

At odds with VoC literature, the main change is not related to the end of the Fordism era (note on p.177)




"Germany,  Italy,  Sweden  and  the  UK over  the  pre-­‐crisis  period  1994-­‐2007" (Baccaro and Pontusson 2016:178)

Sample (note on p.178)




"Over  the  period  1994-­‐2007,  the UK  relied  on  household  consumption  as  the  main  driver  of  economic  growth,  spurring household  consumption  through  a  combination  of  real  wage  growth  and  the  accumulation  of household  debt.    In  marked  contrast,  Germany  came  to  rely  on  export-­‐led  growth,  repressing wages  and  consumption  to  boost  the  competitiveness  of  the  export  sector.    Sweden  enjoyed robust  growth  of  both  exports  and  household  consumption.    Italy,  finally,  experienced  sluggish growth  in  both  domains  and,  hence,  overall  stagnation" (Baccaro and Pontusson 2016:178)

Discussion of if these countries are wage- or profit-led. This is not relevant for dissertation.
Additionally, other scholars explored this question in a better way. (note on p.178)




"wo  of  our  cases,  Germany  and  Sweden,  are  consistently  coded  as  Coordinated  Market Economies,  or  CMEs  for  short,  in  VofC-­‐inspired  literature.    The  UK  is,  of  course,  conventionally considered  to  be  an  arch-­‐typical  Liberal  Market  Economy  (LME)  while  Italy  is  typically  assigned to  the  residual  category  of  Mixed  Market  Economies  (MMEs)." (Baccaro and Pontusson 2016:179)

How these countries are categorized in VoC terms. (note on p.179)




"CPE  literature  to  date  has  been  far  too  preoccupied  with  building  typologies  and classifying  countries" (Baccaro and Pontusson 2016:179)

Literature is more worried about classification (note on p.179)




"As  a  field  of  inquiry  spanning  sociology  and  political  science,  comparative  political  economy emerged  in  response  to  the  economic  crisis  of  the  1970s." (Baccaro and Pontusson 2016:180)

Origins of CPE tradition. (note on p.180)




"VofC  approach"  developed  by  Hall  and  Soskice in  the  1990s  placed  firms  and  business  networks  center-­‐stage" (Baccaro and Pontusson 2016:180)

VoC as a firm centric approach (note on p.180)




"conceiving  "varieties  of  capitalism"  as  institutional  equilibria  from  which  rational actors  do  not  have  any  incentive  to  deviate.5" (Baccaro and Pontusson 2016:181)

Note: VoC uses institutions similar to North and Aoki. (note on p.181)




"Most  distinctively,  VofC  scholars  have consistently  argued  that  globalization,  far  from  being  a  source  of  convergence  between  LMEs and  CMEs,  has  served  to  accentuate  the  differences  between  these  models  of  capitalism,  with firms  and  governments  seeking  to  gain  (or  maintain)  competitiveness  based  on  the  distinctive comparative  advantages  bestowed  by  each  model.6" (Baccaro and Pontusson 2016:181)

This really importante: There is a consensus in VoC in which globalization generated a divergence path (not convergence) due to trial to use its distinctiveness as a source of comparative advantages. (note on p.181)




"comparative  political  economists  instead  focused  on  the  role  of  "supply-­‐side institutions"—corporate  finance  systems,  industrial  relations  regimes,  vocational  training systems  and  the  like—  in  determining  the  sustainable  ("non-­‐inflation-­‐accelerating")  rate  of unemployment." (Baccaro and Pontusson 2016:181)

CPE focus on suply-side.

Idea: QCA chapter as an demand-led alternative to include institution in CPE framework. (note on p.181)




"Quality  Production  (DQP)  into  his  theory  about  comparative  institutional  advantage  and capacities  for  innovatio" (Baccaro and Pontusson 2016:182)

Exemple of institutional comparative advantage. (note on p.182)




"The  critics  of  VofC—ourselves  included—have  failed  to  generate  alternative  analytical categories  for  grappling  with  the  core  problématique  of  comparative  political  economy:  the (national)  diversity  of  capitalism." (Baccaro and Pontusson 2016:182)

Gap in the literature. (note on p.182)




"By  and  large,  the  existing  literature  conceives  rising earnings  inequality  as  an  LME-­‐specific  phenomenon" (Baccaro and Pontusson 2016:183)

VoC attributes the decrease of wage-share almost exclusivelly to LME. (note on p.183)




"Lucy  Barnes,  there  is  no  discernable  difference  between  LMEs  and  CMEs,  as  conventionally coded,  with  respect  to  either  levels  of  household  debt  or  increases  in  household  debt  since 1995  and  cross-­‐national  diversity  with  respect  to  rising  household  indebtedness  cuts  across  the LME/CME  divide" (Baccaro and Pontusson 2016:184)

Both LME and CMEs presents an increase in household debt.

Ideia: opening the section by stablishing this problem in VoC literature. (note on p.184)




"CMEs,  CPE  scholars  have emphasized  dualizing  institutional  reforms  and  a  growing  divide  between  labor-­‐market "insiders"  and  "outsiders."" (Baccaro and Pontusson 2016:184)

Why inequality increased in CME. (note on p.184)




"Thelen  treats  deindustrialization  as  the  main  driver  of institutional  and  political  change  in  advanced  capitalist  political  economies" (Baccaro and Pontusson 2016:184)

Other reference for the main conclusion of VoC literature. (note on p.184)




"Our  emphasis  on  exports  and  competitiveness  represents  a  return  to  core  themes  of  the CPE  literature  of  the  1980s  and  the  1990s,  but  we  depart  from  that  literature  in  two  crucial respects" (Baccaro and Pontusson 2016:185)

Similarities to pior VoC literature: emphasis on exports and competitiveness
Differences: PK approach (class struggles) and demand-sed emphasis. (note on p.185)




"how  distributional  shifts  affect  growth  models  and  the role  and  interaction  of  different  components  of  aggregate  demand  -  have  not  featured prominently  in  the  CPE  literature  to  date." (Baccaro and Pontusson 2016:185)

Purpose of the paper. (note on p.185)




"New-­‐Kaleckian  macroeconomists,  "regulationists"  have  emphasized that  the  rapid  and  remarkably  stable  growth  characteristic  of  the  1950s  and  the  1960s  was made  possible  by  a  set  of  institutional  arrangements—in  the  first  instance,  collective  bargaining and  unemployment  insurance—that  boosted  labor's  bargaining  power  and  served  to  ensure that  wage  growth  kept  pace  with  productivity  growth,  thus  feeding  aggregate  demand." (Baccaro and Pontusson 2016:190)

Connections between neo-Kaleckian literature and "regulationists" (note on p.190)




"Some  heterodox  economists  use  "financialization"  as  an  umbrella  term  for  institutional or  regulatory  changes  that  have  moved  advanced  capitalist  economies  onto  a  profit-­‐led  growth path.3" (Baccaro and Pontusson 2016:192)

Relation between neo-Kaleckian models and financialization literature: financialization shited wage-led regimes to profit-led ones. (note on p.192)




"Fordist  model  of  wage-­‐led  growth:  consumption-­‐led  growth  financed  by  credit,  investment-­‐led growth  and  export-­‐led  growth." (Baccaro and Pontusson 2016:193)

Proposed typology. (note on p.193)




"The  empirics  presented  in  this  part  are  organized  as  follows.    First,  we  show  that  Germany,  Italy, Sweden,  and  the  UK  relied  on  different  combinations  of  exports  and  consumption  as  drivers  of GDP  growth  in  the  period  1994-­‐2007.    Second,  we  discuss  the  way  in  which  household consumption  is  financed  and  present  data  suggesting  that  debt  financing  as  well  as  real-­‐wage growth  fuelled  household  consumption  in  both  Sweden  and  the  UK.  Third,  we  explore  the  co-­‐ evolution  between  growth  models  and  the  structure  of  earnings  inequality." (Baccaro and Pontusson 2016:194)

Big picture of the results (note on p.194)




"The  second,  and  more  important,  point  is  that  the implications  of  export-­‐led  growth  depend  crucially  on  the  composition  of  exports  or,  in  other words,  their  degree  of  price-­‐sensitivity" (Baccaro and Pontusson 2016:207)

Some export-led-related observation. (note on p.207)
