:mtime:    20211202152740 20211013082514
:ctime:    20211013082514
:END:
#+TITLE: serrano_2002_Conflito: Conflito distributivo e inflac\~ao de custos (2002, )
#+OPTIONS: toc:nil num:nil
Time-stamp: 2021-02-18
- tags ::


* Backlinks

[[denote:20230216T235158][Inflação e Conflito Distributivo]]


* FISH-5SS


|---------------------------------------------+-----|
| <40>                                          |<50> |
| *Background*                                  |     |
| *Supporting Ideas*                            |     |
| *Purpose*                                     |     |
| *Originality/value (Contribution)*            |     |
| *Relevance*                                   |     |
| *Design/methodology/approach*                 |     |
| *Results*                                     |     |
| *(Interesting) Findings*                      |     |
| *Research limitations/implications (Critics)* |     |
| *Uncategorized stuff*                         |     |
| *5SS*                                         |     |
|---------------------------------------------+-----|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: serrano_2002_Conflito
 :AUTHOR: Serrano, F.
 :JOURNAL:
 :YEAR: 2002
 :DOI:
 :URL:
 :END:


* Extracted Annotations (18/02/2021 10:48:03)
:PROPERTIES:
 :NOTER_DOCUMENT: /home/gpetrini/Zotero/storage/FP5FISSW/Serrano - CONFLITO DISTRIBUTIVO E INFLAÇÃO DE CUSTOS.pdf
 :END:


"Na teoria neoclássica a demanda efetiva só pode ter relevância no curto prazo pois no longo se supõe existir um mecanismo automático da oferta agregada gerar sua própria demanda, pelo ajuste dos preços e salários nominais. Dessa forma a curva de oferta agregada, pelo menos no longo prazo, é vertical ao nível do produto potencial, pois enquanto a economia estiver fora deste ponto os preços e salários nominais estarão variando." (Serrano 2002:1)

Oferta vertical no longo prazo; ajuste via preços. (note on p.1)




"os preços não podem ser flexíveis, determinados pela interseção da curva de demanda agregada "bem comportada" com a curva de oferta agregada vertical de plena capacidade uma vez que : i) a curva de demanda agregada" (Serrano 2002:1)


porque os preços não são flexíveis parte 1 (note on p.1)




"não tem porque ser "bem comportada" e ii) o próprio produto potencial não é fixo e independente da tendência da demanda efetiva ." (Serrano 2002:2)

porque os preços não são flexíveis parte 2 (note on p.2)




"Para os neoclássicos a inflação persistente é sempre em última análise explicada por um excesso de demanda agregada, mesmo quando aparentemente é de custo." (Serrano 2002:2)

Inflação na teoria neoclássica (note on p.2)




"No entanto, se governo não emitir mais moeda o que acontece é que o aumento inicial de preços diminui a demanda agregada pois a oferta real de moeda diminui . Esta redução da oferta real de moeda e do nível de demanda agregada e reduz o produto e o emprego. O desemprego resultante leva a uma queda dos salários nominais que são repassadas aos preços até que o nível de demanda agregada retorne à posição de pleno emprego." (Serrano 2002:2)

Mecanismo de ajusto pós aumento inicial dos preços; retorno ao pleno emprego. (note on p.2)




"é apenas temporária e no longo prazo a inflação que realmente acontece é de excesso de demanda." (Serrano 2002:3)

Na teoria neoclássica, toda inflação de custos é temporária. (note on p.3)




"Contudo se abandonarmos a idéia de curva de demanda agregada bem comportada e de oferta de moeda exógena vemos que a inflação de custos , isto é, causada por aumentos autônomos nos preços de oferta pode sempre ocorrer , mesmo em situações onde não haja excesso de demanda agregada." (Serrano 2002:3)

No entanto, inflação de custos pode ser permanente mesmo sem excesso de demanda (note on p.3)




"Os preços de oferta aumentam e geram inflação de custos por conta de uma incompatibilidade distributiva entre os seus diversos componentes (salários, lucros etc.) e não por uma escassez física de produtos." (Serrano 2002:3)

O porquê do aumento dos preços de oferta. (note on p.3)




"inflação de demanda, quando ocorre, tende a ser um fenômeno de curto prazo, pois pode levar um tempo para as quantidades produzidas conseguirem responder à estímulos de demanda." (Serrano 2002:3)

Na teoria heterodoxa, inflação de demanda é temporária; ajusta-se por quantidades. (note on p.3)




"Vamos supor também que o período de produção é mais curto do que o período de contratual de pagamento de salários de forma que a folha de salários não faz parte do capital que precisa ser adiantado para se produzir." (Serrano 2002:4)

Hipótese que permite não incluir folha de salários. (note on p.4)




"PX = (1+r) AP + W L onde 'A' é a quantidade física de insumo o necessária para produzir X unidades do produto e W é o salário nominal e L a quantidade de trabalho empregada. O preço unitário do produto é dado por : P = (1+r) A P + W L X X" (Serrano 2002:4)

"Repare que a<1, caso contrário não tecnicamente viável produzir o produto." (Serrano 2002:4)

Hipótese para produção tecnicamente viável. (note on p.4)




"Note que dada a tecnologia , existe nesta economia uma relação inversa entre a taxa de lucro embutida nos preços de oferta e o nível dos salários reais . Isto pode ser observado dividindo-se a equação acima por P e observando como uma unidade física do produto bruto é distribuída entre salários reais , lucros e reposição do capital : 1 = (1+r) a + v  onde W/P = v, é o salário real." (Serrano 2002:5)

Relação inversa entre taxa de lucro e salários reais (v) (note on p.5)




"Note que mesmo que o salário seja zero a taxa de lucro não pode ser infinita pois é preciso utilizar insumos para produzir os produtos . Então seu limite vai depender da tecnologia (quanto menor for 'a' maior será rmáx )." (Serrano 2002:5)

Taxa de lucro máxima é restringida pela tecnologia. Então não será infinita se os salários forem nulos. (note on p.5)




"Os preços de oferta nos modelos de inflação de custo mais simples aparecem expressos na forma da adição de uma margem bruta de lucros (ou mark-up) sobre os custos salariais. P = (1+m) Wl" (Serrano 2002:6)

Determinação dos preços de oferta via markup real. (note on p.6)




"Trata-se de um mark-up real sobre custos de reposição pois ele é aplicado em cima do valor dos vigentes no mesmo momento em que o produto é vendido." (Serrano 2002:6)

O porque esse markup é real. (note on p.6)




"P = 1 W l 1-(1+r)a logo o mark-up real é dado por : m = 1 - 1 1-(1+r)a" (Serrano 2002:6)

Explicitando a taxa de lucro e a tecnologia na equação do markup (note on p.6)




"'r' seria determinado de forma unilateral pelas empresas. Nesse caso, é fácil ver que a variável de ajuste é o salário real." (Serrano 2002:7)

Se o markup é fixo e exógeno, o ajuste é via salário real. (note on p.7)




" =  Neste modelo a inflação é neutra em termos distributivos pois os salários reais não iram se alterar, a não ser que mude a margem de lucro ou a tecnologia." (Serrano 2002:7)

Inflação é neutra em termos distributivos. (note on p.7)




"A dificuldade com este modelo é entender porque os trabalhadores insistem em pedir reajustes nominais que na prática em nada alteram seus salários reais. Em modelos deste tipo com o mark-up real fixo o conflito distributivo sempre é resolvido a favor das empresas" (Serrano 2002:8)

Não há, na prática, conflito distributivo nesse tipode de modelo. (note on p.8)




"Uma variante deste modelo que tenta explicar porque os trabalhadores insistem em reajustes nominais é supor que existem, por exemplo, dois tipos de trabalhadores (1 e 2) ganhando W1 e W2" (Serrano 2002:8)

Se existir mais de um tipo de trabalhador, explica-se o porquê dos trabalhadores exigirem reajustes *nominais*.
Além disso, a inflação deixa de ser neutra em termos distributivos. (note on p.8)




"Outra extensão do modelo de mark-up real fixo é quando existem outros tipos de custo, como por exemplo petróleo importado (ou outros insumos produzidos fora da economia)." (Serrano 2002:9)

Incluindo preços importados no modelo. (note on p.9)




"Nesta versão a inflação é uma média ponderada entre o aumento dos salários  e do aumento do preço petróleo na moeda nacional (ê + *). Nesse caso o conflito distributivo se dá indiretamente entre os trabalhadores e os países produtores de petróleo." (Serrano 2002:9)

Conflito se dá entre trabalhadores e produtores do insumo produzido internacionalmente. (note on p.9)




"Ou seja o que está implícito na hipótese de margem real dada é que a margem nominal esta é automaticamente e instantaneamente corrigida pela inflação. A inflação é função da variação dos custos no mesmo período." (Serrano 2002:10)

Hipótese implícita nos modelos com margem real fixa. (note on p.10)




"Como vimos então essa hipótese resolve o conflito distributivo sempre a favor dos lucros. Ou seja, o conflito distributivo só gera inflação e uma redistribuição da renda entre os diversos componentes dos custos sejam diferentes grupos de trabalhadores entre os trabalhadores, seja entre os trabalhadores e os produtores de insumos importados , etc." (Serrano 2002:11)

Consequência da hipótese anterior (note on p.11)




"No caso da margem nominal ficar constante ao longo tempo teremos também que a taxa de inflação de inflação será dada pela taxa de crescimento dos custos do período anterior" (Serrano 2002:11)

Alternativamente, outros modelos supõem que é a taxa nominal (sobre os custos históricos) é constante. (note on p.11)




"Essa defasagem entre os aumentos de custos e os de preços significa que a inflação não é mais neutra para as empresas , que , ao menos para uma dada margem nominal, terão redução de rentabilidade real se a taxa de crescimento dos custos aumentar." (Serrano 2002:12)

Como consequência, inflação deixa de ser neutra para as empresas. (note on p.12)




"Dessa forma a variação dos salários reais ΰt iria depender da taxa de variação dos salário nominais em um período em relação à taxa do outro período" (Serrano 2002:12)

Nesse exemplo, a variação dos salários reais depende do ajuste dos salários nominais anterior. (note on p.12)




" t < t-1 (nesse caso t < t-1) logo t <  logo mt > mt-1 e ΰt < 0  t > t-1 (nesse caso t > t-1) logo t >  logo mt > mt-1 e ΰt > 0" (Serrano 2002:12)

Se a taxa de crescimento dos custos corrente for menor do que no período anterior, a margem de lucro real será maior que a do perído anteiror e, portanto, os salários reais irão decrescer. (note on p.12)




"Isto mostra que quando o mark-up real não é fixo , a inflação não é neutra para as empresas e faz sentido para os trabalhadores resistir a reduções do ritmo de crescimento dos salários nominais , a não quando houverem garantias que estas seriam acompanhadas por reduções das margens nominais das empresas." (Serrano 2002:12)

Consequências de quando o markup real deixa de ser fixo. (note on p.12)




"Em seu conhecido modelo de decisões de preços sob alta inflação Roberto Frenkel supõe que : 1+n = (1+e) (1+ md) Nesse modelo as empresas desejam uma taxa real md e supõe que os custos vão aumentar e. Então 1+ m = (1+e) (1+md) (1+ )" (Serrano 2002:13)

Determinantes da margem nominal: modelo Frenkel (note on p.13)




"Ele chega a uma à conclusão de que se as expectativas são aceleracionistas, a inflação de fato vai aumentar pois as margens nominais estarão aumentando a cada período." (Serrano 2002:14)

Explicação da inflação aceleracionista a luz desse modelo. (note on p.14)




"A dificuldade com esta formulação é que a explicação da inflação e de sua aceleração ou redução fica completamente arbitrária e "psicológica" dependendo das hipóteses subjetivas que se façam sobre expectativas, todas de difícil comprovação empírica e das hipóteses que se faça sobre a elasticidade da demanda das empresas." (Serrano 2002:14)

Limitação do modelo: explicação depende de fatores expectacionais, dificultando a validação empírica. (note on p.14)




"Pivetti segue um sugestão de Piero Sraffa de que a taxa de juros monetária fixa o peso para a taxa de lucro produtiva. Para Sraffa os preços normais são determinados pelos custos de capital e custos de produção. Assim a taxa de lucro deve ser no mínimo igual à taxa de juros, seja porque o custo do capital emprestado tem que cobrir pelo menos a taxa de juros (custo financeiro) , seja porque as empresas sempre tem a opção de fazer aplicações financeiras em vez de produzir (custo de oportunidade). Essa teoria foi desenvolvida por Pivetti para explicar a inflação de custo." (Serrano 2002:15)

Determinantes da taxa de lucro monetária: Pivetti.

Taxa monetária de juros determina o piso para a taxa de lucro produtiva. Juros é tanto um custo financeiro (custo do capital emprestado) quanto um custo de oportunidade (aplicação financeira). (note on p.15)




"Neste modelo, se a taxa de juros nominal fica constante a margem nominal de lucros também é constante. Logo a política monetária , no longo prazo, acaba tendo uma influência na regulação da rentabilidade do capital produtivo." (Serrano 2002:15)

Política monetária afeta rentabilidade do capital produtivo no longo prazo. (note on p.15)




"Neste modelo diferentes regras de política monetária de longo prazo geram diferentes regras de variação da margem de lucro nominal e portanto diferentes resultados para o conflito distributivo e para a inflação." (Serrano 2002:16)

É um modelo mais flexível (note on p.16)




"Na versão aberta desse modelo, isto é incluindo abertura comercial e financeira temos que a taxa de juros nominal doméstica tem que satisfazer a seguinte restrição, para evitar a fuga de capitais e uma série de desvalorizações descontroladas: i > i* +  + êe onde:  é o risco país; êe é a variação esperada da taxa de câmbio; e i * é a taxa de juros internacional" (Serrano 2002:16)

Modelo Pivetti para uma economia aberta: existem restrições para evitar fuga de capitais e desvalorizações. (note on p.16)
