:mtime:    20211202152745 20211013082514
:ctime:    20211013082514
:END:
#+TITLE: lavoie_2001_Minsky: Minsky's financial fragility hypothesis: a missing macroeconomic link? (2001, )
#+OPTIONS: toc:nil num:nil
Time-stamp: 2021-03-01
- tags ::


* Backlinks


[[denote:20230216T235200][Minskian theory]]

[[denote:20230216T235201][Investimento, fluxo de caixa e dinâmica da alavancagem: regime minskiano ou paradoxo da dívida?]]


* FISH-5SS


|---------------------------------------------+-----|
| <40>                                        |<50> |
| *Background*                                  |     |
| *Supporting Ideas*                            |     |
| *Purpose*                                     |     |
| *Originality/value (Contribution)*            |     |
| *Relevance*                                   |     |
| *Design/methodology/approach*                 |     |
| *Results*                                     |     |
| *(Interesting) Findings*                      |     |
| *Research limitations/implications (Critics)* |     |
| *Uncategorized stuff*                         |     |
| *5SS*                                         |     |
|---------------------------------------------+-----|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: lavoie_2001_Minsky
 :AUTHOR: Lavoie, M., & Seccareccia, M.
 :JOURNAL:
 :YEAR: 2001
 :DOI:  http://dx.doi.org/10.4337/9781781009758.00012
 :URL: https://www.elgaronline.com/view/1840643595.00012.xml
 :END:


* Extracted Annotations (01/03/2021 17:04:14)
:PROPERTIES:
 :NOTER_DOCUMENT: /HDD/PDFs/lavoie_seccareccia_2001_minsky's.pdf
:NOTER_PAGE: 2
 :END:
"Much like Keynes, Minsky saw modern capitalism as an inherently unstable system governed by the behaviour of private investment. Yet, unlike Keynes, who had stopped short of providing a comprehensive analysis of the financial process, Minsky had endogenized finance and pointed to the dynamic interaction of the financial with the industrial sector as the source of that endogenous instability (Dymski and Pollin, 1992, p. 38)." (Lavoie and Seccareccia 2001:2075)

Minsky similarities (instability) and advances (interaction of financial with industrial sector) in respect to Keynes. (note on p.2075)

"Hyman Minsky's principal legacy and, indeed, most outstanding contribution to economic analysis is the construction of a solid theoretical edifice in which money and internal finance play a pivotal role, all of which was done within a business cycle perspective." (Lavoie and Seccareccia 2001:2075)

Minsky main legacy: money and internal finance are relevante -> business cycle (note on p.2075)

"Our belief is that leverage ratios could rise as much as they could decline during an economic expansion. It all depends on what is happening to such parameters as central bank interest rate policy and the behaviour of government deficits. Higher debt ratios are not a necessary consequence of higher business investment" (Lavoie and Seccareccia 2001:2076)

Main argument: Higher debt ratios are note necessary consequence of higher business investment. (note on p.2076)

"For this reason, the chapter also seeks to evaluate empirically Minsky's hypothesis by studying time series evidence for Canada and for some of the G-7 countries for which appropriate data are available. Our empirical research on the presumed procyclical nature of leverage ratios offers at best rather mixed evidence in support of the financial fragility hypothesis." (Lavoie and Seccareccia 2001:2076)

[Purp] Purpose of the chapter and sample. (note on p.2076)

"However, a careful reading of this paper shows that the formal macroeconomic model, which leads Minsky to conclude that economic expansions lead to higher debt and leverage ratios for business firms is, in fact, based on a loanable funds approach that stands largely in opposition to the Keynesian principle of effective demand (Lavoie, 1997)." (Lavoie and Seccareccia 2001:2076)

Minksy analysis depend on loanable funds approach !-> PED (note on p.2076)

"In Minsky's 1972 model, this upward slope of the supply-price curve of investment goods is due to the presence of diminishing returns. As Minsky (1982, p. 217) says, 'there is a rate of production of investment goods such that a further increase will result in rising costs per unit. Thus there is a rising portion of the supply curve for investment goods'." (Lavoie and Seccareccia 2001:2078)

Minsly supply-price curve of investment good have diminishing returns. (note on p.2078)

"On the other hand, the negative slope of the demand price for investment goods arises in Minsky's 1972 analysis from a sophisticated analysis of the financial relationships. For Minsky, when evaluating any asset, investors must take into account both the flows of profits that this asset will generate in the future and the likelihood that the asset eventually may have to be sold at a loss on some secondary market. The higher the proportion of real investment goods that are being acquired through borrowing, the higher the probability that the firm may have to face a liquidity crisis, and hence the higher the possibility that the assets might have to be sold at a loss" (Lavoie and Seccareccia 2001:2078)

Negative demand curve of investment goods also includes the likelihood to sell an asset on some secondary market. (note on p.2078)

"In the JMK book, the rising portion of the supply-price schedule of investment goods is no longer due to diminishing returns. It is entirely associated with the increasing lender's risk tied with higher marginal leverage ratios." (Lavoie and Seccareccia 2001:2078)

Latter, the positive slope is related to increasing lender's risk. (note on p.2078)

"What about the hyperbola representing corporate internal funds - the main focus of the present analysis? In the 1972 paper, Minsky assumes that these funds are a given, without any further explanation. Indeed, he makes the following suggestion: 'Let us assume that the flow of corporate internal funds, Nc - gross profits after taxes of the Flow of Funds accounts is a close approximation to the relevant concept - is invariant with respect to the pace of investment'. Thus, for any period, the flow of corporate internal funds is a constant, although real investment in the same period can take a multiplicity of values." (Lavoie and Seccareccia 2001:2079)

The most problematic assumption according to the authors: corporate internal funds are constant. (note on p.2079)

"Is this still true, however, at the aggregate level? The section in JMK where Minsky presents his famous graph is then followed by a new section, entitled 'Aggregate Investment', which discusses explicitly the link between his graphical model and aggregate investment (1975, pp.113-16). There, Minsky makes use of the insight which he had noted a few pages before (page 107) - that is, 'aggregate investment, by affecting income, affects the aggregate [corporate internal funds]'." (Lavoie and Seccareccia 2001:2080)

In some aspects, Minsky recognizes that an increase in aggregate investment could affect corporate internal funds, but do not formalize it. (note on p.2080)

"Despite his own admonitions, however, Minsky comes back to the conclusion that he had put forth in the case of the representative firm. Minsky (ibid.) makes the following crucial claim: 'Whenever the willingness of debt-finance increases and is carried through, as is illustrated in diagram 5.5, then the objective ratio of the [cash commitments] to the [corporate internal funds] increases.' Yet diagram 5.5 was derived in the case of the representative firm" (Lavoie and Seccareccia 2001:2080)

Then, Minky make references to the representative firm diagram again. (note on p.2080)

"As John King (1996, p. 70) has clearly underlined, what is missing in the early Minsky is a clear representation of the determination of profits. Even if Minsky had previously referred to Kalecki's (1937) principle of increasing risk, he seems to be totally unaware of the latter's profit equations, at least until 1977." (Lavoie and Seccareccia 2001:2081)

What is missing in Minsky analysis is a representation of the determinants of profits. (note on p.2081)

"Davidson points out that the definition of a financially fragile economy may not be as easy as it looks, once the impact of effective demand is taken into account." (Lavoie and Seccareccia 2001:2083)

Davidson also pointed out this flaw (note on p.2083)

"One must also mention the interesting mathematical paper by Delli Gatti and Gallegati (1990), who take as close a Minskyan approach as is feasible, and end up with possible un-Minskyan results. Their model takes into account effective demand, with an endogenous determination of both the level of profits and the demand price of investment goods. They show that an economy with increasing profits and prices of capital assets, as would occur in the Minsky boom, 'does not necessarily lead to an increasing leverage ratio' (1990, p. 370)." (Lavoie and Seccareccia 2001:2083)

Delli Gatti and Gallegati (1990), two minskians, proved that the increasing profits does not necessarily lead to an increasing leverage ratio. (note on p.2083)

"In our opinion, it is controversial because it was initially derived from a macroeconomic model that was built on the loanable funds approach and which ignored the principle of effective demand, and because it was later heuristically justified on the basis of a microeconomic construction subject to the fallacy of composition." (Lavoie and Seccareccia 2001:2083)

According to the authors, Minsky proposition was problematic due to the loanable funds approach with the absence of PED. (note on p.2083)

"As was mentioned earlier in regard to Minsky's famous diagram, the investment and growth process is propelled forward by the behaviour of asset prices." (Lavoie and Seccareccia 2001:2084)

[ABM] Asset prices are relevant in Minskian analysis in which propells the growth process and its investment counterpats.

Asset inflation -> Investment <-> growth -> Asset inflation (note on p.2084)

"It ensues that a strong procyclical behaviour of corporate indebtedness would provide solid prima facie evidence in support of Minsky's financial fragility hypothesis." (Lavoie and Seccareccia 2001:2085)

In summary, a procyclical behaviour of corporate indebtedness is crucial to HIF (note on p.2085)

"Figure 4.1 provides evidence for six of the G-7 countries for which data on corporate indebtedness were readily available for the period 1971-95." (Lavoie and Seccareccia 2001:2085)

[SMPL] (note on p.2085)

"When some further econometric testing was done to check whether, when controlling for other possible factors that may have independently impacted on corporate indebtedness, the underlying Minsky relationship would hold, the results were not much better. These results are presented in Table 4.1. When applying the standard ADF tests, since at least one of the variables (growth in real GDP) was not found to be trend-stationary, as displayed in the lower panel of Table 4.1," (Lavoie and Seccareccia 2001:2085)

[METHOD] Graphical inspection and ADF tests (note on p.2085)

"The first on the fiscal side is government budget surpluses (+) [or deficits (-)] as a share of GDP of all levels of government combined, which would be expected to impact positively on debt/equity ratios because of their positive effect on the numerator and their negative effect on the denominator of the dependent variable. The second additional explanatory variable on the monetary side, instead, is a measure of real interest rates, calculated as the difference between the nominal Treasury bill rates and the rates of inflation (of the Canadian Consumer Price Index), and which would seek to capture the positive Domar effect on corporate indebtedness. Finally, the third variable is the personal savings rate, defined as personal savings as a percentage of household disposable income, so as to pick up the Keynesian effect of consumer demand on corporate indebtedness." (Lavoie and Seccareccia 2001:2090)

Additional explanatory variables:
- government budget surpluses :: increase debt and decrease equity
- Real interest rate
- Personal savings rate (% household disposable income) (note on p.2090)

"In the case of budget deficits, the variable had a sign that varied somewhat according to specification and, in addition, it was not always significant. Possibly, this may reflect a problem of specification, owing to the fact that the deficit/ GDP variable may not be considered a strictly exogenous variable because of the probable feedback effect arising from the dependent variable. In much the same way, real interest rates had the expected positive sign but, as with the budget deficit variable, were not generally significant. Finally, the only variable that tended to be persistently more significant with the expected positive sign was the personal savings rate, which would perhaps suggest that the behaviour of household savings do have the anticipated positive Keynesian effect on business debt." (Lavoie and Seccareccia 2001:2090)

[RESUL] Summary of the econometric estimations:
- Budget defints was not always significant
- Real interest rates had the expected positive sign, were not generally signigicant
- household saving do have the anticipated positive effect (note on p.2090)

"By implication, this would indicate that, in the Granger sense, variations in debt/equity could have caused changes in real GDP growth (which is compatible with the basic principle of effective demand), while, at the same time, we have evidence to support the null hypothesis that changes in real GDP growth would not have caused changes in debt/equity. In this latter case, once again, the Minsky hypothesis did not fare very well, at least, with existing Canadian observations on aggregate corporate indebtedness." (Lavoie and Seccareccia 2001:2091)

[RESUL] Granger causality tests

GDP !-> debt-equity
debt-equity -> GDP (note on p.2091)

"The purpose of our chapter has been to explore both theoretically and empirically one of Minsky's most important contributions to economic analysis: the financial fragility hypothesis." (Lavoie and Seccareccia 2001:2091)

[OBJ]~ (note on p.2091)
