:PROPERTIES:
:ID:       ad8d247d-82a0-498c-a19a-4e3eb1653c55
:END:
#+title:      data_assimilation
#+date:       [2024-03-14 qui 12:04]
#+filetags:   :calibration:overview:placeholder:
#+identifier: 20240314T120430


#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+options: num:nil ^:{} toc:nil

* Introductory notes

This section is highly based on [[denote:20250205T112724][Data Assimilation: A Mathematical Introduction]]



** Mathematical background

*** Notation

- Unknown :: \(a\)
- Data :: \(b\)
  - \(\mathbb{P}(b)\) :: Normalizes the posterior to a pdf
- Prior :: \(\mathbb{P}(a)\)
- Likelihood :: \(\mathbb{P}(b|a)\)
  - Easily to be determined explicitly
- Posterior :: \(\mathbb{P}(a|b) = \frac{1}{\mathbb{P}(b)}\mathbb{P}(b|a)\mathbb{P}(a)\)


** Dictionary

This section provides a dictionary for each term used in DA, translated to [[denote:20250202T114248][Agent Based Models]] terms.

- Single [[denote:20250203T181801][Monte Carlo Simulations]] :: Particle;

* Different approaches to DA

The [[denote:20250203T182500][Particle Filter]] used in [cite/t:@sun2022] is the following:
- Perform \(N\) [[denote:20250203T181801][Monte Carlo Simulations]]
- Compute the weight of each realization \(i\) (or particle)
  - The weight takes into consideration the value of state variables of this realization and compares with the observational (data)
    - The more distant a realization is to the data, the lower is its weight
  - In [cite/t:@sun2022], they perform a resampling approach so there is not particle weight that becomes neglectable.
    To do this, they draw \(X\) copies from a multinomial distribution, then remove the initial realization.
    This resample procedure is not employed to each time step, but only when some trigger conditions are match.
    For this specific paper, the resampling is relevant for the model stability.
- From their theoretical model, the compute the output/forecast values (or [[denote:20250202T115137][Bayesian Prior]]) given the past observed data available
- Then, they update the weights considering the next available data
- Using this new weights, computes the analyzed values (or [[denote:20250202T115114][Bayesian Posterior]]) and its corresponding distributions

The drawbacks of the [[denote:20250203T182500][Particle Filter]] is its weaker statistical properties (on convergence) and higher computational costs.
On the other hand, it does not need to make any assumptions regarding the variables' distribution.
Similarly to the [[denote:20250202T122100][ensemble_kalman_filter]], it is more appropriate to [[denote:20250203T182206][Non-linear Model]].

* TMP :noexport:

# Local Variables:
# jinx-languages: "en_US"
# End:
