#+title:      Medium-Term Business Cycles
#+date:       [2024-09-06 sex 14:57]
#+filetags:   :bib:dsge:rbc:technologicalchange:
#+identifier: 20240906T145727
#+reference:  comin_2006_mediumterm
#+bibliography: ~/Org/zotero_refs.bib

STATUS: INCOMPLETE

* FISH-5SS

** 5SS


** Abstract

#+BEGIN_ABSTRACT
Over the postwar period, many industrialized countries have experienced significant medium-frequency oscillations between periods of robust growth versus relative stagnation.
Conventional business cycle filters, however, tend to sweep these oscillations into the trend.
In this paper we explore whether they may, instead, reflect a persistent response of economic activity to the high-frequency fluctuations normally associated with the cycle.
We define as the medium-term cycle the sum of the highand medium-frequency variation in the data, and then show that these kinds of fluctuations are substantially more volatile and persistent than are the conventional measures.
These fluctuations, further, feature significant procyclical movements in both embodied and disembodied technological change, and research and development (R&D), as well as the efficiency and intensity of resource utilization.
We then develop a model of medium-term business cycles.
A virtue of the framework is that, in addition to offering a unified approach to explaining the high- and mediumfrequency variation in the data, it fully endogenizes the movements in productivity that appear central to the persistence of these fluctuations.
For comparison, we also explore how well an exogenous productivity model can explain the facts.
#+END_ABSTRACT



** Background and motivation

- *Theoretical Background:*
-


** Supporting Ideas and hypothesis


*** Supporting Ideas


*** Hypothesis


** Purpose and contribution


** Relevance

- This is one of the few DSGE models that have [[denote:20240906T150431][Technological change]] together with deterministic growth
  - As a consequence, this is a suitable for comparison with [[denote:20250202T114248][Agent Based Models]], in special with those with [[denote:20240708T155455][Schumpeterian growth models]] flavor


** Methodology


- *Sample:*
- *Model:*
- *Variables:*
- *Shocks:*
- *Validation:* The model is validated by contrasting the estimated results with statistical moments of empirical data. In adition, the authors also compare the cross correlations to evaluate the cyclical comovements of data/simulated pairs.
  - In particular, the authors contrast the unconditional standard deviation in respect to different frequencies
  - Instead of contrasting simulations, the authors evaluate how a *single shock* --- which is the driving force of the model --- is able to explain the unconditional moments of data
  - They also contrast the baseline model with a 2-sector RBC
    - The reason is to check how well a more contentional model could capture the results and, as a consequence, enhance the reason to have endogenous technological change.

** Results

General results:
-

Specific results:
-

** Interesting findings and not categorized stuff


** Critics




* Additional Backlinks

* References

#+print_bibliography:
