#+title:      Agent Based Summer School - Sant'Anna
#+date:       [2024-07-07 dom 18:34]
#+filetags:   :summerschool:
#+identifier: 20240707T183450

[[denote:20250202T114248][Agent Based Models]]

* Introduction to agent based models and complexity theory - Fagiolo


Every model is a simplification of the reality.
The question is about the level of simplification adopted.

- Rationality: agents do not make persistent mistakes when predicting the beheviour of other agens (Nash Equilibrium) or of the state of economy ([[denote:20240708T113039][Rational Expectations]])
- [[denote:20240708T113226][Representative Agent hypothesis]]: Agents in the model may differ as to their characteristics and behaviour, but this is often *irrelevant* to the outcomes of the model, as the average behaviour of the economy tracks the behaviour of the average individual
- Interaction: agents in the model either do not interact at all (General equilibrium), or they interact with everyone else (Game theory) or cannot interact (RI model)
- Equilibrium: The model must be studied when in equilibrium, therefore, the only legitimate prediction of the model is when it is in equilibrium

This over-simplifying assumptions impose top-down restrictions.
The follow-up question is about the validation of the assumptions in the real data?
- Agents are boundedly rational
  - Have limitedcapabilities
  - Make persistent mistakes
  - Inconsistent expectations
- Heterogeneity persistent and relevant for the aggregate behaviour of the economy
  - The average behavior of the economy is different of the behaviour of the average behaviour
  - Implicity assumes that the system is linear
- Agent interact in non-trivial networks, in way that are complicated but predictable, an never as it is assumed in neo-classical models


* Complexity economics and coevolution - Almudi and Fatas-Villafranca

** Example of simple model

Consider a population of agents with \(n\) possible behavioral rules.
...
Checking the references mentioned there, it is possible to show how heterogeinity (little by little) enters into the models.
They show that the fitness function, for example, depends on several moments of the statistical distribution.

Demand is the key driver of the mechanisms of the competitiveness fitness function of the model (Depending if it is "bieases" towards price or competiviveness).


** Coevolution

- Coevolution exists since the beginning of evolutionary theory
- Innovation and technological change happens in a institutional environment
  - They evolve together
  - It does not take in place in a isolated setup

Coevolution takes place among complex populations (set of agents), and not among variables.
This agents are endowed with different strategies, potential empirical replicated traits (?).
Then, need to identify if the replication/selection/innovations are bi-drectionally affected.

In the example, low knowledge radius in capital goods sector implies that consumption goods firms with low understanding of more sophisticated machines (check in the paper).
On the other way around, the consumption goods firms that are selected are the ones with low performance, selection the more cheaper machines.
As a consequence, downstream will start to compete in terms of prices.

* Schumpeter meeting Keynes: policy-friendly models of economic growth and business cycles

** Introduction

*** Motivations

The puzzling dichotomy between growth and business cycles theory.
Consequences:
- [[denote:20240708T155455][Schumpeterian growth models]] never meets Keynesian theory of [[denote:20240708T155553][Effective Demand]] and aggregate [[denote:20240708T155635][Business Cycles]]
- A Peculiar schizophrenia between macroeconomic policies, if any, for the "short run" and "structural" policies for the long run

Briding short- and long-run dynamics in a model able to robustly replicate most relevant micro and macro [[denote:20240708T155703][Stylized Facts]]


** Model structure
*** Time step

1. Bank fix the maximum credit supply
2. KG performs R&D, innovate and imitate
3. CG fix production and investment
4. Firms asks for credit, machine are paid
5. Production begins and firms hire workers
6. The consumption-good market opens
7. Firms repay their debt, bank profits and equity are computed accordingly
8. Firms' entry and exit
9. Machines are delivered to consumption-goods firms

*** Technical change

There is both [[denote:20240708T155825][Product Innovation]] and [[denote:20240708T155856][Process Innovation]] because productivity of vintages improve them (product), while the production technique is a process innovation.
The innovation is a two step stochastic process, in wich R&D is linked to innovation/imitation.

The beta distribution is chosen because is very simple, but easily able to search the shapes (flexibility).
The support of this distribution is the center of the current level of the technology.
The idea is to have failures in the innovative process.
Also, the goal is to have non-linearities with the step.

*** Investment

The payback replacement parameter indicates the likelly to replace the vintages.

*** Financial Structure

There is a financial hierarchy in which firms prioritize internal funds rather than external finance.
The limit of credit is exogenously defined.

- Fixed number of banks
- Banks are heterogenous in their number of clients
  - Draw from a Pareto distribution
    - Input validation from the data
- There is a capital adequacy ratio: multiple of the equity of the bank
- There is an endogenous capital buffer: credit supply is reduced if the bank is fragile
  - The higher the number of bad loans, the less willniness the bank is to lend credit
- Bank allocate assuming a pecking-order base, ranking the firms according to their net worth
  - In reallity, firmrs either get the total amount of credit and not a fraction of the requested value
  - There is heterogeneous risk premium accirdubg to the credit class (\(q\)) togehter with a scalling parameter
    - This define the interest rate

*** Capital goods market


Select the producer with lowest \(p_{i} + c_{i}^{1}b\) according to the information contained in the "brochures".
This is price vs quality ratio.

*** Consumption goods market

- Imperfect competition: prices $\Rightarrow$ variable unit cost of production
  - Note: prices do not clear the market. They can accumulate inventories
- Market-share evolveca rcording to a "quasi" replicator dynamics (from evolutionary biology)
  - This ensure the interactiona mong CG firms
  - A spicie that is more fitted to the environment (more competitive), can survive (increase market-share)
  - Otherwise, only firms with the lowest price would dominate the market
    - The other assumption is that households have imperfect information to know the best price. This would explain why the best first do not dominates the market

*** Entry and exit

- Newest firm are smaller than those on the market

** Empirical validation

- Haldande and Turrell, 2018

[[denote:20240708T155703][Stylized Facts]]:
- Self sustained, endogenous growth with endogenous business cycles
  - The [[denote:20240708T155635][Business Cycles]] is not periodic, but stochastic
  - The Dickey-Fuller on the log and level
- Correlation structure
  - Consumption, net investment, and changes in inventories are procyclical and coincident variables
  - Countercyclical unemployment
  - Countercyclical prices, procyclical inflation
  - Countercyclical markups
  - Total credit is pro-cyclical and coincident
    - It is important that this amplify the business cycles
- Fat tail growth distribution
  - Not normal distribution of GDP (not Gausian)
  - Tails are more important, indicating that [[denote:20240708T155635][Business Cycles]] are a complex phenomena
- Banking crises
  - Bank profits and bank equity are procyclical
  - Boom abd burst cycles in the credit
- Large productivity dispersion among firms
  - Mean productivity overtime is growing, but the second moment is positive and constant
    - Not too much different, but persistent heterogeneous
  - Inter-firm productivity differentials are persistent over time
- Firm size distribution is right-skewed than log-normal distribution
  - Coexistance of very few big firms together with a lot of small firms
- Growth rate distribution of firms is fat tail (Subotin distribution)
- Investment lumpiness
  - A lot firms investment almost-zero together with a few investing a lot

** Policy experiments

*** Schumpeterian policy

**** Changes in the techonological opportunity

Changes of the mass of the Beta distribution governing new technological draws.
*Results:* GDP growth rises, unemployment decrease with increasing technologia oclpportunities

**** Search capabilities

Changes in the parameters affecting R&D.
*Results:* GDP growth rises, GDP volatility and unemployment fall as the R&D productivity increases.


**** Changing appropriability conditions

Includes a patent system.
*Results:* reduce GDP growth raten and raise unemployment.
Because the restrict other firm to innovate.
The question is how much patent do you need.


*** Competition policy

**** Anti-trust policy

Capital good firms with a market-share higher than a fixed threshold cannot add new customers.
*Results:* Spurs GDP growth and it reduces both unemployment rate and output volatility.

*** Keynesian policy

**** Eliminate the public sector

Keynesian policies are necessary to support sustained long-run economic growth.
Schumpeterian policies are not enough to push the economy away from low growth trajectories.


* Evolutionary agent-based models of technical change


Generic properties of [[denote:20240708T111511][Complex system]]:
- Interaction implies emergence
- No isomorphism between macroscopic phenomena and the behaviour of individual entities
- Complexity is intimately related with non-linearities
  - History counts
  - Knowledge accumulation involves dynamic increasing returns
    - This is an extreme source of non-linearity
  - General equilibrium is incompatible with innovation due to non-linearities generates multiple paths
- Evolution involves the emergence of new elements (entities, morphologies, etc)

Major questions of political economy:
- What are the drivers and patterns of change of the "capitalist machine" of production and innovation?
- What are the mechanisms of (imperfect) coordination among a multitude of self-seeking agents often characterized by conflicts interests?
  - Imperfect coordination is the output of change
- Why do some countries succeed in industrializing while others remain dramatically poor?

Stylized facts to be explained:
- The patterns of development
  - Forging ahead
  - Catching-up
  - Falling behind
- The Kuznetsian patterns of long-term growth
  - Being right or wrong
- The Kaldorian stylized facts
- The macroeconomic patterns
  - Trends
  - Fluctuations
  - Crisis
  - Quite frequent involuntary unemployment

The major building blocks for an answer:

- The generation of scientific knowledge
- The development of new artifacts and techniques of production
- Organization of production and distribution
- The political and legal structure
- The cultural domain

* Labor market

** Regimes of regulation

Domains of [[denote:20240710T103520][Regimes of regulation]]:
- Accumulation regime :: relations among technological progress, income distribution and aggregate demand
- Institutional forms :: wages-labor nexus and nature of the State
- Mode of regulation :: mechanisms by which the former two domains evolve, develop, and interact.
  - This generates phases of coordination, mismatches, cycles and crises.
  - For example, the gap between wage and productivity growth rate reflects a uncoordinated system
  - Decentralised decisions are taken without the need of each individual or organization to understand the whole of the system
  - It shapes the accumulation regime
  - It reproduces a system of social relationship


** Model setting

*** Theoretical questions

- Why involuntary unemployment?
- why is not the economic system able to generate full employment?


The standard answers depart from NAIRU and from search and matching models.
The general conclusion, unemployment is a supply-side problem associated with rigidities and firctions.

*** Types of flexibility

Defined by Atkinson (1985)

- External numerical flexibility :: implies that workers can be quickly, cheaply and easily hired-fired
- Financial flexibility :: flexibility of monetary wages
- Internal flexibility (not modeled) :: workers can be internally reallocated


* Climate change

** Empirical evidences

- The probability of adapt to economic damages of natural disasters are not increasing in the same pace as the recurrence of this economic damages.

** Model

- Machines are characterized by energy efficiency (EE) and environmental friendliness (EF)
- Technical change occurs along all the three dimensions
  - The core of the model is technical change
  - Technological distance needs to be adjusted
    - Includes energy efficiency and emission intensity on top of labor productivity
- Production also depends on energy and carbon taxes
- The introduction of this modifications also affects the replacement investment
- Carbon taxes can also cause economic crisis because it reduces investment
- The energy sector is produced
  - Plants are heterogeneous in terms of cost structure, thermal efficienes and enviromental friendliness
    - The unit cost of green energy is zero, while dirty energy has a unit cost related to fossil fuels
  - Total energy production cost depends on the mix of active plans
  - Energy sector invest to axpand production capacity
    - The cost of bulding up a green plant is positive, while for dirty energy is zero
      - Firms invest in R&D in order to reduce the cost of bulding up the green energy
  - The price is defined by the last (infra-marginal) plant activated to produce energy
    - The regulatory authority sort the plants in terms of the cost of production
- The climate box define the climate model
  - Links carbon emissions to the dynamics

** Question

- Clarification: Is the carbon taxes homogenous accross sectors?
- Clarification: Is the desired capital goods stock affected be the energy and emissions?

* Financial markets, regulations, and monetary policy: insights from Agent-Based models


- The financial system is stable not when banks are isolated safe, but their network should be safe
- Bank bankrupcy is also costly
- This are cycle model, so results are not in terms of growth rate

** Q&A

- Mention QCA that could help with the qualitative configurations
  - In QCA as well, configurations are not additive
- Ask about asset prices and how this could create different channels for houshing market
- Are there government consumption?
  - If this government consumption has positive growth rate, the model should have growth
- Is there residential investment? Supply of houses are fixed?
  - A: No constructor sector
- Are asset inflation considered to affect consumer credit?
  - Specially related with house prices and its effects of collateral of households

* Empirical validation of agent-based models

** Key notions

*** Estimation

- Identification: search of conditions under which the distribution of the data at the true parameter is difference from that at any possible parameter
- Estimation is similar to calibration but relies on global identification
 
*** Validation

- Validation should provide a measure of adequacy of a model w.r.t. to same purpose
  - In ABM literature:matching between model's and real world DGP
  - If the purpose of the model is causal analysis: matching should be done in terms of *causal structures*

*** Causation

- Different accounts of causality
  - Difference-making account
  - Production account
- The ideia is that a causal calim is credible if it is sustained by both types of evidence.
  - This is the ideia of "evidential pluralism"
- ABMs are string in contribution to causal inference both from a machanistic and a Difference-making point of view


** Calibration methods in ABM literature

*** Indirect inference

*** Method of simulated moments

*** Simulated maximum likelihood

*** Model confidence set

*** Machine learning techniques

** Causal inference approach to ABM validation

*** General protocol for calibration and validation
