#+OPTIONS: num:nil ^:{} toc:nil
#+title:      Forecasting in a Complex Environment: Machine Learning Sales Expectations in a Stock Flow Consistent Agent-Based Simulation Model
#+date:       [2025-02-06 qui 12:14]
#+filetags:   :bib:
#+identifier: 20250206T121427
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl
#+reference:  catullo_2022_Forecasting



* FISH-5SS


** 5SS

[cite/text:@catullo_2022_Forecasting;] present an macroeconomic [[denote:20250202T114248][Agent Based Models]] in which firms employ [[denote:20250203T181113][Machine Learning]] algorithms to predict sales directions.
In general, they report than an improve in firms predictions increase profits, reducing wage-share and, long-run economic growth.
Those results are robust to the policy experiments (monetary and fiscal shock).

** Background and motivation

- Orthodox macroeconomic models  rely on [[denote:20240708T113039][Rational Expectations]] hypothesis, which is not realistic.
  - There still room for heterodox models to improve and avoid [[denote:20250203T180947][Lucas' Critique]]
  - Besides there are some changes in orthodox models (such as [[denote:20250203T180644][Learn to Forecast Experiments]]), they are still quasi-rational models since agents still maximize intertemporally
- It dialogues with [[denote:20250203T184226][Switching Mechanisms]], but do not employ them
- Some [[denote:20250202T122308][Experimental Finance]] papers provide evidence that simple heuristic rule outperform --- or explain agents behavior better --- compared to more sophisticated rule [cite:@anufriev_2012_Evolutionary;@hommes_2013_Behavioral]
  - In this direction, the paper are accordance with [cite/text:@dosi2020] that more sophisticated rule imply worse macroeconomic performance

** Supporting Ideas and hypothesis

- This paper is based on a simplified version of[cite:@caiani_2019_does]   in which:
  - Wages update rule are simpler
- In each scenario, all firms follow the same behavioral rule
- It is a pure closed labour economy
  - So, there is no capital, and no investment
    - It is not possible to compare with other models
  - The model is "Wage-led"
- The number of firms and banks are endogenous and depends on households' capital contribution
- As in [cite/text:@caiani_2019_does], firms updates sales and prices decisions based on stochastic procedures
- The innovative procedures follows [cite/text:@dosi_2010_Schumpeter]
- Each household can be employed by more than one firm
  - This was adopted to reduce computional cost
  - Workers that work in R&D receive extra wages
- Consumption decision depends both on disposable income and on financial wealth (banking deposits)
- Firms follow an monopolistic [[denote:20250203T175458][Hotelling Competition]]
  - Households demand depends both on sensitivity on prices (related to preferences) and on distance
- Banks have a [[denote:20250202T115430][Capital Requirement]] parameter and have a minimal reserve requirement
- Central Bank follow a [[denote:20250203T184305][Taylor Rule]]
- The entrant firm heritage the data of a randomly choose incumbent firm
- For some reason, the model starts with zero public and private resources
  - They argue that follows [cite:@godley_2007_Monetary], in which credit creating allows economy to grow

** Purpose

- Analyze how more sophisticated prediction rules affect macroeconomic performance
  - Actually, this paper is more a proof-of-concept in order to propose a paper in which firms react to news, passing Lucas' Critique

** Contribution

- Improving behavioral rules is the next step in Agent Based Models as a policy tool

** Relevance

- For the [[denote:20250203T172959][Dot-Com Crisis]] chapter, this paper provide an dialog with Agent Based Models that deals with [[denote:20240708T175224][Expectations Formation and Behaviour Macroeconomics]]

** Methodology

- Macroeconomic Agent Based Models in which firms employ [[denote:20250203T181113][Machine Learning]] algorithms regarding sales expectations
- The authors evaluate the *direction* of firms' sales expectations and not the exact value using Autoregressive and [[denote:20250203T174635][Genetic Algorithm]] approach
  - The Genetic Algorithm depends on firms' past sales, aggregate inflation and unemployment growth rates
  - Model is calibrated in order to generate zero means forecast errors
  - It could be argued that the [[denote:20250203T184155][Supermultiplier Models]] also related the investment decision to the direction of the aggregate demand ([[denote:20250202T120807][Innovation bubble ABM]])
- The experiments are:
  - Tight capital requirements ([[denote:20250203T181204][Macroprudential Policies]] shock)
  - Decrease in public target deficit

** Results

- The negative shocks have persistent contrationary effects, but the prediction precision is high depending on the magnitude of the shock
- Changes in the market competition does not affect firms' forecast precision
- Using more sophisticated rules generates higher leverage, implying an economy more sensible to do exogenous shocks

** Interesting findings and not categorized stuff


- The monetary shock seems to have faster effects
  - This may be related to the banking credit duration
- For the Innovation bubble ABM chapter, it could be interesting to plot some aggregate variables according to the proportion of some heuristic rule in the x-axis (figure 10 in this paper)

** Critics

- Banking credit last for only one period. This may affect the results of the monetary shock
- Since all firms follow the same behavioral rule, there still room for my own contribution (endogenous heuristic emergence)
- The Genetic Algorithm uses inputs that firms seems to not be so much attentive ([cite: see  @coibion_2018_How;])

** Abstract

#+BEGIN_ABSTRACT
The aim of this paper is to investigate how different degrees of sophistication in agents’ behavioral rules may affect individual and macroeconomic performances. In particular, we analyze the effects of introducing into an agent-based macro model firms that are able to formulate effective sales forecasts by using simple machine learning algorithms. These techniques are able to provide predictions that are unbiased and present a certain degree of accuracy, especially in the case of a genetic algorithm. We observe that machine learning allows firms to increase profits, though this result in a declining wage share and a smaller long-run growth rate. Moreover, the predictive methods are able to formulate expectations that remain unbiased when shocks are not massive, thus providing firms with forecasting capabilities that to a certain extent may be consistent with the Lucas Critique.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)


"how different degrees of sophistication in agents' behavioral rules may affect individual and macroeconomic performances"
([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 1]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=1&annotation=M9UKAYPZ][pdf]]) [OBJ]

"agent-based macro model firms that are able to formulate effective sales forecasts by using simple machine learning algorithm" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 1]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=1&annotation=VRWDG92L][pdf]]) [METHOD]

"firms to increase profits, though this result in a declining wage share and a smaller long-run growth rate" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 1]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=1&annotation=XCK64AWK][pdf]]) [RESULT]

"effect of fiscal and macroprudential shocks (a variation of the capital requirement for banks)" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 1]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=1&annotation=JJRK8XE7][pdf]]) [METHOD]

"In particular, in every period each firm formulates a forecast on the growth rate of its sales and uses it to determine its production choices." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=LCP9XNV9][pdf]]) [METHOD] It seems related to the intended Dot-Com model

"The model is based on Caiani et al. (2018, 2019a)" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=X4N8AA9B][pdf]]) [LITERATURE] Family model

"We test different methods to make sales forecasts: a genetic algorithm (GA), an autoregressive model (AR) and a naïve approach (N)" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=KTETDC5R][pdf]]) [METHOD] Different rational heuristics applied.

"The system modeled is a wage-led closed economy (Caiani et al., 2018; 2019a); therefore, a lower wage share tends to reduce the long-run growth trend" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=ATRS5JXQ][pdf]]) Model structure

"We compare different scenarios featured by different learning rules, though within each scenario all firms behave according to the same rule" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=JZXHP6VV][pdf]]) [IMPORTANT] This is different from the proposed Dot-com model.

"This results in a rising profit share that has as a counterpart a decrease of the wage share. This is what we can expect in a closed economy, which is the kind of economy we model in our paper" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=22PSHXBL][pdf]]) [RESULT] Higher profits, lower wage-share, lower growth rate.

"In a sense, then, firms endowed with more sophisticated forecasting rules exhibit a behavior which is, to a certain extent, Lucas critique proof" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=PHSFWJCK][pdf]]) [INTERESTING]

"Mainstream macro models typically assume that agents are characterized by rational expectations (Muth, 1961)." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=JQ3VPNTI][pdf]]) [LITERATURE] Context

"However, the impression is that this literature is providing some sort of quasi-rational expectations equilibrium models," ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 2]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=2&annotation=BCSXKSD3][pdf]])
"which only partly deviate from the fully rational benchmark, perhaps underrating the macroeconomic implications of a different modeling of agents' behavior more in line with the original interpretation of bounded rationalit" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 3]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=3&annotation=TSY9BEX9][pdf]])

"though they are for example able to understand that a trend is present in the evolution of a variable. This is the case of a Learning-To-Forecast (LtF) experiment" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 3]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=3&annotation=82R5Q6N9][pdf]])

"For instance, three typical patterns in aggregate price behavior have been observed in the context of Learning-To-Forecast experiments (Hommes et al., 2005): slow monotonic convergence, permanent oscillations and dampened fluctuations" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 3]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=3&annotation=6C4H9SXZ][pdf]]) [LITERATURE]

"Anufriev and Hommes (2012) show that a simple model of individual learning can explain these kind of aggregate regularities emerging in experimental data (see also Hommes, 2013, for a more general view): the model is based on evolutionary selection among heterogeneous expectation rules driven by their relative performance; in other words, agents can switch from a rule to another one based on the relative performance of each single rule" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 3]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=3&annotation=DKUT3WRT][pdf]]) Mention of rational heuristic rule

"They show that simpler rules outperform more sophisticated ones provided that the memory length is sufficiently long for an effective adaptive foresigh" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 4]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=4&annotation=QP9VHMCU][pdf]])

"Indeed, a sophisticated rule like recursive least squares give rise to less accurate individual predictions and worsen the macroeconomic performance, suggesting that rather than being rational, agents following “rational heuristics" may lead to more accurate individual forecasts and better aggregate result” ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 4]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=4&annotation=4WUVLA8R][pdf]])

"In the case of our paper, then, while individual forecasts ameliorate due to more rational behavioral rules (with zero mean errors), economic growth decelerates due to a lack of aggregate deman" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 4]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=4&annotation=5R3GDNIA][pdf]]) 5SS

"our aim is to provide a proof-of-concept: endowing firms with machine learning sales expectations allows us to demonstrate that agents are able to react to news, like shocks, returning to zero mean error in a reasonable time, thus passing to a certain extent the Lucas critique (Lucas, 1976)." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 5]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=5&annotation=CWLUKAG9][pdf]])

"is that the model simulates a closed economy" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 5]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=5&annotation=7S644KHR][pdf]])

"been simplified to avoid the necessity of formulating expectations on unemploymen" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 5]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=5&annotation=JX2MFM8V][pdf]])

"The model considers a 'pure labor' economy where firms' production is carried out by using labor only." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 5]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=5&annotation=GTCWL3DK][pdf]])

"endogenously varying number of firms (It ) and banks (Zt" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 5]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=5&annotation=CETNJ29U][pdf]]) [HYPOTHESIS]

"simple scheme dependin" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 6]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=6&annotation=53R7BXD3][pdf]])

"The expenditure in R&D determines the probabilities of increasing productivity (Prsuccessi,t )throughboth genuine incremental innovation and imitation (Dosi et al., 2010)" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 7]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=7&annotation=47KLUM3Q][pdf]])

"credit lasts for only one period" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 7]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=7&annotation=MLXPKABW][pdf]]) [HYPO]

"Each households can be employed by different firms (until a maximum of ψ firms" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 7]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=7&annotation=6KATQSD9][pdf]]) "Moreover, workers receive an extra wage from innovation activities" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 7]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=7&annotation=LG6JAQBN][pdf]]) [FINDS]

"Households' desired consumption (CD i,t ) is a function of current disposable income (yD h,t ) and current wealth held in the form of deposits (Dh,t ), given the marginal propensities cy and cd" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 8]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=8&annotation=WGQGCD97][pdf]])

"We define dhi as the distance between consumer h and a firm i. Consumers samples randomly ψ firms and compare the supply of those firms ranking them according to price and variety; household h prefers firm i to firm j if" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 8]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=8&annotation=NH3CU75M][pdf]]) Matching mechanism.

"Households having a positive desired investment act together as an investment fund to create new firms or new banks. If funds collected are sufficient (i.e. see Section 3.6.1), new enterprises are created" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 8]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=8&annotation=PALAGFZN][pdf]])

"capital requirement μ1" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 8]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=8&annotation=754NUKUY][pdf]])

"Banks have to respect minimal reserve requirements, computed as a share μ2 of their deposits: RMz,t = μ2Dz,t" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 9]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=9&annotation=IGMHRK7N][pdf]])

"discount interest rate according to a Taylor rul" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 9]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=9&annotation=IR654NE5][pdf]])

"Thus, the number of banks and firms is determined endogenously in reason of households' investmen" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 10]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=10&annotation=2WLZJAPS][pdf]]) [HYPOTHESIS] Important distinction.

"Moreover, sales expectations cannot be lower that the minimum production level that can be fund with inner resources ( Ai,t wi,t φi,t)." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 10]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=10&annotation=A8FQZEBR][pdf]])

"deciding the direction of change, e.g. increase production, whereas the size of the change is randomly determined by an idiosyncratic shock" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 10]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=10&annotation=8PU2DCYY][pdf]]) [WRITING] Argue that the SSM could be view in this way.

"why we choose to focus only on forecasting the sign of the sales variation in each perio" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 10]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=10&annotation=W9FVCHP3][pdf]])

"On the contrary, when past sales are lower than the desired production and sales expectations are negative, firms reduce prices and production faster than in the baseline rule (by U[0, 2δ])" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 11]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=11&annotation=YYG3UZC6][pdf]])

"The genetic algorithm (GA) uses an informative set of three variables: firm's past sales, the aggregate inflation growth rate and the aggregate unemployment growth rate." ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 11]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=11&annotation=AMP9XBCK][pdf]]) [CRITIC] Empirical literature points that firms are not so attentive to those variables.

"autoregressive model (AR), which provides a punctual sales growth one-step-ahead predictions" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 11]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=11&annotation=8E2CFPS5][pdf]])

"Moreover, in order to increase the precision of these two methods, which rely on the volume of data that they may process, new entering firms inherit data processed by a randomly chosen incumbent firm" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 11]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=11&annotation=99GGLSRZ][pdf]]) [HYPOTHESIS] Data inhitage.

". This is due to the fact that following a procedure inspired by Godley and Lavoie (2007), the model starts with zero public and private resources and gradually money is created, through public expenditure, letting the economy grow" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 12]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=12&annotation=RIHQGXS3][pdf]]) [HYPOTHESIS]

"We calibrated both the genetic algorithm (GA) and the autoregressive method (AR) in order to let their forecasting error converge to zero" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 12]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=12&annotation=DM3U5SW8][pdf]])

"With respect to the baseline scenario, namely the one without expectations (B), using the predictive methods firms tend to increase their production, because they understand that the economy tends to grow. This lead to higher leverage with respect to the baseline scenario and generates also higher concentration in the market (Fig. 3). In turn, higher concentration allows firms to increase their mark-up and, thus, to increase their profits. However, at the same time, higher leverage slightly increases failure probability, contributing to the reduction of the firm number and so to the higher market concentration" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 13]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=13&annotation=7PP8SEKY][pdf]]) [RESULTS] Baseline. It seems to have an minskyian regime

"prudential shock in the form of a tighter capital requirement (μ1) and a fiscal shock in the form of a cut of the public target deficit (dmax)" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=SNP9Z9FQ][pdf]]) [EXPERIMENTS]

"shocks have a relevant contractionary impact on outpu" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=DKDJTRTY][pdf]])

"In particular, the effect of fiscal shocks are larger than the credit ones. For instance, a 50% reduction in the capital requiremen" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=7CVL987H][pdf]]) [RESULT

"the shocks have qualitatively the same impact on the economy" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=DGCC8LGN][pdf]]) [RESULT]

"more sophisticated expectations their leverage tends to be higher, thus the economic system is more vulnerable to exogenous shocks" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=EMYY89K5][pdf]]) [RESULT]

"my. The negative impact of the fiscal shock tends to be larger but the macroprudential shocks have faster effect" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=BJK7HJZD][pdf]]) [MEMO] Credit last for one period only.

"Considering the GA predictive method, until the shocks are not too strong, agents are still able to formulate unbiased expectations" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 14]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=14&annotation=T27ARULI][pdf]]) [FINDS]

"We modify the level of competitiveness, varying the parameter β, which represents the consumers' sensitivity to price. When we increase β the importance of prices decreased and thus the market becomes less competitive" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 18]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=18&annotation=5H8EBDUD][pdf]]) [EXPERIMENT]

"GA firms make higher profits; this results in a lower growth due to a reduced demand" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 18]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=18&annotation=WYPMTAFR][pdf]]) [RESULT]

"Changing the level of competitiveness does not impact on the predictive performance under fiscal shocks" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 18]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=18&annotation=Z5LB3YU7][pdf]]) [RESULT] ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 19]]) {PLOT] Possible plot: x-axis with the proportion of firms with an specific expectational rule.

"While, considering macroprudential shocks, when competitiveness raises (β = 0.2) the effectiveness of the predictive method slightly decline" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 20]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=20&annotation=RSQH59RE][pdf]])

"Larger size causes a reduction of the number of firms, thus competition among firms becomes weaker and firms see their profits increase with respect to wages" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 20]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=20&annotation=K756X73X][pdf]]) [RESULT]

"In this last case, agents tend to have higher leverage, so they are more affected by restrictive macroprudential measures" ([[zotero://select/library/items/2HPVD3WQ][Catullo et al., 2022, p. 20]]) ([[zotero://open-pdf/library/items/H8DEA2CT?page=20&annotation=8RHNDB6B][pdf]])

* Additional Backlinks

[[denote:20250205T154234][Journal of Economic Dynamics and Control]]

[[denote:20250203T180559][Learning and Heuristics]]

[[denote:20250202T114248][Agent Based Models]]

[[denote:20250204T144517][Forecast]]

[[denote:20250203T174635][Genetic Algorithm]]

[[denote:20250203T181113][Machine Learning]]

* References



#+print_bibliography:
