#+title:      Trabalho com Projetos Integradores
#+date:       [2025-08-09 Sat 11:27]
#+filetags:   :univesp:
#+identifier: 20250809T112751

* Tema 2: Metodologias ativas de aprendizagem, PBL e Design Thinking

** Metodologias ativas de aprendizagem

Nesse vídeo, é discutido em que consiste a etapa final do PI em termos de como é avaliado.
AO longo do vídeo, ressalva as rubricas de correção.

- Instrumentos de avaliação
  - Relatório final
  - Vídeo de protótipo
* Tema 3: Tranversalidade, interdisciplinaridade e trabalho colaborativo ([2025-08-16 Sat])
** Video-aula: Transversalidade, Interdisciplinaridade e Pedagogia de Projetos

- O argumento do vídeo é que a metodologia de projeto permite trabalhar e utilizar elementos de transversalidade e interdisciplinaridade.
  - Transversalidade contempla elementos que são comuns a várias áreas do conhecimento (ética, valores, etc)
  - Enquanto a interdisciplinaridade enfatiza os elementos comuns entre disciplinas e como tais elementos podem ser trabalhados
- Junto disso, a contextualização escolar permite internalizar elementos privados do aluno à vida escolar
  - Soma-se a isso a possibilidade de considerar diferentes tipos de conhecimentos que vão além do conhecimento científico e formal
- Existem objetivos simultâneo na formação escolar: estudo disciplinar e formação ética
- Admiti-se o conhecimento como algo não-linear e associado como uma rede de significados
  - A metodologia de projetos se propõe romper com essa linearidade
    - Esse rompimento se dá pela articulação entre interdisciplinaridade e transversalidade
  - Entende-se projeto como algo diferente de planejamento (previsibilidade)
    - Para elaborar um pedagogia baseada em projeto, o planejamento deve ser feito em rede e contemplar a conexão entre diferente áreas do conhecimento e permitir atividades não previstas
      - Produção do conhecimento como um processo aberto
- Entende-se que esta metodologia é uma estratégia de intervensão em sala de aula, permitindo:
  - Abertura para o novo
  - Perspectiva de transformar a realidade
    - Associado com o exercício de cidadania (ética)
  - Possibilidade de decisões e incertezas
  - Dar um sentido ao conhecimento como busca de relações entre os fenômenos naturais, sociais e pessoais
  - Planejar estratégias que vão além da compartimentalização disciplinar
  - Participação ativa dos estudantes nos seguintes eixos:
    - Indentificação de problemas *contextualizados*
      - Contextualizados pela literatura, inclusive
    - Elaboração de perguntas (em oposição à fornecer respostas)
    - Busca por respostas às perguntas propostas para lidar com os problemas

** Texto-base: A interdisciplinaridade e a transversalidade como mediação do processo de ensino

OBS: Link não está funcionando. Procurando pelo título do texto, não encontrei nenhuma entrada com o mesmo título.

** Fórum de discussão

Nas instruções do fórum, estava indicado para fazer em duplas.
Por se tratar de uma atividade criada a 4 anos atrás, estou considerando que o enunciado não está atualizado e, por essa razão, optei por não respondê-lo.
No entanto, respondi as questões de estudo que avaliei como satisfatórias para atestar a apreensão do material desigado.
