#+title:      Univesp
#+date:       [2025-02-10 seg 21:02]
#+filetags:   :placeholder:
#+identifier: 20250210T210228

* PJI450

** Quinzena 0: <2025-02-10 seg>

- Planilha de alocação
- Localizar os grupos
- Definido o que é esperado em cada quinzena
- Não está definido o produto final deste PI
- Cada facilitador terá uma cerca de 6 grupos
- Entre as quinzenas, haverá uma reunião de dúvidas no mesmo horário
- Atividades:
  - Localização dos grupos
    - Identificar os DRPs de cada grupo
    - Se apresentar em cada um dos grupos
    - Fazer reuniões quinzenais com as equipes
      - Reuniões individuais de cada grupo (1h)
      - Preferencialmente para o fim do dia
        - "Profª, desde o início, em 2023, eu tenho me apresentado na quinzena zero e oferecido os horários disponíveis para orientação. Sempre peço 3 opções de horário e registro, como preferência, quem me envia primeiro, por e-mail. Os horários são sempre fixos para organização deles. Posso continuar desta maneira?"
      - Reuniões devem ficar gravadas e é preferível que todos os participantes entrem de forma síncrona
    - Definir alguns horários para ter as reuniões com os grupos
    - Criar os fórums quinzenais (até <2025-02-14 sex>)
      - Principal meio de comunicação (AVA)
        - Usar e-mail com a supervisora
        - Entrar na plataforma com recorrência
      - Após abertura das salas pelo AVA
    - Pergunta sobre bolsa

#+caption: Localização dos grupos
|---------+----------------------------------------------------------+--------------------------------+----------------------------+------------------------|
|---------+----------------------------------------------------------+--------------------------------+----------------------------+------------------------|
| Matéria |                           Link                           |              DRP               |        Facilitador         |       Supervisor       |
|  <c10>  |                          <c20>                           |             <c32>              |           <c10>            |         <c10>          |
|---------+----------------------------------------------------------+--------------------------------+----------------------------+------------------------|
| PJI450  | https://ava.univesp.br/ultra/courses/_14087_1/cl/outline | DRP05-PJI450-SALA-001GRUPO-015 | 23228537@cursos.univesp.br | magna.rocha@univesp.br |
| PJI450  | https://ava.univesp.br/ultra/courses/_14087_1/cl/outline | DRP05-PJI450-SALA-001GRUPO-016 | 23228537@cursos.univesp.br | magna.rocha@univesp.br |
| PJI450  | https://ava.univesp.br/ultra/courses/_14087_1/cl/outline | DRP05-PJI450-SALA-001GRUPO-017 | 23228537@cursos.univesp.br | magna.rocha@univesp.br |
| PJI450  | https://ava.univesp.br/ultra/courses/_14087_1/cl/outline | DRP05-PJI450-SALA-001GRUPO-018 | 23228537@cursos.univesp.br | magna.rocha@univesp.br |
| PJI450  | https://ava.univesp.br/ultra/courses/_14087_1/cl/outline | DRP05-PJI450-SALA-001GRUPO-019 | 23228537@cursos.univesp.br | magna.rocha@univesp.br |
|---------+----------------------------------------------------------+--------------------------------+----------------------------+------------------------|
|---------+----------------------------------------------------------+--------------------------------+----------------------------+------------------------|

*** Criação de forúms dos grupos

- Ferramenta do grupo, então precisa ser criado na sala do grupo
- Preencher apenas título do fórum e deixar a descrição em branco
  - Título é o título do grupo e incluir nome do facilitador para diferenciar
- Não alterar as configurações para garantir a padronização
- Depois, criar linha de discussão
- Não é possível fazer correção ou exclusão das linhas de discussão
- Colocar as atividades das quinzenas e indicar link para a reunião
- Forúm também é um registro do trabalho dos facilitadores
  - É recorrente que os alunos fazam reclamações via ouvidoria, então esse registro é importante
  - Observar quando algum grupo está inativo
  - Caso ninguém apareça na reunião, deixar registrado no forúm
- É possível fazer uma inscrição no forúm para receber e-mails sempre que algum aluno responde


*** Inter-quinzena

- Visita ao AVA
  - Calendário do PI
    - Início das atividades: <2025-02-17 seg>
      - Nenhuma entrega a ser feita
    - Quinzena 2: <2025-03-03 seg>
      - Entrega do plano de ação <2025-03-11 ter>
        - Delimitar subtema
        - Devem ter feito a visita à instituição
    - Orientar os alunos para não contar com o prazo de carência
    - Datas de início são sugestões
      - Alunos podem antecipar, mas não atrasar
  - O AVA disponibiliza modelos das entregas
  - Pedir para que os alunos levem o termo de autorização do uso da imagem, termo de entrevista
    - Anexado no fim e não no corpo do texto
  - Comum que os alunos utilizem o recurso de que não conseguem contato com o orientador
  - As orientações para as entregas do projeto integrador
- Especificidades do projeto integrador
  - Ter uma visão geral do material das quinzenas
  - Graduandos em pedagogia e já realizaram um PI anteriormente
  - Objetivo geral:
    - *Construir* um brinquedo com materiais de baixo custo e desenvolver um plano de aula que contextualize seu uso.
      Espera-se que a construção se dê em conjunto com uma (um) professora(o) e uma turma de educação infantil.
- Especificidades da quinzena 1
  - Ver REA
  - Reconhecer a importância do trabalho em equipe
  - Definir cenário do projeto
    - Não é necessário que todos possam fazer a visita
  - Entender o contexto do projeto
  - Iniciar o levantamento bibliográfico
    - Os mesmos textos indicados pelos professores podem ser utilizados
- Prioridades da quinzena 1
  - Agendar primeira reunião com o grupo
    - Usar collaborate da sala para agendar a primeira reunião
      - Não usar collaborate do grupo, mas sim da sala
    - Marcar acesso de convidados para criar link
  - Criar fórums da quinzena do grupo
    - Indicar objetivos da quinzena
    - Enviar link para reunião
    - Se ninguém aparecer, fazer a gravação com todas as orientações e disponibilizar
      - Postar a gravação e indicar que ninguém apareceu
      - Ficar ao menos 30 minutos na sala
      - Trabalhos não orientados serão zerados
  - Estou em outro fuso, como proceder?
- Equipe de acessibilidade
- Dúvidas gerais
  - Perguntar hora aos alunos?
    - Preferência nessa semana
      - Preferência para a noite
      - 19h-20h

** Quinzena 1

*** Grupo 015 (<2025-02-20 qui>)

- Iniciar gravação
- Registrar presentes
  - Viviane (Inspetora) - Educação infantil (Tietê)
  - Deisiana (Creche) - Tietê (Não compareceu)
- Breve introdução
- Já trabalharam juntos antes?
  - Ao menos duas pessoas
- Estão geograficamente próximos?
  - Ao menos duas pessoas
- Definido cenário do projeto?
  - Ainda não
- Entendido o contexto do projeto?
  - Ainda não
- Levantamento bibliográfico?
  - Sem comentários específicos
- Como está a divisão de tarefas?
- Horários para as próximas quinzenas
  - Viviane: 19h sem preferência para dia de semana
- Anotações
  - Orientadora não comparecia (PI passado)
  - Pouca adesão das demais pessoas
    - O mesmo ocorreu no PI anterior
      - Apenas 3 pessoas participaram
  - Se sentiram perdidas no PI anterior
  - Autoavaliação: fiz uma reunião com pouca estruturada


*** Grupo 016 (<2025-02-20 qui>)

O PI tem como tema a educação infantil, especificamente, o brincar na construção socioafetiva da criança.
A proposta é que o grupo construa um brinquedo com material de baixo custo e, a partir dele, desenvolva e aplique um plano de aula que contextualize o seu uso.
Espera-se que a construção se dê em conjunto com o professor de uma turma da educação infantil.

- Iniciar gravação
- Registrar presentes
  - Iasmin
  - Rebeca
  - Vanessa
  - Vania
  - Natalia - Gestão de RH
- Breve introdução
- Já trabalharam juntos antes?
  - Sim
- Estão geograficamente próximos?
  - Sim
- Definido cenário do projeto?
  - Talvez com a mesma diretora
- Entendido o contexto do projeto?
  - Quebra cabeça de emoções
  - Roleta de emoções
- Levantamento bibliográfico?
  - Fundamentos da educação infantil
  - Pensamento computacional
- Como está a divisão de tarefas?
  - Tentar que todo mundo participe de todas as atividades
- Horários para as próximas quinzenas
  - Quarta às 21h
- Anotações
  - Primeira PI foi tranquila
  - Assunto que está estudando em uma matéria
  - Creche também ou só fundamental?
    - Checar
  - Sobrecarga no PI anterior
    - Uma das participantes ficou com sobrecarga na escrita



*** Grupo 017 (<2025-02-21 sex>)

O PI tem como tema a educação infantil, especificamente, o brincar na construção socioafetiva da criança.
A proposta é que o grupo construa um brinquedo com material de baixo custo e, a partir dele, desenvolva e aplique um plano de aula que contextualize o seu uso.
Espera-se que a construção se dê em conjunto com o professor de uma turma da educação infantil.

- Iniciar gravação
- Registrar presentes
  - Ana Lúcia: Anhembí
- Breve introdução
- Já trabalharam juntos antes?
- Estão geograficamente próximos?
  - Algumas pessoas sim
- Definido cenário do projeto?
- Entendido o contexto do projeto?
  - Pescaria das emoções
    - Peixe de papelão, EVA
- Levantamento bibliográfico?
- Como está a divisão de tarefas?
- Horários para as próximas quinzenas
- Observações
  - Duas pessoas trabalham em escolas
    - Talvez dê para aplicar em uma delas
      - Conversar com a diretora
  - Já falaram sobre o projeto
    - Ideia de consenso
  - Alguns integrantes não responderam
    - Juliane e Larissa

*** Grupo 018 (<2025-02-21 sex>)

O PI tem como tema a educação infantil, especificamente, o brincar na construção socioafetiva da criança.
A proposta é que o grupo construa um brinquedo com material de baixo custo e, a partir dele, desenvolva e aplique um plano de aula que contextualize o seu uso.
Espera-se que a construção se dê em conjunto com o professor de uma turma da educação infantil.

OBS: Ninguém compareceu.

- Iniciar gravação
- Registrar presentes
- Breve introdução
- Já trabalharam juntos antes?
- Estão geograficamente próximos?
- Definido cenário do projeto?
- Entendido o contexto do projeto?
- Levantamento bibliográfico?
- Como está a divisão de tarefas?
- Horários para as próximas quinzenas
- Observações

*** Grupo 019 (<2025-02-21 sex>)

O PI tem como tema a educação infantil, especificamente, o brincar na construção socioafetiva da criança.
A proposta é que o grupo construa um brinquedo com material de baixo custo e, a partir dele, desenvolva e aplique um plano de aula que contextualize o seu uso.
Espera-se que a construção se dê em conjunto com o professor de uma turma da educação infantil.

OBS: Ninguém compareceu

- Iniciar gravação
- Registrar presentes
- Breve introdução
- Já trabalharam juntos antes?
- Estão geograficamente próximos?
- Definido cenário do projeto?
- Entendido o contexto do projeto?
- Levantamento bibliográfico?
- Como está a divisão de tarefas?
- Horários para as próximas quinzenas
- Observações

** Quinzena 2

*** Conteúdo

**** Tópicos abordados

- Importância da afetividade na formação do sujeito
  - Como docente pode ajudar na construção de laços afetivos

**** Objetivos

- Interagir com a comunidade externa
  - Coletar os dados necessários para a definição do tema e do problema do PI
- Definir e estudar o contexto do problema
  - O que está causando o problema ou a necessidade do contexto?
  - Por que é importante solucionar este problema?
  - Com quais sujeitos seria possível contar para a solução desse problema?
- Criar o plano de ação para a solução do problema escolhido
  - Avaliação:
    - Descreveu o processo de escolha do local com detalhes?
      - Quais outras alternativas? O que definiu a escolha do local?
    - Descrição da conversa com a comunidade externa
    - Identificação de possíveis problemas relacionados ao tema norteador
    - Identificação do tema específico
    - Descrição do planejamento das próximas atividades
    - Adequação da norma da língua portuguesa


**** Avaliação do projeto integrador

- Metodologias ativas de aprendizagem:
  - Design Thinking
  - Metodologia baseada em problemas e por projetos
- Plano de ação (15%)
  - Organização do grupo
  - Avaliado por meio das rúbricas de avaliação
- Relatório Parcial (25%)
  - Título provisório
  - Introdução
    - Cita o tema dentro do objetivo geral do trabalho
  - Desenvolvimento (Metodologia)
  - Referências
    - Ênfase no relaciomento entre as disciplinas
    - Indicar quais disciplinas foram utilizadas para a construção do relatório
- Relatório Final (35%)
  - Título
  - Resumo
  - Introdução
  - Desenvolvimento
    - Adequação à metodologia será considerada
  - Resultado
  - Considerações
  - Referências
  - OBS: Relatório final só será corrigido se houver entrega do vídeo (10%)
- Autoavaliação (15%)

**** Desenvolvimento afetivo

- **Afetividade e Inteligência**: Segundo Piaget, inteligência e afetividade são indissociáveis e fundamentais para a conduta humana.
  - Inteligência e afetividade fazem parte da conduta
- **Estágio Sensório-Motor (0-2 anos)**: O bebê interage com o mundo através dos sentidos e desenvolve sentimentos instintivos ligados ao conforto, desconforto e sucesso/fracasso.
  - Senso estético e do que é agradável e desagradável
  - Início do pensamento pré-operatório e surgimento dos afetos intencionais.
- **Estágio Pré-Operatório (2-6 anos)**: A criança desenvolve capacidade de representar o mundo através da fantasia, imitação e jogos simbólicos, mas sem pensamento lógico.
  - Inteligência pré-representacional
  - **Afetos no Pré-Operatório**: Nessa fase surgem simpatias e antipatias arbitrárias, baseadas em critérios simples, como vestimentas ou gostos similares.
  - **Egocentrismo Infantil**: A criança ainda não compreende totalmente a perspectiva dos outros e tem dificuldades em compartilhar ou entender a noção de empréstimo.
  - Afetos intuitivos
- **Estágio Operatório Concreto (7-11 anos)**: O pensamento lógico começa a se desenvolver, permitindo à criança compreender regras e relações matemáticas de forma estruturada.
  - **Cooperação e Regras**: Nesse estágio, a criança aprende a negociar, argumentar e aceitar normas coletivas, desenvolvendo um senso de justiça e trabalho conjunto.
  - Afetos lógicos, tentativa de coerência por parte da criança
  - Transição para pensamento lógico e começo da cooperação intelectual.
- **Estágio Operatório Formal (a partir de 11 anos)**: O adolescente desenvolve pensamento abstrato, capacidade crítica e ideológica, ligando afetividade a ideais e valores.
  - Desenvolvimento do pensamento formal e conexão da afetividade a ideais abstratos.
- **Piaget e o Método Científico**: Piaget baseia suas teorias em observações empíricas e enfatiza a necessidade de mais pesquisas sobre a afetividade para aprofundar sua compreensão.

**** O lúdico e a afetividade na educação infantil didáticos para o ensino: a prática docente e o planejamento didático

- Importância da Afetividade: A afetividade desempenha um papel essencial na formação do sujeito e na mediação docente, promovendo um ambiente propício ao aprendizado.
  - Piaget destaca a harmonia entre racionalidade e emoção
  - Vygotsky afirma que a razão surge da emoção
  - Wallon considera a afetividade central no desenvolvimento infantil
- Afetividade e Cognição: A afetividade otimiza a interação entre sujeitos, retroalimenta a cognição e fortalece a motivação para o aprendizado.
- Papel do Professor: Demonstrar envolvimento nas atividades lúdicas, observar e planejar cuidadosamente o ambiente de aprendizado são atitudes fundamentais para um ensino eficaz.
  - Compromisso Político do Professor: *Se importar* com os alunos, planejar atividades e criar um ambiente inclusivo são ações que refletem a afetividade no ensino.
- Ludicidade e Aprendizado: O jogo é um elemento central no desenvolvimento humano e está presente na cultura desde os primórdios
  - Huizinga defende que a ludicidade é essencial para a aprendizagem (Homo Ludens)
    - Jogos possuem regras rígidas e inegociáveis, mas podem ser aprendidas de forma mais leve
  - Walter Benjamin é no momento de brincar que o aluno explora o espaço
    - A brincadeira permite que as crianças ressignifiquem seu ambiente, desenvolvendo a criatividade e a imaginação
    - Exploração sem a rigidez da estruturação
  - O incentivo ao uso de fantasias e à confecção de brinquedos favorece a imaginação e o aprendizado espontâneo.

**** O lúdico e a afetividade na educação infantil: Keite Melo

A afetividade e a ludicidade são pilares fundamentais para o desenvolvimento integral da criança na educação infantil.

O envolvimento pessoal e emocional do docente é crucial para a constituição de vínculos afetivos e para o sucesso do processo educativo.

***** A Afetividade na Formação do Sujeito

- Historicamente, a educação priorizou a racionalidade em detrimento das emoções.
- Autores como Vygotsky, Wallon, Piaget e Freire destacam a importância das emoções no desenvolvimento humano.
- A teoria de Wallon coloca a afetividade como central na constituição do sujeito, integrando corpo, razão e emoção.
- A afetividade está diretamente relacionada à aprendizagem, sendo essencial para o sucesso educativo.

***** Afetividade e Ludicidade – Diálogo para Educação Infantil

- A ludicidade, associada a jogos e brincadeiras, é fundamental para o desenvolvimento infantil.
- Para Leontiev, o brincar é a atividade principal da criança, promovendo mudanças psicológicas e sociais.
- Johan Huizinga e Walter Benjamin destacam a importância do jogo e da brincadeira no desenvolvimento cultural, emocional e cognitivo.
- A ludicidade e a afetividade estão inter-relacionadas, sendo essenciais para a educação infantil.

***** Intervenções Docentes para Constituição da Afetividade Junto aos Alunos

Estratégias para promover a afetividade e a ludicidade incluem:

1. Contação de histórias afetivas
2. Brincadeiras de faz de conta
3. Dinâmicas de grupo cooperativas
4. Espaços de escuta e diálogo
5. Atividades sensoriais e artísticas
6. Brincar junto aos estudantes
7. Resgatar brincadeiras tradicionais
8. Olhar nos olhos dos estudantes
9. Explorar o ambiente externo
10. Produzir brinquedos com os alunos
11. Promover brincadeiras que simulem o cuidado com os colegas
12. Cantar músicas e conversar durante cuidados diários














**** Delimitação do tema e o desenho do problema

***** Definição do problema

- Hipóteses:
  - Realizada e visita /in loco/
  - Os dados foram coletados (falas e observações)
    - Isso irá definir como identificar o problema
      - "Foco no usuário" que utilizará o protótipo
- Necessário:
  - Definir local da realização para o desenvolvimento da tarefa
    - Online, no polo
  - Organizar os dados e informações coletadas na visita
    - Uso do caderno de campo
    - Compartilhar dados da entrevista com cada participante
    - Dar sentido ao contexto geral
      - Talvez tratar os dados
  - Escolher quais problemas serão estudados na busca de soluções inovadoras
- Esperado:
  - Definição de uma pergunta: "Como podemos ... ?"
    - Centrado no ser humano?
    - Clareza na conclusão
    - Relevância?
    - Possível de ser resolvido?
      - Condições de resolver dado prazo e estrutura?

***** Organização de dados

- Mapa da empatia
  - Identificação do sujeito da ação
    - O que o sujeito quer, pensa, sente, vê, fala e faz
    - Identificar necessidades a partir da visita
- Organização qualitativa em termos de categorias (tabulação)
- Mapa conceitual

*** Reunião geral

- Criar fórum sobre quinzena 02 de preferência até dia <2025-02-28 sex>
- Participação nas lives é desejável, mas não obrigatório
- Fórum da quinzena mais completo possível
  - Indicar prazo de entrega
- Pode ser uma readaptação, mas precisa ser construído
- Se não tiver orientação, não deve ser avaliado
  - Caso os alunos nunca comparecem nas reuniões
  - Indicar no fórum de que não serão aceitos trabalhos em que o grupo não teve orientação
  - Se ninguém do grupo comparecer, não terá correção
- Se atentar para os casos em que membros dos grupos não estão participando do trabalho
- Incluir para replicar conteúdo do fórum por e-mail
- Brinquedo enquanto algo lúdico
  - Jogo não foge do tema
  - Quem costroi é o grupo e o professor
    - Não é necessário que os alunos da turma construam o brinquedo
    - É desejável que o professor participe, mas não é obrigatório
      - Ouvir sugestões, por exemplo
- Rubricas estão disponíveis (avaliação)
  - Centro de notas
  - Documentos e informações gerais
    - Orientações para avaliação do projeto integrador
- O levantamento bibliográfico é responsabilidade dos estudantes. O orientador pode mostrar como fazer.
  - Kishimoto, Piaget, Bruner, Vygotsky auxiliam da compreensão do brincar.

*** Pauta

**** Tópicos

- Ler a rúbrica de correção do plano de ação
- Tirar dúvidas sobre o plano de ação
- Ler orientações para postagem do Plano de Ação
  1. o AVA ainda ficará aberto para postagens durante o período de carência (entre os dias 12/03 e 16/03), usem esse prazo adicional apenas no caso de imprevistos;
  2. apenas um integrante do grupo deve fazer a postagem dos trabalhos, pelo ícone "Entregas" na aba lateral da página da disciplina ou pela link das "Atribuições do grupo" na página do grupo;
  3. todos os trabalhos devem estar no formato PDF seguindo os modelos disponibilizados pela Univesp na Documentação do PI em "Modelos de Documentos";
  4. os alunos possuem no total três tentativas de postagem, mas não são obrigados a usar todas as tentativas;
  5. após o envio das três tentativas o sistema fecha e não é possível enviar novo arquivo (mesmo que o último envio seja feito antes do encerramento do prazo final);
  6. apenas uma tentativa do grupo será corrigida;
  7. apenas o trabalho desenvolvido de forma colaborativa e com acompanhamento do orientador será avaliado;
  8. ao concluir a entrega, se certifiquem que o arquivo foi enviado! Isso pode ser feito verificando se uma mensagem aparece em rosa no topo da página depois de clicar em Enviar
- Reforçar a necessidade de visitar a escola antes de elaborar o plano de ação. Foco da visita:
  - Apresentar a proposta do PI para a comunidade escolar
  - Reforçar aos professores, coordenadores e diretor que o projeto precisará ser colocado em prática (em Abril)
  - Sugerir que os alunos apliquem um questionário para ajudar a definir o público alvo e definir o problema que será abordado;

**** Checks

- Integração entre os membros do grupo?
- Acompanhamento do material da segunda quinzena?
- Ciência dos prazos referentes às entregas?
- Interação com a comunidade externa?
- Coleta de dados?
- Identificação do problema a partir da interação com a comunidade externa?
- Compreendido o contexto do problema?
- Avaliado se o problema é factível de ser resolvido?
  - Considerando prazos e estrutura da instituição?
- Entrega do plano de ação? (11/03)
  - Identificação de como as tarefas serão divididas?
  - Identificação do local de atuação?

*** Grupo 015 <2025-03-05 Wed>

- Participantes
  - Deisiana
  - Luciana
  - Viviane
  - Julia
  - Valdirene
  - Renata
  - Michele
- Grupo não definiu a escola
- Consiguiram identificar todos, mas a comunicação parece falha
  - Inconsistências durante a reunião


*** Grupo 016

- Presentes
  - Iasmin
  - Ana Beatriz
  - Rebeca
  - Vania
  - Aline
- Grupo não definiu a escola que vão atuar, mas existem alternativas
- Ao que tudo indica, o grupo possui algumas falhas na comunicação
  - Isso emperrou a escolha da escola que irão atuar e discussão de outros assuntos pertinentes à quinzena
- De modo geral, a reunião teve pouca interação com os alunos
- Não foi definido qual brinquedo será construído
- Os integrantes do grupo estão em contato
  - Maior parte do grupo veio do PI anterior

*** Grupo 017

- Presentes
  - Ana Lúcia
  - Bianca Samara
  - Tatiane
  - Amanda
- Grupo está integrado
- Apenas dois membros não foram identificados
- Escola de atuação já foi definida
- Definiram quem irá atuar
- Pediram um parecer sobre o plano de ação antes da entrega oficial

*** Grupo 018 <2025-03-07 Fri>

- Integração entre os membros do grupo?
  - Grupo me relatou estar bem integrado
  - Mas parece existir alguma falha de comunicação
    - Alguns dos integrantes do grupo não estava a par da visita, por exemplo
- Acompanhamento do material da segunda quinzena?
  - Me informaram que estão acompanhando
- Interação com a comunidade externa?
  - Estão em contato com a escola
- Identificação do problema a partir da interação com a comunidade externa?
  - Ainda não foi feito
- Avaliado se o problema é factível de ser resolvido?
  - Considerando prazos e estrutura da instituição?

*** Grupo 019 <2025-03-07 Fri>

**** Quinzena 01 (Reunião Bonus)


O PI tem como tema a educação infantil, especificamente, o brincar na construção socioafetiva da criança.
A proposta é que o grupo construa um brinquedo com material de baixo custo e, a partir dele, desenvolva e aplique um plano de aula que contextualize o seu uso.
Espera-se que a construção se dê em conjunto com o professor de uma turma da educação infantil.

- Breve introdução
- Já trabalharam juntos antes?
- Estão geograficamente próximos?
- Definido cenário do projeto?
- Entendido o contexto do projeto?
- Levantamento bibliográfico?
- Como está a divisão de tarefas?
- Anotações
  - Grupo bem integrado
  - Grupo bem motivado
    - Gerou debates sobre a profissão durante a reunião
    - Ênfase em questões sociais


**** Quinzena 02


- Integração entre os membros do grupo?
  - Grupo bem integrado com alguns membros mais participativos que outros
- Acompanhamento do material da segunda quinzena?
  - Aparentemente sim
- Ciência dos prazos referentes às entregas?
  - Sim
- Interação com a comunidade externa?
  - Estão em contato com a escola e a diretora foi solicita ao envolvimento com a Univesp
- Coleta de dados?
  - Não foi realizada. Definição do brinquedo a ser desenvolvido foi feita antes da visita.
    - De todo modo, o problema que os integrantes do grupo levantaram é coerente com as necessidades da escola
- Identificação do problema a partir da interação com a comunidade externa?
  - Identificação do problema a partir das necessidades de um dos integrantes do grupo
    - Em função disso, tema do grupo se relaciona também com a inclusão de alunos com autismo
- Compreendido o contexto do problema?
  - Sim
- Entrega do plano de ação? (11/03)
  - De modo geral, o grupo está bastante adiantado
    - Foi feito um protótipo e apresentação de um vídeo para a diretora da escola
- Status do trabalho
  - Plano de ação completo
  - Protótipo desenvolvido
    - Irão utilizar um "vai e vem musical"
  - Vídeo de demostração gravado


*** Inter-quinzena

Correção:
- Zerar nomes que não aparecem na entrega
- Existe um campo para comentário interno que não é compartilhado com os alunos
- Não ficou claro onde está localizado o campo de comentário para ser compartilhado aos alunos

** Quinzena 3

*** Conteúdo

**** Objetivos

- Definir o título do trabalho
- Fazer o levantamento bibliográfico
- Refinamento de ideia
- Desenvolvimento da solução

**** Percurso histórico do brincar

É uma constituição histórica
- Brincar como imitação das atividades adultas
- Crianças vistas como pequenos adultos e associadas à religião
- A partir do renascimento, houve um maior foco ao desenvolvimento ao pensamento lógico
  - Restrito às classes mais abastadas
- Na revolução industrial, houve a produção em massa de brinquedos, mas dedicados ao um público menor
- Na idade moderna passam a ser construídos brinquedos com intuitos pedagógicos
- Na idade contemporânea, há o reconhecimento do brincar como inerente à infância
  - Brinquedos industrializados se sobrepõem aos artesanais
    - Brinquedo industrial é padronizado, os artesanais permitem que a criança possa ter uma maior interação e personalização
  - Mais recentemente, existem mais atividades digitais que implicam excesso de dela
    - Associado à mobilidade e à conexão contínua

**** Design Thinking: Ideação

- Brainstorming
- Workshop de cocriação
- Cardápio de ideias
- Matriz de posicionamento
*** Reuniões

**** Reunião de Equipe

**** Grupo 015

Este grupo relatou algumas dificuldades na elaboração do plano de ação:
- Indicou a falta de um suporte imediato
  - Provavelmente sugerindo que eu participasse de algum grupo informal (não institucional)
- Também pontuaram a falta de instrução em algumas situações
  - Em especial, pouca clareza
- Relataram que a diretora não tinha acesso ao PPP, adiando o início da atividade

**** Grupo 016


O grupo continuou avançando na elaboração do PI, incluindo:
- Levantamento bibliográfico a partir do conteúdo disponível no AVA. Em especial, fundamento da educação II

O grupo teve dificuldade em se reunir com a escola por falta de organização do próprio grupo:
- Isso fez com que alterassem a escola que irão atuar assim como o tema do PI
  - Irão trabalhar sobre mordidas na primeira infância por meio de quebra-cabeça de emoções
    - A boa notícia é que este problema foi relatado pela própria diretora da creche, tornando o PI menos genérico e coerente ao design thinking
  - A avaliação do plano de ação levou essas informações em consideração, mas penalizou o grupo com menos um ponto em virtude da falta de organização


**** Grupo 017

- Definição do título: Título no plano de ação estava bem desenvolvido
- Levantamento bibliográfico:
  - Vão começar a fazer o levantamento bibliográfico após a prova
- Refinamento da ideia:
  - Refinando junto com o levantamento bibliográfico
- Desenvolvimento da solução:
  - Alunos que estão mais próximos da escola começaram a fazer o brinquedo

**** Grupo 018


- Definição do título:
  - Em andamento
- Desenvolvimento da solução:
  - Irão desenvolver um boliche de emoções
    - Em reunião discutimos quais problemas podem ser resolvidos a partir do brinquedo proposto
      - De modo geral, o grupo não pareceu ter nenhum problema em mente
        - O foco dos desenvolvimentos foi centrado inteiramente no desenvolvimento do brinquedo
    - O boliche está associado à discussão das emoções para gerar maior engajamento das crianças
      - Foi relatado que os alunos tem uma relação forte com o filme "Divertidamente"
- Refinamento da ideia:
  - A partir de discussões com o grupo, foram evidenciados os seguintes problemas que podem estar relacionado com a atividade
    - Compreensão dos sentimento de perder/ganhar um jogo
    - Desenvolvimento de habilidades motoras
    - Trabalhar paciência dos alunos
      - Este Provavelmente será o caminho a ser desenvolvido
        - Também se relaciona com o problema de exposição do tempo de tela
          - Que também pode causar maior ansiedade, gerando um ciclo vicioso
    - Vale pontuar que a escola tem o hábito de desenvolver atividade com a comunidade externa (pais) e os integrantes do grupo pretendem incluir isso no PI
      - Alunos levarão os brinquedos para casa
      - Desenvolverão uma ficha de protótipo de como brincar com os filhos
      - Por consequência, reduz o tempo de tela fora da escola também
- Levantamento bibliográfico:
  - Levantamento bibliográfico em função do refinamento do tema

**** Grupo 019

O grupo continuou avançando na elaboração do PI, incluindo:
- Criação do plano de aula
- Levantamento bibliográfico a partir das sugestões do DEISA (?) e nos materiais existentes no AVA

Em reunião, foram levantadas as seguintes questões:
- Como assegurar que a criança vai participar da elaboração do brinquedo?
  - Customização?
- Como lidar com situações em que existem um número ímpar de alunos?
  - R: Um dos professores aplicadores irão formar dupla com este aluno
  - Como lidar com uma possível situação em que o aluno com autisto é isolado/se isola?

** Quinzena 4


*** Conteúdo


**** Objetivos

- Apresentar solução inicial
  - Tema central do projeto
  - Problema que querem solucionar
  - Literatura: Conceitos principais que embasam o problema
- Estruturar e entregar projeto parcial


**** Cuidar, educar, brincar

O vídeo indica outros momentos da vida (banho, refeições, etc) da criança que são importantes para o aprendizado.
Representa a união entre o cuidar e o educar.
O mesmo vale para o brincar.
Em cada faixa-etária, as crinças podem aprender diferentes coisas por meio do brincas:
- 0-2: aprendizado sobre a sensoriedade e habilidades motoras
- 2-3: Imitação de outras pessoas, sem assumir papeis.
- 3: Assumir papeis a partir do aprendizado da imitação (faz de conta)

**** O brincar e o desenvolvimento integral da criança

- Objetivos: Compreender a importância do brincar para a formação dos alunos e conquistar a socialização e o desenvolvimento psicossocial
  - Brincar não é entretenimento, mas trabalhar as linguagens da vida em sociedade
  - Brincar implica um domínio da linguagem simbólica e reconhecer o não-brincar
    - Atribuindo novos significados à realidade
  - Amplia diferentes linguagens
  - Oportuniza inclusão

**** O movimento do corpo infantil: uma linguagem da criança


- A criança que dá sentido e significado ao brincado
  - O professor apenas instiga e oferece os brinquedos
- Movimento como forma da criança explorar o mundo
- Escolarização se inicia no ensino fundamental, enquanto o ensino infantil trabalha os pilares que irão dar suporte à escolarização

**** Protótipos

- Utilizados na fase de desenvolvimento do conceito para gerar mais ideias
  - Pensar em forma como alguém pode interagir com o conceito
- Concretiza a ideia do grupo
- Releva questões que a equipe deve responder
- Comunicação externa sobre o conceito



**** Post sobre quinzena


Boa tarde pessoal, tudo bem?
 
Iniciamos a Quinzena 4, cujos objetivos são:
- Ampliar o conhecimento sobre a temática do PI e ter clareza sobre o que se espera como resultado dele.
- Construir a solução inicial, coletar sugestões com a comunidade externa e escrever o relatório parcial.
- Entregar Relatório Parcial  até 08/04, com carência até 13/04.


Até o dia 08/04 vocês deverão postar a entrega de Relatório Parcial. Para evitar problemas, leia atentamente as orientações abaixo:
1. o AVA ainda ficará aberto para postagens durante o período de carência (entre os dias 09/04 e 13/04), usem esse prazo adicional apenas no caso de imprevistos;
2. apenas um integrante do grupo deve fazer a postagem dos trabalhos, pelo ícone "Entregas" na aba lateral da página da disciplina ou pela link das "Atribuições do grupo" na página do grupo;
3. todos os trabalhos devem estar no formato PDF seguindo os modelos disponibilizados pela Univesp na Documentação do PI em "Modelos de Documentos";
4. os alunos possuem no total três tentativas de postagem, mas não são obrigados a usar todas as tentativas;
5. após o envio das três tentativas o sistema fecha e não é possível enviar novo arquivo (mesmo que o último envio seja feito antes do encerramento do prazo final);
6. apenas uma tentativa do grupo será corrigida;
7. apenas o trabalho desenvolvido de forma colaborativa e com acompanhamento do orientador será avaliado;
8. ao concluir a entrega, se certifiquem que o arquivo foi enviado! Isso pode ser feito observando o seguinte
   1. uma mensagem deve aparecer em rosa no topo da página assim que o aluno faz o envio do trabalho”
   2. plataforma envia uma mensagem para o e-mail institucional Outlook do aluno que fez o envio, com a mensagem “seu trabalho foi recebido” e um número de protocolo (guardar esse número email!)."

Além disso, gostaria de reforçar duas coisas:
1. É importante vocês "testarem" o protótipo (brinquedo) para incluir um relato sobre isso no Relatório Parcial (na seção “2.5 Resultados preliminares: solução inicial”);
2. Necessidade de anexar na entrega do Relatório parcial, o *Termo de Consentimento Livre e Esclarecido* e *Autorização do Uso de Imagem*.


Para realizar esta entrega, os seguintes items devem estar bastante claros para o grupo:

✅ Tema central do projeto
✅ Problema que querem solucionar
✅ Revisão da Literatura: Conceitos principais que embasam o problema

Em nossa reunião, vamos discutir a estrutura do relatório parcial e as rúbricas de avaliação.
Aqui vai o link para nossa reunião: LINK

Conto com a presença de vocês!

Qualquer dúvida, escrevam aqui nesta linha de discussão.


Abs,

Gabriel




*** Reunião com coordenação

- Materiais das quinzenas costumam ser suficientes
- Mencionar data de entrega do relatório na postagem
- Ver modelo postado
- Grupos que não conseguiram autorizações, devem anexar no relatório parcial
  - Se não houve essa entrega, deve ser descontado ao menos meio ponto
- Esperando a supervisora responder sobre cidade ou DRP

**** Reunião de dúvidas

- Ver se a rubrica do relatório parcial está correta ou se está associado ao relatório final
- Os alunos estão no começo da graduação e terão outros PIs até o fim da graduação

*** Grupos

**** Grupo 015

Vamos retomar o que fizemos até aqui e checar se existem quaisquer lacunas:

- Qual é o tema central do projeto?
- Qual é o problema que querem solucionar?
- Revisão da Literatura: Conceitos principais que embasam o problema
- Apresentar solução inicial e estruturar o reletório parcial

OBS: O grupo ainda não fez a reunião com a escola e não tem o tema definido
- Aparentmente tiveram algum problema em se reunirem com a professora
  - Isso emperra todas as etapas seguintes do projeto
- Apenas uma aluna compareceu (Deisiana)

**** Grupo 016

Memo: Irão trabalhar sobre mordidas na primeira infância por meio de quebra-cabeça de emoções

Vamos retomar o que fizemos até aqui e checar se existem quaisquer lacunas:

- Qual é o tema central do projeto?
- Qual é o problema que querem solucionar?
- Revisão da Literatura: Conceitos principais que embasam o problema
- Apresentar solução inicial e estruturar o reletório parcial

OBS: Grupo muito pouco participativo
- Membro mais ativo do grupo não esteve presente hoje e isso pode explicar a pouca interação
- Não me responderam nenhuma das perguntas que fiz durante a reunião

**** Grupo 017

Memo: Pescaria dos sentimentos

Vamos retomar o que fizemos até aqui e checar se existem quaisquer lacunas:

- Qual é o tema central do projeto?
- Qual é o problema que querem solucionar?
- Revisão da Literatura: Conceitos principais que embasam o problema
- Apresentar solução inicial e estruturar o reletório parcial

OBS: Ninguém compareceu.

**** TODO Grupo 018

Memo: Boliche de emoções

Vamos retomar o que fizemos até aqui e checar se existem quaisquer lacunas:

- Qual é o tema central do projeto?
- Qual é o problema que querem solucionar?
- Revisão da Literatura: Conceitos principais que embasam o problema
- Apresentar solução inicial e estruturar o reletório parcial

OBS:
- O grupo talvez tenha dificuldade em conseguir todas as autorizações a tempo em virtude da transferência de uma das participantes que trabalha na escola que irão atuar
  - Perguntar Magda
- De modo geral, as ideias do trabalho estão bem articuladas
- O ponto mais frágil parece ser a identificação do problema por meio da interação com a escola
  - Das interações que tive com o grupo, essa identificação pareceu ser de improviso.
- Remarcar data da próxima reunião no google agenda e gerar novos links

**** Grupo 019

Vamos retomar o que fizemos até aqui e checar se existem quaisquer lacunas:

- Qual é o tema central do projeto?
- Qual é o problema que querem solucionar?
- Revisão da Literatura: Conceitos principais que embasam o problema
- Apresentar solução inicial e estruturar o reletório parcial

-----

Atualizações do grupo:

- Entraram em contato com a diretora e planejam aplicar a aula no dia 25/04
- Aprimoraram o brinquedo para dar mais ênfase ao desenvolvimento da percepção sensorial da criança e segurança
  - Algumas partes do brinquedo serão levadas prontas (partes pequenas que podem ser engolidas)
- Já fizeram alguns testes com o brinquedo e está funcionando
- O grupo informou que irão trabalhar com músicas que a escola está habituada de trabalhar com os alunos
- Memo: o grupo tinha desenvolvido um passo a passo sobre a montagem do brinquedo no plano de ação

** Quinzena 5
*** Conteúdo


**** Objetivos: Análise dos resultados

- [ ] Analisar as sugestões da comunidade externa
  - A solução final foi realizada com base na necessidade da comunidade?
  - É prática?
  - É viável?
- [ ] Atualizar plano de ação
- [ ] Autoavaliação?
  - Preciso refazer alguma etapa do projeto?
  - O que mais preciso estudar?
  - Preciso visitar novamente a escola?
  - Já apresentei a solução para a comunidade?
    - Quais foram as opniões da comunidade?
- [ ] Construir solução final

**** Currículo e cultura

- Objetivo: refletir sobre a diversidade cultural reverberada no currículo, por meio dos conteúdos e das práticas cotidianas.
- Currículo: não se restringe a uma lista de conhecimentos escolares, incluindo:
  - Arquitetura escolar
  - Tempo
  - Organização da escola
  - Procedimentos e concepções implícitas na linguagem e na abordagem
- Cultura: lente de interpretação para ler, interpretar e, assim, intervir no mundo
  - Diferenças identitárias não são estáveis ou lineares e sem contradições
- Currículo multicultural:
  - Multiculturalismo conservador se restringe à tolerância de outras culturas, mas não a valorização ou inclusão das diferenças
    - Há uma hierarquização entre as culturas
  - Multiculturalismo crítico
    - Representação de raça, classe e gênero como resultado de lutas sociais mais amplas sobre símbolos e significações
    - Como expor isso em sala de aula?
      - Comparar manchetes para inferir a intenção da mídia
      - Atividades como juri simulado

**** Brincadeiras que valorizam as diferenças identitárias na Educação Infantil

- Objetivos:
  - Exaltar as diferenças identitárias na docência da educação infantil
    - Evitar trazer diferenças a partir de um tratamento do "exótico" e não apenas em datas comemorativas
  - Reconhecer brinquedos e brincadeiras de diversas subculturas do país
  - Avaliar proposições de sensibilização para a inclusão na Educação infantil por meio da ludicidade
    - Ludicidade impulsiona o conhecimento e apropriação da interculturalidade
    - Importante reconhecer a influência e construção socio-histórico-cultural das origens indigenas e africanas das brincadeiras brasileiras
- Avaliação das brincadeiras
  - Utilização de linguagem capacitista?
  - Plano de atividade inclui todos os estudantes?
    - Inclusão de crianças neuroatípicas e as com deficiência?

**** Recebi o /feedback/ e agora?

- Preciso refazer alguma etapa do projeto?
- O que mais preciso estudar?
- Preciso visitar novamente a escola?
- Já apresentei a solução para a comunidade?
  - Quais foram as opniões da comunidade?

*** Reunião com coordenação

- Ainda consta rúbrica de avaliação do relatório final no AVA
- Relatar que o grupo teve dificuldade em ter acesso às autorizações por dificuldades que a escola impôs (G019)
  - Diretora não estava, mudança de telefone da escola, etc
  - Na minha avaliação, o grupo fez o que estava ao alcance para conseguir a autorização, mas outras coisas os prejudicaram
- Correção dos relatórios parciais
  - Não houve correção do AVA
  - Inserir de nota manual

*** Reunião com os grupos



**** Objetivos da quinzena (para alunos)

- Analisar as sugestões da comunidade externa;
- Atualizar o plano de ação (se necessário) e fazer plano de aula;
- Construir a solução final.

**** Notas

| Grupo | Intro (1) | Obj (1) | Just (1) | Teoria (2) | Method (1.5) | Solucao (1.5) | ABNT (2) | Total |
|-------+-----------+---------+----------+------------+--------------+---------------+----------+-------|
|   015 |      0.75 |     0.5 |      0.5 |        1.0 |         1.25 |           0.5 |        2 |   6.5 |
|   016 |         1 |       1 |        1 |          2 |          1.5 |           1.5 |      1.0 |    9. |
|   017 |         1 |       1 |        1 |          2 |          1.0 |           1.5 |      1.5 |    9. |
|   018 |         1 |       1 |        1 |          2 |          1.5 |           1.5 |        2 |   10. |
|   019 |         1 |       1 |        1 |          2 |          1.5 |           1.5 |        1 |    9. |
#+TBLFM: $9=$2+$3+$4+$5+$6+$7+$8

**** Grupo 015

***** Comentários sobre o relatório parcial

NOTA: muito provavelmente entre 6 e 8

- IMPORTANTE: Estou levando em consideração a dificuldade que o grupo teve em ter acesso à escola
- Design thinking: estão investigando um problema identificado via conversa com a escola. (bom)
  - Não mencionaram as metodologias sugeridas pela Univesp em nenhum momento
- Usaram o padrão da ABNT (bom)
- Conseguiram autorização da escola (bom)
- Vocês não estão relacionando o problema (alfabetização matemática) com o tema norteador do PI (desenvolvimento socioafetivo da criança)
- A atividade em questão (Bingo) tem basicamente nenhuma modificação em relação ao tradicional e não trata de temas associados ao tema norteador do PI
  - MEMO: tema do PI é o desenvolvimento de um brinquedo para desenvolver a socioafetividade, não é o brinquedo em si
  - MEMO: tema do projeto não é desenvolver um brinquedo, mas trabalhar temas associados ao desenvolvimento da socioafetividade por meio de um brinquedo
    - Brinquedo é o meio, não o fim do projeto
- Objetivos pouco detalhados
  - Conscientização de quem? Das crianças, dos professores? Dos membros do grupo? da Comunidade externa?
- Vocês escreveram uma justificativa sobre o porquê um brinquedo pedagógico é importante
  - Pouco relacionaram com o desenvolvimento socioafetivo ou com o problema em questão (alfabetização matemática)
- Fundamentação teórica: Não relacionaram o problema com o desenvolvimento socioafetivo da criança, mas sim, o porquê a alfabetização matemática é importante.
- De modo geral, não fizeram nenhuma modificação ao bingo tradicional. Existiria alguma outra forma que poderia auxiliar na alfabetização matemática dos alunos?
  - Por exemplo (pensando alto): invés de terem cartelas com os número, poderiam ter cartelas com algumas operações simples (1+1) ou vice-versa. Imagino que possam existir outras adaptações que possam se encaixar na proposta do PI.
    - Outra ideia: fazer com que as duplas se revezem;
    - Outra ideia: "bingo humano". A cartela é desenhada no chão, cada criança tem um número. Uma criança (ou mais) sorteia os números e precisa identificar a criança com o número correspondente.
  - Reforço, até o momento, pouco foi mencionado sobre o desenvolvimento socioafetivo da criança.

Sugestões importantes para o relatório final:

- Vocês precisam definir uma data para atuarem na escola
- Relacionar melhor o problema que vão investigar (alfabetização matemática) e o tema do PI (desenvolvimento socioafetivo)
- Pensar em alguma adaptação que permita explorar melhor o problema. Como está, vocês não desenvolveram um brinquedo/brincadeira/atividade. Estão apenas aplicando algo já existente.
- IMPORTANTE: Não é necessário fazer algo completamente novo ou do zero, mas é importante que vocês adaptem para investigar o problema em questão.

OBS: Nenhum aluno compareceu à reunião
**** Grupo 016

***** Comentários sobre o relatório parcial

NOTA: muito provavelmente entre 8 e 9 (cap imposto pela exigência de anexarem as autorizações)

- Não anexaram as autorizações exigidas pela Univesp
- Resumo está bom
- Imagino que vocês podem omitir a menção sobre a divergência entre o relatório *final* e o plano de ação. Talvez uma nota de rodapé.
  - Não tenho uma resposta definitiva a isso
    - Vantagem: reflete o design thinking
    - Desvantagem: não é uma informação necessária para o projeto final
      - Normalmente, em um trabalho acadêmico é relatado o que foi feito e as prováveis lacunas do que é proposto
        - O que não foi feito não costuma ser muito relevante
- Estão tratando de um problema identificado pela interação com a comunidade externa
  - A reincidência das mordidas evidencia a importância do problema
- Descrição do brinquedo/brincadeira/atividade está bem feita
- Objetivos específicos estão bem claros
- Achei que a hipótese de trabalho bem elaborada
  - HO: mordidas são normais
  - H1: mordidas como resultado de comportamento agressivo
- Relação com desenvolvimento socioafetivo:
  - Parece estar indicado de forma mais implícita/indireta
    - Percebido a partir das diferentes etapas do desenvolvimento infantil via identificação do comportamento
    - Seria bom ter partes que em isso é mais explícito
  - Encerram a discussão sobre personalidade, temperamento e desenvolvimento cognitivo e emendam para diretrizes da BNCC sem articularem bem os pontos
- Me parece que parte da justificativa poderia ser tratada como fundamentação teórica
  - Nesta mesma seção, poderia ter mais referência ao tema norteador do PI
- O tempo verbal do texto me dá a entender que a aula já foi realizada. Se este for o caso, podemos discutir em reunião
- ABNT:
  - Sumário não está paginado
  - Na página 11, vocês incluiram citações sem indicar as páginas
    - Na mesma página, é preferível um texto estruturado do que listar citações
    - Na mesma página, não indicaram página da tabela ou algum título/identificação desta tabela
  - Na página 12, vocês incluiram citações sem indicar as páginas

**** Grupo 017


***** Comentários sobre o relatório parcial

NOTA: muito provavelmente entre 8 e 10

- Anexaram as autorizações exigidas pela Univesp
- ABNT:
  - Não atualizaram o número de folhas
  - Página 7: não incluiram página da citação
- Justificativa:
  - O que quiseram dizer com fase de empatia Design Thinking?
- Fundamentação teória: vocês descreveram bem as diferentes perspectivas do problema
- Metodologia
  - Descreveram melhor o brinquedo/brincadeira/atividade que irão desenvolver
  - Deixaram explícito qual o problema que o grupo identificou em conversa com a escola?
  - A forma como redigiram o texto também está pouco fluida. A impressão que dá é que combinaram um conjunto de instruções que estava disposto em uma lista. Sugiro que deem mais atenção à conexão com os problemas identificados com a escola e forma de expor o problema.
    - Exemplo: seção 2.4.5
- Resultados
  - Nessa seção é a primeira vez que vocês indicam como identificaram o problema (primeiros dois parágrafos)
    - Isso deveria aparecer antes (introdução e/ou justificativa e/ou metodologia)
  - Nesta versão vocês indicaram melhor o que é a solução inicial e como vocês aplicaram e elencaram o que era esperado com essa atividade

- Comentários internos:
  - Tem um parágrafo da justificativa que soa como chatgpt
  - O que quiseram dizer por "teoria do jogo"
  - Teve pouca relação com os problemas que deveriam ser identificados em virtude da visita a campo (Metodologia)


**** Grupo 018

***** Comentários sobre o relatório parcial

NOTA: muito provavelmente entre 8 e 10

- Anexaram as autorizações exigidas pela Univesp
- ABNT:
- A introdução está bem construída e conduz o leitor à problemática de vocês
  - Notem que a hipótese do tempo de exposição às telas aparece sem intermediações
    - Imagino que após aplicarem os formulários, vão conseguir dar suporte a essa hipótese
      - OBS: Notei que evidenciaram um relato de um dos pais por meio da Priscila
    - Sugestão: na introdução, puxar alguma referência que permita o leitor entender o porque vocês acharem que essa hipótese pode ser uma boa pista
  - Sugestão para o relatório final: escrever um parágrafo que antecipa a estrutura do relatório (seção x apresentará y, seção z mostra w, etc)
    - Isso pode ser colocado logo após o último parágrafo da introdução
- Justificativa:
  - Deixaram explicitado que identificaram o problema por meio do contato com a escola
  - Vocês conseguiram justificar a importância do trabalho de forma muito clara
- Discussão teórica
  - Na seção 2.4.2, é dito que as "evidências apontam", mas nenhum estudo é referenciado
- Seção de metodologia está completa
  - O mesmo vale para a seção da solução inicial
- Questionários
  - QUESTIONÁRIO PARA PAIS E RESPONSÁVEIS:
    - Muito bem estruturado, de fácil entendimento e de rápida resposta
    - Único problema potencial é que introduz um viés de resposta dos pais quererem responder enquanto "bons pais"
      - Anonimizar
      - Essas categorias de pergunta não parecem ser muito relevantes para o tema discutido
    - Também pode existir um viés sobre a opinião sobre o projeto
      - Com resposta não anonimizada, é esperado que mais pessoas respondam que gostaram do que efetivamente gostaram
    - Sugestão de pergunta: quanto tempo você acha que deve ser adequado para que as crianças passem em frente às telas
      - Isso poderia medir a noção que os pais têm sobre o que é o recomendado/letramento sobre o tema
  - QUESTIONÁRIO PARA PROFESSORA
    - Pergunta 2.6 me parece ser bastante importante

**** Grupo 019

NOTA: muito provavelmente entre 8 e 10

Feedback sobre a nova versão do relatório parcial:
- Correção gramatical
- Não fizeram o upload das declarações necessárias
- Omitiram parte da discussão instituicional
  - OBS: Eu tinha comentado que parte desta discussão não fazia sentido na seção dos objetivos, mas sim da fundamentação teórica/justificativa
    - Em resposta, os alunos simplesmente removeram essa discussão


** Quinzena 6


*** Reunião com os grupos

**** Grupo 015
**** Grupo 016
**** Grupo 017
**** Grupo 018
**** Grupo 019

** Quinzena 7

*** Conteúdo
**** Práxis da Educação Infantil - Análise de Brinquedos e Brincadeiras
***** Resumo

- **Objetivo da aula**
Analisar brinquedos e brincadeiras atuais utilizados por crianças.
Avaliar interações corporais e movimento na educação infantil.
Propor brincadeiras que destaquem corpo e movimento.

- **Importância do movimento**
Brincadeiras ao ar livre estimulam o desenvolvimento motor e social.
Crianças precisam usar o corpo para aprender e interagir.

- **Uso excessivo de telas**
Imagens mostram crianças imóveis com celulares, sem interação.
Postura corporal inadequada e ausência de socialização são preocupantes.
Contato precoce com tecnologia afeta linguagem e empatia.

- **Impactos do consumo digital**
Excesso de telas contribui para o consumismo e isolamento.
Propagandas e vídeos geram crianças mais individualistas.
Referência da SBP: crianças <2 anos não devem usar telas.

-‍ **Influência dos adultos**
Adultos hiperconectados servem de modelo negativo.
Comportamento digital impacta diretamente as crianças.
Falta de interação familiar prejudica o desenvolvimento afetivo.

- **Tecnologia como brinquedo**
Jogos digitais não são ideais para a primeira infância.
Celular não substitui interações reais e brincadeiras tradicionais.

- **Propostas alternativas**
Sugestões de brincadeiras simples e de baixo custo.
Exemplos: caretas no espelho, sombras, fantoches, pescaria com tampinhas.
Para todas as faixas da educação infantil, há opções lúdicas e educativas.

- **Parceria com a família**
Escola deve envolver pais na promoção de brincadeiras fora da escola.
Educar adultos sobre a importância do brincar.

- **Exemplo prático**
Professora Alessandra relata experiência em escola bilíngue no RJ.
Brincadeiras e interações estruturam toda a rotina pedagógica.
Brincadeiras de baixo custo para diferentes faixas etárias.
Brincadeiras com espelho, prendedores, sombras, chaves, entre outras.
Para 17 meses a 3 anos: fantoches, brincadeiras cantadas, acertar o alvo.
De 4 a 5 anos: bonecas de pano, dança das caveiras, pescaria

A escola da professora Alessandra Braga prioriza o brincar no planejamento.
Aulas bilíngues e de educação física integram o brincar como eixo principal.
Interações entre alunos e com professores são observadas continuamente.
Processo de aprendizagem se torna significativo por meio da brincadeira.
Participação da comunidade escolar é incentivada em festas e eventos.

Encerramento e motivação
Professor comprometido com o brincar deve também brincar.
Brincar fortalece vínculos, saúde emocional e o aprendizado.
Manter viva a criança interior contribui para a prática docente.
Desejo de continuidade das práticas investigativas e lúdicas.


*** Reunião com a coordenação

*** Postagem


Olá pessoal, tudo bem?

Este é a nossa última quinzena em que iremos concluir o Projeto Integrador. Conforme o calendário do PI, entre os dias 12/05 e 20/05 vocês deverão postar a entrega de três trabalhos: Relatório Final, Avaliação Colaborativa e Vídeo de Apresentação do PI. Para evitar problemas, leia atentamente as orientações abaixo:

1. ATENÇÃO: a correção do Relatório Final é condicionada à entrega do Vídeo de apresentação do PI. Ou seja, os grupos que não entregarem o Vídeo receberão nota 0 no Relatório Final independente se ele foi enviado ou não;
2. É responsabilidade do grupo garantir que as configurações de acesso do link do “Vídeo de Apresentação do PI” estejam bem definidas, de forma que orientador consiga assistir a gravação. Caso o acesso seja negado, o trabalho será considerado como não enviado!
3. o AVA ainda ficará aberto para postagens durante o período de carência (entre os dias 21/05 e 25/05), usem esse prazo adicional apenas no caso de imprevistos;
4. apenas um integrante do grupo deve fazer a postagem dos trabalhos, pelo ícone "Entregas" na aba lateral da página da disciplina ou pela link das "Atribuições do grupo" na página do grupo;
5. apenas trabalhos enviados no Ambiente de Aprendizagem (AVA), pelos links apropriados, serão considerados para a atribuição de nota;
6. todos os trabalhos devem ser entregues no formato PDF seguindo os modelos disponibilizadas pela Univesp na Documentação do PI em "Modelos de Documentos";
7. apenas o trabalho desenvolvido de forma colaborativa e com acompanhamento do orientador será avaliado (o grupo não pode se dividir e realizar mais de uma entrega; caso isso ocorra, o orientador tem autonomia para decidir qual delas será avaliada);
8. os alunos possuem no total três tentativas de postagem, mas não são obrigados a usar todas as tentativas;
9. apenas uma das tentativas será corrigida; após o envio das três tentativas o sistema fecha e não é possível enviar novo arquivo (mesmo que o último envio seja feito antes do encerramento do prazo final);
10. ao concluir a entrega, se certifiquem que o arquivo foi enviado! Isso pode ser feito observando o seguinte:
    - uma mensagem deve aparecer em rosa no topo da página assim que o aluno faz o envio do trabalho;
    - a plataforma envia uma mensagem para o e-mail institucional Outlook do aluno que fez o envio, com a mensagem “seu trabalho foi recebido” e um número de protocolo (guardar esse número e-mail!).
11. Importante: Para os grupos cuja a avaliação colaborativa será feita de forma conjunta comigo, *todos* os integrantes do grupo precisam estar presentes para serem avaliados. A minha nota será feita de forma assíncrona.


Próxima Reunião Síncrona
📅 Data: [insira a data]
🕒 Hora: [insira o horário]
🔗 Link: [insira o link da reunião]

Caso alguém não possa participar dessa reunião (ou da reunião da avaliação colaborativa) de forma síncrona, aproveito este post para me despedir de vocês.
Tem sido um prazer orientá-los neste PI.

Bom trabalho a todos,
Abs
Gabriel


*** Reunião com os grupos

**** Grupo 015
***** Primeira versão
Comentários gerais:

- O grupo inclui as disciplinas que ajudaram a elaborar o projeto integrador (bom)
- O desenvolvimento da centopeia numérica ajudou a atividade proposta ser diferente de um bingo convencional (bom)
- A descrição de como a atividade foi construída e aplicada está bem clara
- Menção às metodologias sugeridas pela Univesp: O grupo não mencionou em nenhum momento as metodologias sugeridas pela Univesp, como indicado nas correções (Design Thinking).
- Relação explícita entre alfabetização matemática e desenvolvimento socioafetivo: Embora o relatório final tenha adicionado mais menções ao desenvolvimento socioafetivo, a conexão direta entre esse tema e a alfabetização matemática ainda não foi suficientemente explorada.
  - Basicamente, o grupo adicionou as palavras "socioafetiva" e "socioafetividade", ou "desenvolvendo-se socio afetivamente" em algumas partes
  - Na explicação de como a atividade foi realizada, isso ficou mais claro
    - Especialmente quando mostram que as crianças com níveis de aprendizado diferente se ajudavam
- Parte da discussão sobre desenvolvimento socioafetivo que está nas considerações finais deveria ser antecipado, suprindo as lacunas no desenvolvimento teório do texto (Seção 2)


**** Grupo 016
**** Grupo 017
**** Grupo 018
**** Grupo 019

* PJI500

** Quinzena 0 [2025-08-04 Mon]

*** Reunião com a coordenação (extraordinária)

- Alunos estão no 5 semestre e já fizeram um PI anteriormente
- Curos:
  - Administração
  - Engenharia de Produção
  - Tecnologia em Processos Gerenciais
- Tema: Mapeamento de processos em ambiente organizacional
  - Objetivo: Criação de um protótipo que busquem soluções para problemas reais e recorrentes
- Funções do Orientador
  - Acompanhar grupos
  - Mediação de conteúdo
  - Mediar conflitos
  - Avaliar trabalhos
- Ações iniciais
  - Apresentação breve
  - Abrir um fórum em cada grupo e se apresentar
  - Encontrar os grupos (4 a 6 grupos)
    - DRP03-PJI500-SALA-001GRUPO-006
    - DRP03-PJI500-SALA-001GRUPO-007
    - DRP03-PJI500-SALA-001GRUPO-008
    - DRP03-PJI500-SALA-001GRUPO-009
    - DRP03-PJI500-SALA-001GRUPO-010
  - Marcar primeira reunião síncrona ([2025-08-11 Mon]a [2025-08-24 Sun])
    - Preferencialmente no período noturno


** Quinzena 1

- Aluno deve se apropriar do conteúdo referente à quinzena I
- Objetivo da quinzena:
  - Análise do cenário de pesquisa
  - Início do levantamento bibliográfico
- Estimular a participação nos fóruns
- Apresentação as etapas e avaliações do PI
  - ênfase no relatório final e produção do vídeo
- Definir com o grupo um dia e um horário para as reuniões
- Sugestões de ações a serem desenvolvidas (items do plano de ação Q02):
  - Pensar no problema/objetivo
    - Associado a uma comunidade (escola, empresa, comércio, etc)
  - Título provisório do trabalho
  - Local a ser desenvolvido o PI
  - Estudar o que está no AVA
- Boas práticas:
  - Incentivar uso de resumo e resenhas, ficha de citações com a ideia de facilitar a escrita do plano de ação
  - Sugerir modelo de proposta individual disponível no AVA
  - Enviar um resumo depois de cada reunião e incluir próximos passos

*** DONE Assistir conteúdo Quinzena 01
CLOSED: [2025-08-24 Sun 17:51] SCHEDULED: <2025-08-11 Mon 16:00-17:30>
:PROPERTIES:
:org-gcal-managed: org
:calendar-id: c_c16eca421b987fdacfb0ae461df81f1b1bf2186448e9401ab3102dd74c8d0471@group.calendar.google.com
:ETag:     "3509849603235262"
:entry-id: t1qolnqjnrg5t7m5l1f1lnb8e4/c_c16eca421b987fdacfb0ae461df81f1b1bf2186448e9401ab3102dd74c8d0471@group.calendar.google.com
:END:
:org-gcal:
:END:

**** Mapeamento de processos

Dicionário de símbolos:
- Círculo: Operação
  - Montagem e desmontagem
  - Mudança intensional de características
- Seta: Transporte
  - Movimentação de materiais e pessoas entre locais de trabalho
  - Deslocamento
- Quadrado: Inspeção
  - Exame para comparação em relação aos padrões estabelecidos
- Letra D: Espera
  - Aguarda por outros materiais ou pela ação seguinte do processo
- Triângulo invertido: Armanezagem
  - Retenção de material cuja remoção deve ser autorizada

***** Ferramentas de descrição e análise

- Mapofluxograma
  - Mapeamento em planta
- Diagrama de fluxo
  - Contém uma descrição de cada etapa do processo em que cada etapa está associada a um símbolo específico
  - Pode ser indicado a distância e tempo percorrido em cada etapa
  - Uma sugestão de como comparar o que é proposto do que era executado é contabilizar número de processos e tempo estimado
- Carta de processo
  - A carta de processo tem a vantagem de poder indicar quais atividades são desempenhadas paralelamente (simultaneamente)
  - Esta carta também pode contemplar mais de um processo
- Carta de atividade
  - Esta carta mostra o tempo das atividades que o operador utilizou para desempenhar determinado processo
- Carta de operação
  - Está pode indicar em maior detalhe a atividade a ser desempenhada (ex: mão esquerda e direita)
- Roteiro de operação

***** Resumo do projeto integrador

- Na visita a campo, sugere-se que os alunos vão com questões pré-definidas
- Existe um feedback de um avaliador externo (empresa)
- Tema: mapeamento de processo em um ambiente organizacional
  - Técnica criada para mapear visualmente os fluxos de trabalho e os processos
  - Envolve a criação de um fluxograma de processo (dentre outras ferramentas)

***** Concepção do projeto

- Mapeamento de processos envolve dialogar com vários setores de uma empresa
- O fluxo de informação pode ter uma direção reversa do processo de produção
- O cliente não é exclusivamente um ator fora da empresa (pode ser outra etapa)
- Este mapeamente é uma etapa no gerenciamento de negócios e de processos, permitindo
  - Padronizar processos de trabalho
  - Determinação de índices para medir desempenho
  - Identificação de gargalos
  - Maior assertividade ao delimitar funções e papeis
  - Previsão de recursos e estimativas de custo mais eficientes
  - Maior controle sobre processos
  - Otimização de fluxos de trabalho


** Quinzena 2

*** Reunião com a coordenação (gravação)

- Ao criar o resumo, disponibilizar o link da gravação
- Se o grupo não aparecer, escrever no resumo que ninguém apareceu, disponibilizar gravação e agendar próxima reunião
- Não deve ser utilizado uma empresa hipotética
- Não deve ser coletado dados sem autorização da empresa
  - As autorizações serão requeridas na quarta quinzena (entrega do relatório parcial)
- Avaliar se faz sentido mapear determinado processo
  - Exemplo da manicure que atende a domicilio por meio de uma plataforma (existe processo), gerenciamento de agendamento, deslocamento
- Ações da quinzena (25/08 a 07/09):
  - Interajam com a comunidade
    - Apresentar carta de apresentação para a empresa que vão atuar
  - Definam o problema
  - Escrever e entregar plano de ação
- Reforçar a importância de estudar o conteúdo do AVA
  - Indicar que isso irá direcionar o trabalho
- Agendar segunda reunião
  - Entre 25/08 a 29/08 preferencialmente
  - Apresentar rubricas de avaliação
    - Indicar que se os grupos seguirem todas as recomendações, vão receber a nota máxima
  - Abrir modelo do plano de ação
- Auxiliar na distribuição de tarefas dentro do grupo
- Acompanhar escrita do Plano de Ação

*** DONE Assistir conteúdo Quinzena 02
CLOSED: [2025-08-24 Sun 18:39] SCHEDULED: <2025-08-23 Sat>

Observações: o conteúdo metodológico é igual ao do PI anterior.

**** Gráficos de atividade (video aula)

Serão considerados os seguintes gráficos de atividade:
 - Gráficos homem-máquina
   - Exemplo: compra de café em uma mercearia
     - O gráfico vai identificar em uma forma visual cada ente envolvido e a respectiva operação
       - Identifica-se quando o respectivo ente está em operação ou aguardando
       - Identifica-se o tempo de cada operação e é possível listar o total de trabalho de todos ao final do ciclo
 - Estudos de micromovimentos
   - Registro das atividades na execução de uma tarefa que envolva homem e máquina no tempo normal de produção
     - Exemplo: como as mãos estão sendo usadas ao operar uma máquina, tronco, etc
 - Filmagem de operações
   - Deve ser acordado com as partes para que elas operem no ritmo normal de operação

**** Lean production (vídeo aula)

- Objetivo:
  - Identificar e reduzir desperdícios na linha de produção
    - Valor: Aqulo que o cliente considera importante no momento específico
    - Fluxo de valor: Soma de todas as fases que levam o produto da cadeia produtiva ao cliente
    - Puxar: Nenhuma etapa deve ser repassada ao cliente ao menos que tenha sido demandada
      - Produzir sob demanda
    - Fluxo: Produção de cada parte do produto por vez
      - Não produz para constituir estoque
    - Perfeição: é preciso que todas as demais fases ocorram para identificar gargalos e realizar a eleminação progressiva do desperdício
  - Aplicar os princípios da manufatura enxuta ao mapeamento de processos em um ambiente organizacional.
  - Foco na redução de desperdícios.
  - Criação de protótipo com base em desejabilidade, viabilidade e praticidade.
- Etapas do Projeto (inspiradas no plano da disciplina)
  - Análise do cenário atual.
  - Planejamento e proposição do tema (problema relacionado aos desperdícios).
  - Levantamento bibliográfico (Lean, Kaizen, Kanban, Poka-Yoke).
  - Proposta de solução (protótipo inspirado em ferramentas Lean).
  - Análise dos resultados.
  - Finalização do protótipo, relatório e vídeo.
- Conceitos Lean Aplicáveis
  - Eliminação dos sete desperdícios:
    - Sobreprodução, espera, transporte, processamento excessivo, inventário, movimento, defeitos.
  - Ferramentas Lean:
    - Kaizen (melhoria contínua).
    - Kanban (fluxo puxado).
    - Poka-Yoke (à prova de erros).
  - Princípios:
    - Qualidade imediata (zero defeito).
    - Minimizar desperdícios.
    - Flexibilidade produtiva.
    - Relacionamento com fornecedores.
- Resultados Esperados
  - Processos mais eficientes, com menos desperdício.
  - Aumento da qualidade, redução de custos e melhor adaptação ao cliente.
  - Protótipo funcional com aplicação prática dos conceitos Lean.

**** Por que mapear processos (Vídeo aula)

Por que mapear?
- Permite que a empresa conheça os processos atuais
- Identificar oportunidades
- Criar soluções ou otimização de processos
- Aperfeiçoamento contínuo

Exemplos fornecidos em aula:
- Hierarquia típica de processos (pastas windows)
  - Macroprocessos que parte da raíz do sistema até a home
  - Permite que a empresa observe como os processos se desdobram e ter uma visão holistica
    - Incluindo caieia de processos, visão operacional (fluxogramas e procedimentos operacionais)
  - SIPOC é um tipo de diagrama que permite mapear esses processos:
    - Quais são as entradas e saídas
    - Início e término das operações
    - Sequência de atividades
    - Responsáveis pelas tarefas
    - Quem são os clientes
    - Sigla: Supplier, Input, Process, Output, Customer; Exemplos:
      - S: Produção, Vendas, TI
      - I: Ordem de produção, pedido de venda, Impressoras, Internet
      - P: Faturamento
      - O: Romaneio, Etiquetas, Relatórios, Aviso de Embarque
      - C: Transportadora, área de expedição (outro processo), Contabilidade

Óptica do cliente:
- Nota: sempre identificar quem é o cliente (processo interno, outras firmas, etc)
- Valores:
  - Acessibilidade
  - Qualidade
  - Design
  - Customização
  - Ergonomia
  - Diversidade de modelos
  - Custo
  - Prazo
  - Inovação
  - Atendimento

Desperdício:
- Atividades que consumem recursos, mas não agregam valor
  - Isso inclui atividades não necessárias ou redundantes
- Exemplos de desperdícios:
  - Defeito (Inspeção e retrabalho)
  - Espera
  - Movimentações desnecessárias
  - Atividades desnecessárias
  - Estoque (gerenciamento, inspeção, etc)
  - Transporte
  - Excesso de produção


*** Grupo 06
*** Grupo 07
*** Grupo 08

- Estão pensando em atuar em um restaurante
  - Talvez mapear a produção de um prato específico
  - Ou de um período específico do restaurante
  - Grupo mostrou objeção ao mapear maior número de processos possíveis

*** Grupo 09
*** Grupo 10

*** Reunião com coordenação (tira-dúvida) ([2025-08-28 Thu])

- De modo geral, nenhuma questão/atualização relevante

* Relatórios

** Relatório I

Número de confirmação:
- 8dc5e3e865584f3fb96d8c5f551c2746
- ef329c38ac4548d49748e3b99a087ce6

** Relatório II

Número de confirmação: 966090b824824439847e95cf5008fea2 (<2025-03-08 Sat>)



** Relatório III

Número de confirmação: 905279677d7b42158e7dcd3a8870014b (<2025-04-07 Mon>)



** Relatório IV

Número de confirmação: 35ef51e287084612bb354d6ae4717c6f (<2025-05-06 Tue>)

** Relatório V

Número de confirmação: 1bf3640711f44deca5a91fa0f40451fc (<2025-06-07 Sat>)

** Relatório VI

Número de confirmação: a715270a618e4f0bbb6cac5469872828 (<2025-07-07 seg>)

** Relatório Agosto

Número de confirmação: 141d0184953e4dd59461a389bcb8d6d4 ([2025-08-09 Sat])

** Relatório de Setembro

- Comparaci às reuniões e assisti às gravações quando não estive sincronicamente
- Abri as respectivas quinzenas
- Realizei reuniões com os grupos e defini horários regulares para as reuniões
- Atividades teóricas:
  - Tema 03 da disciplina INT410
  - Quinzena 2 PJI500
  - Tema 04 e 05 da disciplina INT410
  - Começando tema 06

* Emacs internals :noexport:

# Local Variables:
# jinx-languages: "pt_BR"
# End:
