#+title:      Schumpeter meeting Keynes: a policy-friendly model of endogenous growth and business cycles
#+date:       [2025-02-05 qua 16:24]
#+filetags:   :bib:
#+identifier: 20250205T162456
#+OPTIONS: num:nil ^:{} toc:nil
#+PROPERTY:header-args R :results output drawer :eval never-export :session KS :exports both
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl
#+reference:  dosi_2010_Schumpeter

* FISH-5SS

** 5SS

[cite/t:@dosi_2010_Schumpeter] present a [[denote:20250202T120251][Policy Oriented]] [[denote:20250202T120740][Innovation-led growth models]] in which supply-side follow [[denote:20240708T155455][Schumpeterian growth models]] while demand is determined in a Keynesian manner.
This [[denote:20250202T121258][Endogenous Growth]] model produces [[denote:20240708T155635][Business Cycles]] and replicates a set of [[denote:20240708T155703][Stylized Facts]].
However, the demand-side of this model only accommodates the condition in order to the supply-side variables lead economic growth.
In general, this is a [[denote:20250202T120931][Heterodox Growth Models]] in which growth is innovation-led and demand constrained.

** Background and motivation

- In most [[denote:20240708T155455][Schumpeterian growth models]], demand-side variables do not play a key role [cite:see @nelson_2004_Evolutionary]
- In [[denote:20250202T121100][General Equilibrium Model]], demand-side only plays a significant role in the presence of frictions

** Supporting Ideas and hypothesis


In general, the authors try to build a most evidence-driven model as possible in which:

- Innovation is modeling using a two-step procedure. First firms try to innovate (imitate); if they are successfull, decide whether to implement the new discovered technology accordingly to its productivity
- When imitating, firms copy the technology from the competitors with similar technological level
  - In the code, the authors use an Euclidean metric to compute the distance from the frontier
- Firms send "brochure" with price and productivity of the produced machines to consumption goods firms
  - Consumption goods firms only have access to a fraction of all capital goods producers
- Capital goods growth rate could not exceed a maximum value [cite:@doms_1998_Capital]
- Firms market-share follows a [[denote:20250203T183408][Quasi-replicator]] mechanism in which depends on it relative difference to average competitiveness
  - Different from the traditional replicator mechanism this one allows for negative market-share values. Thus, it also detects the firms that will exit the market and, then recompute the actual market-share
- New entrants are assumed to be smaller than incumbents
- Government pay a unemployment benefit as a share of actual wage
- Households expend their whole income in consumption

There are some theoretical hypothesis:
- Expansion investment follow an [[denote:20250202T114158][Accelerator Model]]
- There is information imperfection
- Firms keep obsolete machines accordingly to its price and productivity considering a payback rule and its affects the replacement rule
  - [cite/t:@sraffa_1960_Production] may have an alternative to this behavioral rule
- Firms use adaptative [[denote:20250202T121158][Expectations]] rule
- If firms cannot finance its production with its own resources, borrow the remaining amount if it do not exceed the an exogenously defined debt/sales ratio
- There is a fixed number of firms. New entrants are ensured to match the number of the dead one

** Purpose

This model aim to:
- Evaluate how [[denote:20240708T155856][Process Innovation]] affects macroeconomic variables
- Analyze how this [[denote:20250202T121258][Endogenous Growth]] innovation engine interacts with aggregate demand
- Examine whether long-run economic growth is fully described by innovation-related variables or if there is room for demand-side variables

Additionally, this model evaluate the consequences of [[denote:20250202T121115][Fiscal Policy]] effects changing government expenditures and unemployment subsidies.
Thus, this model aims to provide a common [[denote:20250202T120251][Policy Oriented]] [[denote:20250202T114248][Agent Based Models]] framework.

** Contribution

This is the first medium-size long range AB [[denote:20250202T120931][Heterodox Growth Models]] [fn::[cite/t:@possas_2004_Multisectoral] previously present a similar framework.].
The main contribution is to provide a theoretical tool to analyze how [[denote:20250202T121115][Fiscal Policy]] and [[denote:20250202T120427][Monetary Policy]] affects economic growth, GDP volatility and innovation regime.

Besides explicitly presenting the interconnections between endogenous innovation and aggregate demand, this model replicates a collection of [[denote:20240708T155703][Stylized Facts]].
Afterwards, subsequent models consider this one as a benchmark to evaluate model's robustness.

** Relevance

This paper present the [[denote:20250202T115328][Canonical Models]] version of the [[denote:20250203T180327][Keynes meets Schumpeter Family]].
Most of the subsequent [[denote:20250202T114248][Agent Based Models]] refers to this one as a canonical version of a heterodox ABM.
Thus, my own work is influenced by this approach.

Considering the objectives of [[denote:20250202T120807][Innovation bubble ABM]] chapter, this paper provides some theoretical discusssion on how to deal with innovation.
Additionally, since this model uses a simple [[denote:20250202T114158][Accelerator Model]], the idea is to implement [[denote:20250203T184155][Supermultiplier Models]] specification and check the possible improvements.

** Methodology

Set of [[denote:20250202T114248][Agent Based Models]] simulated experiments.
The model have aggregate consumers, government, banks (implicity), and heterogenous firms (consumption- and capital goods producers).

The model is calibrated in order to replicate some [[denote:20240708T155703][Stylized Facts]]
The authors run each experimental  design using [[denote:20250203T181801][Monte Carlo Simulations]]
In order to evaluate the feedbacks between different supply (Schumpeter) and demand (Keynes) "engines", they implement shocks keeping the other constant.



** Results

*** General results

- Innovation is not enough to generates a sustainable long-run growth path
- Demand-side variables have effects on economic volatility and employment, but seems to be a necessary condition for the model's stability

*** Reported stylized facts

- Consumption and investment is procyclical and the latter is more volatile than GDP
- Productivity and inflation are procyclical
- Prices and markup are countercyclical
- Firms differ in terms of labor productivity
- Investment lumpiness [cite:@doms_1998_Capital]


*** Schumpeterian experiments

- If technological opportunities are rule out, the model collapses
- Higher technological opportunities have a positive effect on economic growth, reduce unemployment and GDP volatility
- When imitation is turned off, there is no difference compared to the baseline scenario
- When some sort o patent restriction is implemented, there is negative effects on economic growth
- Lower entries barriers (measured in terms probability of success of entrants) have positive effects on economic growth
- Anti-trust policies generates lower volatility and unemployment level with higher GDP growth

*** Keynesian experiments

- When turnning off the Keynesian instruments, economic growth is reduced, unemployment and GDP volatility increases
- Changes in the unemployment benefit share and tax rate have no effect on economic growth
  - The only effects regards economic volatility
- The effects of different parameters regarding wage setting are small
- In general, the Keynesian policies restricts the overall economic growth rate. The Schumpeterian side is not enough to sustain higher long-run growth levels


** Interesting findings and not categorized stuff


- Innovation make firms differentiate over time. Thus, productivity levels makes firms persistently heterogenous.
- When imitation is rule out, there is no difference compared with the baseline scenario

** Critics

- The demand role in the model is smaller than is stated by the authors
  - The authors themselves note that changes in fiscal policy regime have no effect on long-run economic growth
- There are some implicity hypothesis, such as the replacement of old vintages
- Some equations are not present in the paper (only in the code)
- It is unclear if this model is fully SFC. There is no equation that specify where the dead firms' capital will go and how the new entrants capital is financed.
- Since the authors use a simple [[denote:20250202T114158][Accelerator Model]] function, unemployment benefit may act as a floor to stabilize the model

Considering the objective of my PhD Dissertation, this model have the following internal limitations:
- Since prices are countercyclical, there is no room for an [[denote:20250202T114928][Asset bubble]] leading economic growth
- Innovation have a dominant impact on economic growth. There is little room for other variables

** Abstract

#+BEGIN_ABSTRACT
This paper studies an agent-based model that bridges Keynesian theories of demand-generation and Schumpeterian theories of technology-fueled economic growth. We employ the model to investigate the properties of macroeconomic dynamics and the impact of public polices on supply, demand and the “fundamentals” of the economy. We find profound complementarities between factors influencing aggregate demand and drivers of technological change that affect both “short-run” fluctuations and long-term growth patterns. From a normative point of view, simulations show a corresponding complementarity between “Keynesian” and “Schumpeterian” policies in sustaining long-run growth paths characterized by milder fluctuations and relatively lower unemployment levels. The matching or mismatching between innovative exploration of new technologies and the conditions of demand generation appear to suggest the presence of two distinct “regimes” of growth (or absence thereof) characterized by different short-run fluctuations and unemployment levels.
#+END_ABSTRACT


* Symbolic model

The idea of this experiment is to find state space equations for this model.
To do so, I'll assume that there is one firm of each type.
At the end, I expect to understand why this model have negative feedbacks regarding firms' expectations.




* DAG

#+begin_src R :dir .
equations <- sfcr::sfcr_set(
                     ## Capital goods firms: _i
                     Ld_i ~ Ldrd_i + Ldc_i,
                     Ldrd_i ~ (RD_i/w)*(Ldrd_i/LdRD_i),
                     LdRD_i ~ sum(Ldrd_i),
                     LdC_i ~ Qd_i/(B_i * l_prod_i),
                     c_i ~ w/A_i,
                     p_i ~ (1 + mu_i)*c_i,
                     RD_i ~ v*S_i[-1],
                     IN_i ~ xi*RD_i,
                     IM_i ~ (1 - xi)*RD_i,
                     theta_in_i ~ 1  - exp(-zeta_1*IN_i),
                     A_i ~ A_i*(1+xA_i),
                     xA_i ~ x1inf + beta(alpha1, beta1)* (x1sup - xinf),
                     B_i ~ B_i*(1+xB_i),
                     xB_i ~ x1inf + beta(alpha1, beta1)* (x1sup - xinf),
                     theta_im_i ~ 1  - exp(-zeta_2*IM_i),


                     ## Consumption goods firms: _j
                     Ld_j ~ LdC_j,
                     LdC_j ~ Qd_j/(A_i),
                     De_j ~ D_j[-1], ## Naive
                     Qd_j ~ De_j + Ne_j,
                     Qpe_j ~ Ld_j*A_1,
                     Nd_j ~ iota*De_j,
                     Ne_j ~ Nd_j - N_j[-1],
                     EId_j ~ Kd_j - K_j,
                     ## RS_j,
                     c_j ~ w/A_j,
                     p_j ~ (1 + mu_j)*c_j,
                     f_j1 ~ f_j[-1], ## To use second lag
                     mu_j ~ mu_j[-1]*(1 + nu*(f_j1 - f_j1[-1])/f_j1[-1]),
                     E_j ~ -omega_1*p_j - omega_2*l_j,
                     E_bar ~ weighted.mean(E_j, f_j1),
                     f_j ~ f_j[-1]*(1 + xi*(E_j - E_bar)/E_bar),
                     Pi_j ~ S_j - c_j*Q_j - r*Deb_j,
                     NW_j ~ NW_j[-1] + Pi_j - cl_j,
                     ## cl_j ~ , ## Internal funds
                     Sd_j ~ f_j*Y, ## FIXME Is this correct?
                     S_j ~ p_2*Sd_j,

                     ## Households
                     C ~ w*LD + wu*(LS - LD),
                     LD ~ Ld_i + Ld_j,
                     wu ~ phi*w,

                     ## Aggregates
                     Y ~ C + EI + (N - N[-1]),
                     EI ~ sum(EId_j),
                     ## N,
                   )

dag <- sfcr::sfcr_dag_cycles_plot(equations)
dag
#+end_src


* Model stress report

This Section present some primary analysis of the following experiments:


#+CAPTION: K-S (original model) stress test: Linear sensitivity analysis
|--------+-------------------------------------+------+----------+-----+------+------|
|--------+-------------------------------------+------+----------+-----+------+------|
| File   | Variable                            | LSD  | Baseline | Min |  Max |  New |
|--------+-------------------------------------+------+----------+-----+------+------|
| S2.lsd | R&D investment propensity           | nu   |     0.04 | 0.0 |  0.1 | 0.08 |
| S3.lsd | R&D allocation to innovative search | xi   |      0.5 | 0.0 | 0.95 |  0.7 |
| S4.lsd | "Physical" scrapping age            | eta  |       20 |   5 |   40 |      |
| S5.lsd | Desired inventories                 | iota |     0.10 | 0.0 |  0.2 |      |
| S6.lsd | Planned utilization level           | u    |     0.75 | 0.7 |  0.9 |      |
|--------+-------------------------------------+------+----------+-----+------+------|
|--------+-------------------------------------+------+----------+-----+------+------|


* Backlinks

[[denote:20250205T154234][Journal of Economic Dynamics and Control]]

[[denote:20250202T120807][Innovation bubble ABM]]

[[denote:20250203T184320][Technological revolution]]

[[denote:20250202T114248][Agent Based Models]]


* References

#+print_bibliography:
