#+title:      Pierangelo Garegnani, ten years after
#+date:       [2025-02-03 seg 18:47]
#+filetags:   :conferences:sraffian:
#+identifier: 20250203T184729
#+OPTIONS: num:nil ^:{} toc:nil

* Additional Backlinks

* Garegnani's research lines ten years after

** A neo-Ricardian Alternative to the Analytical

*** Introduction

Alternative microeconomics to [[denote:20250202T122123][environment_economics]] and [[denote:20250202T122013][ecological_economics]].
Most heterodox economics had main contributed to *Macroeconomics and Finance* (Green investment and endogenous money).

*** Ecological degradations as externalities

Corrective policies are introduced in order to *internalize* negative [[denote:20250202T114051][Externalities]] as a result of production process.

*** What does Ecological Economics do differently

The substitutability between capital and labour is argued to be strong over weak sustainability.
This relies on the marginalist assumption of dimmishing returns to increases of only one factor.

*** Ecological Marxism (EM)

Relies on Marx and Engels critiques of capitalism.
Recently, ecological surplus is proposed

** Girardi - Did capital strike? Redistribution, firm value and private investment during the 1981-1983 Frebch Socialist Experiment


Does egalitarian redistribution stifle private investment?

*** The 1981-1983 French Socialist experiment

- Social-Communist coalition takes power
- Pro-labor and egalitarian redistribution program
  - Tax policy :: Wealth tax, income taxes on firms and high incomes
  - Labor market :: Reduce of work-week and retirement age
  - Nationalizations ::

*** Capital strike

[[denote:20250202T115448][Capital Strike]] hypothesis: Redistributive plataform $\Rightarrow$ lower expected profitability $\Rightarrow$ lower private investment.
It is argued that there also other factors (most external) that could explain private investment decrease.

*** Dataset


- Stock market prices :: impact on expected profitability and its contributions

*** Impact on expected profitability

- Early survey on voting seen that a socialism win was not expected
- Large negative effect on value of French firms
  - US firms, for example, does not have this effect in the same period
  - Firms listed in French does not had a negative
  - Nationalization targets were the higher negative effect
- Firms more exports oriented had larger share price decrease

*** Macroeconomic effects of the French Socialist Experiments


**** Synthetic Control analysis

- Build a 'doppleganger' France as a optimally-weight average of other advanced economies
- Outcome of interest
  - Business investment
  - Real GDP
  - Equity values
  - Inflation

**** Firm-level DiD analysis


- Financial statements for a sample of global public companies
- Negative effect on profitability, but investment there were no sign of negative effect
  - Investment stagnation was in line with other countries investment stagnation





* Roundtable Garegnani's legacy ten years after
