#+OPTIONS: num:nil ^:{} toc:nil
#+title:      A Note on Interactions-Driven Business Cycles
#+date:       [2025-02-06 qui 14:41]
#+filetags:   :bib:
#+identifier: 20250206T144122
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl
#+reference:  westerhoff_2007_Note


* FISH-5SS


** 5SS

[cite/text:@westerhoff_2007_Note] present a [[denote:20250203T180258][Keynesian Multiplier]] model with a interactive process in which marginal propensity to consume is endogenous.
The model produces [[denote:20240708T155635][Business Cycles]] depending on the composition of optimistic and pessimistic consumers, eventhought neither of the models have this cyclical pattern.


** Background and motivation

- This model departure from a [[denote:20250203T174044][Generic Opinion Formation]] model

** Supporting Ideas and hypothesis

- It assumes that marginal propensity to consume is endogenous
- Following empirical research, assumes that optimistic consumers consume more
- It is assumed constant [[denote:20250202T114954][Autonomous Expenditures]] (government consumption and private investment)
- There is an asymmetry between the consumers states
  - When GDP is growing, it is harder to pessimistic consumers to convince others to became pessimistic as well (the reverse is also valid)
  - There is an autonomous component change as well

** Purpose, Relevance, and Contribution

Regarding the [[denote:20250202T120807][Innovation bubble ABM]] chapter, this paper presents some interesting insights for interactive [[denote:20240708T155635][Business Cycles]].
For a future research, it could also provide inspiration for a interaction between different investment functions.

- This paper aims to extends the canonical Keynesian Multiplier model with an interactive process to reflect socioeconomic ineractions

** Methodology

- Micro-macro interactive model (not explicitly an [[denote:20250202T114248][Agent Based Models]])
- Uses [[denote:20250203T181801][Monte Carlo Simulations]] procedure
- Generic Opinion Formation in which consumers can assume an optimistic or pessimistic state
  - The main difference with this model is the inclusion of a [[denote:20250202T121139][Feedback mechanisms]] from the macroeconomic level to the individual level
  - At each time step, consumers interact and evaluate if will change its state or not
  - The average propensity to consume assumes \(\alpha^{P} \leq A \leq \alpha^{O}\), thus
    - \(Y^{min} = Y(\alpha^{P})\) and \(Y^{max} = Y(\alpha^{O})\) when the average propensity to consume assumes the extreme values

** Results

- The model generates Business Cycles eventhought each of the isolated components (Keynesian Multiplier and Generic Opinion Formation) does not have this property
- The model rationalle follows:
  - If average propensity to consume increases, GDP increases as well, increasing the probability to \(A\) continue to increase (due to the asymetry between optmistic and pessimistic). This process continues until the average propensity to consume reaches the maximum value, reducing the GDP growth rate and, consequently, increasing the probability to optimistic changes the state to pessimistic
- The Business Cycles is generated by [[denote:20250202T121645][Consumer Sentiments]]

** Interesting findings and not categorized stuff

- The model has \(N + 1\) equilibra in the Keynesian Multiplier

** Critics and questions

- If marginal propensity to consume is endogenous, this implies that [[denote:20250202T113822][Income Distribution]] is endogenous as well?
  - If so, is this compatible with the [[denote:20250203T184155][Supermultiplier Models]]?
- It is unclear the reason of the absence of exponentially distribution of cycle-length generates a macroeconomic feedback
- Does this results holds if Autonomous Expenditures is not constant?

** Abstract

#+BEGIN_ABSTRACT
Within the standard Keynesian multiplier framework, extended by a micro-model of interactive formation of individual consumption propensities, we demonstrate that socioeconomic interactions can lead to cyclical fluctuations in aggregate economic activity.
The underlying micro-model of direct interactions is a version of Alan Kirman’s generic opinion formation model, with an additional feedback effect from macroscopic variables on the transition probabilities.
Our model engenders cyclical fluctuations of economic variables, despite the fact that neither the Keynesian multiplier model nor Kirman’s model does so on its own.
#+END_ABSTRACT


* Specific notes

** Model

Let \(K\) to be the number of consumers with higher propensity to consume (optimistic):

\[K = \alpha^{O}N\]

At the next time step, the number of optmistic will change accordingly to:
\begin{equation}
\Delta K_{t} = \\
\begin{cases*}
  +1 \Leftrightarrow P^{+}_{t-1} = \frac{N - K_{t-1}}{N}\left(\epsilon + \left(1 - \delta^{P\to O}\frac{K_{t-1}}{N - 1}\right)\right)\\
-+1 \Leftrightarrow P^{-}+_{t-1} = \frac{K_{t-1}}{N}\left(\epsilon + \left(1 - \delta^{O\to P}\frac{N - K_{t-1}}{N - 1}\right)\right)\\
0 \Leftrightarrow 1 - P^{+} - P^{-}
\end{cases*}
\end{equation}

in which \(\delta^{X\to Y}\) indicates the probability to change from state X (optimistic/pessimistic) to Y (pessimistic/optimistic) that have the following law of motion:

\begin{equation*}
\delta^{P\to O} =
\begin{cases}
\delta + \gamma \,\,\, \text{if} \,\, g_{Y} > 0\\
\delta - \gamma \,\,\, \text{if} \,\, \text{otherwise}
\end{cases}
\end{equation*}


\begin{equation*}
\delta^{O\to P} =
\begin{cases}
\delta + \gamma \,\,\, \text{if} \,\, g_{Y} < 0\\
\delta - \gamma \,\,\, \text{if} \,\, \text{otherwise}
\end{cases}
\end{equation*}

* Annotations (zotero)



``micro-model of interactive formation of individual consumption propensities'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 85]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=1&annotation=P8QFJKKB][pdf]])
{METHOD}

``Alan Kirman's generic opinion formation model,'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 85]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=1&annotation=KMNK232N][pdf]])
{BACKGROUND}

``Our model engenders cyclical fluctuations of economic variables, despite the fact that neither the Keynesian multiplier model nor Kirman's model does so on its own.''
([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007,
p. 85]])
([[zotero://open-pdf/library/items/HAHQH34C?page=1&annotation=2GJ4TNMU][pdf]])
{RESULT} Generates Business Cycles eventhough each part of the model is deterministic.

``extended by a micro-model of interactive formation of individual consumption propensities, that direct socioeconomic interactions can lead to cyclical fluctuations in aggregate economic activity (i.e. to business cycles).'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 86]])
([[zotero://open-pdf/library/items/HAHQH34C?page=2&annotation=ERXEI3NW][pdf]])
{PURPOSE}

``two individual states as optimism---associated with a higher consumption propensity---and pessimism---associated with a lower consumption propensity'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 86]])
([[zotero://open-pdf/library/items/HAHQH34C?page=2&annotation=4JSFSCQY][pdf]])
{METHOD} The authors related the marginal propensity to consume as states of [[denote:20250202T120344][Optmism bias]] and [[denote:20250202T120415][Negative bias]].

``with Gt+1 comprising all autonomous expenditures (private and government),'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 86]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=2&annotation=YGP7YHJB][pdf]])
{METHOD} There is autonomous expenditures.

``This interaction process is in the spirit of Kirman (1993), with the additional feature of a feedback from aggregate (macroscopic) variables acting upon the individual transition probabilities of the process.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 87]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=3&annotation=4IULAHK7][pdf]])
{CONTRIBUTION} The aggregate variables affects the individual variables.

``we assume that an optimistic consumer will consume more---and thus save less---relative to a pessimistic one.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 87]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=3&annotation=BHSUQA88][pdf]])
{HYPOTHESIS} Marginal propensity to consume is endogenous; optimistic consumer expendes more.

``Let Kt = αtN denote the number of consumers with the higher value of consumption propensity (optimists) at time t. In each time step, two consumers meet at random and the first consumer will adopt with a given probability 1 − δ(·) the state of mind---and along with it the consumption propensity---held by the other. In addition, there is a small probability of an autonomous change. In our model---unlike the Kirman (1993) model---the probability δ may be asymmetric with respect to whether an optimist influences a pessimist or vice versa, dependent on the aggregate state of the economy. The idea is that it should be harder for an optimist to convince a pessimist to adopt his (the optimist‘s) state of mind if aggregate output is decreasing than if it is increasing, and vice versa.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 87]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=3&annotation=IC3J74LW][pdf]])

{DESCRIPTION} Describes the interaction process.


([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 88]]) INCLUDE\\ This indicates an assymetry. When GDP is growing, it is harder to pessimistic convince others to became pessimistic as well.

``using the MonteCarlo simulation approach'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 88]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=4&annotation=68DXXEG4][pdf]])

{METHOD}

``appearance of cyclical fluctuations of national income resembling those found in empirical data.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 88]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=4&annotation=G4LVX2LX][pdf]])

{RESULTS}

``displays the distribution of cycle-lengths'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 88]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=4&annotation=I3K549DA][pdf]])

{RESULTS} The cycle length seems to be a quite of large.

``First, note that there are N + 1 equilibria in the multiplier model, corresponding to the average consumption-propensity taking a value in the range aP ≤ At ≤ aO.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 89]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=5&annotation=4KQ6J8PD][pdf]])

{FINDS} There are multiple equilibria.

``Since in our model cycle length is not exponentially distributed, there is also a fundamental feedback from the real-sector dynamics to the process itself.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 89]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=5&annotation=XW9T8BH4][pdf]])

{QUESTION} It is unclear why the absence of length distribution generates macroeconomic feedbacks.

``This influence is most clearly visible if we focus on the change in the direction of movement of At.IfAt has increased in the previous periods, so has Yt, and the increase of the latter, in turn, makes At more likely to continue to increase (because the probabilities of convincing are asymmetrical). But once At comes close to its maximal value, and the increase of Yt slows down or comes to a halt, the transition probabilities are more likely to switch from δP→O = δ − γ'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 89]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=5&annotation=ZR9S2BJ2][pdf]])

{DESCRIPTION} TODO: Rewrite with my own words.

``in our type of models there is an additional influence channel acting through consumer sentiment.'' ([[zotero://select/library/items/Z4QDSMNW][Westerhoff e Hohnisch, 2007, p. 90]]) ([[zotero://open-pdf/library/items/HAHQH34C?page=6&annotation=B3YKP6TW][pdf]])

{RESULTS/CONTRIBUTION}

* Additional Backlinks

[[denote:20250206T143903][Journal of Economic Interaction and Coordination]]

- [[denote:20250202T114158][Accelerator Model]]
- [[denote:20250203T184226][Switching Mechanisms]]
- [[denote:20250202T120908][Heterogenous Agents]]
- [[denote:20250202T122209][Evolutionary Selection]]
- [[denote:20250202T115151][Behavioral extrapolation]]

* References

#+print_bibliography:
