#+title:       Post-Growth Transition, Working Time Reduction, and the Question of Profits
#+date:       [2026-01-08 Thu 11:38]
#+filetags:   :bib:distribution:made:postgrowth:todo:wtr:
#+identifier: 20260108T113858
#+reference:  oberholzer_2023_postgrowth

[[denote:20260107T154800][Reading list]]

[[denote:20260108T111817][Green ABM for Working Time Reduction]]

* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis


** Purpose, Relevance, and Contribution


** Methodology


** Results


** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
The ecological macroeconomics literature has developed models, which outline the transition from today's growth-dependent economies to post-growth systems where output can be stabilized to limit resource consumption while good living conditions and high employment are ensured. Working time reduction plays a pivotal role in those transitional strategies to relax the trade-off between economic growth and unemployment. This analysis contributes to the research by developing a macroeconomic model where, in contrast to the existing models, a sufficient profit rate is the precondition of any private-sector economic activity. It is shown that under such assumptions working time reduction is not enough to stabilize output but is a threat to macroeconomic stability. To make the post-growth transition successful, working time reduction must go along with supporting economic policies and macroeconomic governance including public investment, which controls the private-sector profit rate to avoid instability and unemployment.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

* Additional Backlinks



* References
