#+TITLE:  (2004, ): Induced investment and business cycles
#+OPTIONS: toc:nil num:nil
#+ROAM_KEY: cite:minsky_2004_Induced
Time-stamp: 2021-04-15
- tags :: Business cycles,Capital investments,Uncertainty

* Backlinks

* FISH-5SS
|---------------------------------------------+-----|
| <40>                                        |<50> |
| *Background*                                  |     |
| *Supporting Ideas*                            |     |
| *Purpose*                                     |     |
| *Originality/value (Contribution)*            |     |
| *Relevance*                                   |     |
| *Design/methodology/approach*                 |     |
| *Results*                                     |     |
| *(Interesting) Findings*                      |     |
| *Research limitations/implications (Critics)* |     |
| *Uncategorized stuff*                         |     |
| *5SS*                                         |     |
|---------------------------------------------+-----|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: minsky_2004_Induced
 :AUTHOR: Minsky, H. P., & Papadimitriou, D. B.
 :JOURNAL:
 :YEAR: 2004
 :DOI:
 :URL:
 :END:

* PDF Highlights
:PROPERTIES:
:NOTER_DOCUMENT: ../PDFs/Minsky e Papadimitriou - 2004 - Induced investment and business cycles.pdf
 :END:

** The survival of firms

"If non-linear accelerator type models are to be used in business cycle theory" (Minsky and Papadimitriou 2004:102)

[PREV] non-linear types must be used. (note on p.102)

"We will examine the hypothesis that the effect upon investment of a change in income depends upon the relation between investment decisions of individual firms and (1) the structure of the product markets in which the firm is operating and (2) the financing conditions which confront the firm.This leads us to a study of the investment behavior of business firms." (Minsky and Papadimitriou 2004:102)

[Hypo] Inducement investment depends on individual firms decisions, which depends on structure of the product markets and financing conditions. (note on p.102)

"Oligopoly, the region between competition and monopoly,does cause us concern,and we will have to set up a working model of such markets." (Minsky and Papadimitriou 2004:102)

Oligopoly will be analyzed separetely (note on p.102)

"Therefore, financing conditions are particularly relevant to any theory of firm investment behavior designed for business cycle analysis." (Minsky and Papadimitriou 2004:102)

Minsky report the relevance of financing conditions -> term under which a firm can obtain financing. (note on p.102)

"The market structure determines the manner in which a change in the product demand curve is transformed into a change in the demand curve confronting a firm, and, within limits, the firm's reaction to its demand curve. The relation between induced investment and market structure therefore depends upon the effect that market structure has upon the determination of the firm's demand curve and upon the firm's behavior principle." (Minsky and Papadimitriou 2004:103)

[IDEA] Market structure and market share is already considered in baseline paper (Pedrosa and Lang, 2021). (note on p.103)

"'if the prices of commodities and the prices of factors were perfectly flexible, then whatever happened to the volume, or velocity of money, you might get cycles in price levels, you might get cycles in income measured in money, but you would not get cycles in the ratio of employed to unemployed resources'" (Minsky and Papadimitriou 2004:103)

[THEORY] If prices were flexible, where would be a nominal business cycle, but not a real one (in terms of ration of employed resources). (note on p.103)

"The factors which made for price rigidity, in the present (1936) were, 'the prominent item in the moral code of business which looks upon price stability as an economic virtue and price cutting as the most heinous of economic sins';6 and 'the general accounting practice of computing costs for all purposes on the average rather than the marginal or differential basis'." (Minsky and Papadimitriou 2004:103)

Some factores determining price rigidity. (note on p.103)

"he price rigidities operate so as to transform any decrease in total (or particular product) demand into a decrease in the quantity taken of the product. With price flexibility the contention is that a decrease in total demand will result in movements down in the incremental cost curve. If factor prices are flexible,the downward shift of the incremental cost curve due to the fall in factor prices will tend to leave the quantity produced,and therefore employment,unchanged.This business cycle theory does not take into account the reciprocal effect of flexible prices of factors and commodities upon the volume of total demand. This phenomenon, due to the assumption of 'induced' expenditures (the consumption function), is the key to Keynesian and later business cycle analysis." (Minsky and Papadimitriou 2004:104)

A brief discussion on the effects of price rigidity and flexibility on inducement of investment. (note on p.104)

"In contrast with the Keynesian and later business cycle theory, the price flexibility cycle theory of Viner did not specifically distinguish between consumption demand and investment demand. The lack of a separate analysis of the factors relevant to the determination of these broad categories of aggregate demand had led to its general abandonment. In addition, this theory relies upon autonomous changes in the quantity of money or in the velocity of money to initiate the cycle." (Minsky and Papadimitriou 2004:104)

Monetary business cycle theory. (note on p.104)

"We will emphasize the relation between market structure and the determinants of the investment behavior of firms rather than the part played by market structure as a" (Minsky and Papadimitriou 2004:104)

Focus on market structure on firm behaviour and not on price rigidity. (note on p.104)

"Before we go further, it is necessary to clarify the relation between a plant and a business firm. A plant can be identified with a collection of fixed productive factors. A firm can be identified as an entrepreneurial or decision making unit. The plant is a set of productive factors which cannot be depreciated or used up rapidly. The size of plant is determined by a firm on the basis of the following information (some of which may be conjectural)" (Minsky and Papadimitriou 2004:105)

Some clarification on the differences between a plant and a business firm. (note on p.105)

"The firm is an economic unit which makes the following decisions: (a) the product to be produced; (b) the rule of behavior to be used in determining the optimum size plant; (c) the rule of behavior of a given plant with respect to a given demand curve; (d) the financing technique to be used." (Minsky and Papadimitriou 2004:105)

[RESUL] Set of firms decisions. Emphasis on (d) financing technique to be use. (note on p.105)

"The production function may be such that one and only one scale of plant is efficient. A scale of plant is efficient if the price compatible with normal or acceptable profits for this plant is not significantly higher than for any other size plant.15If one and only one scale of plant is efficient,the long run cost curve that results is the typical U-shaped cost curve. Firms which are too small,in terms of their financing ability,to acquire plants of the efficient size will in time be eliminated from the industry.Their productive equipment will either be modified and utilized in plants of efficient size or their productive equipment will be redundant. Firms which have large equities in relation to the cost of acquiring this technically optimum scale of plant will in time be multiple plant firms." (Minsky and Papadimitriou 2004:106)

Some discussion on efficient plant scale. There is some relation with normal or acceptable profits. (note on p.106)

A partir daqui parece começar a discutir fatores financeiros. (note on p.112)

"The objective phenomenon related to the survival of a firm is its balance sheet structure. What we will do is construct cost curves which take into account the effects of the balance sheet structure of a firm upon its survival conditions." (Minsky and Papadimitriou 2004:144)

"In such a case the maintenance of the ability to pay debts when due requires one of the following: 1. 2. 3. the firm begins with excess liquidity; the firm sells assets to acquire liquidity; the firm borrows (sells debt) to acquire liquidity." (Minsky and Papadimitriou 2004:145)

"A firm may have assets in its balance sheet which are not necessary for its production process (government bonds, idle cash and excess inventories are examples) or it may not. If it has such assets, a period of losses will not necessarily result in a decrease of plant size." (Minsky and Papadimitriou 2004:145)

Assets prevent plant size reduction (note on p.145)

"eliminating from the balance sheet the liabilities which are most harmful to survival." (Minsky and Papadimitriou 2004:145)

IMPORT: Eliminating balance shett liabilities that treat firm's survival instead of investing. (note on p.145)

"Such assets superfluous to production do improve the survival potentialities of a firm. For long run analysis, however, they are irrelevant." (Minsky and Papadimitriou 2004:146)

Superfluous assets to production improve the survival, but is irrelevant in the long run (note on p.146)

"firm with no superfluous assets, so that any further losses will entail either a decrease of plant capacity or an increase in borrowing." (Minsky and Papadimitriou 2004:146)

In the LR, the firm could decrease plant capacity or increase borrowing. OBS: There is no empirical evidence on the firs one. (note on p.146)

"The firm may obtain control over these necessary productive factors by means of a number of different types of contracts. We need to distinguish between two types of contracts by which a firm may obtain control over a productive factor: either by purchasing or renting (or hiring) the factor. We will take up the effects upon the survival of a firm of these different types of contracts." (Minsky and Papadimitriou 2004:147)

[DISCUSS] Type of contracts for productive factors: purchasing or renting. (note on p.147)

"The acquisition of title to productive factors which is financed by an increase in net worth has different repercussions upon the survival attributes of a firm than the acquisition of title to a productive factor which is financed by an increase in the firm's debt." (Minsky and Papadimitriou 2004:147)

Survival is different if asset increase occurs with debt increase and not net worth. (note on p.147)

"If the term of the debt is longer than the normal life of the productive factor the survival conditions are easier, and if the term of the debt is shorter than the normal life of the productive factor the survival conditions are harder than if their periods are the same length." (Minsky and Papadimitriou 2004:147)

Comparing debt term with productive normal life. (note on p.147)

"Renting or hiring does seem,on the surface,to be different from the purchase of a productive factor." (Minsky and Papadimitriou 2004:147)

[OFF] Renting. (note on p.147)

"side from risk premiums, the two different types of contracts impose the same cash requirements upon the firm. The distinction is not between rental or ownership of a productive factor; the relevant distinction is between equity financing as against both the renting or the purchasing, by means of debt financing, of a factor." (Minsky and Papadimitriou 2004:148)

Debt vs net worth is more relevant than rent vs purchase. (note on p.148)

"In what follows we will assume except for the rental of such short run variable factors as labor,that a firm will acquire control over factors of production whose value is greater than its owners' equity by means of debt financed purchase.It must be pointed out,however,that where we derive a rising supply curve for factors of production to a firm because of the deterioration of the firm's financing conditions, as it increases its debts with a fixed equity base,the firm may,if there is a well-organized rental market for such factors of production, be actually confronted by an infinitely elastic supply curve of the factor." (Minsky and Papadimitriou 2004:149)

[HYPO] acquire value > owner's equity by means of debt. (note on p.149)

"of the scale of output, and with a given plant the optimum size of inventories will vary uniquely with the output of the plant." (Minsky and Papadimitriou 2004:150)

About inventories. (note on p.150)

"The volume of cash which a firm has in its balance sheet will also be a function of its level of output. We can consider Keynes' three attributes of a cash balance as being relevant to the firm as well as the household: firms can hold cash for transactions, precautionary and speculative purposes." (Minsky and Papadimitriou 2004:150)

Reasons for firms to hold cash ~ Keynes ~ level of output. (note on p.150)

"The speculative portion of cash balance is irrelevant for our analysis of the firm as a production unit. As has been mentioned earlier, a firm may be used as an investment trust or as a vehicle for financial operations by its owners. Speculative cash balances are of that nature. Decisions on the part of management to speculate by increasing the cash balance, however, are relevant to the analysis of investment decisions by the firm." (Minsky and Papadimitriou 2004:150)

Speculative reason is not that important by the analysis, but are relevant to the investment decisions. (note on p.150)

"The structure of the assets of a firm is determined by the following variables: the scale of plant, the level of operation of the plant over a time period, the temporal nature of both the demand for the product and the production process, the risk attached to the assets and the requirements imposed by the liabilities (which accounts for precautionary cash and other" (Minsky and Papadimitriou 2004:150)

determinants of firm's assets. (note on p.150)

"Any asset total greater than that so determined (as everything is scaled to the size of plant, the plant and equipment items are constant) involves the use of the firm by its management for something more than the production process: for 'speculative' or 'investment' purposes." (Minsky and Papadimitriou 2004:151)

Any total >= -> speculative or investment purposes.
Investment is a residual of firm survival. (note on p.151)

"he liability side of the balance sheet also has a structure,but this structure cannot be so intimately related to the production process of the firm. The liability structure is more a matter of choice by the firm's management." (Minsky and Papadimitriou 2004:151)

Liabilities are more a choice than a production result. Liabilities <- management <- capital structure. (note on p.151)

"The money market institutions determine the alternative financing techniques available to a firm,and the conditions under which the firm can use each financing technique so as to acquire sufficient resources to obtain the assets necessary for a given level of operations." (Minsky and Papadimitriou 2004:151)

Banks determines the alternatives and techniques. (note on p.151)

"The attributes of liabilities which are relevant to the behavior of a firm are the money costs which are attached to each liability, the date upon which payment of each liability is due, and the penalties under the law for non-payment of obligations as their due date occurs." (Minsky and Papadimitriou 2004:151)

Liabilities attributes: costs, date, penalties. (note on p.151)

"financing is the ideal: the necessary costs are zero - all equity returns being contingent; there is no repayment date; and the penalty for non-payment of dividends is not necessarily a loss of control of the firm by the owner" (Minsky and Papadimitriou 2004:151)

Ideal penalty.
[IDEA] Firms behaviour based on desired/normal liability attribute. (note on p.151)

"The other liability forms entail both a cost and a due date.The cheaper the costs,the more desirable the liability;and the further away the due date, the more desirable the liability. The money market behaves so that,for a given scale of operations,the larger the proportion of the assets of a firm which are financed by debt instruments, the less desirable the liabilities of the firm are as financial institutions assets, and therefore theless desirable are the liabilities which the firm can have." (Minsky and Papadimitriou 2004:151)

Firms' liabilities preferences. (note on p.151)

2021/04/12 (note on p.152)

"Therefore, the balance sheet of the firm which uses a small plant intensively will exhibit a more preferred class of liabilities than the balance sheet of the firm with the larger scale plant." (Minsky and Papadimitriou 2004:152)

Which firm scale is preferred regarding class of liabilities. (note on p.152)

"Balance sheets of firms which exhibit debt instruments on the liability side differ in the cost per unit of debt and in the average term of the debt. Both a higher cost per unit of debt, and a shorter average term of debt impair the survival chances of a firm, all other things being the same. A balance sheet of a firm is said to deteriorate as (1) the average cost of liabilities which the firm has increases; (2) the average term of the liabilities decreases (if the distribution of the asset side of the balance sheet remains fixed); and as (3) the ratio of equity to total liabilities decreases." (Minsky and Papadimitriou 2004:152)

Firm's balance sheet deterioration causes: increase of interest rate; decrease of debt term and; increase of leverage. (note on p.152)

"Therefore, the fundamental attribute of the balance sheet is the ratio of equity to total assets." (Minsky and Papadimitriou 2004:152)

Leverage (equities/assets) is the main attribute of balance sheet deterioration. (note on p.152)

"Balance sheet deterioration affects a firm in two ways: it does mean that a larger total revenue is needed at each level of operations if the firm is to survive, and the shorter term of the debt does make the liquidity conditions more stringent. From the standpoint of survival of the firm, the ideal balance sheet is one in which equity is the only liability entry. Therefore, we shall use this type of balance sheet as a zero point in our analysis." (Minsky and Papadimitriou 2004:152)

How balance sheet deteriorarion affects firms: more income to interest rate payment; the shorter term, the lower liquidity.
Benchmark: no liabilities. (note on p.152)

"greater than this involves borrowing, and the operation of the plant at any level lower than this involves an increase in speculative and investment assets in the firm's balance sheet" (Minsky and Papadimitriou 2004:153)

Increase in asset to higher level than the operational leads to an increase in speculative and investment assets. (note on p.153)

"In what follows we will for expository purposes assume that there is a one to one correspondence between a firm and a planning curve.In the real world a firm may own a number of plants, which may be associated with different production functions.This assumption is a deviation from the reality of a 'conglomerate'firm." (Minsky and Papadimitriou 2004:153)

Hypothesis: firm == plant. (note on p.153)

"For each size of plant we can therefore state the maximum output that the fixed owners' equity of a firm can finance." (Minsky and Papadimitriou 2004:153)

For a plant, there is a level of max outupt (q) that does not require debts other than owners' equity. (note on p.153)

"Price" (Minsky and Papadimitriou 2004:154)

Price of what? Output? Capital goods?

Probably factors' price excluding debt. (note on p.154)

"Financing possibilities of a given owner's equity" (Minsky and Papadimitriou 2004:154)

Similar to a frontier of owner's equity financing. After this point, any marginal outpur requires both factor's price increase and debt costs. (note on p.154)

"SRMC" (Minsky and Papadimitriou 2004:154)

Short -run marginal cost curve. (note on p.154)

"If we assume a constant interest rate on such financing, and if the amount of such financing is a linear function of the level of output greater than that which can be financed by the firm's own resources, the total cost curve for this element of cost is a straight line with a slope equal to the interest rate times the financing necessary per unit of output.If outputs smaller than that amount which can be financed by internal funds are to be produced,the firm may earn a return on these superfluous funds.As the return which a firm can earn by investing such superfluous funds is generally lower than the cost of the funds it borrows, the cost of financing curve will have different slopes for outputs lower than the output which can be financed internally than it has for outputs which require borrowed funds." (Minsky and Papadimitriou 2004:154)

Total cost curves (complete diagram with debt service) which have different slopes due to capacity to finance with undistributed profits.

Question: firms usually intend to distribute profits motivated by various reasons, how this "firms survival analysis" is compatible with this? (note on p.154)

"Figure 6.2" (Minsky and Papadimitriou 2004:155)

This figure show the breaks in cost curves after undistributed profits frontier.

Question: It is not clear why total viariable costs (without finance) has a positive slope. This is the case of factors substitution? Full-employment? (note on p.155)

"In the short run, with no superfluous assets in the original balance sheet, the survival condition is that total revenue is greater than the total variable cost associated with the particular plant (the total variable cost curve in this" (Minsky and Papadimitriou 2004:155)

Short-run survival condition: revenue > variable cost (excluding user capital cost). (note on p.155)

"Figure 6.3" (Minsky and Papadimitriou 2004:156)

Discontinuity in both average and marginal costs regarding financing expenditures.

Question: there is an implicity assumption that firm will borrow only after use of all retained profits? (note on p.156)

"In the long run (in this case the existence of superfluous assets is irrelevant), the survival condition is that total revenue yields not less than a zero rate of return on owners' investment." (Minsky and Papadimitriou 2004:156)

Long-run survival condition: return of total revenuel ~ rate of reurn on owner's investment > 0. (note on p.156)

"The zero rate of return to owners' investment has to be underlined. This means that the long run survival conditions depend upon the balance sheet structure of firms. A firm which has no debt - for example, wholly owned plant and working capital - has easier survival conditions than a firm which debt finances a portion of its plant or working capital." (Minsky and Papadimitriou 2004:156)

The long-run survival condition depend upon balance sheet structure of firms. (note on p.156)

"Therefore, for a particular plant, the average cost curve, which is identified as the survival average cost curve, must take into account the balance sheet position of the firm. This average cost curve asserts that the plant associated with the given marginal cost curve,and with the given structure" (Minsky and Papadimitriou 2004:156)

"140 Induced investment and business cycles of debt in its balance sheet, can survive over all time in the future only if the per unit revenue associated with any output is always greater than the per unit cost of that output which is shown by the survival average cost curve. As soon as the balance sheet changes, with the same plant, the survival average cost curve changes. If a firm that makes profits above dividends retires a portion of its debt,its survival average cost curve falls.The minimum survival average cost curve is the average cost curve associated with a zero return on the total investment necessary to operate a plant at a given level. It is the effective survival average cost curve only for a firm which, when operating that plant at that level, has zero debts. As a firm's debts approach zero, the survival average cost curve approaches this zero return on total assets average cost curve." (Minsky and Papadimitriou 2004:157)

Sumarry of the firm's financial survival conditions (note on p.157)

"These two curves are the same for every firm in the industry with a given size plant. They are independent of balance sheet structure, being transformations of the production function. The larger the proportion of assets,for a given size plant at a given level of operation,that is financed by borrowed funds, the higher the survival average total cost curve; also, the less advantageous the terms upon which a particular firm can borrow, the higher the survival average total cost curve. We therefore find that in an industry where firms have identical size plants the survival conditions will vary for the different firms." (Minsky and Papadimitriou 2004:157)

Short-run survival condition curves which are indpendent of balance sheet structure.
Firms with identical size plants will have different survival condition based on balance sheet strucutre. (note on p.157)

"If we assume that regardless of the amount of borrowing, the interest rate and the borrowing per unit of output remain the same, the marginal cost curves for all firms, once they begin borrowing, are the same as they are for that level of operations which can be financed out of internal funds." (Minsky and Papadimitriou 2004:159)

If r = cte, costs are equal at le q_n level. (note on p.159)

"If r is a which borrow to finance a part of their operations are the same.q0,so that the interest rate increases with the amount of borrowing, then the marginal cost curves for all firms which borrow to finance a part of their operations are not the same - the firm which borrows a smaller proportion will have a lower marginal cost for each output - or it can produce a larger output at a given marginal cost." (Minsky and Papadimitriou 2004:159)

If r varies with q, the marginal costs of firms will differ regarding the balance sheet strucutre. (note on p.159)

"A firm whose balance sheet has no debts,for example the firm whose survival curve is marked ATC0 in Figure 6.5, could stand a fall in the market price to p3and still survive,whereas a firm whose balance sheet is such that it has the survival average cost curve marked ATC1 as its survival curve, could not survive a fall in the price of the product below p1." (Minsky and Papadimitriou 2004:159)

If the market price (of what?) decreases, firms with less debts will have more chance to survive. (note on p.159)

"A marginal firm therefore can be defined as a firm whose survival conditions are such that any fall in the market price of the product will cause an end to the firm's existence (or a decrease in the 'owners'equity')." (Minsky and Papadimitriou 2004:159)

[DEF] Marginal firm: if market price of the product decrease, the firm will no longer exist. (note on p.159)

"The long run survival average cost curve for a firm has to include the effects of the method by which plants of varying size would have to be financed." (Minsky and Papadimitriou 2004:160)

In the long-run, tje cost curve must include the financial instrument by wich plants of *varyung size* would have to be financed. (note on p.160)

"1lant for a firm to build must take into account 2he terms available to the firm to finance scales of operations greater than the output which its own resources can finance." (Minsky and Papadimitriou 2004:161)

Example of long-run condition. (note on p.161)

"This survival short run average cost curve indicates the prices and quantities of the output of the firm produced by the given plant which enables the firm to pay all its financing costs (including the repayment of the debt when due) without decreasing the owners'equity." (Minsky and Papadimitriou 2004:161)

[DEF] Survival short run average cost curve (SRAC). (note on p.161)

"This gives us the important result that the long run marginal cost curve which determines the optimum plant for firms that finance their operations by debt is independent of the planning rate that the firm may use." (Minsky and Papadimitriou 2004:161)

[RESUL] LRMCC -> optimum plant -> independent of panning rate. (note on p.161)

2021/04/14 - 12h09 (note on p.163)

"The difference between the total cost, zero returns and the total cost r returns for any output greater than that which can be financed by owners' equity is a constant, r, times the owners' equity. Therefore, the LRACr approaches LRAC0 as output increases beyond that which can be equity financed. Hence the difference between the r yield price and the zero yield price decreases with output.Therefore,given r,the larger the debt financed output planned for,the smaller the fall in price which would result in a firm changing from making profits to making losses.The size of the fall in price which could be withstood without such losses can be considered as a measure of risk.The greater the fraction of output that is financed by debt, the greater the risk of losses." (Minsky and Papadimitriou 2004:163)

Differences in total cost, zero returns and \bar r. The greater the debt, the lower the price deacrese will treat firm's survival -> measure of risk. (note on p.163)

"We now have cost curves which take into account financing conditions. The financing constraint may be looked upon as one possible explanation for the finite size of firms where the production function does not exhibit decreasing returns to scale." (Minsky and Papadimitriou 2004:163)

[RESUL] All this discussion explains why firms have finit plant size evean though presents decreasing returns to scale. (note on p.163)

"Therefore, the long run marginal cost curve for the large firm will lie below the long run marginal cost curve for the small firm, adjusted for the scale of owners' equity" (Minsky and Papadimitriou 2004:163)

Large firms have for acces to credit compared to the smaller ones (note on p.163)

"he money market operates so that each firm is confronted with a 'monopsonistic'supply curve of at least one factor of production - finance." (Minsky and Papadimitriou 2004:164)

"This subjective evaluation of balance sheet structure is a particular version of 'The Principle of Increasing Risk' associated with Kalecki.19 Let us assume that a particular output with a given size of plant can be financed by owners'equity. A larger plant can be financed only by resorting to borrowed funds. The cost curves as drawn earlier took into account the objective costs associated with the best method available to the firm of financing various outputs. In addition to this objective cost of debt financing,each dilution of equity which takes place as increasing proportions of the output are financed by debt instruments involves an increasing risk to the entrepreneur that he may lose his own investment,that he may lose his valuable organization." (Minsky and Papadimitriou 2004:164)

Similarities with Kalecki's Principle of Increasing Risk (note on p.164)

"The difference between the minimum price which a firm can stand and still survive with or without borrowing is a measure of the risk that the borrower carries" (Minsky and Papadimitriou 2004:165)

"Therefore, the planning long run average cost curve which allows for risk involves, for each balance sheet which has debt in it, a return greater than zero, and this return greater than zero increases with the deterioration of the firm's balance sheet." (Minsky and Papadimitriou 2004:166)

"For each output greater than q1, which can be financed internally, the firm in planning considers a larger return than ron owners'equity as compensation for the additional risk it carries by borrowing. A new long run average cost curve therefore can be drawn to replace the rreturn on owners' equity curve as the planning curve:this curve yields an increasing return on owners'equity as debt financing increases." (Minsky and Papadimitriou 2004:166)

\bar r also increases as a result of increasing risk involved. (note on p.166)

"In this case,no matter how much the demand for the product of the firm increases, the firm will not increase its borrowings, and therefore, no investment by the firm will result from a rise in demand." (Minsky and Papadimitriou 2004:167)

There is some point which after it no investment will be determined by the increase for its products. (note on p.167)

"In such a situation, a necessary prerequisite for the accelerator to operate for the firm is that the equity interest increase. The risk factor implicit in financing investment by borrowing can act to break an accelerator expansion." (Minsky and Papadimitriou 2004:167)

[IMPORT] So, the risk related to finance cn break the accelerator expansion (note on p.167)

"As a result of the rise in interest rates, the gap between the survival price and the market price is reduced.The marginal cost of the output is now greater than the price of the output. The firm has too great a debt load for its expected earnings and the entrepreneur can:" (Minsky and Papadimitriou 2004:167)

[EFFEC] Interest rate increase. (note on p.167)

"1. 2. reduce the scale of operations (and, in time, the scale of its plant), thereby decreasing the firm's debt load. This will lower the required difference between the market price and the survival price; increase the equity base, which also lowers the survival average cost curve, and also decreases the required difference between the market price and the survival price." (Minsky and Papadimitriou 2004:167)

Firms' alternative to an increase in interest rate (note on p.167)

"his determines the minimum price of the product consistent with the survival of the firm." (Minsky and Papadimitriou 2004:168)

[IDEIA] This financial mechanism could be include in the mark-up prices and are related to balance sheet structure (note on p.168)

"n entrepreneur, whenever the price of its product is greater than the price which yields zero return on its own investment,may use this income to: (a) pay dividends; (b) increase his equity base and use this larger equity base to finance plant expansion; (c) increase his equity base and use the retained earnings to repay debt. What combination of (a), (b), or (c) the entrepreneur uses depends" (Minsky and Papadimitriou 2004:168)

What to do with superfluous assets. If there is optimism, expand plant (note on p.168)

"The use of retained earnings as a basis for plant expansion means that the savings which are taking place are being used as an equity base. If the ratio of borrowings to equity is , an expansion of investment by (1 ) savings is possible without a deterioration in the ratio between equity and debt financed capital. If a firm uses retained earnings to pay off debt, then, for the firm, the ratio of equity to debt increases. The savings of the firm have been channeled into 'institutions' which own debt. If the institutions which finance investment by owning equities and which finance investment by owning debt are strictly compartmented, then the retained earnings of the firm have increased the debt financing ability of the economy. If lenders look at the ratio of equity to debt in the balance sheet of firms as the standard to be used in their lending activities, such growth in debt financing ability, unless there is an increase in equity financing from some other source, would imply that a deterioration of the ratio of equity to debt financing for other firms is necessary if the earnings of the firms that expand equity to reduce debt are to be transformed into investment demand." (Minsky and Papadimitriou 2004:169)

Similar to loanable funds (note on p.169)

"We can assume that the difference between the survival (zero return) price and the expected price is a measure of the firm's risk of failure.A firm may protect itself against this risk by setting a minimum difference between the survival price and the 'expected'price of the product.This is equivalent to moving to higher internal rates on owned capital as the ratio of debt financed to equity financed capital increases. The resultant average cost curve yields a long run marginal cost curve which rises more rapidly than LRMCias debt increases." (Minsky and Papadimitriou 2004:171)

[IDEA] Firms adjust how to distribute profits and not the price. (note on p.171)

"The effect of the risk element therefore is to decrease the size of the optimum plant as compared to the optimum plant in a riskless world,and also,by increasing the slope of the planning curve,to decrease the amount of investment induced by a given rise in demand." (Minsky and Papadimitriou 2004:174)

Minsky suggests reduce Y* in the presence of financial risk (note on p.174)

"The marginal cost curve is the derivative of the total cost curve independent of financing plus the derivative of the financing charges." (Minsky and Papadimitriou 2004:175)

** Monetary behavior and induced investment

"The fundamental problem on the supply side of the investment goods market is how resources are made available to the investing unit. This is essentially a savings and a money market phenomenon." (Minsky and Papadimitriou 2004:237)

Lonable funds (note on p.237)

"According to the accelerationist doctrine, excess demand in the consumption goods industries implies a rise in the demand for capital goods. Therefore the first type of structural unemployment is typical of the expansion phase of the business cycle." (Minsky and Papadimitriou 2004:238)

Unemployment and the accelerator (note on p.238)

"Savings are made available to investing units through various financial intermediaries which are inexorably intertwined with the banking (money creating) system.Changes in the money supply or in its velocity of circulation can make resources available to investing units." (Minsky and Papadimitriou 2004:238)

Lonable funds and the disponability of resources to firmas through M or v. (note on p.238)

"The monetary aspects of business cycles are primarily associated with two phenomena: 1. 2. the financing of investment during an expansion;and the survival conditions of firms on the downswing." (Minsky and Papadimitriou 2004:239)

Expansion: More resources to investment
Downsing: deterioriation of survivals conditions (note on p.239)

"Business cycles are both monetary and real phenomena." (Minsky and Papadimitriou 2004:239)

"The inherent stability school, in its primitive form, takes the guise of a harvest, weather, or even of a war cycle.The more sophisticated writers of this school have emphasized monetary instability.Their position is that the economy is inherently stable and that the perverse behavior of the monetary system is the fundamental cause of observed cycles." (Minsky and Papadimitriou 2004:239)

Monetary business school (note on p.239)

"Among the 'real' school of business cycle theorists are the accelerationists." (Minsky and Papadimitriou 2004:239)

Real school: accelerationists (note on p.239)

"The natural view of the role of money for accelerator business cycle theories is that the monetary system makes possible the 'accelerator created' demand for investment goods." (Minsky and Papadimitriou 2004:241)

Credit allows the accelerator mechanism to occur (note on p.241)

"n our analysis we divide previous receipts into consumption and ex-ante savings. The other four of Schumpeter's list of financing sources can be classified as either changes in velocity or changes in the money supply." (Minsky and Papadimitriou 2004:242)

"To Schumpeter's original view of the monetary process we have to add a specific consideration of the liquidity phenomenon. The rise in liquidity preference that Hicks relies upon for the rapidity of the downturn has a" (Minsky and Papadimitriou 2004:242)

"counterpart in the expansion phase - liquidity preference falls. This entails (1) that business firms are willing to go into debt - to see their balance sheet deteriorate, and (2) that owners of liquidity are willing to become illiquid - to spend (or invest) their liquidity. These monetary phenomena are essential permissive elements for an accelerator expansion." (Minsky and Papadimitriou 2004:243)

"; is the investment in excess of savings financed? Typically the accelerator theorists ignore this problem. Similarly, the effects of savings in excess of investment on the downswing are ignored." (Minsky and Papadimitriou 2004:243)

Minsky discussion is based on these questions. (note on p.243)

"If at induced investment can be realized. The price level does not change.Yt2) is financed,then ptwill be greater than pt1.There does not exist any guarantee that of investment can be affected without repercussions upon the ceterus paribusassumptions implicit in the value of ." (Minsky and Papadimitriou 2004:244)

"rces may affect the ceterus paribus supply' phenomena are dealt with in the second part of this chapter." (Minsky and Papadimitriou 2004:244)

"The excess of demand over supply at the price results in a rise in financing rates and terms." (Minsky and Papadimitriou 2004:245)

I ant > S ant -> increase in interet rate (note on p.245)

"such an upward shift reduces the scale of the optimum plant and thereby lowers investment to that level at which realized I is equal to ex-ante S." (Minsky and Papadimitriou 2004:245)

... and decrease investment so I ant = S ant (note on p.245)

"A necessary condition for the accelerator process to function is that there exists a source of financing of investment in addition to ex-ante savings." (Minsky and Papadimitriou 2004:245)

"S(Yt-1)" (Minsky and Papadimitriou 2004:245)

[Prolem] Investment increases income which also increases savings

... Ok, Minsky states that this is the case if there is any resources other than ex ante savings to finance investment (note on p.245)

"Investment is therefore susceptible to inducement by the operations of the financial markets. Changes in the period over which an investment stimulus operates may transform an 'explosive'movement into a 'damped'movement of income." (Minsky and Papadimitriou 2004:246)

"The adjustment in realized savings depends upon changes in income; the adjustment of realized investment depends upon changes in planning curves." (Minsky and Papadimitriou 2004:246)

"Ex-ante savings can be utilized in two ways: one is to finance investment; the other is for monetary changes. When realized investment is greater than ex-ante savings, the monetary changes are inflationary; when ex-ante savings are greater than realized investment,the monetary changes are deflationary." (Minsky and Papadimitriou 2004:246)

"The accelerator gives us the demand for financing.We combine the supply of savings with the monetary changes into a 'supply of financing'schedule. The supply and demand schedules for financing determine realized investment and the interest rate. Realized investment is the essential varying element in an accelerator business cycle model." (Minsky and Papadimitriou 2004:247)

"When economic units save,they can finance investment either directly or through financial intermediaries by acquiring either equities or debt assets. If the money supply is increasing, the increased money supply can only finance investment by means of an increase in debt.21If velocity is increasing (or liquidity decreasing) the investment that results from the utilization or economizing of cash balances by non-firms may result in either a rise in debt financing or a rise in equity financing." (Minsky and Papadimitriou 2004:247)

"These monetary phenomena are not the cause of the business cycle. Depending upon the nature of the monetary system, the monetary phenomena associated with the business cycle are but the image of the savings and investment phenomena. However, the way in which the monetary system reacts to the changes in savings and investment relations is an important determinant of the realized cyclical pattern." (Minsky and Papadimitriou 2004:248)

"Case 2a, where the money supply is infinitely elastic, is a world of a paper money authority which ignores price level considerations, or a world in which a central bank follows a 'needs of business' rule." (Minsky and Papadimitriou 2004:249)

Seems to be the more relevant one (note on p.249)

"the inducement to invest is there and the bank's behavior is necessary to realize the induced investment" (Minsky and Papadimitriou 2004:249)

This rationale seems adequate (note on p.249)

"A useful construction is to assert that for each level of money income Y, there exists a minimum quantity of money MTwhich is necessary to sustain the volume of payments associated with Y." (Minsky and Papadimitriou 2004:250)

"T Lortfolio money to finance investment increases actual V. If the quantity of money is constant, ML, portfolio money must fall when actual Vrises" (Minsky and Papadimitriou 2004:250)

"en actual Vrises. interest rate is determined by the demand curve for investment; ex-ante savings and the terms upon which holders of liquidity are willing to substitute earning assets for money and money for earning assets.If ,then the interest rate is determined by the demand for investment,the supply of savings and the terms upon which individuals are willing to increase their holdings of portfolio cash." (Minsky and Papadimitriou 2004:250)

"If we assume a constant money supply, then realized investment can differ from ex-ante savings only if there is a change in the velocity of circulation of money." (Minsky and Papadimitriou 2004:251)

"The utilization of money which had been held as an asset for the purchase of an investment good is the way in which the rise in income is affected. For this to happen,the rise in the demand curves for the product must result in making the giving up of the virtues of liquidity desirable." (Minsky and Papadimitriou 2004:251)

There is some similarities with Keynes (Ch 17) in a QMT framework based on money velocity changes. (note on p.251)

"The market rate of interest rises as money is withdrawn from the asset fold to finance investment in excess of savings. The effective planning curves of firms which are financing their expansion by debt rises, and the amount of investment induced by a given shift in demand, are reduced." (Minsky and Papadimitriou 2004:251)

"The decrease in liquidity raises the survival limits of firms. This in turn raises the effective planning rate of firms more than the rise in interest rates alone indicates. This acts to decrease the amount of investment induced by a given upward shift in aggregate demand." (Minsky and Papadimitriou 2004:251)

"1her interest rates, cash assets would be used to 1nt; at lower interest rates savings will be absorbed by cash balances. The amount of financing available at any interest rate is equal to the sum of ex-ante savings and the change in cash balances." (Minsky and Papadimitriou 2004:252)

"vest)" (Minsky and Papadimitriou 2004:253)

Interest rate determines investment (note on p.253)

"This will mean that the business cycle will be characterized by weaker booms than alternative monetary systems would provide. Such a monetary system will be associated with a tendency toward relatively stable income; the accelerator being damped down, the investment booms will" (Minsky and Papadimitriou 2004:254)

2021/04/14 - 17h43 (note on p.255)

Since quantity of money is an endogenous variable, this section may not be useful. (note on p.255)

"Assume that commercial banks create money by lending to business firms. The increase in the money supply is equal to the difference between induced investment and ex-ante savings: MI ex-anteS ex-anteY" (Minsky and Papadimitriou 2004:255)

"During an expansion, the increase in the money supply takes place through investing business firms adding bank debt to their liabilities. Assuming that the percentage distribution of ex-ante savings between debt and equities is constant, a cumulative explosive expansion on the basis of the creation of money will result in a fall in the ratio of equity to debt in the balance sheet of firms." (Minsky and Papadimitriou 2004:256)

Since M increases without limits during expansion, there would be a cumulative explosive expansion in which equity/debt will fall. (note on p.256)

"This will raise the effective planning curves of firms which will lower the amount of investment induced by a given rise in income." (Minsky and Papadimitriou 2004:256)

As a consequence, borrowers' risk will rise and will reduce the investment induced by the rise of income.

NOTE: is borrowers' risk and not lenders' (note on p.256)

"The smaller rate of increase of income decreases induced investment. With a fall in income,the excess of ex-ante savings over induced investment will be utilized to reduce debt.Also,the failure of firms whose survival limit has risen during the expansion will result in the substitution of equity for debt in balance sheets. Both changes during the downswing raise the ratio of equity to debt in firms' balance sheets,32 which in turn lowers their effective planning curves. This acts as a stabilizer on the downswing." (Minsky and Papadimitriou 2004:256)

The stabilizer during a downturn -> Equity/debt ration increase -> decrease effective planning curves. (note on p.256)

"However, this requires an increasing rate of change in the price level" (Minsky and Papadimitriou 2004:257)

A "politicaly" viable inflation could prevent any deteriorarion in balance sheets. (note on p.257)

"Assume a constant arithmetical increase in the money investment is realized.d: . Then the total amount of financing available assuming no excess liquidity in the community is . Only if is the monetary constraint effective, and in this case realized investment is (1 )Yt1 ." (Minsky and Papadimitriou 2004:257)

The case with finit money supply. (note on p.257)

"Therefore, for t+1, induced investment is If (1 ) implies that then realized investment is constrained by the financing ability of the community and income increases at the geometric rate (1 )." (Minsky and Papadimitriou 2004:258)

This rationale could give some insight about how to specify the model. (note on p.258)

"The second point is that the rate of growth of income is not determined by the properties of the accelerator process but by the properties of the monetary system." (Minsky and Papadimitriou 2004:258)

In this case, growth is money-restricted. (note on p.258)

"The monetary system may be such that the quantity of money has a ceiling.Given an explosive upward movement of income,the money supply will expand, permitting the financing of investment in excess of income. When the monetary ceiling is reached, investment will fall to the quantity that can be financed by savings. This will stabilize income; therefore the next period's induced investment will be zero.Such a monetary system will result in a sharp break in the level of income." (Minsky and Papadimitriou 2004:259)

This summirizes the argument: accelerator can proceed until reach the monetary ceiling. After that, induced investment is limited to savings availability. (note on p.259)

"If velocity is greater than 1, and if an excess of investment over ex-ante savings is financed by an increase in the quantity of money, then excess liquidity results. This excess liquidity can be utilized to finance investment." (Minsky and Papadimitriou 2004:260)

Excess liqudity finance investment (note on p.260)

"We therefore have that: BankDebt [YtYt1]V 1 YtYt1 . TotalAssets YtYt1 V YtYt" (Minsky and Papadimitriou 2004:260)

What exceed transacion cash/induced investment (note on p.260)

"If the distribution of the public's investments in business firms is unchanged as between debt and equity assets,during an expansion the balance sheets of business firms will deteriorate." (Minsky and Papadimitriou 2004:261)

As a consequence, balance sheets deteriorate during expansion. (note on p.261)

"Therefore, the possibility that the deterioration of firms'balance sheets will reduce the efficacy of a rise in income to induce investment will be lower." (Minsky and Papadimitriou 2004:261)

However, the turning points will be less abrupt compared with V = 1 case. (note on p.261)

"Also as bank debt of firms is generally shorter term than firms' debt to the public, a change in these parameters will affect the dating of business firm liabilities. This can operate so as to affect the survival constraint of firms." (Minsky and Papadimitriou 2004:261)

[FINDS] Since terms of equities are longer than bank credit, these changes will deteriorate the balance sheets. (note on p.261)

"will be that hitting the ceiling in the money supply will be a downturn in income. However, the possibility exists that velocity changes will counteract the effect of the ceiling in the money supply." (Minsky and Papadimitriou 2004:261)

The dynamics is similar to V = 1 case. If hit the money celing, there would be a downturn in income. (note on p.261)

"planning curves" (Minsky and Papadimitriou 2004:261)

TODO - Check what means planning curves (note on p.261)

"risk elements.Therefore,an explosive 2or process may be broken by such changes in liquidity preference." (Minsky and Papadimitriou 2004:262)

Risk elements and liqudity preferences may broke the accelerator. (note on p.262)

"Productive capacity of period t can differ from that of period due to the following factors: 1. 2. 3. any change in production technique; any change in population; the investment that took place in period and prior periods which is first available for productive use in period t." (Minsky and Papadimitriou 2004:264)

Changes in productive capacity (note on p.264)
