#+TITLE:  (2010, ): O conflito distributivo e a teoria da inflac\~ao inercial
#+OPTIONS: toc:nil num:nil
#+ROAM_KEY: cite:
Time-stamp: 2021-02-18
- tags ::

* Backlinks

* FISH-5SS
|---------------------------------------------+-----|
| <40>                                          |<50> |
| *Background*                                  |     |
| *Supporting Ideas*                            |     |
| *Purpose*                                     |     |
| *Originality/value (Contribution)*            |     |
| *Relevance*                                   |     |
| *Design/methodology/approach*                 |     |
| *Results*                                     |     |
| *(Interesting) Findings*                      |     |
| *Research limitations/implications (Critics)* |     |
| *Uncategorized stuff*                         |     |
| *5SS*                                         |     |
|---------------------------------------------+-----|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: serrano_2010_conflito
 :AUTHOR: Serrano, F.
 :JOURNAL: Revista de Economia Contempor\^anea
 :YEAR: 2010
 :DOI:  http://dx.doi.org/10.1590/S1415-98482010000200007
 :URL: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1415-98482010000200007&lng=pt&tlng=pt
 :END:

* Extracted Annotations (18/02/2021 12:18:06)
:PROPERTIES:
:NOTER_DOCUMENT: ../PDFs/Serrano - 2010 - O conflito distributivo e a teoria da inflação ine.pdf
:NOTER_PAGE: 3
 :END:

"cos, no caso iguais ao custo salarial unitário do período anterior, dado pela razão entre o salário nominal (W-1) e o produto por trabalhador (B-1). A outra é em termos de uma margem bruta real de lucros m sobre os custos de reposição do período atual (W/B). Assim, teríamos: P = (1 + n) (W-1/B-1) ou P = (1 + m) (W/B)" (Serrano 2010:397)

Duas formas de escrever os custos de produção: markup nominal e real (note on p.397)




"Primeiro, em termos de custo histórico e margem nominal. Nesse caso, a taxa de infl ação corrente é dada pela taxa de crescimento dos custos defasada de um período e pela variação do nível da margem de lucro nominal" (Serrano 2010:397)

Duas formas de escrever inflação (note on p.397)




"Nesse caso, para uma dada margem de lucro nominal n, a infl ação do período corrente vai ser a taxa de crescimento dos custos do trabalho do período anterior. Isso tem a importante consequência distributiva de que se a taxa de crescimento dos salários nominais w aumenta (diminui), a margem real de lucro real m vai cair (aumentar). Portanto, o valor do salário real não vai ser afetado pelo crescimento dos salários nominais, mas será uma função positiva de sua aceleração. Assim, aumentos da taxa de crescimento (aceleração) dos salários nominais aumentam a infl ação com uma defasagem. Mas, exatamente porque existe uma defasagem, tais aumentos mudam a distribuição de renda." (Serrano 2010:398)

Em um modelo com taxa nominal de lucro dada, a inflação causará efeitos distributivos por conta da existência de uma defasagem de ajuste. (note on p.398)




"Note que isso é muito diferente do que acontece quando supomos que é a margem de lucro real m que é dada exogenamente. Neste último caso, temos que o markup nominal sempre se ajusta plenamente a qualquer aceleração do crescimento dos salários nominais ((n - n-1) - (w - w-1) = 0). Com efeito, a taxa de infl ação é sempre igual à taxa corrente de crescimento dos salários, sem nenhuma defasagem: p = w" (Serrano 2010:398)

Mesmo exemolo, mas com taxa real dada -> taxa nominal se ajusta. (note on p.398)




"É interessante notar como os resultados desse caso intermediário de ajuste parcial da margem nominal, em termos qualitativos, se parece mais com o caso do markup nominal fi xo. Aumentos na taxa de crescimento dos salários nominais vão aumentar o salário real, já que: w - p = (1 - x)(w - w-1) (11) Os ganhos reais serão erodidos, mas não eliminados (para x < 1), pelo aumento (parcial) do markup nominal." (Serrano 2010:399)

No caso intermediário, com reajuste parcial, os resultados são mais próximos do modelo com taxa de lucro nominal fixa: existirá variação dos salários reais. (note on p.399)




"Como veremos adiante, uma das duas hipóteses fundamentais da teoria da infl ação inercial é a de que o markup real é sempre fi xo (x = 1)" (Serrano 2010:399)

Uma das hipóteses do modelo de inflação inercial: markup real fixo. (note on p.399)




"Uma parte tem a ver com o fato de que os trabalhadores desejam por algum motivo aumentos do seu salário real (que tanto pode ser para repor perdas no passado ou captar ganhos de produtividade para ampliar seu poder aquisitivo)." (Serrano 2010:399)

Determinantes do aumento do salário real: desejo de aumento dos salários reais (note on p.399)




"trabalhadores esperam e sabem que haverá alguma infl ação durante o período de vigência do contrato de trabalho." (Serrano 2010:400)

Determinantes do aumento do salário real: expectativa que haverá inflação ao longo da vigência do contrato (note on p.400)




"Além disso, é evidente que a infl ação passada será pelo menos um dos determinantes da infl ação esperada, mesmo na ausência de esquemas formais de indexação salarial. É claro que, havendo indexação formal à infl ação passada, a importância desta para a taxa de crescimento dos salários nominais será maior e possivelmente poderá cobrir toda a parte de infl ação esperada do crescimento dos salários nominais." (Serrano 2010:400)

Inflação passada é um dos determinates da inflação esperada. Na existência de indexação, este componente é mais importante. (note on p.400)




"Portanto, no caso mais geral, a taxa efetiva de crescimento do salário nominal pode sempre ser escrita como: w = c + ap-1 (12) onde c é o aumento autônomo dos salários nominais negociados e a mostra o quanto os aumentos de salários nominais seguem automaticamente a infl ação passada por conta da indexação formal dos contratos ou das expectativas dos trabalhadores." (Serrano 2010:400)

Equação dos salários nominais: w = c + ap(-1) (note on p.400)




"Essa formulação geral nos permite seguir a sugestão de Sraffa de dividir os salários em dois componentes: o "elemento sempre presente de subsistência", que mais ou menos automaticamente leva a algum crescimento dos salários nominais quando os preços dos bens-salários aumentam, e o outro componente dos salários, resultante da barganha entre trabalhadores e capitalistas, em que os trabalhadores tentam disputar uma parte do excedente da economia.5" (Serrano 2010:401)

Dois componentes sugeridos por Sraffa: subsistência e disputa por parte do excedente da economia (note on p.401)




"a taxa de infl ação em todos os três modelos (o de margem real fi xa, o de margem nominal fi xa, e o de ajustamento parcial da margem nominal) vai sempre tender a: p = c / (1 - a) (13) A grande diferença entre os modelos será o que acontece quando há uma mudança permanente, por exemplo, um aumento em c ou a" (Serrano 2010:401)

Equação geral da taxa de inflção de acordo com os três modelos. (note on p.401)




"No caso do markup real fi xo, a infl ação vai aumentar, mas o salário real não será afetado, pois os preços vão seguir o aumento da taxa de crescimento dos salários imediatamente." (Serrano 2010:401)

m fixo: inflação aumenta mas salários reais não. (note on p.401)




"No caso do markup nominal fi xo, a infl ação também vai aumentar, mas haverá um aumento permanente no nível do salário real e uma queda permanente no markup real, já que a infl ação só vai acelerar depois do aumento de custos salariais." (Serrano 2010:401)

n fixo: salários reais e markup real varial; inflação ocorrerá apenas depois que os custos salariais aumentem. (note on p.401)




"Repare que todos os modelos descritos no fi nal tendem, para dados valores dos seus vários parâmetros, a gerar uma taxa de infl ação constante no tempo. No entanto, nenhum deles é um modelo de infl ação inercial propriamente dito, pois a inércia infl acionária é apenas parcial (o parâmetro a < 1). Além disso, um choque heterodoxo neutro que apenas congelasse os preços e eliminasse a indexação salarial (e tornasse a = 0) poderia reduzir bastante, mas não eliminaria completamente, a infl ação de custos (pois c > 0)." (Serrano 2010:401)

Os três modelos geram uma inflação constante e a inflação é parcialmente inercial.

Com congelamento de preços e indexação (a=0), a inflação de custos não é eliminada (c>0). (note on p.401)




"A primeira, que já vimos, é a de que o markup real é fi xado exogenamente (x = 1). A segunda é que os trabalhadores reajustam seus salários pelo pico de salário real atingido no período anterior, isto é, a taxa desejada e obtida de crescimento dos seus salários nominais é igual à taxa de infl ação do período anterior." (Serrano 2010:402)

Hipóteses do modelo de inflação inercial

Markup real é fixo

Ajuste dos salários é pelo pico do salário real anterior.

Em termos do esquema analítico: a =1; c =0 (note on p.402)




"Nessa visão, o confl ito distributivo ativo (c > 0) é visto como usualmente temporário e não causa infl ação e, sim, a aceleração da infl ação: p - p-1 = c" (Serrano 2010:402)

Nessa visão, o conflito distributivo não é a causa da inflação, mas sim o determinante de sua aceleração. (note on p.402)




""componente de realimentação" da infl ação, que vinha da prá- tica de indexação de contratos que repunham periodicamente o pico de seu valor real no início do período anterior." (Serrano 2010:403)

Componente de realimentação da inflação (note on p.403)




"O gradualismo con sistia em políticas de renda (controle de preços e salários), juntamente com o controle da oferta monetária e/ou da demanda agregada nominal, de forma a manter a economia no "pleno emprego". O "tratamento de choque" (ortodoxo) consistia no rígido controle da oferta monetária e/ou da demanda agregada nominal, que, para zerar a infl ação, deveria crescer apenas à taxa de expansão do produto de "pleno emprego"." (Serrano 2010:403)

Gradualismo VS tratamento de choque (note on p.403)




"Note que, ao aceitar a hipótese de inércia parcial, logicamente Simonsen estava implicitamente aceitando uma curva de Phillips positivamente inclinada a longo prazo e a consequente existência de um trade-off de longo prazo entre o nível do produto e emprego, de um lado, e o nível da taxa de infl ação, 12 de outro, pois se a < 1 e na ausência de choques de oferta (c = 0), a infl ação tenderá a ser igual a:13 p = b (Y - Y*)/(1 - a)" (Serrano 2010:404)

Implicitamente, assumia-se uma curva de phillips positivamente inclinada no longo prazo: trade-off entre produto-emprego x taxa de inflação (note on p.404)




"Em primeiro lugar, acreditavam que a política salarial imposta pelo governo brasileiro depois de 1974 havia passado, na prática, a indexar plenamente os salários pela infl ação passada" (Serrano 2010:404)

Inercialistas - Hipo 1: w = p(-1) (note on p.404)




"os inercialistas argumentaram que a mudança da periodicidade dos reajustes salariais no Brasil de anuais para semestrais em novembro de 1979 teria sido a principal causa da forte aceleração infl acionária entre 1979 e 1980." (Serrano 2010:405)

Principal causa da inflação: mudança da periodicidade dos reajustes - Anuais -> semestrais. (note on p.405)




"choques de demanda tinham, por um lado, efeitos muito pequenos e um tanto incertos sobre a variação dos salários nominais e, por outro, efeitos menores ainda e bem mais duvidosos sobre as margens reais de lucro (logo, b era visto como muito pequeno ou nulo" (Serrano 2010:405)

Os efeitos dos choques de demanda eram pequenos (note on p.405)




"markup real, embora fosse sempre visto como exógeno em relação à evolução dos salários nominais e da infl ação,20 era sempre determinado por alguma variante da teoria da distribuição de Cambridge, em que a margem de lucro era função crescente da taxa de acumulação desejada pelos capitalistas, dadas as propensões marginais a poupar das classes sociais. Isso deveria implicar margens de lucro certamente pró-cíclicas, mesmo que se pensasse em um ajustamento relativamente longo em relação ao markup de equilíbrio de "médio prazo" (era esperado, assim, um coefi - ciente b positivo, porém não muito grande).2" (Serrano 2010:405)

Markup real de acordo com a teoria da distribuição de Cambridge: Margens de lucro são pró-ciclicas (função da taxa de acumulação) (note on p.405)




"Somente com polí- ticas de rendas (controles de preços e salários) seria possível um combate racional à infl ação" (Serrano 2010:405)

Solução de acordo com os inercialistas: políticas de renda (note on p.405)




"Todavia, uma vez passado o choque (c voltava a ser zero), a infl ação se estabilizava aproximadamente em um novo patamar mais alto." (Serrano 2010:406)

Persistência da inflação em um patamar elevado. (note on p.406)




"Ao fi nal, o Plano Cruzado consistia: no congelamento de preços com conversão salarial pela média, proposto por Francisco Lopes (1984b); no uso da "tablita" de conversão de contratos fi nanceiros usada na Argentina e proposta aqui por Modiano (1986); e no uso da escala móvel proposta por Paulo Renato de Souza (1984), da Unicamp" (Serrano 2010:406)

Componentes do plano cruzado:

Conversão pela média;
Tablita (contratos financeiros)
Escala móvel (gatilho): sem que a inflação chegasse a um patamar de x% (20 no cruzado), propunha-se reajuste salarial. (note on p.406)




"A primeira é explicar por que os trabalhadores pedem aumentos em seus salários nominais no modelo básico da infl ação inercial (a = 1, x = 1)" (Serrano 2010:407)

Problema 1: por que os trabalhadores pedem reajustes salariais se os salários reais não mudam?

Não há, na prática, conflito distributivo (note on p.407)




"No modelo básico de infl ação inercial, toda vez que há um choque de oferta adverso, a infl ação acelera e o salário real médio cai. Só que é importante lembrar que, nesse caso, o salário real cai exatamente pelo mesmo montante que cairia se os salários nominais estivessem constantes, ou até sendo reduzidos." (Serrano 2010:407)

Choques de oferta possuem efeitos negativos sobre a inflação enquanto o salário real médio cai. (note on p.407)




"Uma maneira de contornar o primeiro problema mencionado é incluir mais algum grupo de agentes no modelo, já que somente entre fi rmas e trabalhadores a teoria fi ca sem sentido. Para tanto, basta supor, por exemplo, que existam diferentes grupos de trabalhadores na economia" (Serrano 2010:407)

Solução: inclusão de grupos de trabalhadores (note on p.407)




"Outra extensão do modelo de markup real fi xo supõe que existam outros tipos de custo, como, por exemplo, um insumo importado (como em Lopes e Modiano e (1983))." (Serrano 2010:408)

Solução 2: inclusão de insumo importado (note on p.408)




"Note que as extensões resolvem a primeira difi culdade apontada anteriormente de explicar por que os trabalhadores se importariam com reajustes em seus salários nominais. Mas a segunda difi culdade da teoria da infl a- ção inercial mencionada não é sobrepujada por essas extensões do modelo inercialista básico: por que aumentar os salários nominais de acordo com a infl ação passada?" (Serrano 2010:408)

Estas extensões só resolvem o primeiro problema (note on p.408)




"O argumento não diz por que qualquer grupo pediria reajuste pela infl ação passada. Aqui, como quase sempre na teoria dos jogos, difícil não é achar um equilíbrio de Nash, difícil é achar um só." (Serrano 2010:409)

Problema 2: porque o reajuste seria pela inflação passada? (note on p.409)




"O único motivo para que o reajuste pela infl ação passada seja adotado pelos outros grupos seria que algum outro grupo já o tenha adotado" (Serrano 2010:409)

Só faz sentido pedirem inflação passada se outro grupo já pediu inflação passada (note on p.409)




"Nesse caso, como vimos, qualquer aumento da taxa de variação dos salários nominais, embora acabe por aumentar posteriormente a infl ação no mesmo montante, aumenta também, ao menos em parte, o salário real médio e reduz a margem de lucro real, por conta da defasagem no repasse dos aumentos de custos aos preços. Isso explica facilmente por que é do interesse dos trabalhadores obter aumentos dos salários nominais, e resolve o primeiro problema apontado" (Serrano 2010:409)

Solução do primeiro problema de acrodo com Serrano: margens nominais não são reajustadas integralmente; defasagens tornam a inflação não-neutra em termos distributivos e explica o porquê de se requerer reaustes (problema 1) (note on p.409)




"trabalhadores não tenham como atuar diretamente sobre as margens nominais de lucro das fi rmas, faz com que haja grande e compreensível resistência de parte dos trabalhadores a qualquer redução do crescimento dos seus reajustes nominais,29 tornando crônica (e assim "inercial") a taxa de infl ação." (Serrano 2010:410)

Assimetria e o porquê da inflação ser inercial: trabalhadores só abririam mais de reajustes se as taxas de lucro nominal cairem no mesmo montante, mas sobre isso não conseguem atuar. (note on p.410)




"Alguns autores kaleckianos ou neomarxistas argumentam que o que chamamos aqui de x depende do poder de barganha das empresas, que seria mais forte em estruturas de mercado mais concentradas e/ou quando o grau de utilização da capacidade é particularmente elevado (veja, nesse sentido, Rowthorn, (1977)." (Serrano 2010:410)

Explicação da inflação a kaleckiana: x depende da estrutura de mercado (note on p.410)




"markup real desejado m* seria determinado pelo grau de concorrência e pelas estruturas de mercado, mas o markup nominal dependeria, também, da expectativa das empresas sobre o aumento de custos c e." (Serrano 2010:410)

Frenkel: markup real depende da estrutura de mercado enquanto o nominal depende das expectativas (note on p.410)




"o que nos mostra que a distribuição vai mudar a favor das fi rmas se elas superestimarem a taxa de crescimento dos salários nominais, e em favor dos trabalhadores se as empresas subestimarem o crescimento dos salários nominais." (Serrano 2010:410)

Se as empresas superestimarem os aumentos salarias, a inflação vai favorecer as empresas em termos distributivos. (note on p.410)




"A decisão posterior de Lopes, de propor um congelamento de preços sem redução de margens nominais, tanto na proposta do choque heterodoxo (Lopes, 1984b) quanto na implantação do Plano Cruzado, como se as margens reais fossem exógenas, aparentemente foi justifi cada pela ideia de que seria mais fácil para o governo (e para a população, que se tornaria por uns meses "fi scais do Sarney") fi scalizar um congelamento geral dos preços do que controlar margens reais de lucro." (Serrano 2010:411)

O porquê do congelamento proposto por Lopes: mais fácil congelar do que controlar margens reais de lucro (note on p.411)




"Formalmente, a "URVização" signifi caria que a taxa esperada de variação de custos w e na equação (19) é determinda pela infl ação passada mensal, como medida pela URV." (Serrano 2010:412)

Como a URV pode ser incluída nesse esquema analítico (note on p.412)




"argumentam que a concorrência vai garantir que o piso para as margens nominais de lucro seja dado pelas taxas nominais de juros (i). Os juros são tanto um custo fi nanceiro (para empresas endividadas) quanto um custo de oportunidade do capital (para todas as fi rmas)." (Serrano 2010:412)

Determinação das margens nominais de acordo com Pivetti (note on p.412)




"Nessa visão, a barganha por aumentos de salários nominais não é, em geral, fútil, mas o quanto os aumentos dos custos são repassados imediatamente aos preços (x) dependerá, a longo prazo, do grau em que a política monetária protege as taxas reais de juros da infl ação. Dessa forma, para a abordagem sraffi ana, a defesa da rentabilidade do capital em geral a partir da indexação da taxa de juros (a "correção monetária") e seu efeito sobre as margens nominais de lucro é um importante elemento da explicação do período de infl ação alta, crônica e "inercial" no Brasil.34" (Serrano 2010:412)

Explicação Sraffiana da inflação Brasileira: Política monetária protegeu a rentabilidade do capital por meio da indexação da taxa de juros (correção monetária) que, por sua vez, determinação as margens nominais e, por consequência, a inflação. (note on p.412)
