#+OPTIONS: num:nil
#+title: Macroeconomia da Demanda Efetiva na abordagem do excedente
#+AUTHOR: Gabriel Petrini
#+DATE: 2º Semestre de 202
#+LANG: pt_Br
#+ROAM_TAGS: "Notas de Aula" "Demanda Efetiva" UFRJ


* Introdução <2020-12-03 qui>
** Apresentação

*Objetivo:* Apresentar os elementos essenciais para a construção de um esquema analítico heterodoxo para a macroeconomia e análise de políticas econômicas em economias com governo e aberta em termos de comércio e fluxos de capital.

O esquema proposto é baseado na retomada da abordagem clássica do excedente, proposta por Sraffa e Garegnani. Nele, o crescimento econômico é liderado pela demanda efetiva através do mecanismo do supermultiplicador, sujeito, a restrição de política econômica, com frequência a de balança de pagamentos.

Já da dinâmica de inflação, cuja tendência é fundamentalmente explicável em termos de "inflação de custos", depende, por sua vez, dos termos de inércia e do conflito distributivo envolvendo salários, câmbio, juros e lucros. Taxas de juros e de câmbio são vistas como variáveis distributivas e não alocativas.

Ao longo do curso, o esquema analítico proposto será comparado e contrastado com outras visões, tanto ortodoxas (Novo Consenso), quanto do pensamento heterodoxo (MMT).

*** Conceitos

- *Longo prazo:* Prazo no qual não é possível ignorar o efeito capacidade do investimento das empresas
  + Problema do investimento não é que é ao mesmo tempo e capacidade produtiva, mas sim que tem essas duas características em momentos diferentes
  + Tempo para que o produto potencial não é dado
** Três grandes princípios teóricos
- Excedente
- Substituição (de fatores)
- Demanda efetiva
**** Excedente VS Substituição de fatores

- Excedente (Economia política clássica e Marx)
  + Remuneração dos proprietários tem limites teconológicos e sociais
  + Concorrência $\Leftrightarrow$ mobilidade de capital
    - Quanto maior a mobilidade, menor a dispersão das taxas de lucro
      + Não estaria errada se a taxa de lucro for heterogênea, mas sim, se a taxa de lucro ter maior dispersão com aumento da mobilidade de capital
- Substituição de fatores (direta e indireta)
  + Neoclássicos ou marginalistas
  + Oferta e demanda de fatores
    - Preferência dos consumidores e donos dos fatores
    - Tecnologia e conjunto de técnicas
    - Dotações
  + Concorrência $\Leftrightarrow$ número de agentes
**** Duas abordagens da distribuição e dos preços relativos 
***** Teorias neoclássicas dos preços e uso dos fatores
- Simétricas (sempre o mesmo mecanismo)
  + Uso do fator e seu preço são determinados *simultaneamente* pelos mecanismos de substituição
- Escassez relativa dos fatores e produtividade marginal
  + Tendência ao pleno emprego de todos os fatores com preço positivo

***** Abordagem do excedente

- Abundância de mão de obra
- Teorias assimétricas
  + Salário de subsistência
  + Complementariedade
- Separação entre remuneração e emprego dos vários "agentes de produção" 
  + Não existe um mecanismo, por exemplo, que estabeleça uma relação entre salário e nível de emprego. Se o salário cair, por exemplo, nada garante que o imprego irá aumentar.
**** Princípio da Demanda Efetiva

- Produção limitada pela demanda efetiva agregada
  + Efetiva no sentido de demanda rentável em termos monetários
  + Poder de compra monetário aos preços que torna a produção lucrativa
  + Não são os fatores de produção
- Investimento determina a poupança (efetiva)
- Taxa de juros *real* como fenômeno estritamente monetário
  + E não se ajusta a uma taxa de juros natural

** Três grandes princípios e sínteses

1. Excente
2. Substituição (de fatores)
3. Demanda Efetiva

- *Síntese Neoclássica:* 2 + 3 $\Rightarrow$ Contradição da economia ser limitada pela demanda e pela oferta
  - Saída via rigidezes de preços e salários
  - Preços relativos expressão escassez relativa somente se parte do suposto do *pleno-emprego*
  - Teoria do produto que não é compatível com pleno-emprego (Demanda Efetiva)
- *Economia do Desenvolvimento:* 1 + 2
  - Saída via escassez dos fatores de produção
- *Projeto Sraffa-Garegnani:* 1 + 3

   

** Três elementos do esquema proposto

1. Demanda efetiva no Longo Prazo
   - Ajustamento da capacidade a tendência da demadna
2. Taxa de juros monetária exógena
   - Variável distributiva
3. Tendência da inflação é de custos
   - Conflito distributivo
Análise do crescimento

*** Demanda Efetiva a Longo Prazo

    #+BEGIN_QUOTE
Toda pessoa sem renda teria uma demanda absoluta por carruagens, mas não tem condições para pagar o quanto é cobrado por esse bem
    #+END_QUOTE
Demanda Efetiva e ajustamento da capacidade a tendência da demanda

- Investimento produtivo privado é induzido pelo nível  e evolução da demanda 
  + Mas continua sendo autônomo em relação ao fluxo circular da renda e curto prazo
  + Empresa só investe um montante que adequa a capacidade à demanda efetiva esperada durante a vida útil do equipamento (é uma demanda derivada)
  + Expectativa de demanda efetiva são revistas a partir da experiência 
    - Princípio do ajuste do estoque de capital, acelerador flexível 
  + Tendência de acumulação e crescimento depende do crescimento dos gastos autônomos que *não* criam capacidade para o setor produtivo privado


- Papel central dos gastos autônomos que não criam capacidade

*Hipótese:* Empresas adquirem capital fixo porque precisam utilizar
- Não há dúvida dessa característica para o capital circulante (dura um único período produtivo)

Essa discussão é importante para contextar a hipótese da austeridade uma vez que reduções na demanda efetiva a curto prazo possuem efeitos sobre o produto potencial no longo prazo.

*** Abordagem da taxa de juros exógena 

- Duas determinações monetarias da taxa de juros
  + Keynes (Teoria Geral) oferta (exógena) e demanda por moeda
    - Juros determinados pelo mercado
  + Sraffa: moeda endógena (crédito)
    - Taxa de juros de curto prazo fixada pela autoridade monetária
    - Taxa longa de juros de longo prazo depende basicamente do "sentido do mercado" sobre a evolução futura fixada pelo Banco Central
    - Bancos não são obrigados a emprestar a todos, mas apenas para quem acham que será rentável
  + *Diferença:* Incerteza e especulação importam
    - Mas são a respeito do comportamento do *Banco Central*
    - Especulam sobre qual será a ação do Banco Central

**** Implicações


- Se o Banco Central tem uma meta para a taxa de juros nominal de curto prazo, compra e vende no mercado secundário *qualquer quantidade* de títulos públicos de curto prazo necessária para estabilziar o interbancário
- Mesmo se a quantidade real de base desejada *diminui* o BaCen sempre que vende os títulos públicos necessários para a taxa de juros se manter
- Protanto, o governo *nunca* quebra e pode sempre se financiar a taxa de juros definida pelo Banco Central
- Nem o Banco Central nem o  Tesouro controlam os prazos dos títulos fora o usado para a política monetária. Também não controlam a composição entre títulos e base na carteira do setor privado. Também não controlam a demanda relativa por títulos pré e pós fixados nem a demanda por títulos indexados e são indexados a preço ou câmbio
- As taxas de juros dos títulos longos seguem a tendência das taxas de juros de curto do Banco Central esperada pelo mercado
- Esta taxa pode ser muito alta se o banco central quiser. Este financiamento *não* implica "monetização" nem em choque de inflação de demanda ou de custos (câmbio)
- *Exceção parcial:* Euro
  
*Resumo:* Mercado não é capaz de forçar o governo a declarar default. Pressão do mercado é insuficiente.

*** Tendência da inflação é de custos, causado por incompatibilidades distributivas

- Nível geral de preços, inflação e aceleração da inflação
  + Persistência: inércia, expectativas, conflitos
    - Teoria estruturalista da inflação supunha uma queda dos salários e que os trabalhadores demandavam uma recomposição de compra e que isso geraria conflito distributivo
      + Caso os trabalhadores aceitassem o salário real, encerraria a inflação
- Inflação de demanda e de custos
  + Inflação de demanda: demanda efetiva maior que o produto potencial
  + Inflação de custos: aumento nominal dos preços de produção
    - Uma expectativa de aumento de inflação no futuro em função de um possível aumento da demanda acima do produto potencial no futuro seria inflação de custo já que tal excesso não ocore no presente e houve aumento nos custos de produção

** Alternativas ao Novo Consenso

*** Novo Consenso

- Produto potencial é dado por fatores de oferta
- Tendência da Inflação é de demanda (NAIRU)
- Regra de Taylor para taxa de juros (Taxa natural de juros)

*** Macroeconomia da Demanda Efetiva

- Produto potencial é afetado pela evolução da demanda (investimento induzido)
- Inflação de custos por meio de conflito distributivo
- Taxa de juros variável institucional e distributiva

* Dois caminhos para a demanda efetiva <2020-12-03 qui> 

** Demanda Efetiva e substituição de Fatores (via marginalismo)

*** Substituição de fatores e tendência ao pleno-emprego

- Muitos métodos alternativos com retornos constantes de escala
  + Resultado de uma dedução teórica e não da validação empírica
- Relação inversa entre preço relativo (real) e uso do fator
  + Tais relações negativas são gerais
    - Depende da hipótese do capital homogêneo
      + Como se não houvesse preço relativo dado que o bem é um só
    - Não é possível postular essa generalidade
- Desemprego de um fator depende apenas do seu próprio preço relativo (rigidez real)
  + Flexibilidade do salário real leva a pleno emprego do trabalho dado o estoque de capital
  + Flexibilidade da taxa de juros de plena utilização da oferta de novo capital (poupança de pleno-emprego) dado o estoque de trabalho

Se fosse uma economia de escambo, não haveria um problema de desequilíbrio de demanda e oferta agregada[fn::Oferta agregada como vontade coletiva de produzir e a demanda agregada como vontade coletiva de comprar produtos]. Em uma economia monetária, há uma separação entre o ato de produzir e de comprar. Como o pleno-emprego seria mantido em uma economia *não*-monetária?

#+BEGIN_EXAMPLE
$\Downarrow C \Rightarrow \Uparrow S^{\star} \Downarrow i \Rightarrow \Uparrow I^{\star}$
#+END_EXAMPLE

- É suposto que o investimento seja bastante sensível à taxa de juros

Resumidamente, a tendência ao pleno-emprego depende tanto da substituição dos fatores quanto a flexibilidade do preço dos fatores. Keynes propõe um crítica em que um dos preços é juros (rígido).

*** Keynes e o equilíbrio abaixo do pleno emprego

- Taxa de juros monetária e assimetria entre mercado de trabalho e mercado de capital novo (ou de produto)
- "Primeiro postulado" no mercado de trabalho
  + Empresas estão sempre na curva de demanda por trabalho e não na oferta de trabalho (?)
    - Salários não são anti-cíclicos
    - *Crítica:* Grau de utilização varia e adoção da hipótese de substuição dos fatores
      + Dada a plena utilização do capital, como ampliar emprego?
- Investimento e "Eficiência Marginal do Capital"
  + Problema associado à taxa de juros decorre da relação inversa, geral e estável entre investimento e taxa de juros
    - Tal relação não se verifica
- Keynes e  a Síntese Neoclássica (rigidez nominal)
  + Keynes não aceitava o efeito Keynes
    - Deflação aumenta a demanda agregada, mas isso não ocorreria: nada garante que o juro nominal siga na mesma direção que a taxa de juros real
    - Salários monetários rígidos são necessários para economia se estabilizar (TG, Ch. 19)
  + Não há nenhum mecanismo monetário que faça que o investimento reaja a um desequilíbrio monetário entre investimento e poupança. Isso porque nunca existe um desequilíbrio *monetário* entre poupança e investimento ao partir do Princípio da Demanda Efetiva
    - Não há porque a taxa de juros se ajustar a movimentos entre investimento e poupança
      + Investimento é parte dos gastos e poupança é parte da renda
  + Teoria dos fundos emprestáveis e teoria clássica da taxa de juros são similares

#+BEGIN_QUOTE
Mantendo todos os demais pressupostos da teoria neoclássica, Keynes mostra que se a taxa de juros sair do valor de pleno-emprego, nada garante que voltará para lá. Isso porque não existe desequilíbrio entre investimento e poupança em termos nominais. Além de que o desemprego é resultado do mercado de produto e não do mercado de trabalho Além de que o desemprego é resultado do mercado de produto e não do mercado de trabalho.
#+END_QUOTE
**** Problemas
- Primeiro postulado no mercado de trabalho
  + Função demanda por trabalho neoclássica
    - *Inclinação:* Mesmo com capital homogêneo o salário real só tem que cair para o emprego aumentar quando o capital disponível esta plenamente utilizado
      + Com Capital ocioso, não há retorno marginais decrescentes
      + Com capital heterogêneo, nada garante que queda geral do salário real leve a escolha de uma técnica que aumente quantidade de trabalho direta e indiretamente necessariamente para produzir uma unidade de produto
        - Crítica do Sraffa pelo lado da demanda
    - *Posição:* Depende do tamanho da dotação de capital que é indeterminada com capital heterogêneo
      + Crítica do Sraffa pelo lado da oferta
- "Terceiro" postulado: função demanda por investimento neoclássica
  + *Inclinação:* Mesmo com capital homogêneo a taxa real de juros só tem a cair para o investimento aumentar quando o trabalho esta plenamente empregado pois com Trabalho ocioso não há retorno marginais decrescentes
    - Mesmo com Capital heterogêneo nada garante que a queda da taxa de juros o salário real leva a escolha de uma técnica que aumente a quantidade (ou valor?) de capital necessário para produzir uma unidade de produto
  + *Posição:* Depende do tamanho da quantidade de trabalho realmente empregada
  + Se juros acima da taxa de juros natural, investimento menor que poupança de pleno emprego. Mantida utilização ... (Ver Slides)
- Kalecki já criticava Keynes
  + Não leva em conta efeito capacidade do investimento
  + Por conta do primeiro postulado e ideia empiricamente incorreta que o salário real é anticíclico
    - Kalecki fugiu do primeiro postulado por meio de concorrência imperfeita
      + Em trabalhos futuros abandonou essa estratégia para justificar a existência de /mark-up/
  + Críticas Sraffianas atribuem tais problemas à visão marginalista de substituição dos fatores

** Demanda Efetiva agregada e Excedente (Quesnay, Marx e Kalecki)

*** Introdução

- *Demanda efetiva setorial:* Produção de cada produto é determinada pela demanda aos preços que incluem um padrão mínimo de rentabilidade (/i.e./ demanda ao preço de produção/limite)
  + Este mínimo fica acima da taxa de juros (custo financeiro e de oportunidade do capital)
  + Empresas com custos inferiores ao da técnica dominante ("socialmente necessária") obtém rendas diferenciais
- *Lei de Say:* No agregado, tudo que é produzido será vendido
  + Poupança determina o inevstimento
  + Não há relaçao inversa entre juros e investimento
    - Há uma correlação positiva (aumento na taxa de juros leva a maior poupança potencial e investimento e também a maior taxa de juros)
  + *Setor:* Demanda $\Rightarrow$ Produto $\Rightarrow$ Capital
  + *Agregado:* Capital $\Rightarrow$ Capacidade $\Rightarrow$ Produto $\Rightarrow$ demanda agregada 
    - Tratamento da decisão de investir e de poupar como sinônimos

*** Marx e Quesnay e a crise de superprodução

- Moeda e possibilidade de crise: "todos são obrigados a vender mas não a comprar"
- As decisões de produzir introduzem poder de compra na economia que no agregado pode no máximo recuperar seus custos (salários).
  + Qualquer nível positivo de atividade requer um gasto autônomo que comprem o excedente
    - Seja investimento ou não
    - "Os capitalistas ganham o que financiam"
    - Autônomo em relação à decisão de produção $\Rightarrow$ injeção de poder de compra monetário
    - Problema é estrutural $\Rightarrow$ superprodução
      + Capitalistas querem reduzir custos (aumentar taxa de mais-valia), mas é necessário ter mais gasto autônomo coletivamente
        - Excedente cada vez maior, mas o gasto autônomo coletivo não aumenta na mesma proporção
      + Contradição entre produção e realização
- *Setor:* Demanda $\Rightarrow$ produto $\Rightarrow$ Capacidade $\Rightarrow$ Capital
- *Agregado:* Capital $\Rightarrow$ Capacidade $=$ produto $\neq$ demanda
  + Nível de produto não determina demanda em uma economia capitalista
  + Gasto autônomo pode ser qualquer nível

Há, portanto, uma teoria do porquê de não valer a Lei de Say, mas não há uma teoria do produto

*** Kalecki e o equilíbrio do produto com subutilização do capital 

#+BEGIN_QUOTE
Se trabalhadores gastam o que ganham, capitalistas ganham o que gastam
#+END_QUOTE


- *Setor:* Demanda $\Rightarrow$ produto $\Rightarrow$ Capacidade $\Rightarrow$ Capital
- *Agregado:* Capital $\Rightarrow$ Capacidade $\neq$ produto $\Leftarrow$ Demanda  
- Caráter dual do investimento: Ciclo e tendência
  + *Agregado:* Capital $\Rightarrow$ Capacidade $\neq$ produto $\Leftarrow$ Consumo + Investimento 
- Crescimento liderado pela demanda (Kalecki, Garegnani) $\Rightarrow$ ajustamento da capacidade à demanda
  + *Setor:* Demanda $\Rightarrow$ produto $\Rightarrow$ Capacidade $\Rightarrow$ Capital
  + *Agregado:* Tendência da Demanda $\Rightarrow$ produto $\Rightarrow$ Capacidade $\Rightarrow$ Capital

*** Encaminhamentos

- Abordagem do Excedente depende menos de fatores psicológicos
  + Exemplo: como explicar crescimento em uma década com base em expectativas?
- Tratar de movimentos estruturais
- Não é somente uma teoria da negação, mas também é propositiva
- Não é preciso supor que existe poder de compra autônomo equivalente ao produto potencial e que decidiu-se não gastá-lo
  + Associação entre produto de pleno-emprego e montante de poder de compra equivalente para comprar esse produto
  + Explicita problema da Demanda Efetiva em uma economia monetária
  + A ordem não é o produto pontencial (físico) $\Rightarrow$ aumento poder de compra (monetário), mas sim o inverso
#+BEGIN_QUOTE
Se só existia $D$ na economia, de onde veio o $D'$? É preciso entender o fluxo circular da renda para compreender o nível agregado e não partir das hipóteses comportamentais. Deixe para a empiria mostrar as hipóteses comportamentais dado esse sistema estrutural. Não é necessário partir da teoria da preferência pela liquidez para se chegar à PDE. PDE não é um problema (/e.g./ teoria da crise), mas sim uma solução.
#+END_QUOTE
 
