#+TITLE: pedrosa_2021_what: To what extent does aggregate leverage determine financial fragility? New insights from an agent-based stock-flow consistent model (2021, )
#+OPTIONS: toc:nil num:nil
#+ROAM_KEY: cite:pedrosa_2021_what
#+ROAM_TAGS: "Reference Update" "High Relevance" Minsky "Good Practices" SFC-ABM "Financial Instability Hypothesis"
Time-stamp: 2021-03-02


* Backlinks

[[file:20210301104540-minskian_theory.org][Minskian theory]]

[[file:20210301105212-investimento_fluxo_de_caixa_e_dinamica_da_alavancagem_regime_minskiano_ou_paradoxo_da_divida.org][Investimento, fluxo de caixa e dinâmica da alavancagem: regime minskiano ou paradoxo da dívida?]]
* FISH-5SS


|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| *Background*                                | K+S family models; Kaleckian profit-equation;[[file:2021-03-01-16-46-18-toporowski_2008_Minsky.org][toporowski_2008_Minsky: Minsky's 'induced investment and business cycles' (2008, Cambridge Journal of Economics)]]  proposal; Steindlian paradox of debt regime.                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| *Supporting Ideas*                            | Peaking-order theory; Elastic labor supply; No empirical support for financial determinants of investment (Why to employ an accelerator-based function); Mark-up depends positively on market-share;                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| *Purpose*                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| *Originality/value (Contribution)*            | Exploration of the monetary implications of Kaleckian profit equation in a AB-SFC model; Proposes both a Financial instability index and a profit-debt concentration index;                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| *Relevance*                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| *Design/methodology/approach*                 | AB-SFC with numerical simulations in which only firm sector is heterogeneous.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| *Results*                                     | Lumpy investment: high investment coexist with low investment; Neither credit rationin nor firm-specific interet ratio alters qualitative results of baseline scenario; Leverage ratio is persistent; *Main:* Aggregate leverage ratio is not an adequate index for systematic financial instability; Who recieves the profits matter: if low-leverage firms recieve, high-leverage have insufficient cash flows to cover the debt servicing -> Speculative -> Ponzi; The first and second leverage ratio quartiles present more variability than the other; Minskian and Steindlian regime coexits; *Main:* Systemic fragility needs to be bottom-up; |
| *(Interesting) Findings*                      | The distribution of total demand among firms depends on relative competitiveness; References for pro-ciclycality of credit; The smaller firms are more pronned to become Ponzi;                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| *Research limitations/implications (Critics)* |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| *Uncategorized stuff*                         | Firms closure is based on peaking-order theory: Firms prioritize internal funds than loans; Entry-exit mechanism is a frequent source of black-holes in ABM model; Why to discart first periods? Agents start as homogeneous units.                                                                                                                                                                                                                                                                                                                                                                                                                |
| *5SS*                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: pedrosa_2021_what
 :AUTHOR: Pedrosa, \'Italo, & Lang, D.
 :JOURNAL:
 :YEAR: 2021
 :DOI:
 :URL:
 :END:
** Questions


- The same amount of firms enters to keep F constant? (note on p.52)
- The greater $xi$ is, more FIH is probable?
  + Reason: more uncertain expenditures and more certain debt? (note on p.53)
- Is possible to adapt equation 17 to the household sector? If so, what are the main differences? If no, why not? (note on p.57)
- Asset price is vanished away? How Minskian is that? (note on p.57)
- Why not G as a function of Y (Eq 20)?
  + Additionaly, is un an observable variable for the government? (note on p.58)
- Why follow the average? Is it reasonable that the incumbent have a better technological element? (note on p.61)

** Equations

*** Evolution of firm's market share


#+BEGIN_latex
\begin{equation}
\label{15}
\theta_{f} = \theta_{f_{-1}}\left(1+v\frac{MS_{-1} - MS_{-2}}{MS_{-2}}\right)
\end{equation}
#+END_latex

*** Particular probability to default

#+BEGIN_latex
\begin{equation}
\label{17}
pr^{D}_{f} = \frac{1}{1 + \exp\left(\phi_{1}\frac{\Pi}{DS} - \phi_{2}\Lambda\right)}
\end{equation}
#+END_latex

- $\Lambda$ Firm leverage
- $DS$ Debt servicing

**** Debt servicing
#+BEGIN_latex
\begin{equation}
\label{p. 14}
DS = (i + 1\lambda)NL
\end{equation}
#+END_latex

*** Divident payout-ratio

#+BEGIN_latex
\begin{equation}
\label{26}
\eta = \frac{\eta_{0}}{1+\exp(\epsilon \frac{DS}{\Pi_{g}})}
\end{equation}
#+END_latex

*** Firm specific bank spread

#+BEGIN_latex
\begin{equation}
\label{31}
\theta_{B} = \mu\frac{DS}{\Pi_{g}}
\end{equation}
#+END_latex

** Derived ideas

- Include peaking-order theory: firms prefer internal funds than loans
- Credit supply depends on expect value of each firm's loan project with a particular probability of default.
  + Employ similar approach to household secor.
- Reissl (2020) propose a firm-specific bank spread. Adapt to household sector
- Further research could include asset prices dynamic and a disaggregated banking sector with creidt constraints and commercial banks more accomodative during booms and less prone to grand during bursts. (note on p.77)
* Extracted Annotations (02/03/2021 10:55:42)

"Several authors extended the FIH to other institutional sectors (e.g. Palley, 1994; Dutt, 2006; Isaac and Kim, 2013; Ryoo, 2016; D'Orazio, 2019, for household debt; Nikolaidi, 2014 and Gimet et al. (2019) for bank-related dynamics). However, in Minsky's view, the investment of non-financial corporations is the main culprit for economic fluctuations, as the aphorism by him quoted in Toporowski (2005) synthetically captures: "investment determines output; finance determines investment" (p. 143)." (Pedrosa and Lang 2021:45)

FIH extended to other institutional sectors, but firms' investment is the main concern of Minky. (note on p.45)

"There are, however, certain implications of Minsky's theory that most interpreters would concur. An important one is the positively-sloped aggregate indebtedness-financial fragility curve (Delli Gatti and Gallegati, 1990; Pedrosa, 2019). This result arises precisely from the limitations of the selffinancing capacity of investment, resulting in a relative increase in debt-financing along with cycles' upswing." (Pedrosa and Lang 2021:45)

One common-groun implication: positively-spoed aggregate indebtedness-financial fragility curve. (note on p.45)

"The incorporation of more micro analysis into the FIH is justified to remedy its known potential weaknesses. As a starting point, in the FIH, financial fragility results from complex interactions between investment, cash flows, and debt" (Pedrosa and Lang 2021:46)

Usually, the microanalysis of FIH potentialyze its weakness. (note on p.46)

"Recently, some authors (Lavoie and Seccareccia, 2001; Toporowski, 2008; Bellofiore et al., 2010, among others) claimed that the FIH failed to incorporate adequately some of those feedbacks and descending implications, putting in jeopardy the validity of its corollaries: (i) the leverage ratio may not increase along with investment; (ii) the aggregate ratio may not be a good proxy of financial fragility, as Minsky himself suggested." (Pedrosa and Lang 2021:46)

FIH fails to include some feedback. (note on p.46)

"As argued by Kalecki (1954), an increase in investment expands profits - in Kaldor's aphorism, capitalists earn what they spend - which invalidates the assumption of given cash flow. Consequently, the aggregate leverage can also be anti-cyclical: an increase in investment, even if debt-financed, can result in higher profits, fostering the accumulation of liquid assets (deposits) and leading to an ex-post decrease in the aggregate leverage. This is the case because the capacity of financing investment with retained profits improves." (Pedrosa and Lang 2021:46)

Minsky assumption is at odds with higher investment -> higher profits. (note on p.46)

"A second issue, raised by Toporowski (2008, 2012) and also related to Steindl (1952) discussions, is that the systemic financial fragility is not independent of the distribution of new liquidity that investment generates. This argument expands on the Kaleckian argument and centres on the role of firms' heterogeneity. The main question it brings is who is getting the additional liquidity brought by the expanding investment. For instance, if the firms with higher growth are capturing sufficient profits, their expansion would not bring further fragility into the system because debt is moving more os less pari passu with financing needs." (Pedrosa and Lang 2021:47)

THe systemic financial fragiliti is not independt of the distribution of new liquidity. In other words, who get additional liquidity matters. (note on p.47)

"The novelty of the paper in this regard is the exploration of the monetary implications of the Kaleckian profit equation in an FIH-AB-SFC model." (Pedrosa and Lang 2021:47)

[CONTR] Exploration of the monetary implications of Kaleckian profit equation in a AB-SFC model. (note on p.47)

"To understand the micro-macro mechanisms underlying the macroeconomic results, we create a synthetic financial fragility index from Minsky's financial fragility scale (hedge, speculative, and Ponzi) and develop an index inspired by Kakwani's (1977) concentration index to measure joint profit-debt distribution. With these indices, we assess the impact of profit and debt joint-distributions (a meso characteristic) on the dynamics of the financial fragility of non-financial firms'." (Pedrosa and Lang 2021:47)

Develop an index to assess the impact of profit and debt on the FIH. (note on p.47)

"At the firm-level, once the internal funding capacity exhausts, higher investment requires higher debt, which entails certain future financial commitments. However, the new productive capacity yields uncertain future cash flows, potentially producing a mismatch between incoming money and the contractual debt servicing." (Pedrosa and Lang 2021:48)

Firms investment is financed by loans if excess internal funding capacity. (note on p.48)

"The model features competition among firms, driven by attempts to increase labour productivity to reduce unit costs (Lee, 2013; Lavoie, 2014), through costly research and development (R&D). R&D is itself divided into trying to imitate competitors and to innovate (discovery of new technologies). The pricing decision follows a mark-up procedure, so firms closer to the technological frontier have lower unit costs, and those farther tend to struggle because they lack cost-competitiveness. In turn, the cost-competitiveness impacts both the market-price competitiveness and the mark-up, with two-fold implications for the profit rates." (Pedrosa and Lang 2021:49)

Fims R&D -> increase labour productivity;
Cost-competitiveness impacts market-price competitiveness and mark-up in both ways. (note on p.49)

"Secondly, the demand for each firm's product depends on the relative prices: those with higher prices tend to lose market share (firms react by lowering their mark-up, squeezing their profit rates if their unit costs are high), while the ones with lower prices tend to gain market share, having room to increase the mark-up (and thus widen the profit rate, if their unit costs are low)." (Pedrosa and Lang 2021:49)

Demand of each firm's product depends on relative prices. (note on p.49)

"Expansionary investment is based on the accelerator principle, which ties capacity growth to the expectation of demand.5" (Pedrosa and Lang 2021:49)

Expansionary investment is based on accelerator principle. (note on p.49)

"spirit of the pecking order theory (e.g. Myers, 1984), firms set the demand for loans preferring internal funds (existing deposits) over debt financing.7 In the model, this happens assuming that firms follow a simple rule of thumb." (Pedrosa and Lang 2021:50)

Peacking order theory: firms prefer internal funds <- rule of thumb. (note on p.50)

"The final dynamic impact of investment decisions on the net debt (debt discounted of the deposit holdings) is undetermined: it may be positive or negative, depending on the balance sheet a firm inherits from the past and on its current profitability." (Pedrosa and Lang 2021:50)

The final dynamic impact of investment -> net debt is undetermined. (note on p.50)

"We assume a closed economy composed of F firms;" (Pedrosa and Lang 2021:50)

[QUEST] Is F fixed?

Closed with no entry or exist of existing firms? (note on p.50)

") a single good" (Pedrosa and Lang 2021:50)

"Investmen as simple as possible, the household epositsmi and Carvalho, 2017; Reissl, 2020, for similar hybrid AB-SFC approaches)." (Pedrosa and Lang 2021:51)

Only firms are heterogeneous. (note on p.51)

"desired level of production" (Pedrosa and Lang 2021:52)

[QUEST] Based on what?

Previous prodution? (note on p.52)

"16. Entry and exit of firms take place." (Pedrosa and Lang 2021:52)

[QUEST] Thus, the same amount of firms enters to keep F constant. (note on p.52)

"The R&D expenditure serves two goals, namely creating new technologies (innovation) and imitating competitors (as detailed below)." (Pedrosa and Lang 2021:53)

R&D: innovation or imitation (note on p.53)

"The division of RD by the firm average productivity yields the number of workers the firms direct to R&D. We assume that firms split the R&D workers between innovation (I N ) and imitation (I M ) efforts." (Pedrosa and Lang 2021:53)

[IDEA] The greater gamma is, more FIH is probable?
Reason: more uncertain expenditures and more certain debt? (note on p.53)

"When a firm succeeds in imitation, it gains access to one competitors' technology (Aim). We also follow Dosi et al. (2010) assumption that firms are more likely to imitate competitors with closer technologies. More specifically, the probability that a firm copies the technology of another is weighted by the distance between one firm's technology to the others'." (Pedrosa and Lang 2021:54)

[PROJ] More detail on innovation\immitation heuristics.

(note on p.54)

"As Ciarli et al. (2019), we assume a completely elastic labour supply. Accordingly, firms are never curbed by labour constraints in either production or R&D plans." (Pedrosa and Lang 2021:54)

[REF] Elasticy labour supply. (note on p.54)

"Nevertheless, there is no consensus in the empirical literature regarding the sensitivity of investment to financial variables. Indeed, the estimated size-effect of such variables on the investment ratio is typically small (Chirinko, 1993; Coad, 2009; Sharpe and Suarez, 2020). In our view, this casts considerable doubt on the use of financial variables as the key determinants of investment. For that reason, the model's specification of investment relies on the dependence on real factors." (Pedrosa and Lang 2021:54)

[REF] No empirical support for financial determinants of investment. Thats why to employ an accelerator-based function. (note on p.54)

"where b is an exogenous parameter reflecting the number of payback periods firms use as a benchmark, c ∗ (Aft−1 ) is the unit cost with each firm's best-known technology, yf j is the payback period estimated for the replacement of the jth machine-tool vintage, and af is a binary variable indicating whether the capital good vintage j is to be replaced or not. afj = 1 if the estimated payback for the particular vintage is less than the benchmark (yfj ≤ b). Conversely, afj = 0 if yfj > b. The total replacement investment of each firm is the sum of all physical capital vintages j that the firm decided to replace following the payback routine. Finally, pe depends on an adaptive process, and it is equal to the lagged price level multiplied by the previous period's general price inflation." (Pedrosa and Lang 2021:55)

Some details on investment replacement mechanism. (note on p.55)

"Regarding real expansion investment (EIf ) (net investment), we follow the acceleration principle as incorporated in canonical neo-Kaleckian models, for its properties have been extensively analysed. The specification we deploy is the one by Amadeo (1986):" (Pedrosa and Lang 2021:55)

Expansion investment follows Amadeo (1986) with autonomous investment and fixed accelerator mechanism. (note on p.55)

"Since the unit labour cost is not under the strict control of firms - for it dynamically depends on uncertain outcomes of R&D activities, on the composition of firms' physical capital, and of a unique nominal wage - the mark-up rate changes as a reaction to the developments in the goods market. Such changes, as in the K+S models, follow the evolution of firms' market share (M Sf ):" (Pedrosa and Lang 2021:56)

Mark-up depends positively on market-share. (note on p.56)

"As argued by Skott and Ryoo (2008), the net equity issuance has been negative in the United States since the 1980s. Besides that, as noticed by Frank and Goyal (2008), in general, equity financing is not very relevant for big open companies' financing. However, small firms do often resort to equity financing (ibid.). While these are relevant facts, they are well beyond the goals and scope of this paper." (Pedrosa and Lang 2021:56)

[REF] References for not using equity issuance for firms financing mechanism. (note on p.56)

"Credit supply. The banking system evaluates firms' applications for loans based on the expected present value of each firm's loan project. The particular probability of default (prD ), modelled using a logistic function, influences this estimation:" (Pedrosa and Lang 2021:57)

Credit supply depends on expect value of ecah firm's loan project with a particular probability of default.

[ABM] Employ a similar function for credit default for households

[QUEST] Is possible to adapt this equation (17) to the household sector? If so, what are the main differences? If no, why not? (note on p.57)

"pe" (Pedrosa and Lang 2021:57)

[QUEST] Asset price is vanished away?
How Minskian is that? (note on p.57)

"Households demand. The real private consumption decision depends on the after-tax real wages and the begin-of-period expected real net wealth (V ) (Godley and Lavoie, 2007)." (Pedrosa and Lang 2021:57)

Household demand depends both on Wages and real net wealth. (note on p.57)

"Government demand. Real government expenditure is defined as a share of the aggregate capital stock (Dos Santos and Zezza, 2008). This share is composed of two parts. First, there is a fixed and exogenous component 0 ≤ Γ0 1, which is defined by the structural size of the government in the economy. Second, there is an anti-cyclical component: the government increases (decreases) temporarily the expenditures as long as the average capacity utilisation of the firms is below (above) a normal level (un). The intensity of government's anti-cyclical reaction is given by 0 ≤ Γ1 < 1:" (Pedrosa and Lang 2021:58)

[QUEST] Why not G as a function of Y (Eq 20)?
Additionaly, is un an observable variable for the government? (note on p.58)

"The distribution of total demand among firms depends on relative competitiveness. In turn, firms' competitiveness (Ef ) is negatively proportional to the firm price and the level of unfilled demand (lf ), normalised to the whole sector's weighted averages:" (Pedrosa and Lang 2021:58)

The distribution of total demand among firms depends on relative competitiveness. (note on p.58)

"Firms' market share evolves in time according to a quasi-replicator dynamic (see Silverberg et al., 1988; Dosi et al., 2010). Firms with above-average competitiveness gains market share and vice-versa:" (Pedrosa and Lang 2021:58)

[REF] Market-share mechanism. (note on p.58)

"The dividend-payout ratio (ηf ) is modelled similarly to Reissl (2020). We assume it is a decreasing function of the actual debt servicing (interest + amortisation) to operating cash flow ratio:" (Pedrosa and Lang 2021:59)

[REF] Dividend-payout ratio (note on p.59)

"Following Foley (2003), a hedge firm generates sufficient operating cash flow to cover both debt service and investment expenses, so that the net debt decreases. A speculative firm manages to cover the debt servicing, but still needs to borrow to finance investment. In this case, the net debt increases, but at a slower pace than investment. Finally, a Ponzi firm cannot cover the debt servicing, implying that the net debt grows faster than investment. Using equations (28) and (29), this classification translates into:" (Pedrosa and Lang 2021:60)

[REF] Minskian typology formalization. (note on p.60)

"Similarly to Reissl (2020), the spread is firm-specific and an increasing function of the debt-servicing to operating cash-flow ratio:" (Pedrosa and Lang 2021:60)

[REF] Bank spread is firm-specific

[ABM] Could be employed to household sector. Based on the New Narrative, both denominator and numerator will depend on asset prices. (note on p.60)

"Entry and exit of firms. The stock-flow consistency of exit-entry dynamics requires the absence of financial "black holes" in the model, while the entry-exit process is frequently a source of black holes in agent-based models (Caiani et al., 2016)." (Pedrosa and Lang 2021:61)

[FINDS] Entry-exit mechanism is a frequent source of black-holes in ABM model. (note on p.61)

"For simplicity, we follow the most common setting in AB models. The entry process occurs whenever a firm exits. The entrant's size corresponds to a share17 of the average capital stock of the incumbents. The balance sheet entries follow the market averages. For instance, we take the average liquidity ratio (deposits to total assets) of the economy to define the liquidity ratio of the firm. The same is valid for the leverage, so on and so forth. The establishment of a new firm is financed mostly by the households, but also by the banking sector (to meet the average leverage of the economy). The entrant firms' technology is obtained by applying a factor Beta(αx2 , βx2 ) on the technological frontier (Amax ) (Dosi et al., 2010)." (Pedrosa and Lang 2021:61)

[QUEST] Why follow the average? Is it reasonable that the incumbent have a better technological element? (note on p.61)

"We run a hundred Monte Carlo (MC) simulations with 500 periods each, in all scenarios. The first hundred periods are strongly affected by the symmetry condition imposed in the calibration (all firms start equal), and hence they are discarded." (Pedrosa and Lang 2021:62)

[FINDS] Why to discart the first periods. (note on p.62)

"investment is pro-cyclical and more volatile than GDP.18" (Pedrosa and Lang 2021:63)

Stylised fact I: investment is pro-cyclical and more voltile than GDP. (note on p.63)

"At the firm-level, Figure 2a shows that our model endogenously generates lumpy investment, well in tune with the empirical evidence (Doms and Dunne, 1998). The lumpiness of investment exists when firms with spiking investment coexist with firms performing zero (or quasi-zero) investment." (Pedrosa and Lang 2021:63)

[RESUL] Lumpy investment: high investment coexist with low investment. (note on p.63)

"We highlight that, despite being presented for the setting S1, the results are qualitatively the same for S2 and S3 settings. Accordingly, neither credit rationing nor firm-specific interest ratio alters remarkably the qualitative results of the baseline scenario." (Pedrosa and Lang 2021:65)

[RESUL] Neither credit rationin nor firm-specific interet ratio alters qualitative results of baseline scenario. (note on p.65)

"Aggregate profits are strongly pro-cyclical and leading the cycle. This is related to the Kaleckian profit equation, which is built-in the model because firms decide how much to invest, but not how much they earn. Unsurprisingly, since profits feed up the deposits of the firms, both the bank deposits of the firms and the liquidity ratio (deposits over total assets) are also pro-cyclical and leading (see Table 1)." (Pedrosa and Lang 2021:65)

[BACK] In all scenarios, profits are pro-cyclical and related to the Kaleckin profit equation. (note on p.65)

"Firstly, the cross-correlations show that aggregate debt, leverage ratio, and net leverage ratio are strongly pro-cyclical, which is in line with empirical evidence regarding the pro-cyclicality of credit (see Lown and Morgan, 2006; Leary, 2009)." (Pedrosa and Lang 2021:65)

[REF] Pro-cyclicality of credit. (note on p.65)

"Secondly, the leverage ratio is very persistent, both at micro (cf. Lemmon et al., 2008, for an empirical discussion) and macro (cf. Frank and Goyal, 2008) levels. In Fig. 2c, as shown by the high levels of leverage autocorrelation." (Pedrosa and Lang 2021:65)

[RESUL] Leverage ratio is persistent. (note on p.65)

"The reasons behind this are the following ones. On the one hand, low leverage implies low financial commitments. A low debt servicing entails, everything else equal, a high amount of free cash flows. This allows an accelerated pace of liquidity accumulation, which reduces the likelihood that a particular firm will need external funds in the future. On the other hand, firms with high leverage tend to have elevated cash disbursements to cover contractual financial obligations. Consequently, the tendency is to have a slower pace of liquidity accumulation because of the low level of free cash flows. Of course, between those two extremes, the cases are more nuanced and less inertial." (Pedrosa and Lang 2021:65)

[RESUL] Mechanism: Low debt, lower debt servicing (and the other way around) (note on p.65)

"Finally, even if all firms start equally, endogenous heterogeneity in firms' financial status emerges. As suggested by the evidence (Pedrosa, 2019; Davis et al., 2019), the smallest firms are more prone to become Ponzi than biggest firms, whereas the biggest firms have a higher probability of being hedge" (Pedrosa and Lang 2021:66)

[RESUL] The smaller firms are more proned to become Ponzi. (note on p.66)

"To summarise the threecategories classification of Minsky into a single variable able to measure the systemic financial fragility, we create a financial fragility index. It attributes discrete values to each financial status, weighted by size. The discrete values are arbitrarily set to 0 for hedge, to 0.5 for speculative, and to 1 for Ponzi firms. This index varies between 0 (where all firms are hedge, so the economy displays no financial fragility at all) and 1, where all firms are Ponzi, and fragility is maximum" (Pedrosa and Lang 2021:66)

[CONTRIB] Financial Fragility index. (note on p.66)

"Inspired by Kakwani's (1977) concentration index, we craft a profit-debt distribution index (henceforth PDIndex, see the appendix A.4 for details on its calculation). It lies in the [-1,1] interval if all profits of the firms are positive. In general, the index yields negative figures, as one can check in Fig. 3b, signalling that firms with low leverage are receiving a disproportionate share of profits as compared to the share of outstanding debt (profits are concentrated in firms with low leverage).19" (Pedrosa and Lang 2021:67)

Profit-debt distribution index ~ concentration index (note on p.67)

"The results reported in Table 2 show that the signs of the effects are the expected: higher profit rates diminish financial fragility, everything else constant; higher investment ratios increase financial fragility, and higher leverage raises the expected financial fragility." (Pedrosa and Lang 2021:67)

[RESUL] Summary of the results fo OLS estimations:

- Higher profits -> lower financial fragility
- Higher investment ratio -> higher financial fragility
- Higher leverage -> higher expected financial fragility (note on p.67)

"The economic intuition for this result is that if the profits are too concentrated in low-leverage firms (low financial commitments), firms with higher leverage (high financial commitments) have insufficient cash flows to cover the debt servicing, pushing them towards speculative and Ponzi financing. The opposite is also true. Thus, for a given level of leverage ratio, investment, and profit rates, multiple levels of financial fragility may occur, depending on the profit and debt joint distributions." (Pedrosa and Lang 2021:68)

[RESUL] Who recieves the profits matter: if low-leverage firms recieve, high-leverage have insufficiente cash flows to cover the debt servicing -> Speculative -> Ponzi. (note on p.68)

"In general, the bottom end of the firm-level leverage distribution drives most of the variability of the overall leverage. This is shown by the quartile leverage ratio coefficient of variation, displayed in Figure 5. It shows that the average leverage ratio of the first and second leverage ratio quartiles present substantially more variability than the top half 0.1 0.2 0.3 0.4 0.5 0.05 0.10 0.ts are robust across specifications." (Pedrosa and Lang 2021:69)

[RESUL] The first and second leverage ratio quartiles present more variability than the other. (note on p.69)

"Hence, the expansion in indebtedness of low-leverage firms is very often behind variations of the aggregate leverage ratio. The main implication is that many times an increase in the leverage ratio will not result in a proportional increase fragile economy." (Pedrosa and Lang 2021:70)

[RESUL] The increase of leverage ratio will not necessarily result in increase fragile economy. (note on p.70)

"Having the profit-distribution index as a benchmark, most of the aggregate leverage variability happens in the first and the second quartiles of firms' leverage. In these quartiles, a higher (lower) profit-debt concentration relates to a lower (higher) leverage ratio. Within the third and fourth quartiles of debt, the total contribution to total leverage tends to be much less sensitive to changes in the profit-debt distribution." (Pedrosa and Lang 2021:70)

Interpretation about why the bottom distribution indebetedness leads the changes in the aggregate leverage ratio. (note on p.70)

"When the profit-debt index decreases, profits are becoming more concentrated within firms with very low (or zero) debt. The low leverage implies low cash disbursements to meet financial obligations. Since a substantial share of profits flows to firms with low financial commitments, the aggregate amount of free cash flows increases, accelerating the sector-wide pace of liquidity accumulation. However, less levered firms absorb much of the growth in liquidity. An implication of the liquidity growth is a considerable level of inertia: more liquidity translates into a low need for external funds to finance investment and production, which dynamically feeds back into lower debt servicing and more liquidity accumulation." (Pedrosa and Lang 2021:71)

Explanation of leverage inertia. (note on p.71)

"Therefore, the existence of such mechanisms mitigates the impact of the aggregate leverage ratio on the systemic financial fragility. The tendency is that the leverage ratio rises whenever more levered firms are getting proportionally more money, more likely providing means of debt validation. Conversely, it tends to go down when less levered firms receive more cash flows, which may foster debt validation problems at the upper tail of the leverage ratio distribution." (Pedrosa and Lang 2021:71)

The relevance of heterogenity in determining the impacts of aggregate leverage ratio on systemic financial fragility. (note on p.71)

"Let us define a Minskian firm as one with positive ex-post debt financing, defined as the new loans taken by each firm, which firms and banks agree at the beginning of the production-investment process, discounted by the retained profits. The retained profits are the gross profits discounted by interest, taxes, and dividends payments. By contrast, we define the Steindlian firms as one with a zero or negative ex-post debt financing." (Pedrosa and Lang 2021:72)

[DEF] Definition of Minskian and Steindlian regimes. (note on p.72)

"An important emergent property of our model is that Minskian and Steindlian firms persistently co-exist (Figure 7a)." (Pedrosa and Lang 2021:72)

[RESUL] Minskian and Steindlian regime coexist. (note on p.72)

"The following global sensitivity analysis (GSA) allows us to verify the robustness of the results in the parametric space, and to gain further insights regarding the drivers of the model's results. Following Salle and Yıldızoğlu (2014), to reduce the computational costs of a complete parameter-space sweep, we combine a parsimonious and efficient sampling schedule, given by a Nearly Orthogonal Latin Hypercube (NOLH) (Cioppa and Lucas, 2007), and estimate a meta-model to approximate the true model. On the meta-model, we perform a Sobol decomposition. Such a variance-based procedure allows the identification of the relative effect of the parameters on the variance of a selected metric (or response variable) of the model.20" (Pedrosa and Lang 2021:73)

[REF] Global sensitivity analysis (GSA); Sobol; meta-model and Nearly Orthogonal Latin Hypercube (NOLH) (note on p.73)

"The GSA confirmed the robustness of the model's core results in the tested parameter space: (i) financial fragility depends on the profit-debt joint distribution; (ii) the dynamics of the aggregate leverage ratio depends on the PDIndex; (iii) Minskian and Steindlian firms co-exist." (Pedrosa and Lang 2021:73)

[RESUL] Summary of the main results. (note on p.73)

"The economic intuitions are as follows. In the first case, as discussed above, a higher accelerator coefficient brings less technological heterogeneity, mitigating the maldistribution of profits. It also implies that firms more often need to resort to debt-financing of investment. The consequence, because 0.84lead to increased importance of debt distribution on the PDIndex. The second case highlights the importance of the relative mark-up. The faster firms adjust their mark-ups to market share variations, the faster the profit distribution Te 0.83ution in the PDIndex, confirming the chHthird effect is related to technological eting the distribution of profits through 0.82" (Pedrosa and Lang 2021:74)

Economic intution on sensitivity of accelerator parameter and mark-up adjustment (note on p.74)

"Consequently, contrarily to what was suggested by Minsky and is often assumed in the financial fragility literature, aggregate indebtedness is not a reliable proxy of systemic financial fragility, at least in what concerns the non-financial firms' fragility that we studied in this paper." (Pedrosa and Lang 2021:75)

[RESUL] *Aggregate* indebtedness is not a reliable proxy of systemic financial fragility. (note on p.75)

"Therefore, as far as systemic financial fragility is concerned, the distribution of profits across firms is crucial to evaluate whether a system is stable or not. Doing justice to the complex nature of economic 0.1nting of systemic fragility needs to 0.10 0.8dynamics of the overall leverage ratio and financial fragility itself. Specifically, we have shown that the distribution of profits across firms does matter, both statically (immediately for financial fragility) and dynamically (because of the dynamics of leverage)." (Pedrosa and Lang 2021:76)

[RESUL] Systemic fragility needs to be bottom-up (note on p.76)

"to introduce asset prices dynamics and a disaggregated banking sector to include credit constraints and make commercial banks more accommodative during booms and less prone to grant credit during bursts." (Pedrosa and Lang 2021:77)

[RELEV] Further research could include asset prices dynamic and a disaggregated banking sector with creidt constraints and commercial banks more accomodative during booms and less prone to grand during bursts. (note on p.77)
