:PROPERTIES:
:ID:       a71ab0e8-2a4c-4930-8d93-9072d676fdab
:ROAM_REFS: cite:hallVarietiesCapitalismInstitutional2001
:END:
#+TITLE: hallVarietiesCapitalismInstitutional2001: Varieties of capitalism: the institutional foundations of comparative advantage (2001, )
#+OPTIONS: toc:nil num:nil
#+filetags: Theoretical QCA VoC
Time-stamp: 2021-02-22
- tags :: Capitalism,Comparative advantage (International trade),Comparative economics,Competition; International,Institutional economics


* Backlinks

[[id:91af4a64-81b2-42dc-a3bc-07a91329a989][Varieties of Capitalisms]]

* FISH-5SS


|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <50>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| *Background*                                  | There is an increase in both deregulation process and internationalization of finance. Both of them would suggest a "convergence hypothesis". VoC stablishes an analysis in which Political Economies tends to ensure its particularities in order to guarantee its comparative institutional advantages                                                                                                                                                                                                       |
| *Supporting Ideas*                            | Firms' internationalization is weaker than expected and government are not defesenless. These ideias supports the dual convergence proposal. In summary, comparative institutional advantages makes firms less mobile. The exploitation of some particular is made by institutional arbitrages (guarantee access to others' countries comparative institutional advantages). Theoretically, is highly based on Williamson and North ideas while its differences are more on granularity of VoC classification. |
| *Purpose*                                     | Systematize the VoC analysis framework, describing its concepts, consequences and distinctiveness to prior literature.                                                                                                                                                                                                                                                                                                                                                                                         |
| *Originality/value (Contribution)*            | Organizes this emerging framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| *Relevance*                                   | This chapter is an introduction to VoC literature and is well known, thus, this is an important reading. Additionally, provides some usefull definitions.                                                                                                                                                                                                                                                                                                                                                      |
| *Design/methodology/approach*                 | Presents some supporting data and comparison with prior literature.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| *Sample*                                      | Developed economies (no econometric procedure)                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Results*                                     | Firm-centric analysis in which the coordination problem is the main issue. Comparative institutional advantages explain some reacts of recent changes; predicts that LME and CME will be even more distinct; Incentives and policy making should occur according to the VoC typology.                                                                                                                                                                                                                          |
| *(Interesting) Findings*                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| *Research limitations/implications (Critics)* | LME and CME typology is not adequate to deal with housing issues since its is a firm-centric clusterization; institutional complementarity is too shalow: the co-ocorrence of institutions implies higher returns. *Alternative:* The presence of a institutional set may replace the function of other set while; the presence/absense of a set must be required (necessary) to an outcome occur. In other words, institutional consequences could not be seriourly analyzed aditivelly.                        |
| *Uncategorized stuff*                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| *5SS*                                         | Presents the VoC approach in which firm is back to the center; coordination problems are the main concerning; globalization do not leads to total convergence while institutional comparative advantages provides some resiliences that explain the dual convergence hypothesis.                                                                                                                                                                                                                               |
|---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: hallVarietiesCapitalismInstitutional2001
 :AUTHOR: P. A. Hall, & D. W. Soskice
 :JOURNAL:
 :YEAR: 2001
 :DOI:
 :URL:
 :END:


* Extracted Annotations (22/02/2021 17:53:33)
:PROPERTIES:
 :NOTER_DOCUMENT: /home/gpetrini/Zotero/storage/RWMXLMTY/Hall e Soskice - 2001 - Varieties of capitalism the institutional foundat.pdf
:NOTER_PAGE: 27
 :END:


"The object of this book is to elaborate a new framework for under­ standing the institutional similarities and differences among the devel­ oped economies" (Hall and Soskice 2001:18)

Object of the book: a new institutional framework.
Aim to developed countries. (note on p.18)




"We outline the basic approach in this Introduction. Subsequent chapters extend and apply it to a wide range of issues." (Hall and Soskice 2001:19)

Goal of this chapter in particular. (note on p.19)




"The 'varieties of capitalism' approach developed here can be seen as an effort to go beyond three perspectives on institu­ tional variation that have dominated the study of comparative capitalism in the preceding thirty years.2" (Hall and Soskice 2001:19)

VoC is an enhancement of the folowing CPE traditions. (note on p.19)




"this approach saw the principal challenge confronting the developed economies as one of modernizing industries still dominated by pre-war practices in order to secure high rates of national growth" (Hall and Soskice 2001:19)

Modernization approach. (note on p.19)




"Accordingly, those taking this approach focused on the institutional structures that gave states lever­ age over the private sector, such as planning systems and public influ­ ence over the flows of funds in the financial system (Cohen 1977; Estrin and Holmes 1983; Zysman 1983; Cox 1986)." (Hall and Soskice 2001:19)

Modernization: set of institutional configuretions -> leverage states -> financial system. (note on p.19)




"inflation became the preeminent problem facing the developed economies," (Hall and Soskice 2001:20)

Background of neo-cporporatism approach. (note on p.20)




"neo­ corporatism (Schmitter and Lehmbruch 1979; Berger 1981; Goldthorpe 1984; Alvarez et al. 1991)" (Hall and Soskice 2001:20)

Neo-corpratism scholars for futher reference. (note on p.20)




"neo­ corporatism was generally associated with the capacity of a state to nego­ tiate durable bargains with employers and the trade union movement regarding wages, working conditions, and social or economic policy" (Hall and Soskice 2001:20)

Neo-corporatism: State -> negotiate bargains with employers and trade unions.
(note on p.20)




"we group analyses of sectoral governance, national innovation systems, and flexible production regimes that are diverse in some respects but united by several key analytic feature" (Hall and Soskice 2001:20)

Social systems of production approach. (note on p.20)




"behavior of firms. Influenced by the French regulation school, they emphasize the move­ ment of firms away from mass production toward new production regimes that depend on collective institutions at the regional, sectoral, or national level (Piore and Sabel 1984; Dore 1986; Streeck and Schmitter 1986; Dosi et al. 1988; Boyer 1990; Lazonick 1991; Campbell et al. 1991; Nelson 1993; Hollingsworth et al. 1994; Herrigel 1996; Hollingsworth and Boyer 1997; Edquist 1997; Whitley 1999)." (Hall and Soskice 2001:20)

From mass to new production regime (Systems of production, influenced by french regulation scholl) (note on p.20)




"generate trust or enhance learning within economic communities." (Hall and Soskice 2001:21)

In system of production approach, institutions -> enhance learning. (note on p.21)




"modern­ ization approach tend to overstate what governments can accomplish" (Hall and Soskice 2001:21)

Limitations of modernization approach: overestimate what governments can achieve. (note on p.21)




"Neo-corporatist analysis directs our attention to the organization of society, but its emphasis on the trade union movement underplays the role that firms and employer organizations play in the coordination of the economy (d. Soskice 1990a; Swenson 1991). We want to bring firms back into the center of the analysis of comparative capitalism and, without neglecting trade unions, highlight the role that business associations and other types of relationships among firms play in the political economy." (Hall and Soskice 2001:21)

Neo-corporatist neglect the role of firmas in the coordination problem.
VoC: bring firm back to the center of analysis. (note on p.21)




"Our premiss is that many of the most important institutional structures­ notably systems of labor market regulation, of education and training, and of corporate governance-depend on the presence of regulatory regimes that are the preserve of the nation-state." (Hall and Soskice 2001:21)

VoC premisse: institutions are nation-wid and depends on regulatory regimes. (note on p.21)




"dominate the analysis of comparative capitalism" (Hall and Soskice 2001:22)

On the following, the authors present some elements of institutions that are relevant, but are not the core of VoC:
Institutions are socializing agencies; confers power on particiular actors and are a matrix of sanctions and incentives.
Reason to use other concept: don not capture the *strateic interactions*. (note on p.22)




"firm at the center of the analysis" (Hall and Soskice 2001:22)

"By integrating game­ theoretical perspectives on the firm of the sort that are now central to microeconomics into an analysis of the macroeconomy" (Hall and Soskice 2001:22)

"By locating the firm at the center of the analysis, we hope to build bridges between business studies and comparative political economy, two disciplines that are all too often disconnected. By integrating game­ theoretical perspectives on the firm of the sort that are now central to microeconomics into an analysis of the macroeconomy, we attempt to connect the new microeconomics to important issues in macroeconomics." (Hall and Soskice 2001:22)

Core of VoC: firm at the center of analysis; game theory to microfundament macroeconomic outcomes. (note on p.22)




"This varieties of capitalism approach to the political economy is actor­ centered, which is to say we see the political economy as a terrain popu­ lated by multiple actors, each of whom seeks to advance his interests in a rational way in strategic interaction with others (Scharpf 1997a)." (Hall and Soskice 2001:23)

VoC as an actor centric approach. (note on p.23)




"They are the key agents of adjustment in the face of technological change or international competition whose activities aggregate into overall levels of economic performance" (Hall and Soskice 2001:23)

Why firms? center of technological change or international competition. (note on p.23)




"we see firms as actors seeking to develop and exploit core compe­ tencies or dynamic capabilities understood as capacities for developing, producing, and distributing goods and services profitably" (Hall and Soskice 2001:23)

Firms are actors seeking to capture dynamic capabilities. (note on p.23)




"As the work on transactions costs and principal­ agent relationships in the economics of organization has underlined, these are problematic relationships (Milgrom and Roberts 1992). Even where hierarchies can be used to secure the cooperation of actors, firms encounter problems of moral hazard, adverse selection, and shirking." (Hall and Soskice 2001:23)

Here, the authors presentes some microeconomic foundationg regarding coordinations problems. (note on p.23)




"ith outside actors involve incomplete contract­y relational, a firm encounters many coordination problems." (Hall and Soskice 2001:23)

Since those dynamic capabilities are relational, firms have coordination problems. (note on p.23)




"five spheres in which firms must develop relationships to resolve coordination problems central" (Hall and Soskice 2001:23)

Spheres firms must have in order to solve coordination problems.
Since the understand of VoC as a firm-centric is enough for dissertation proposes, this part will not be properly reported. (note on p.23)




"From this perspective, it follows that national political economies can be compared by reference to the way in which firms resolve the coordination problems they face in these five spheres." (Hall and Soskice 2001:25)

According to VoC, national political economies must be compared by the way the way firms solve the coordination problem.
Thus, the following typologic, do not sound adequate to deal with housing problems. (note on p.25)




"I n liberal market economies, firms coordinate their activities primarily via hierarchies and competitive market arrangements. These forms of coor­ dination are well described by a classic literature (Williamson 1985)." (Hall and Soskice 2001:25)

Definition of liberal market economies. (note on p.25)




"In coordinated market economies, firms depend more heavily on non­ market relationships to coordinate their endeavors with other actors and to construct their core competencies" (Hall and Soskice 2001:25)

"Institutions, organizations, and culture enter this analysis because of the support they provide for the relationships firms develop to resolve co­ ordination problems. Following North (1990: 3), we define institutions as a set of rules, formal or informat that actors generally follow, whether for normative, cognitive, or material reasons, and organizations as durable entities with formally recognized members, whose rules also contribute to the institutions of the political economy.9" (Hall and Soskice 2001:26)

"In general, these will be institutions that reduce the uncertainty actors have about the behavior of others and allow them to make credible commitments to each other." (Hall and Soskice 2001:27)

Which an why some institutions are prefered? (note on p.27)




"A standard literature suggests that these are institutions providing capacities for (i) the exchange of information among the actors, (ii) the monitoring of behavior, and (iii) the sanctioning of defection from coopera­ tive endeavor (see Ostrom 1990)." (Hall and Soskice 2001:27)

What capabilities institutions generates? (note on p.27)




"Similarly, the terms on which finance is provided to firms will depend on the monitoring capacities present in the economy." (Hall and Soskice 2001:27)

How finance enters in VoC literature: depends on monitoring capacities. (note on p.27)




"namely institutions that provide actors potentially able to coop­ erate with one another with a capacity for deliberation. By this, we simply mean institutions that encourage the relevant actors to engage in col­ lective discussion and to reach agreements with each other.lO Deliberative institutions are important for several reasons. Deliberative proceedings in which the participants engage in extensive sharing of information about their interests and beliefs can improve the confidence of each in the strategies likely to be taken by the others." (Hall and Soskice 2001:28)

The relecance of *deliberative institutions*.
Note: it is mor common in CME. (note on p.28)




"deliberative institutions can enhance the capacity of actors in the political economy for strategic action when faced with new or un­ familiar challenge" (Hall and Soskice 2001:29)

Deliberative also can guide actors to through unfamiliar chalanges. (note on p.29)




"Many analyses take the view that the relevant outcomes in economic performance or policy follow more or less directly from differences in the formal organization of the political econom" (Hall and Soskice 2001:29)

"Because we believe such outcomes are the products of efforts to coordinate in contexts of strategic interaction, however, we reject the contention that they follow from the presence of a particular set of institutions alone, at least if the latter are defined entirely in terms of formal rules or organizations." (Hall and Soskice 2001:29)

"But formal institutions are rarely sufficient to guarantee that equilibrium" (Hall and Soskice 2001:29)

"As we have noted, the presence of a set of formal institutions is often a necessary precondition for attaining the relevant equilibrium in contexts of coordination. But formal institutions are rarely sufficient to guarantee that equilibrium." (Hall and Soskice 2001:29)

Formal institutions may be necessary conditions, but not sufficient ones: informal institutions may be required as well to guarantee the equilibrium. (note on p.29)




"Accordingly, taking a step beyond many accounts, we emphasize the importance of informal rules and understandings to securing the equi­ libria in the many strategic interactions of the political economy. These shared understandings are important elements of the 'common know­ ledge' that lead participants to coordinate on one outcome, rather than another, when both are feasible in the presence of a specific set of formal institutions" (Hall and Soskice 2001:30)

Informal institutions are important for VoC also.
Reason: leads participants to coordinate with the outcome rather than anoter objective. (note on p.30)




"This is an entry point in the analysis for history and culture. Many actors learn to follow a set of informal rules by virtue of experience with a familiar set of actors and the shared understandings that accumulate from this experience constitute something like a common culture." (Hall and Soskice 2001:30)

History and culture enters in VoC by means of informal institutions. (note on p.30)




"First, although we make use of the influential dichotomy between 'markets' and 'hierarchies' that Williamson (1975) has impressed on the field, we do not think this exhausts the relevant variation. Markets and hierarchies are features of LMEs and CMEs but we stress the systematic variation found in the character of corporate structure (or hierarchies) across different types of economies and the presence of coordination problems even within hierarchical settings (Milgrom and Roberts 1992)." (Hall and Soskice 2001:31)

First difference between VoC and NIE: Hierarquies and Markets typologies are not enough. (note on p.31)




"two institutional forms as the only ones firms can employ to resolve the challenges they confront." (Hall and Soskice 2001:31)

Firm can employ other form of institutions rather than only market or hierarchy. (note on p.31)




"we think it unrealistic to regard the over arching institutional structures of the political economy, and especially those coordinating the endeavors of many actors" (Hall and Soskice 2001:32)

VoC reject the Chandler's Institutions -> firm strategy frameword.
A single firm cannot create colective institutions. (note on p.32)




"In short, there are important respects in which strategy follows structure. For this reason, our approach predicts system­ atic differences in corporate strategy across nations, and differences that parallel the over arching institutional structures of the political economy. This is one of the most important implications of the analysis." (Hall and Soskice 2001:32)

The implication of VoC distinctiveness
(note on p.32)




"We also agree that differences in corporate strategy can be conditioned by the institutional support available to firms at the regional or sectoral levels" (Hall and Soskice 2001:32)

"We think this justified by the fact that so many of the institutional factors conditioning the behavior of firms remain nation­ specific." (Hall and Soskice 2001:33)

Hypothesis: Conditioning institutional facts reamins nation-specific. (note on p.33)




"To put the point in the most general terms, however, firms and other actors in coordinated market economies should be more will­ ing to invest in specific and co-specific assets (i.e. assets that cannot readily be turned to another purpose and assets whose returns depend heavily on the active cooperation of others), while those in liberal market economies should invest more extensively in switchable assets (i.e. assets whose value can be realized if diverted to other purposes)." (Hall and Soskice 2001:34)

General statemente: CME -> specific assets; LME -> awitchable assets (note on p.34)




This point is relevant. It must be argue that Chang's reasoning is different than this one. (note on p.34)




"The presence of institutional complementarities reinforces the differences between liberal and coordinated market economies." (Hall and Soskice 2001:34)

"Following Aoki (1994), we extend this line of reasoning to the institu­ tions of the political economy. Here, two institutions can be said to be complementary if the presence (or efficiency) of one increases the returns from (or efficiency of) the other." (Hall and Soskice 2001:34)

Definition of institutional complementarity according to Aoki (1994): the presence of an institution increases the returns of the other (smilar to complementary goods).
This ideia is slight differente from Chang's: institutions may not exist in the absence of other; a set of institution may have a similar result as another equivalent one (/e.g./ Inflation Targeting in countries with CB not commited with this goal) (note on p.34)




"Aoki (1994) has argued that long-term employment is more feasible where the financial system provides capital on terms that are not sensitive to current profitability." (Hall and Soskice 2001:35)

Aoki (1994) reasoning. (note on p.35)




"It suggests that nations with a particular type of coordination in one sphere of the economy should tend to develop complementary practices in other spheres as well.1" (Hall and Soskice 2001:35)

Implication of institutional complementarity in VoC: countries with X (one sphere) tend to develop Y (other sphere)
In other words, the state that there is a correlation occurance of institutional sets. (note on p.35)




"If this is correct, institutional practices of various types should not be distributed randomly across nations. Instead, we should see some clus­ tering along the dimensions that divide liberal from coordinated mar­ ket economies, as nations converge on complementary practices across different spheres." (Hall and Soskice 2001:35)

As a consequence, there should have a clustering between liberal and coordinated markets.
Is VoC a correlation classification framework? (note on p.35)




"Mediter­ ranean', marked by a large agrarian sector and recent histories of exten­ sive state intervention that have left them with specific kinds of capacities for non-market coordination in the sphere of corporate finance but more liberal arrangements in the sphere of labor relations (see Rhodes 1997)" (Hall and Soskice 2001:38)

Mediterranean countries- the residual classification (note on p.38)




"Despite some variation over specific periods, both liberal and coordinated market economies seem capable of providing satisfactory levels of long-run economic performance, as the major indicators of national well-being displayed in Table 1.1 indicate." (Hall and Soskice 2001:38)

This occur because they are choosing advanced economies, so this outcomes are almost a definition of usual development classification. (note on p.38)




"In coordinated market economies, firms resolve many of these problems through strategic interaction." (Hall and Soskice 2001:39)

CME: firms resolves coordination problems with strategic interaction. (note on p.39)




"The financial system or market for corporate governance in coordinated market economies typically provides companies with access to finance that is not entirely dependent on publicly available financial data or current returns." (Hall and Soskice 2001:39)

Thus, there must exist other way to monitor the firm performance: informal networks. (note on p.39)




"Thus, the corporate strategies found in many CMEs also depend on tax provi­ sions, securities regulations, and networks of cross-shareholding that" (Hall and Soskice 2001:40)

Overview of investment funding relations. (note on p.40)




"(iii) Many firms in coordinated market economies employ production strategies that rely on a highly skilled labor force given substantial work autonomy and encouraged to share the information it acquires in order to generate continuous improvements in product lines and production processes (Sorge and Warner 1986; Dore 1986). However, companies that adopt such strategies are vulnerable to 'hold up' by their employees and the 'poaching' of skilled workers by other firms, while employees who share the information they gain at work with management are open to exploitation.23 Thus, CMEs need industrial relations institutions capable of resolving such problems." (Hall and Soskice 2001:41)

Labor relations in CME. (note on p.41)




"setting wages through industry-level bargains between trade unions and employer associations" (Hall and Soskice 2001:41)

How CME solves wages setting problems. (note on p.41)




"depend on education and training systems capable of providing workers with such skills.2" (Hall and Soskice 2001:42)

Depend on education and trainning. (note on p.42)




"Germany relies on industry-wide employer associations and trade unions to supervise a publicly subsidized training system." (Hall and Soskice 2001:42)

"make extensive use of long-term labor contracts" (Hall and Soskice 2001:43)

The cannot relly on technology transfer (note on p.43)




"cultivate inter-company relations of the sort that facilitate the diffusion of technology across the economy" (Hall and Soskice 2001:43)

"A consider­ able amount of research is also financed jointly by companies, often in collaboration with quasi-public research institutes." (Hall and Soskice 2001:43)

"The complementarities present in the German political economy should be apparent from this account. Many firms pursue production strategies that depend on workers with specific skills and high levels of corporate commitment that are secured by offering them long employ­ ment tenures, industry-based wages, and protective works councils. But these practices are feasible only because a corporate governance system replete with mechanisms for network monitoring provides firms with access to capital on terms that are relatively independent of fluctuations in profitability. Effective vocational training schemes, supported by an industrial-relations system that discourages poaching, provide high levels of industry-specific skills. In turn, this encourages collective stan­ dard-setting and inter-firm collaboration of the sort that promotes tech­ nology transfer." (Hall and Soskice 2001:44)

Overview of complementarities on Germany case. (note on p.44)




"there is less institutional support for non-market forms of coordination." (Hall and Soskice 2001:44)

LME defined as Non-CME. (note on p.44)




"(i) Several features of the financial systems or markets for corporate govern­ ance of liberal market economies encourage firms to be attentive to cur­ rent earnings and the price of their shares on equity markets." (Hall and Soskice 2001:44)

Funding in LME depends on observable data -> valuation and shares prices. (note on p.44)




"In the industrial relations arena, firms in liberal market economies generally rely heavily on the market relationship between individual worker and employer to organize relations with their labor forc" (Hall and Soskice 2001:46)

"There­ fore, these economies depend more heavily on macroeconomic policy and market competition to control wages and inflation (see Franzese in this volume; Hall and Franzese 1998)" (Hall and Soskice 2001:47)

Wage and inflation in LME. (note on p.47)




"(iii) The education and training systems of liberal market economies are generally complementary to these highly fluid labor markets. Vocational training is normally provided by institutions offering formal educa­ tion that focuses on general skills because companies are loath to invest in apprenticeship schemes imparting industry-specific skills where they have no guarantees that other firms will not simply poach their appren­ tices without investing in training themselves." (Hall and Soskice 2001:47)

Education and training. (note on p.47)




"Inter-company relations in liberal market economies are based, for the most part, on standard market relationships and enforceable formal contracts." (Hall and Soskice 2001:47)

"How then does technology transfer take place in liberal market economies? In large measure, it is secured through the movement of scientists and engineers from one company to another (or from research institutions to the private sector) that fluid labor markets facilitate. These scientific personnel bring their technical knowledge with them." (Hall and Soskice 2001:48)

Technology transfer in LME. (note on p.48)




"Special note should be taken of the complementarities between the internal structure of firms and their external institutional environ­ ment in liberal and coordinated market economies. In LMEs, corporate structures that concentrate authority in top management make it easier for firms to release labor when facing pressure from financial markets and to impose a new strategy on the firm to take advantage of the shifting market opportunities that often present themselves in economies characterized by highly mobile assets. By contrast, in CMEs, where access to finance and technology often depends on a firm's attractiveness as a collaborator and hence on its reputation, corporate structures that impose more consensual forms of decision-making allow firms to develop repu­ tations that are not entirely dependent on those of its top management. By reducing the capacity of top management to act arbitrarily, these structures also enhance the firm's capacity to enter credibly into rela­ tional contracts with employees and others in economies where a firm's access to many kinds of assets, ranging from technology to skills, may depend on its capacity for relational contracting" (Hall and Soskice 2001:50)

Overview of complementarities in LME. (note on p.50)




"In particular, we are suggesting that it can be fruitful to consider how firms coordinate their endeavors and to analyze the institutions of the political economy from a perspective that asks what kind of support they provide for different kinds of coordina­ tion, even when the political economies at hand do not correspond to the ideal types we have just outlined." (Hall and Soskice 2001:50)

Objective: to analyse whcih institution support some kind of coordination solving procedure. (note on p.50)




"One important axis of difference among CMEs runs between those that rely primarily on industry-based coordination, as do many of the northern European nations, and those with institutional structures that foster group-based coordination of the sort found in Japan and South Korea." (Hall and Soskice 2001:51)

Variation inside CME: industry-based or group-base. (note on p.51)




"However, recent developments have dealt a serious blow to this account of comparative economic advantage. The most important of these include the expansion of intra-industry trade and increases in the international mobility of capital. If the theory is correct, nations should not import and export high volumes of goods from the same sector; and there is a real possibility that international movements of capital will even out national factor endowments. As a result, some economists have become skeptical about whether comparative advantages really exist, and many have begun to seek other explanations for the expansion of trade and the geographic distribution of production" (Hall and Soskice 2001:53)

Some scholars questioning the comparative economic advantage.
Contrafactual: expansion of intra-industry trade. (note on p.53)




"concept of compara­ tive institutional advantage. The basic idea is that the institutional struc­ ture of a particular political economy provides firms with advantages for engaging in specific types of activities there. Firms can perform some types of activities, which allow them to produce some kinds of goods, more efficiently than others because of the institutional support they receive for those activities in the political economy, and the institutions relevant to these activities are not distributed evenly across nations." (Hall and Soskice 2001:54)

Definition of comparative institutional change. (note on p.54)




"Most of this literature, however, looks for the ingredients of absolute advan­ tage, i.e. it identifies factors more of which will improve the perform­ ance of any economy. We seek institutional features that might confer comparative advantage and, thus, be better suited to explaining cross­ national patterns of product or process specialization (Zysman 1994)." (Hall and Soskice 2001:55)

Literature focus on market relations and legal framework; other emphasise innovation systems (such as Dosi) to explain competitive advantage in absolute terms: identifies which facores will improve the performance of the economy. (note on p.55)




"Although there may be types of comparative advantage that these institutional frameworks confer that we have not yet explored, we focus here on their impact on innovation since a firm's capacity to inovate is crucial to its long-run success." (Hall and Soskice 2001:55)

Thereafter, the authors exemplifies with a comparative analysis for innovation. (note on p.55)




"Coordinated market economies should be better at supporting incre­ mental innovation. This follows from the emphasis we have put on the relational requirements of company endeavors." (Hall and Soskice 2001:56)

Predictions for innovation in CME: incremental ones. (note on p.56)




"However, the institutional framework of liberal market economies is highly supportive of radical innovation." (Hall and Soskice 2001:57)

Institutions in LME, on the other side, supports radical innovation. (note on p.57)




"In short, the institutional frameworks of liberal market economies provide companies with better capacities for radical innovation, while those of coordinated market economies provide superior capacities for incremental inovation. Therefore, to the extent allowed by transport costs and the efficiency of international markets, there should be national patterns of specialization in activities and products; and these should reflect rational responses to the institutional frameworks identified here rather than random geographic agglomeration." (Hall and Soskice 2001:58)

Conclusion of the summary example. (note on p.58)




"Economists have also long believed that skill levels can be important to comparative advantage, and our analysis suggests that the availability of labor with particular types of skills will be dependent on precisely the kinds of institutions that distinguish liberal from coordinated market economies." (Hall and Soskice 2001:61)

Interesting finding: skill levels by its own is not enough to promote comparative advantage.
It will depends on the institutional sets. (note on p.61)




"Broadly speaking, the problem was seen as one of inducing economic actors to cooperate with the government." (Hall and Soskice 2001:62)

priviously to VoC, the main goal of policy-making is to promote the incentives to induce economic agents to cooperate with the government. (note on p.62)




"From our perspective, however, the principal problem facing policy­ makers is quite different: it is one of inducing economic actors to co­ operate more effectively with each other" (Hall and Soskice 2001:62)

In VoC, the main goal is to induce agentes to *cooperate with each other*. (note on p.62)




"Accord­ ingly, one of the principal ways in which policy-makers can improve national economic performance is to secure better forms of coordination among private-sector actors." (Hall and Soskice 2001:62)

What government shoudl do? Ensure institutions that enable better coordinations. (note on p.62)




"It follows that economic policies will be effective only if they are incen­ tive compatible, namely complementary to the coordinating capacities embedded in the existing political economy (Wood 1997)." (Hall and Soskice 2001:63)

Most important, those incestives must bem compatibles with the capacities embedded in the economy.
In other words, incentives in LME must be compatible with LME capacities. (note on p.63)




"Let us distinguish between 'market incentive' policies and 'coordination-oriented' policies. The former rely on market­ based incentives to induce actors to perform more effectively. The latter attempt to improve the competencies of firms, such as their skill levels or technological capabilities, by addressing firm needs with relative precision. Thus, coordination-oriented policies must be based on high levels of information about the activities of the firm" (Hall and Soskice 2001:64)

Definition of market and coordination-oriented incentives. (note on p.64)




"here should be a correspondence between types of political economies and types of welfare states. And that appears to be the case." (Hall and Soskice 2001:67)

There should be a relation between VoC typologies and types of welfare states. (note on p.67)




"For political economy, the principal issue raised by globalization concerns the stability of regulatory regimes and national institutions in the face of heightened competitive pressure (Boyer and Drache 1996; Rodrik 1997)." (Hall and Soskice 2001:72)

The main issue regarding globalization in PE literature is the stability of regulatory regimes and national institutions. (note on p.72)




"Conventional views of globalization contain a 'convergence hypothesis' analogous in force, but considerably less san­ guine in implications, to an earlier one based on theories of industrialism (Kerr et al. 1960; Graubard 1964)." (Hall and Soskice 2001:73)

Firms will not move activities off-shore due to the development of institional comparative advantages. (note on p.73)




"Some scholars argue that the internationalization of trade and finance has not been as extensive or unprecedented as is often believed. Others argue that national governments are not as defenseless in the face of these developments as they appear, because governments have simply used international institutions or the excuse of global pressure to pursue reforms they wanted in any case (Wade 1996; Boyer 1996; Cohen 1996)." (Hall and Soskice 2001:73)

Contrafactuals to convergence hypothesis: internationalization is not so strong as expected; governments are not defenseless. (note on p.73)




"firms in LMEs and CMEs develop distinctive strategies and struc­ tures to capitalize on the institutions available for market or non-market coordination in the economy." (Hall and Soskice 2001:73)

Firms in LME and CME are not similar and not becoming more alike. (note on p.73)




"Second, our perspective suggests that firms will not automatically move their activities off-shore when offered low-cost labor abroad. Cheaper labor that comes with commensurate skill and productivity levels is always attractive, but firms also derive competitive advantages from the institutions in their home country that support specific types of interand intra-firm relationships." (Hall and Soskice 2001:73)

"Comparative institutional advan­ tages tend to render companies less mobile than theories that do not acknowledge them imply." (Hall and Soskice 2001:73)

In summary, comparative institutional advantages make firms less mobile as expected. (note on p.73)




"Our concept of comparative institutional advantage also suggests that firms may exploit new opportunities for movement to engage in a form of institutional arbitrage. By this, we mean that companies may shift par­ ticular activities to other nations in order to secure the advantages that the institutional frameworks of their political economies offer for pursuing those activities" (Hall and Soskice 2001:74)

Definition of institutional arbitrage: firms shifts parts of their activities to toher nations to secure advantages in that instituional sets (note on p.74)




"Thus, companies may move some of their activities to liberal market economies, not simply to lower labor costs, but to secure access to institutional support for radical innovation." (Hall and Soskice 2001:74)

Exemple of institutional arbitrage. (note on p.74)




"The result should be some weakening of organized labor and a substantial amount of deregulation, much as conventional views predict." (Hall and Soskice 2001:74)

There are some predicitions similar to conventional theory. (note on p.74)




"Instead of the monolithic movement toward deregulation that many expect from globalization, our analysis predicts a bifurcated response marked by widespread deregulation in liberal market economies and limited movement in coordinated market economies.4o" (Hall and Soskice 2001:75)

VoC states a bifurcated prediction instead of a monolithic movement towards rederegulation. (note on p.75)




"Deregulation has been far-reaching in the liberal market economies of Britain, the United States, New Zealand, Canada, and Australia but much less exten­ sive in the coordinated market economies of northern Europe" (Hall and Soskice 2001:76)

In summaru, deregulation tendencies are stronger in LME than in CME. (note on p.76)




"There is another side to globalization, however, with effects that some argue are more ambiguous. It lies in the pressures stemming from the internationalization of finance, where developments have recently been dramatic, if not unprecedented." (Hall and Soskice 2001:77)

The internationalization of *finance*, on the other side is unprecedented (note on p.77)




"Therefore, firms seeking access to these funds face pressure to revise their accounting standards, appoint independent directors, and deliver the high rates of return associated with 'shareholder value'." (Hall and Soskice 2001:77)

Gravitation towards shareholder valorization. (note on p.77)




"Similarly, some of the large banks and insurance companies in CMEs that once cultivated close relations with manufacturing firms have been disengaging from them in order to free up resources for global expan­ sion." (Hall and Soskice 2001:78)

CME banks vs finance internationalization (note on p.78)




"These developments threaten traditional practices in CMEs in several ways. On the one hand, they could disrupt the intricate systems of cross­ shareholding and inter-corporate linkage that provide capacities for network monitoring, thereby reducing the access of firms to capital that is not tied to current profitability. On the other, they could force firms whose strategies and structure have reflected responsiveness to a wide range of stakeholders, including employees, to become more attentive to shareholders and rates of return; and this might reduce their capacity to make credible commitments to long-term collaborative relationships with other firms and employees." (Hall and Soskice 2001:78)

These changes threaten CMEs, however, they handle this problem in a CME manner. (note on p.78)




"On one side are works that focus on institutions and the ways in which they reproduce stable patterns of behavior. Their relatively static view implies that national systems are unlikely to change very much in the face of globalization. On the other are works that attribute great force to the pressures associ­ ated with globalization. They tend to see national practices as inertial factors that will be transformed by these pressures." (Hall and Soskice 2001:79)

There are two versions of change:

1. National systems are unlikely to change
2. Glogalization make pressure to changes (note on p.79)




"We expect firms to respond with efforts to modify their practices so as to sustain their competitive advantages, including comparative institutional advantages. Thus, much of the adjustment process will be oriented to the institutional recrea­ tion of comparative advantage." (Hall and Soskice 2001:80)

According to VoC< firms reacts to shock trying to preserve its comparative institutional advantages. (note on p.80)




"Institutional complementarities should play an important, if ambig­ uous, role in these processes of adjustment" (Hall and Soskice 2001:80)

Complementaries institutions may play a role in the same or even in the other direction. (note on p.80)
