:PROPERTIES:
:ID:       8003093b-6857-4226-bb7e-f46c9b128da8
:ROAM_REFS: @assenza_2015_Emergent
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Assenza, Delli Gatti, Grazzini: Emergent Dynamics of a Macroeconomic Agent Based Model with Capital and Credit - (2015, Journal of Economic Dynamics and Control)
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: "Journal of Economic Dynamics and Control"
#+FILETAGS: AgentBasedModels Upstream-DownstreamDynamics CATSModelFamily
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS

[cite/t:@assenza_2015_Emergent] enhance the [[id:88dc308c-ddfb-4216-9587-0085cd197621][CATS ABM family]] by including both a capital and a credit market.
This small-scale model can reproduce endogenous [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]] with [[id:67c15aaa-7b6e-4407-b2de-71570ce061f5][Financial Crises]].
The authors state that the model novelty are the main drivers of this pattern.
However, the constant High Powered Money seems to be a more adequate candidate for the booms and bursts.


** Background and motivation

- Some small-scale models do not have capital goods modeled
  - This is the case for the first [[id:175002f6-69a8-4fa1-a7da-b76802ecc21e][General Equilibrium Model]]s and [[id:88dc308c-ddfb-4216-9587-0085cd197621][CATS ABM family]]


** Supporting Ideas and hypothesis


- Labor and capital are homogeneous for simplicity
  - There is no endogenous innovation process as in the [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]].
- It is assumed that each firm has one capitalist owner. Thus, the number of the firms match the number of capitalists households
  - Capitalists households act as rentiers
- When not employed, workers households dis-saves its net worth
  - There is no unemployment benefits
  - Households deposits is not remunerated
- Capital-goods firms use only labor to produce
- Consumption-goods are non-storable, thus those firms cannot use their inventories to meet demand
  - Capital goods, otherwise, are storable
- There is no complete information and there is [[id:48e49516-bdf2-4a72-9895-225d8fc06fc2][Transaction Costs]]
  - [[id:48e49516-bdf2-4a72-9895-225d8fc06fc2][Transaction Costs]] is included imposing a finite number of interactions among agents
    - Consumption- and capital-goods firms have higher [[id:48e49516-bdf2-4a72-9895-225d8fc06fc2][Transaction Costs]] compared to labor market
- Households sorts consumption-goods firms according to its prices and choose to buy from the one with lower price
  - If their demand is not fullfilled, they move on to the next in the queue
    - If their demand is not fullfilled even after visit all firms, they have involuntary savings
  - Households do not spend their whole budget in the first firm
- Wages are homogeneous among firms and households and unemployed households visit a random sample of firms
  - Thus, household will always accept the offer
  - There is no hiring or firing costs
  - Vacancies are filled when a firm is visited by an unemployed household
- Household consumption function follows [[id:701434fb-497d-4da9-a78c-7dee02300b39][Permanent Income Hypothesis]]
  - Consumption depends onf human and financial wealth and follows an adaptative algorithm
  - At odds with neoclassical [[id:701434fb-497d-4da9-a78c-7dee02300b39][Permanent Income Hypothesis]], households consider past income instead of expected income
  - Marginal propensity to consume is a non-linear function of wealth as in [[id:c66dd680-5e52-432f-b2a1-afa7188199a7][Carrolls's consumption function]]
- Both firms reacts to market signals in which compares its production with effective final demand as well as competitors' average price
  - It is assumed that average price is publicaly available
- Firms set price in an adaptative manner depending if they seeting its price above or bellow the average. However, the amount that firms will change price is stochastic
  - Thus, it is a partial and assymetric mechanism. Firms do not change prices and quantities at the same time
  - There is a minimum price that ensure that firms must covers its average cost
- It is assumed that only a fraction ($\gamma$) of capital goods can be replaced
- Firms use the average capital stock in their investment decisions
- Banks grant credit to firms as long as they do not exceed certain leverage ratio
  - Bank estimate individual bankruptcy ratio according to firm's leverage
    - Thus, there are different interest rates for different firms in different periods
  - Bank is assumed to be risk-neutral
  - Policy rate is similar to the one apply to the risk-free firm (does not go bankrupt)
  - Banks distribute profits to capitalists households
- The stock of High Powered Money is constant over time

** Purpose

To evaluate what are the consequences of the interaction between capital goods and credit grating in a small-scale [[id:9789613e-f409-4593-b958-a2c9c8283bb6][Agent Based Models]].
The reason for this step foward is to add realism to the [[id:88dc308c-ddfb-4216-9587-0085cd197621][CATS ABM family]].

** Contribution

This model adds a stylized supply chain (upstream-downstream dynamics (INSERIR ID)) by including capital- and consumption-goods firms in the [[id:88dc308c-ddfb-4216-9587-0085cd197621][CATS ABM family]];


** Relevance

This paper is one of the main references for [[id:88dc308c-ddfb-4216-9587-0085cd197621][CATS ABM family]] which have a capital and credit market.
This could be consider a representative sample of this framework, providing a [[id:434076e6-3bce-497b-ade1-7f8e3fde763e][Canonical Models]].

** Methodology

The authors present an simulated [[id:9789613e-f409-4593-b958-a2c9c8283bb6][Agent Based Models]] composed by workers and capitalists households, consumption- and capital-goods firms, and a bank.


** Results

- The intersection between Capital and Credit markets with adaptative behavior is the main determinant of GDP volatility and implies endogenous [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]] with [[id:67c15aaa-7b6e-4407-b2de-71570ce061f5][Financial Crises]]
  - And this result is an emergent property that occur in all simulations
  - Close to the collapse, there is an increase of debt and riskness of consumption-goods firms, be denied to recieve credit; reducing production and investment
- Long-run GDP gravitates towards full-employment
- Consumption is less volatile than GDP which is less volatile than investment
- All macroeconomic variables are coincident with GDP
- When economy moves toward full-employment, capital goods price are pushed up (since production cannot meet demand since there is labor restriction)
- The authors states that the microeconomic adaptative-behavior is the main determinant of correlations among macroeconomic variables
  - However, this adaptative behavior must occur together with the capital and credit market in order to replicate the reported stylized facts
  - They argue that this heuristic create [[id:0fb81bfc-4e95-4099-8568-c55b704d6165][Externalities]] which allows the emergence of the reported results


** Interesting findings and not categorized stuff




** Critics


- It is unclear at are the economic driver of the model
- As the authors themselves notice, the sorting mechanism imply a no branding fidelity
- The hypothesis regarding firms sorting according to its price and households consumption function implies a defined negative demand curve for goods. There is no such evidence of such restrict hypothesis (see [[id:669465fc-f4fb-4569-ae8c-6ff779c6b05c][IEE859 - Teoria do valor e preços (Prof. Franklin Serrano)]])
- Since High Powered Money is constant and exogenous, this seems to be the main reason of emergence of [[id:67c15aaa-7b6e-4407-b2de-71570ce061f5][Financial Crises]]
  - A more adequate alternative must have endogenous money supply
  - Thus, firms expansions reaches a financial ceiling so money flows from one agent to another, leaving the first credit constrained
- It seems unreasonable to assume that firms change prices in a stochastic manner
  - However, when innovation is endogenous, stochastic and affects labor cost (as in [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]]), prices become stochastic as well



** Abstract

#+BEGIN_ABSTRACT
In this paper we present and discuss a Macroeconomic Agent-Based Model with Capital and Credit (CC-MABM) which builds upon the framework put forward by Delli Gatti et al. (2011). The novelty of this model with respect to the previous framework consists in the introduction of a stylized supply chain where upstream firms --- i.e. producers of capital goods (K-firms) --- supply a durable and sticky input (capital) to the downstream firms, who produce consumption goods (C-firms) to be sold to households. Both C-firms and K-firms resort to bank loans to satisfy their financing needs. There are two-way feedbacks between firms and markets which yield interesting emerging properties at the macro level. We show that the interaction of upstream and downstream firms and the evolution of their financial conditions --- in a nutshell: Capital and Credit --- are essential ingredients of a ``crisis'' i.e. a sizable slump followed by a long recovery.
#+END_ABSTRACT


* Specific notes


** Firms' investment function

Firms consider the average capital stock ($\bar K$) in their decision making:

#+BEGIN_latex
\begin{equation}
\bar{K}_{i,t-1} = \nu \bar{K}_{i,t-2} + (1- \nu)\omega_{i,t-1}\bar{K}_{i,t-1}
\end{equation}
#+END_latex
in which $\nu$ is a positive and smaller than one parameter and $\omega$ is the capacity utilization ratio.
In this case, the history of capacity utilization ratio will influence the purchase of capital goods in the future.

Considering both expansion and replacement investment, planned total investment is defined as:
#+BEGIN_latex
\begin{equation}
I_{i,t} = \left(\frac{1}{\bar{\omega}} + \frac{\delta}{\gamma}\right\bar{K}_{i,t-1} - K_{i,t}
\end{equation}
#+END_latex
in which $\bar \omega$ is the desired long-run capacity utilization rate, $\delta$ is the depreciation ratio, and $\gamma$ is the replacement ratio.
Thus, firms mus decide how much to invest and the desired capacity utilization ratio.

Iterating, the current capital stock will be:
#+BEGIN_latex
\begin{equation}
K_{i,t} = (1 - \delta\omega_{i,t-1})K_{i,t-1} + I_{i,t-1}
\end{equation}
#+END_latex

According to [cite/t:@assenza_2015_Emergent p~. 12], when the available capital stock is greater than the desired level, firms can apply the desired capacity utilization level to all the capital stock.
If there is insufficient capital stock, firms utilize them at full capacity.

As [cite/t:@dawid_2018_Chapter p. 117] points out, there is any foward-looking behavior in this investment function.
Firms consider past capital stock in a non-myopic manner.
Differently from other [[id:9789613e-f409-4593-b958-a2c9c8283bb6][Agent Based Models]], this model have a long run planning (in terms that not only consider near-future market fluctuation) since consider past information.
In summary, this investment specification is based on long run estimates of capital requirements [cite:@dawid_2018_Chapter p. 137].
The [[id:ed384551-c7ba-492f-be69-15906157ef9d][Sraffian suppermultiplier growth model]], on the other hand, imply a foward-looking behavior in order to adapt current production to expectations of final demand.

* Additional Backlinks

[[id:2645660a-bff8-4f35-8bb9-c4de28e46ddd][Investment determination]]

* References

#+print_bibliography:
