:PROPERTIES:
:ID:       afc761fd-1fd0-4a52-9c6d-5aaaf100982e
:END:
#+TITLE:  (2018, ): Varieties of capitalism and growth regimes: the role of income distribution
#+OPTIONS: toc:nil num:nil
Time-stamp: 2021-02-19
- tags :: Functional income distribution,growth models,personal income distribution,varieties of capitalism,wage coordination

* Backlinks

[[id:91af4a64-81b2-42dc-a3bc-07a91329a989][Varieties of Capitalisms]]

* FISH-5SS
|---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <40>                                        | <60>                                                                                                                                                                                                                                                                                                       |
| *Background*                                  | Increasing interest in the consequences of inequality after the GFC.                                                                                                                                                                                                                                       |
| *Supporting Ideas*                            | Increasing inequality leads to more instability. VoC literature argues that CME countries tend to have low inequality and surpluses in current account.                                                                                                                                                    |
| *Purpose*                                     | Evaluate the macroeconomic implications of income distribution to stability thoought the lenses of CPE.                                                                                                                                                                                                    |
| *Originality/value (Contribution)*            | Put together the "growth side" in VoC and "personal income distribution description side" in neo-Kaleckian model. In other words, the authors try to unify the strengths of each approach. They also put together and analysis of functional and personal income distribution.                             |
| *Relevance*                                   | For dissertation, the relevance of this paer is to show the recent conclusion of macroeconomic VoC literature (citation only).                                                                                                                                                                             |
| *Design/methodology/approach*                 | Estimate macroeconomic panel for current account against personal and functional distribution with some standard controls.                                                                                                                                                                                 |
| *Sample*                                      | 18 industrialized economies (1981-2007)                                                                                                                                                                                                                                                                    |
| *Results*                                     | Mains results: rise in top 1% inequality $\Rightarrow$ lower current account; fall in wage share $\Rightarrow$ higher current account.  The authors relate the result with cascade consumption discussion. Other result: the coordination of wage bargain has a limited effect in current account balance. |
| *(Interesting) Findings*                      | The authors states that they confirm VoC divergence tendency due to comparative institutional advantages.                                                                                                                                                                                                  |
| *Research limitations/implications (Critics)* |                                                                                                                                                                                                                                                                                                            |
| *Uncategorized stuff*                         |                                                                                                                                                                                                                                                                                                            |
| *5SS*                                         |                                                                                                                                                                                                                                                                                                            |
|---------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

* Specifics comments
 :PROPERTIES:
 :Custom_ID: behringer_2018_Varieties
 :AUTHOR: Behringer, J., & van Treeck, T.
 :JOURNAL: IMK Working Paper
 :YEAR: 2018
 :DOI:
 :URL: https://ideas.repec.org/p/imk/wpaper/194-2018.html
 :END:

* Extracted Annotations (19/02/2021 15:21:09)
:PROPERTIES:
:NOTER_DOCUMENT: ../PDFs/behringer_treeck_2018_varieties_of.pdf
 :END:

"analyse the macroeconomic implications of changes in income distribution" (Behringer and Treeck 2018:1)

Purpose of the paper (note on p.1)




"relative importance of wage coordination and income distribution in explaining the emergence of global imbalances" (Behringer and Treeck 2018:1)

Mechanism: how income distribution and wage coordenation leads to global imbalances. (note on p.1)




"Wage coordination affected current account balances both directly and, more importantly, indirectly through its effects on income distribution." (Behringer and Treeck 2018:1)

Wage coordination affect both CME and LME and had an indirect effect through income distribution. (note on p.1)




"sample of 18 industrialized countries over the period 1981-2007." (Behringer and Treeck 2018:1)

Sample (note on p.1)




"coordinated market economies (CMEs) such as Germany or Japan tend to combine lower income inequality and current account surpluses, whereas liberal market economies (LMEs) such as the United States or the United Kingdom typically produce higher income inequality and current account deficits (e.g. Hall and Gingerich, 2009; Hall, 2014; Hope and Soskice, 2016)" (Behringer and Treeck 2018:3)

CME and LME an its relation to inequality and current account results. (note on p.3)




"However, according to the VoC perspective, shifts in income distribution typically are not seen as being causally linked to aggregate demand and the current account. Rather, the more coordinated wage bargaining institutions in CMEs essentially explain both why the wage structure is more compressed and income inequality is lower in CMEs" (Behringer and Treeck 2018:3)

VoC do not stablish a prominent role to income distribution. CME particularities, for instance, explain why inequality is lower and it does not have an direct impact on aggregate demand. (note on p.3)




"The latter, rather than income distribution, explain why CMEs tend to run current account surpluses, whereas LMEs tend to rely much more heavily on domestic demand (see Iversen and Soskice, 2010)" (Behringer and Treeck 2018:3)

This characteristics, therefore, implies conservative policy making, generating higher currente account surpluses. (note on p.3)




"Baccaro and Pontusson (2016) argue that the decrease of the wage share and the rise in income inequality observed in most advanced economies since the early 1980s could prima facie be expected to reduce consumption and aggregate demand and hence economic growth." (Behringer and Treeck 2018:4)

One of Baccaro and Pontusson (2016) conclusion. (note on p.4)




"However, Baccaro and Pontusson (2016) oer no theoretical explanation of why dierent growth models have developed in particular countries." (Behringer and Treeck 2018:4)

Baccaro and Pontusson limitation according to the authors: they do not explain why some countries developt each growth regime. (note on p.4)




"Moreover, we argue that the "growth model perspective" proposed by Baccaro and Pontusson (2016), like most of the neo-Kaleckian literature, fails to clearly distinguish between the potential macroeconomic implications of the functional distribution of income (wages versus profits) on the one hand, and the personal distribution of income (top-end income inequality in particular) on the other hand" (Behringer and Treeck 2018:4)

Limitation of neo-Kaleckian models according to the authors: fail to clirify the distinction between the macroeconomic implications of personal and functional income distribution. (note on p.4)




"While the VoC literature predicts that CMEs produce lower wage dispersion and lower personal income inequality than LMEs, it has no explicit theories about the determinants of functional income distribution and about the implications of income distribution (personal and functional) for aggregate demand and external imbalances." (Behringer and Treeck 2018:4)

VoC, on the otherside, is abble to discribe the differences between personal income distribution, but do not have an explanition for its macroeconomic implications to growth. (note on p.4)




"We ask, firstly, how are these dierences in income distribution related to the emergence, since the 1980s, of dierent growth models that have been characterised by current account surpluses in CMEs and current account deficits in LMEs (see Figure 1)? And secondly, what has been the role of dierences in the coordination of wage bargaining across countries and over time in bringing about the dierent growth models by impacting either directly on the current account balance or indirectly on the distribution of income?" (Behringer and Treeck 2018:5)

Questions to be addressed in this paper. (note on p.5)




"We contribute to answering these questions using a macro panel of 18 industrialized countries over the period 1981-2007. In particular, we estimate current account regressions in which measures of personal and functional income distribution as well as of wage coordination are included alongside a number of standard control variables" (Behringer and Treeck 2018:5)

Method. (note on p.5)




"We find that a rise in top-end inequality (relative to trading partners) leads to a lower current account, ceteris paribus. By contrast, a fall in the wage share is associated with a higher current account, ceteris paribus." (Behringer and Treeck 2018:5)

Mains results: rise in top 1% inequality -> lower current account; fall in wage share -> higher current account. (note on p.5)




"While dierent theoretical explanations of our results are possible, we argue that the finding of a negative eect of top-end income inequality on household saving and the current account is broadly consistent with theories of consumption grounded in the notion of upward-looking status comparisons, in the tradition of the relative income hypothesis (Duesenberry, 1949; Frank, 2005)." (Behringer and Treeck 2018:5)

The authors relate the result with cascate consumption discussion. (note on p.5)




"In CMEs, by contrast, relative income eects on consumption owing to upward-looking status comparison were less pronounced because top household incomes increased far less, workers with specific skills have a higher demand for precautionary saving, credit markets are more regulated, and important positional goods are provided through government funding." (Behringer and Treeck 2018:5)

This relative consumption effect is less strong in CME countries. (note on p.5)




"Our current account regressions also suggest that the coordination of wage bargaining has only a limited direct eect on the current account balance" (Behringer and Treeck 2018:6)

"Borrowing from the extensive VoC literature on wage coordination (e.g. Iversen and Soskice, 2010; Iversen and Soskice, 2012), we argue that in countries with a higher degree of wage coordination, trade unions in the face of weakening bargaining power accepted aggregate wage restraint leading to a strong fall in the wage share but managed to prevent a strong rise in top-end wage and income inequality." (Behringer and Treeck 2018:6)

The authors share a conclusion with VoC literature: higher wage coordinantion in face of weaking bargianin -> accepted wage restraint -> wage share fall with strong rise in income inequality. (note on p.6)




"e institutional capacities of wage coordination have largely persisted in a number of major CMEs and hence unions have retained a larger influence on corporate decisions, including those related to top executive compensation." (Behringer and Treeck 2018:6)

Implications for CME (note on p.6)




"Next, we discuss the possible implications of dierent patterns of income distribution for national growth models and current account balances" (Behringer and Treeck 2018:9)

Objective of this section is out of scope of dissertation discussion. (note on p.9)




"According to our estimations, the eect of wage coordination on the current account is at least partly an indirect one. Dierences in the degree of wage coordination may be linked to dierent patterns of income distribution in dierent countries." (Behringer and Treeck 2018:16)

Wage coordenation has a weak direct effect on CC balance. (note on p.16)




"have been highlighted more prominently than previously" (Behringer and Treeck 2018:18)

"In this strand of the literature, there is a strong emphasis on skill-biased technological change as the main cause of rising personal income inequality, with trade and financial globalization being regarded as additional explanatory factors (e.g. Jaumotte et al., 2013). In recent works, the role of trade unions, labor market, tax policies and financial deregulation in aecting inequality have been highlighted more prominently than previously (Dabla-Norris et al., 2015; Jaumotte and Osorio-Buitron, 2015)." (Behringer and Treeck 2018:18)

Personal income distribution determinants in orthodox models. (note on p.18)




"The CPE and the economic sociology literature have laid a stronger focus on the political and institutional determinants of income distribution. As noted above, the CPE literature has been mainly preoccupied with the personal distribution of income. For a long time, a widely accepted notion emanating from the CPE literature was that trade unionism and centralized wage bargaining have an equalizing eect on earnings dispersion and income inequality (e.g. Wallerstein, 1999; Pontusson et al., 2002; Koeniger et al., 2007; Pontusson, 2013 for an overview)." (Behringer and Treeck 2018:18)

Personal income determinants according to CPE. (note on p.18)




"Only a few studies have looked at the functional distribution of income with a focus on political and institutional factors." (Behringer and Treeck 2018:18)

Besides the relevance of institutions in determining *personal* income distribution, fewer scholars have studied *functional* income distribution in this terms. (note on p.18)




"We are not aware of any studies that have analyzed the determinants of the functional and the personal distribution in conjunction with each other for the same country sample and time period." (Behringer and Treeck 2018:19)

Paper relevance: functional and personal income distribuition togther. (note on p.19)
