:PROPERTIES:
:ID:       e5243b8b-40cf-4ee4-b284-3815a7b08892
:ROAM_REFS: @bordalo_2018_Diagnostic
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Bordalo, Gennaioli, Shleifer: Diagnostic Expectations and Credit Cycles - (2018, J. Finance)
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: J. Finance
#+FILETAGS: [A],Ch DotCom,Credit Cycle,Diagnostic Expectations,Due: Sep/2022,EMPIRICAL,Expectation biases,Heuristics switching,READ,Switching mechamism,TO BASE
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis


** Purpose, Relevance, and Contribution


** Methodology


** Results


** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
We present a model of credit cycles arising from diagnostic expectations—a belief formation mechanism based on Kahneman and Tversky’s representativeness heuristic. Diagnostic expectations overweight future outcomes that become more likely in light of incoming data. The expectations formation rule is forward looking and depends on the underlying stochastic process, and thus is immune to the Lucas critique. Diagnostic expectations reconcile extrapolation and neglect of risk in a unified framework. In our model, credit spreads are excessively volatile, overreact to news, and are subject to predictable reversals. These dynamics can account for several features of credit cycles and macroeconomic volatility.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

* Additional Backlinks

* References



#+print_bibliography:
