:PROPERTIES:
:ID:       d970d888-2db0-4513-8b2f-400da087a22a
:ROAM_REFS: @brown_2009_Financing
:END:
#+title: Brown, Fazzari, Petersen: Financing Innovation and Growth: Cash Flow, External Equity, and the 1990s R&D Boom - (2009, J. Finance)
#+options: num:nil ^:{} toc:nil
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: J. Finance
#+FILETAGS: [A],Ch DotCom,Dot Com crisis,Due: Sep/2022,EMPIRICAL,Innovative Bubble,READ
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS

Young firms are more susceptible to financing than mature firms.
In addition, they are responsible for most of the R&D boom ([[id:8d3c092d-8546-4dc0-8a04-55d3d8a09191][Dot-Com crisis]]) in the 1990s.
Thus, financing is a key channel in explaining R&D.

** Background and motivation


** Supporting Ideas and hypothesis


** Purpose, Relevance, and Contribution


** Methodology


** Results


** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
The financing of R&D provides a potentially important channel to link finance and economic growth, but there is no direct evidence that financial effects are large enough to impact aggregate R&D. U.S. firms finance R&D from volatile sources: cash flow and stock issues. We estimate dynamic R&D models for high-tech firms and find significant effects of cash flow and external equity for young, but not mature, firms. The financial coefficients for young firms are large enough that finance supply shifts can explain most of the dramatic 1990s R&D boom, which implies a significant connection between finance, innovation, and growth.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

* Additional Backlinks

* References



#+print_bibliography:
