:PROPERTIES:
:ID:       9452fbde-b270-4d25-8160-bbc29de9fb1a
:ROAM_REFS: @caballero_1999_Aggregateb
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Caballero: Aggregate Investment - (1999, )
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories:
#+FILETAGS: [C],Cannonical reference,Ch DotCom,DUE: Ago/2022,Investment determinants,SKIM,Stylized Facts
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis


** Purpose, Relevance, and Contribution


** Methodology


** Results


** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
The 1990s have witnessed a revival in economists’ interest and hope of explaining aggregate and microeconomic investment behavior. New theories, better econometric procedures, and more detailed panel data sets are behind this movement. Much of the progress has occurred at the level of microeconomic theories and evidence; however, progress in aggregation and general equilibrium aspects of the investment problem also has been significant. The concept of sunk costs is at the center of modern theories. The implications of these costs for investment go well beyond the neoclassical response to the irreversible-technological friction they represent, for they can also lead to first-order inefficiencies when interacting with informational and contractual problems.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

* Additional Backlinks

* References



#+print_bibliography:
