:PROPERTIES:
:ID:       06c10cb7-6884-4fd7-acf9-86f4105a3ecd
:ROAM_REFS: @dosi__Complexity
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Dosi, Pereira, Roventini, Virgillito: A Complexity View on the Future of Work. Meta-modelling Exploration of the Multi-Sector K+S Agent Based Model. - (    , )
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories:
#+FILETAGS:
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS

This model enhance the [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]] by including product innovation and possibility of new sectors.
As a general conclusion of the meta-model analysis, Gini index is the most sensitive metric, related to firms entry-exit and the [[id:ea87d10c-b233-440a-a314-c0388969c422][Replicator Dynamic]].
Unemployment, on the other hand, depends more on firms performance rather than technological change as the [[id:e9ace35a-b26b-4696-aeb2-cfe2683efd54][Technological Unemployment]] hypothesis suggests.

** Background and motivation

This paper is motivated by the debate of the future of Work associated with [[id:e9ace35a-b26b-4696-aeb2-cfe2683efd54][Technological Unemployment]].
The main objective is to evaluate the duality of technological change: efficiency increasing (increasing unemployment) and job creating activity (decreasing unemployment)

** Supporting Ideas and hypothesis

- According to the authors, the main source of change in economics are associated with technological and organizational innovations; conflicts over distribution; hierarquies and definition of properties; competition (due to firms entry and exit); and Knowledge accumulation.


- Consumption goods firms choose the capital goods supplier according to the machine price and productive.
  - The have access to the information of a subset of the market.
- As usual in the [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]], market share evolves according to an [[id:ea87d10c-b233-440a-a314-c0388969c422][Replicator Dynamic]].
- Each consumption good firm produces a single category of product (basic or luxury)
- Consumption goods have the following attributes: category, price, quality, newness, and complexity
- The probability of luxury goods to enter into the market depends on [[id:8651d790-2079-4233-b8ba-a01e1ada53e8][Technological revolution]]; while basic goods are random
  - The number of entering firms depends on the sector-wide liquidty conditions
- Government and central bank does not employ workers
  - This hypothesis is also true for the [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]] chapter
- There is no credit for workers. They decide how much to spend in basic goods, and the remaining in luxury ones.
  - One of the reasons is that they are not divisible (the same could be applied to houses, for example)
  - In order to acquire a luxury good,
    - Pass minimum period since last purchase
    - Have enough funds, otherwise it will be saved for later use.
- More sophisticated products require more labour force
  - Workers' skills are firm-specific and not industry-specific. So, whenever a worker quit his job, the skill procedure restarts.

** Purpose, Relevance, and Contribution

Considering the [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]] chapter, this paper is relevant to discuss the model [[id:9b4c1c41-c7b2-4c08-8bfd-712dd798dffd][Sensitivity Analysis]] and how to perform a meta-analysis. In addition, it provides some suggestion on how to present the model results.
Regarding the [[id:63b1aea6-c7ca-4d77-8896-b170a907a2ef][Housing Agent Based Model]] chapter, this paper provides some interesting hypothesis about government behavioral equations, such as minimal wage imposition. The same applier to labor market.

In addition to incremental innovation as in the Canonical [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]] model, there is also [[id:8651d790-2079-4233-b8ba-a01e1ada53e8][Technological revolution]] (radical innovation), creating a new technological paradigm.
This model also includes the possibility of the emergence of new sectors.

** Methodology

[[id:9b4c1c41-c7b2-4c08-8bfd-712dd798dffd][Sensitivity Analysis]] and [[id:53311f03-840f-4f1b-ab8b-30093246726f][Agent Based Validation]] using [[id:9789613e-f409-4593-b958-a2c9c8283bb6][Agent Based Models]]

** Results


- Gini index is the most sensitive metric, while hiring rate is the least one
  - This could be related to the hypothesis associated with luxury goods entry
  - Considering the Gini index and the unemployment rate, the replicator parameters are important. Most of the inputs have an additive behavior.
- The labor market is highly sensible to parameter of the capital goods sector, eventhought this sector does not employ most of the workers. The Capital threshold and the relative capital productivity are the most relevant in the block. The other relevant variables are the subset of job applications and the desired inventories ratio.
  - Regarding the [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]], this paper also shows the relevance of inventories ratio to model stability
- The determinants of industrial concentration are more sector-specific.
- The most important result is that unemployment is more related to firms performance, survival and growth patterns than technological variables.

** Interesting findings and not categorized stuff

- This paper also indicates the advances of NOHL compared to [[id:ee46629c-a9ef-43d8-aa89-cc78bf3a6b69][Monte Carlo Simulations]]. The former requires smaller samples
  - This paper also describe how to perform a meta-model analysis:
    - Construct an appropriate DoE (NOHL)
    - Choose among Kriging meta-model specifications
    - Global [[id:9b4c1c41-c7b2-4c08-8bfd-712dd798dffd][Sensitivity Analysis]]
    - Response surface
  - A [[id:9b4c1c41-c7b2-4c08-8bfd-712dd798dffd][Sensitivity Analysis]] on the sample of the NOHL DoE is enough to analyze the global model.
  - The advantages of s SOBOL decomposition is that is a global approach (evaluate the whole parametric space) and reports the direct and indirect effect of an input. The indirect effect captures the interaction with all the others parameters.

** Critics

- There are asymmetries regarding the type of firm (luxury or basic) that will enter into the market. Since luxury goods firms enter more frequently with [[id:8651d790-2079-4233-b8ba-a01e1ada53e8][Technological revolution]], this could underestimate the effect of [[id:e9ace35a-b26b-4696-aeb2-cfe2683efd54][Technological Unemployment]].
  - This hypothesis is not tested in the meta-analysis
  - It is unclear if the number of firms is fixed
- The absence of credit to workers implies some awkward hypothesis. For instance, if workers do not have enough funds to buy luxury goods, they will fiercely save the amount to next period.

** Abstract

#+BEGIN_ABSTRACT
When complexity meets economics, complexity economics turns out to be something more than simple interactions across individuals/entities, it turns into what has been labelled the bicycle postulate made of two components, coordination and change. Granted the “Complex evolving system approach”, we provide an example of the effectiveness of the complexity view in economics applied to the context of the current debate on the future of work drawing upon the agent-based “Schumpeter meeting Keynes” multi-sector model (Dosi et al., 2022) and the meta-modelling approach developed in Dosi et al. (2018). The complexity approach proves to be an alternative, useful lens to address the technical change vs employment relationship modulated by demand patterns, income distribution, structural change and labour market organizations. It allows to enlarge the scope of investigation beyond production functions of tasks, relative prices of capital vs labour, inputs substitutability, comparative advantages of workers in their skill levels, the latter elements upon which the dominant neoclassical approach on the employment-technology nexus is rooted.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

#+begin_src emacs-lisp :eval no
(while (search-forward "\u00ab" nil t)
    (replace-match "``" nil t))

(replace-string "\u00bb" "''")
#+end_src

``context of the current debate on the future of work» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 1]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=2&annotation=N72UT9TY][pdf]])
{BACKGROUND}

``All approaches and definitions of complexity however tend to converge at least on four characteristics: (i) a complex system is made up of the interactions of single units/agents giving rise to system level properties different from individual properties; (ii) emergence is the collective result of local interactions; (iii) structures and hierarchical orders are widespread and in that they influence the interaction across individual entities and represent propagation and amplification mechanisms; (iv) the system might reach threshold points and limit behaviours that whenever crossed give rise to the birth of a new system configuration.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 2]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=3&annotation=7EVXNWUI][pdf]])
{DEFINITION} Characteristics of complexity.

``Change in economics, the opposite of a notion of an equilibrium point requiring no deviation, occurs for many reasons, but primarily on the one hand because of technological and organizational innovation, and on the other hand because of conflict over distribution of resources, definition of property rights and ultimately attribution of power and hierarchies over the division of labour (Dosi, 2022; Dosi and Virgillito, 2019).» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 2]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=3&annotation=7ZBZUQWW][pdf]])
{DISCUSSION} Reasons of change in economics: technological and organizational innovation; conflicts over distribution, hierarquies and definition of properties.

``the definition and appropriation of market power of some firms/sectors vis-à-vis others. In addition, entry and exit phenomena shape the competition landscape, with some new actors arriving and some others dying. Last, but not least, capitalism cannot be understood without considering processes of accumulation of knowledge and learning under dynamic increasing returns» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 3]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=4&annotation=R842YVJG][pdf]])
{DISCUSSION} Other key elements are competition (due to firms entry and exit) and knowledge accumulation.

([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 4]])
{INCLUDE} Try to specify a similar representation as Figure 1.

``The government levies taxes on firm and bank profits, pays unemployment benefits, imposes a minimum wage, absorbs excess profits and losses from the central bank» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 5]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=6&annotation=FN35E6GR][pdf]])
{IDEAS} Other aspects of the government sector for future chapters [[id:63b1aea6-c7ca-4d77-8896-b170a907a2ef][Housing Agent Based Model]] chapter.

``Innovation is of two types, "incremental" or "radical". Incremental innovation gradually increases existing technologies' productivity both on new machine construction and usage. Radical innovation introduces a new, qualitatively different generation of machines, associated to a new technological paradigm, which is more productive to use but also more expensive to produce» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 5]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=6&annotation=I8DKAHFW][pdf]])
{CONTRIBUTION} In addition to incremental innovation as in the Canonical [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]] model, there is also [[id:8651d790-2079-4233-b8ba-a01e1ada53e8][Technological revolution]] (radical innovation), creating a new technological paradigm.

``Firms choose the capital-good supplier comparing the price and the productivity of the machines they are aware of.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 5]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=6&annotation=4BTMQFUH][pdf]])
{MODEL} Searching mechanism for consumption and capital goods firms relations.

``Market shares evolve according to a replicator dynamics: more competitive firms expand, while firms with relatively lower competitiveness levels shrink, or exit the market.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=RS8RBAIX][pdf]])
{DESCRIPTION} How to state the [[id:ea87d10c-b233-440a-a314-c0388969c422][Replicator Dynamic]].

``Each industry produces goods from a single category.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=BVFKHIGY][pdf]])
{HYPOTHESIS}

``Products from different industries are heterogeneous in five consumer-relevant attributes: category, price, quality, newness and complexity.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=4IG3SALW][pdf]])
{HYPOTHESIS} Consumption goods attributes in the consumer's perspective.

``Conversely, there is a positive probability of a new luxury-good industry entering the economy after the introduction of each new machine generation, due to a successful radical innovation in the capital-good sector. New basic-good industries enter randomly, with probability inversely proportional to the number of incumbent basic industries.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=UBVR8K37][pdf]])
{HYPOTHESIS} There is different hypothesis regarding the type of consumption goods firms that will enter. Luxury producers probability increases in line with radical innovation, basic goods are random.

``When the industrial liquidity-to-debt ratio is growing, firm entry gets easier, and vice versa.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=DGL2J5AH][pdf]])
{HYPOTHESIS} The number of entring firms depends on sector-wise liquidity conditions. It is unclear if the total number of firms is fixed.

``For simplicity, banks, the central bank and the government occupy no workers.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=KFGHV3H4][pdf]])
{HYPOTHESIS/TODO} It would be better to mention in the models that I currently developing that this hypothesis hold as well.

``The aggregate supply of labour is fixed and all workers are available to be hired in any period. When unemployed, workers submit a certain number of job applications to a random subset of firms. Employed workers apply for better positions. Larger firms have a proportionally higher probability of receiving job applications, which are organised in separated, firm-specific application queues. The labour market is also characterized by imperfect information as firms only observe workers' skills and wage requests on their own queues, and workers are aware only of the wage offers they may receive from firms where they applied for a job. Firms, on the grounds of received orders (capital-good sector), of the expected demand (consumption-good sector), and the current labour productivity levels, decide whether to (i) hire new workers, (ii) fire part of the existing ones, or (iii) keep the current labour force.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 6]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=7&annotation=HENADZZN][pdf]])
{DESCRIPTION/FUTURE} Some hypothesis regarding the labour market with heterogenous households.

``Consumer splits the income between basic- and luxury-good budgets, entirely allocating her income to basic goods up to a given threshold, corresponding to the median of income distribution, and the excess, if any, to luxury consumption.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 7]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=8&annotation=6R47BBYN][pdf]])
{HYPOTHESIS} Regarding the consumption decisions, households first decide the amount spent on basic goods and the remaining on luxury.

``Luxury goods, which are not divisible, are acquired whenever three conditions are met: (i) a minimum period from last acquisition passed, (ii) at least one not-recently-bought good is obtainable, and (iii) the available luxury budget (current plus accumulated) is enough to buy at least one unit of the chosen good. If these conditions are not met, the available luxury budget is saved for the next period.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 7]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=8&annotation=4LV3VRRQ][pdf]])
{HYPOTHESIS/FUTURE} Decisions related to the luxury goods aquision. This could be applied, in some extent, to the residential investment decisions as well ([[id:63b1aea6-c7ca-4d77-8896-b170a907a2ef][Housing Agent Based Model]] chapter).

``Workers cannot get credit from banks for consumption.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 7]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=8&annotation=4SMS4SQ8][pdf]])
{HYPOTHESIS} No credit to households.

``The model, building on the labour-augmented K+S according to the strategy of implementation below presented (Figure 3), is meant to analyse the long-term patterns of labour demand under the fundamental duality of technical change between the labour shedding effects of efficiency-enhancing process innovation and the job-creating ones of product innovation.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 9]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=10&annotation=V5X498ZE][pdf]])
{Contribution} Analyze the duality of the effect of technological change on labor.

``warranted by a high pass-through of productivity growth to wage growth, an overall compensation between the dual effect of technical change tends to apply and no episode of deep technological unemployment occurs. Notice, however, that is made possible by the contemporaneous presence of, first, socio-relational conditions which ensure a high elasticity of wages to productivity, and, second, a sustained arrival of new final goods characterized by an increasing complexity and by high income elasticity of demand.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 10]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=11&annotation=GMUFKZBN][pdf]])
{HYPOTHESIS/IMPORTANT} The institutional set up ensure the absence of technological unemployment. The reason for this is that more complex products require more labor force.

``It significantly improves the efficiency of the sampling process in comparison to traditional Monte Carlo approaches, requiring far smaller samples -- and much less (computer) time -- to the proper estimation of meta-model coefficients (Helton et al., 2006, Iooss et al., 2010).» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 11]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=12&annotation=JGX6I9EF][pdf]])
{TECHNICAL} Advantages of NOHL compared to [[id:ee46629c-a9ef-43d8-aa89-cc78bf3a6b69][Monte Carlo Simulations]]. The former requires smaller samples.

``1. NOLH DoE: construct an appropriate design of experiments (DoE) performing efficient sampling via the NOLH approach. 2. Kriging meta-modelling: estimate and choose among alternative Kriging metamodel specifications. 3. Global sensitivity analysis: analyse the meta-model sensitivity to each parameter of the model using Sobol (variance) decomposition. 4. Response surface: graphically map the meta-model response surface (2D and 3D) over the more relevant parameters and identify critical areas.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 13]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=14&annotation=QWMS7RAP][pdf]])
{TECHNICAL} Steps for performing the meta-model analysis.

``λ(x) : Rk → R, a function representing the global trend of the meta-model Y under the general form» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 13]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=14&annotation=HG45V8ZD][pdf]])
{TECHNOCAL} (\lambda(\vec{x})) represents the global trend of the meta-model.

``In Eq. (1), δ(x) : Rk → R models the stochastic process representing the local deviations from the global trend component λ.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 13]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=14&annotation=2TFIQB5H][pdf]])
{TECHNOCAL} The (\delta(x)) is the stochastic deviation of the trend.

``Therefore, the Kriging meta-model requires l + k + 1 coefficients to be estimated over the n observations selected by an appropriate design of experiments (DoE).9 As discussed before, l = 1 or 2 is adopted. k is determined by the number of parameters of the original model. In practical terms, we constrained the experimental domain to ranges of the parameters that are empirically reasonable and respect minimal technical restrictions of the original model.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 14]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=15&annotation=VW7GQ2EY][pdf]])
{TECHNICAL} Requirements for the [[id:6bacf779-d0b5-4e8e-8657-0fc3b3191fa7][Kriging Meta-Model]].

``Building on this assumption, one can propose the global SA analysis of the Kriging meta-model -- as we attempt here -- to evaluate the response of the original model over the entire parametric space, providing measurements of the direct and the interaction effects of each parameter.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 14]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=15&annotation=D3ZAB4NX][pdf]])
{HYPOTHESIS/TECHNICAL} A [[id:9b4c1c41-c7b2-4c08-8bfd-712dd798dffd][Sensitivity Analysis]] on the sample of the NOHL DoE is enough to analyse the global model.

``This method is particularly attractive because it evaluates sensitivity across the whole parametric space -- it is a global approach -- and allows for the independent SA analysis of multiple output models while being able to deal with non-linear and non-additive models (Saltelli and Annoni, 2010)» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 14]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=15&annotation=7A3GWWJQ][pdf]])
{TECHNICAL} The advantages of s SOBOL decomposition is that is a global approach (evaluate the whole parametric space) and reports the direct and indirect effect of an input. The indirect effect captures the interaction with all the others parameters.

``This methodology deals better with non-linear and non-additive interactions than EE.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 15]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=16&annotation=UCCTWLUL][pdf]])
{FINDS} Advantages of SVD over EE.

``This analysis indicates that the Gini index is the most sensitive metric (47/20/8 at 5/2/1% significance) while the hiring rate is the least sensitive (34/6/0 factors at 5/2/1%).13» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 15]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=16&annotation=ADYFI8PC][pdf]])
{RESULTS} Gini is the most sensitive, while firing/hiring the least.

``Notably, the most relevant factors, accounting for more than 50% of the two metrics variance, are ωu (average number of applications sent by an unemployed worker per period), m1 (relative "capital" productivity in the capital-good sector), κmax (maximum threshold to capital expansion of consumptiongood firms), and ι (desired inventories share of consumption-good firms). This result puts light on the relevance of the capital-good (machines) sector dynamics (m1, κmax) on the labour market performance, even if a relatively small share of jobs is directly generated in this sector.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 16]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=17&annotation=5TSJ2J3U][pdf]])
{RESULTS} The labor market is highly sensible to parameter of the capital goods sector, eventought this sector does not employ most of the workers. The Capital threshould and the relativa capital productivity are the most relevant in the block. The other relevant variables are the subset of job applications and the desired inventories ratio.

``In turn, the Gini index and the unemployment rate show the significant importance of the market dynamics, at the inter- (χc) and intra-industry (χ2) levels. The replicator equation parameters χc and χ2 define the intensity of the competition, or how fast a competitive advantage turns into more wallet or market share for an industry or firm, respectively. Most of the factors here present an additive behaviour, that is, the interaction between them is relatively weak.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 16]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=17&annotation=9KRS7ZUG][pdf]])
{RESULTS} Considering the Gini index and the unemployment rate, the replicator parameters are important. Most of the inputs have an additive behaviour.

``Last, the market-concentration indicators present, as expected, more unrelated sets of important factors.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 16]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=17&annotation=KMISXH96][pdf]])
{RESULTS} The determinants of industrial concentration are more sector-specific.

``As in the case of inequality, also unemployment rather than being primarily driven by technological parameters inducing eventual technological unemployment, is by far more affected by market concentration, and in that by industry behaviour. These results highlight the importance of investigating the root causes of unemployment primarily with respect to firm performance, survival and growth patterns, rather than over-emphasizing the role of technological variables. Indeed, workers history is tightly linked with firms history.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 17]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=18&annotation=RSBDGLMP][pdf]])
{RESULT/IMPORTANT} Unemployment is more related to firms performance, survival and growth patterns than technological variables.

``veloped upon the K+S family which includes the arrival of new paradigmatic trajectories (product innovation upstream) adopted by downstream firms populating new emerging sectors.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 18]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=19&annotation=M9I8JVH9][pdf]])
{MODEL} This model enhance the [[id:3ff828b3-ceb5-4a18-8ba8-19b647bad967][Keynes meets Schumpeter family]] by including product innovation and possibility of new sectors.

``The aim is to study the extent to which the erosion in the employment relations coupled with bad versus good alternative specialization strategies impact upon the overall dynamics of labour demand creation/destruction.» ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 23]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=24&annotation=ZLAZZVM9][pdf]])
{OBJECTIVE/CONTRIBUTION}

``The adopted definition of skills implies that the latter are firm-specific rather than industry-specific and accumulate with job tenure. Therefore, whenever workers quit and are hired by a new firm, a new process of firm-level skill acquisition starts. The acquired minimum skill level in the entry period represents an economy-wide minimum floor.'' ([[zotero://select/library/items/AMRCGYTY][Dosi et al., p. 28]]) ([[zotero://open-pdf/library/items/ZRCEMD9A?page=29&annotation=YKWIZEH5][pdf]])
{HYPOTHESIS} Workers' skills are firm-specific and not industry-specific. So, whenever a worker quit his jog, the skill procedure restarts.
* Additional Backlinks

* References



#+print_bibliography:
