:PROPERTIES:
:ID:       8324a647-625d-4968-bc63-cf5209a2f1bf
:END:
#+title: Expectations formation and  Behavior macroeconomics

#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+HUGO_CATEGORIES: "Literature Balance" "Dissertation writings"
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+OPTIONS: num:nil ^:{} toc:nil

* Introduction

This note contains an overview of the literature about [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] formation and some discussion on [[id:053144da-4f34-4a23-97cb-c5af4b600164][Behavioral Finance]].
The idea is to summarize some conclusions to be further utilized in the [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]] chapter.


** Motivation

At the current stage (<2021-12-15 qua>), my motivation is to report whether firms have some sort of [[id:29ce4a60-6429-44ef-a5b2-f48fba192d79][Behavior Bias]] when forming their expectations.
The empirical reason for this is to mimic some pattern during the [[id:8d3c092d-8546-4dc0-8a04-55d3d8a09191][Dot-Com crisis]] in which high-tech firms experienced [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]], leading to an [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] related to the innovation process.


** Log

- Entry initalization :: <2021-12-15 qua>


* Theoretical findings

- Information rigidity and inattention models (ADD BACKLINK) provide theoretical support for agents not be attentive to all information available [cite:@coibion_2018_How]
  - Thus, it is related to [[id:cdc7d683-cbb8-4611-805c-0e058411c9e2][Learning and Heuristics]] literature in which agents do not process all information in a [[id:4002418c-d54c-4355-857b-2dfc2444b779][Complex System]]
  - In other words, agents intentionally limit the number of variables they track
- A [[id:f37ac1bb-3de3-40a8-9224-c713e9b2e2e6][Behavioral extrapolation]] heuristic is the most parsimonious way to estimate expectations [cite:@gennaioli_2016_Expectations]
  - At odds with information rigidity models, its is not reasonable to assume that agents will not be attentive to their past expectations
- [[id:29ce4a60-6429-44ef-a5b2-f48fba192d79][Behavior Bias]] models associate deviations from the [[id:1a84049d-62ce-4f17-a492-cd1a6a74ebe9][Fundamentals]] as a results of a [[id:38ef3b8c-65b7-4dab-aca1-6f94db9f4287][Cognitive restriction]]. Thus, those models assume that agents are [[id:c35474df-becc-4ac3-8370-d381ec5df2ab][Boundedly Rational]]
- Only [cite/t:@demarzo_2007_Technological] investigate the relation between [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] and [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]] even when investments are not profitable
  - They present a General Equilibrium (ADD BACKLINK) in which a Relative Wealth Effect (ADD BACKLINK) make risky investment persistent
    - The main idea is a decreasing function of investors utility whith others wealth increase
    - Since resource are scarce, investors compete for them and wealth concern initiate endogenously
    - Thus, the modeling approach generates positive [[id:c5c9caae-7306-485e-ab15-bc579733407a][Feedback mechanisms]]

* Empirical findings
** Macroeconomic evidence

- [cite/t:@kopp_2018_Determinants]
- [cite/t:@gennaioli_2016_Expectations] report results for aggregate level, but the extrapolate from firm-level data. Thus, this is not precisely a macroeconomic evidence


** Evidence from [[id:d0986877-a46e-4c2b-965a-a7bdf6aa952f][Survey Data]]

Most empirical studies using [[id:d0986877-a46e-4c2b-965a-a7bdf6aa952f][Survey Data]] focus on household and just a few of them analyze firms [cite:@coibion_2018_How;@gennaioli_2016_Expectations].

- [cite/t:@coibion_2018_How] report that firms do not pay much attention to [[id:7bf9c01a-c5aa-4984-a9a0-12dfa1e3e9c7][General price inflation]] as they do to GDP or sectoral inflation
  - Design: Managers response related to New Zeland firms (2013-2016)
  - Firms updates their expectations more frequently when:
    - are in a more dynamic sector
    - there are more "bad news"
    - there are more [[id:4a226c14-c204-4493-b5f9-e06aa06e2954][Uncertanty]], postponing the decisions
    - intend to make a price change
  - The effect of "new information" is not persistent
  - *Off-topic:* Input costs is the main determinant of sectoral inflation
- [cite/t:@koga_2017_Behavioral]analyze how [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] affects investment decions in capacity expansion and R&D
  - Design: Japanese firms from 1989-2015
  - This is one of the few papers that relate [[id:65283fb0-edd5-4472-b9e2-0e32542305b8][Optmism bias]] and [[id:bcc9f9e2-34dc-4e1c-b00f-47d5de24c0a5][Negative bias]] with investment
  - They find that optmism rises R&D while pessimism suppres it
  - They report that firms disagre more on industry demand than GDP
  - [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]] fluctuations affect expectations on the short-run
  - Highly profitable firms are more optmistic while those with liquidity constraints are more pessimist
  - They authors report a non-linear effect during the [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]]. When firms become more optmistic they increase in R&D; when become more pessimist decrease expansion investment
    - *Off-topic:* Similarly, [cite/t:@archibugi_2013_Economic] find that during the upswing, innovation is more related to [[id:4bd0e068-575b-4d0f-bb3e-3a399c6325a5][Creative Accumulation]] than to [[id:8a78794f-08bc-4a01-a176-599aeea1a679][Creative Destruction]] for UK firms
      - Question The [[id:8d3c092d-8546-4dc0-8a04-55d3d8a09191][Dot-Com crisis]] may be more [[id:8a78794f-08bc-4a01-a176-599aeea1a679][Creative Destruction]]?
      - They also find that there is no long-term innovative persistence
  - [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] of future demand is the main determinant of investment plan
- [cite/t:@gennaioli_2016_Expectations] report the high explanatory power of [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] in the [[id:2645660a-bff8-4f35-8bb9-c4de28e46ddd][Investment determination]] and find evidence for a [[id:29ce4a60-6429-44ef-a5b2-f48fba192d79][Behavior Bias]]. Thus, [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] are not just an uninformative noise
  - Design: CFO response fro US firms (2005-2014)
  - Other conventional investment theories do not overcome this result
  - They relate investment plans with future (expected) profitability
  - The results also hold for the aggregate level
    - The extrapolate the firm-level data by weighting each firm by its revenue
  - *Off-topic:*
    - The authors find no evidence for the [[id:a3dc72f3-bb99-4601-b58e-cc12229748f8][Rational Expectations]] hypothesis
    - The authors find weak explanatory power of [[id:4a226c14-c204-4493-b5f9-e06aa06e2954][Uncertanty]] (stock prices as proxy)
    - The authors suggests to revise the [[id:6674acce-800f-489e-9ddc-ea48873dbf6e][Tobin's Q]] theory

** Evidence from the lab

It is important to not that most studies that focus on investors' behavior investigate stock prices movements.
Thus, those models are a generalization of [[id:1a81aea9-3f06-4877-904e-5aa5ea051512][Asset-pricing models]].
In the [[id:053144da-4f34-4a23-97cb-c5af4b600164][Behavioral Finance]] and [[id:c41a871c-bfe1-470b-8c55-35650903af74][Experimental Finance]] literature, [[id:dfe69c29-9425-48b9-bf72-39b6a9ede338][Learn to Optmize Experiments]] seems to focus more on quantities rather than prices (compared to [[id:88bb712d-d234-4e6c-a850-e3a55f5a30be][Learn to Forecast Experiments]]).
However, both of then does not study how those behaviors affects real variables.

- [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] amplifies the effects of Financial Crisis (ADD BACKLINK) [cite:@hommes_2017_Booms]
- Models that propose [[id:d6b88985-00f9-44dd-bcfa-5033fea9e73e][Switching Mechanisms]] generates bubbles depending on the market structure[fn::These results does not depend on the experiment type ([[id:88bb712d-d234-4e6c-a850-e3a55f5a30be][Learn to Forecast Experiments]] or [[id:dfe69c29-9425-48b9-bf72-39b6a9ede338][Learn to Optmize Experiments]]) or to the number of participants.]
  - Positive feedback :: Generates [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]]
  - Negative feedback :: Quickly converges to the [[id:1a84049d-62ce-4f17-a492-cd1a6a74ebe9][Fundamentals]]
- Other relevant aspect of [[id:d6b88985-00f9-44dd-bcfa-5033fea9e73e][Switching Mechanisms]] models is the [[id:e708fe89-4dff-4751-bf6b-78999dad4275][Evolutionary Selection]] in which the expectational rule that performed better tend to become more frequently used
  - [cite/t:@dosi_2020_RATIONAL; @reissl_2021_Heterogeneous] report that the simple heuristic performed better
    - These models have a result compatible with a negative feedback market. However, it is unclear where are the origins of these structure.
- The more [[id:fe80e1b8-d6ef-40ee-bbf3-e85901693248][Chartists]] in the market, more unstable the system becomes
- [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] ends endogenously due to the share of different investors type [cite:@hommes_2017_Booms; @anufriev_2013_Evolutionary; @brock_1997_Rational] or the end of [[id:0ded6f11-7638-483a-b9fb-2e1204b572be][Financial Frictions]] [cite:@scheinkman_2003_Overconfidence;@xiong_2013_Bubbles]
- Long-run forecaster are usually better described by adaptative learning while short-run is better described by trend-extrapolation [cite:@bao_2021_Expectation]
- When facing more complex environments, agents tend to use simpler heuristics [cite:@bao_2021_Expectation]
- Bubbles are more likely when regards assets returns rather than prices [cite:@bao_2021_Expectation]
- There are also suppot for the Information Rigidity Models (ADD BACKLINK) [cite:@bao_2021_Expectation]
- Usually, bubbles are initialized by an exongenous shock in [[id:1a84049d-62ce-4f17-a492-cd1a6a74ebe9][Fundamentals]] (such as the [[id:8d3c092d-8546-4dc0-8a04-55d3d8a09191][Dot-Com crisis]]) and amplified by [[id:aaecf5b0-903e-4cb7-9579-1f67c41a04a8][Fundamentalist]]s.



Among the replicated [[id:8e9dd4a4-0f29-46d1-b8e4-5befe4df94cb][Stylized Facts]] from the financial markets [cite/t:@hommes_2021_Behavioral] points out that [[id:d6b88985-00f9-44dd-bcfa-5033fea9e73e][Switching Mechanisms]] models reproduce:
- Endogenous booms and bursts; bubbles and crashes
- High persistency
- Clustered volatility
- Fat tails
- Rational [[id:11044897-734e-47b1-9abd-b5d2a10cbaf0][Speculation]] is destabilzing [cite:@delong_1990_Positive]

* Modeling approaches


Regarding [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] generating process, there are three main approaches:
1. Generated by some sort of [[id:0ded6f11-7638-483a-b9fb-2e1204b572be][Financial Frictions]] (Information Rigidity, [[id:4dd9747a-0849-49bc-99dc-f226c5605270][Short sales constraints]])
2. Unconventional utility functions (such in [cite/t:@demarzo_2007_Technological])
3. Related to some soft of [[id:38ef3b8c-65b7-4dab-aca1-6f94db9f4287][Cognitive restriction]] or in [[id:cdc7d683-cbb8-4611-805c-0e058411c9e2][Learning and Heuristics]] procedures
   1. This approach focus more on [[id:f8110b7b-dc7d-4b58-8fa5-4c8cae7a290c][Heterogenous Agents]] with a [[id:e708fe89-4dff-4751-bf6b-78999dad4275][Evolutionary Selection]] mechanism[fn::Note: [[id:4dd9747a-0849-49bc-99dc-f226c5605270][Short sales constraints]] also rely on Heterogeneous Expectations (ADD BACKLINK)]

Considering those compatibles with Agent Based Models (ADD BACKLINK), those with Heterogeneous Expectations (ADD BACKLINK) are more adequate.
Among them, there are models that evaluate the share of [[id:aaecf5b0-903e-4cb7-9579-1f67c41a04a8][Fundamentalist]]s and [[id:fe80e1b8-d6ef-40ee-bbf3-e85901693248][Chartists]] [cite:@ge_2017_Endogenous;@hommes_2017_Booms;@lebaron_1999_Time] while other use a [[id:d6b88985-00f9-44dd-bcfa-5033fea9e73e][Switching Mechanisms]] in which agents change the expectational updating rule.
The modeling approach proposed by [cite:@brock_1997_Rational;@anufriev_2013_Evolutionary] are one of the most accepted among [[id:053144da-4f34-4a23-97cb-c5af4b600164][Behavioral Finance]] literature because it replicates some of financial market characteristics and endogenously generates [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]].
In this strand, the emergence of [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] depend on market feedback (see above).

* Balance

- Expectations regarding future demand is one of the main determinants of investment
- Firms' expectations deviates persistently from [[id:1a84049d-62ce-4f17-a492-cd1a6a74ebe9][Fundamentals]] and this finding is robust
  - The literature disagre with the explanations for this result
- Regarding the relation between [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]] and [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]], some authors highlight the relevance of [[id:4dd9747a-0849-49bc-99dc-f226c5605270][Short sales constraints]] [cite:@ofek_2003_DotCom] while other emphasizes the compositions of investors type/expectational rule [cite:@anufriev_2012_Evolutionarya; @brock_1997_Rational] or even the market feedback type [cite:@bao_2019_When]
- Few works relates investment decisions with long-term plans. [cite/t:@pastor_2009_Technological], for instance, connects the investment decions regarding new technologies with the rational choice to wait for implementing it due to [[id:4a226c14-c204-4493-b5f9-e06aa06e2954][Uncertanty]]
- None of the revised studies relates expectational errors with [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]] even thought it is not profitable


** Research questions and some preliminary answers

- Do firms persistently make wrong decisions regarding the real variables? :: There is no paper which answers this specifically. What is known is that firms make mistakes persistently
  - To which variable do they pay more attention? :: Regarding real variables, possibly to those which affects its final demand or its market share
  - Is it reasonable to assume that they will mix sectoral and aggregate signals up? :: According to empirical results, it is not. Firms pay attention to aggregate variables. What may be reasonable is that there are some private information (such as its own productivity level)
    - Do they extrapolate a sectoral growth to the whole economy or the opposite? :: There is no such study, but firms seems to have a extrapolative behavior. The causal relation is not clear
    - Do firms still invest even its market-share is constant or decreasing? :: There is no such study. [cite/t:@demarzo_2007_Technological] propose an unconventional approach in which risky investment are not ruled out. This approach does not seem to take off
  - Is it reasonable to assume that firms have a long-term planning? :: There are some mixed evidence. Some studies report that expectations have short-term effects while other highlight the discontinuity of innovations. Further research is required.
- Do autonomous investment lead the [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]] persistently? :: There is no such paper. Further research is required.
- Does the behavioral component generate [[id:628bc545-800c-4f2b-beb6-6933d381a2ad][Asset bubble]]? :: Yes. [[id:d6b88985-00f9-44dd-bcfa-5033fea9e73e][Switching Mechanisms]] models and [[id:a3b9da87-5fcc-4e91-a3e7-65531ab57ad6][Heterogeneous expectations]] hypothesis support this statement.
- Does autonomous investment have a positive feedback? :: Unclear. The only paper the explicitly deals with this complementarity is [cite/t:@demarzo_2007_Technological]
- How do firms form expectations regarding the others? :: Apparently, the consider others performance when decide to invest, but none of the revised paper confirm this undoubtedly
  - How do they estimate competitors' market-share? and their productivity? :: None of the revised paper discuss this topic


* Future work
** WAIT Search for how firms estimates competitors market-share?

*Who:* New meeting

* References

#+print_bibliography:
