:PROPERTIES:
:ID:       f719e2d4-ad8d-4227-89ee-69043bb59e79
:ROAM_REFS: @guttmann_2017_Financialization
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Guttmann: Financialization Revisited: The Rise and Fall of Finance-Led Capitalism - (2017, Economia e Sociedade)
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: Economia e Sociedade
#+TAGS: Finance-led capitalism,Financialization,Securitization,Shadow banking,US dollar as world money
#+HUGO_TAGS:
#+BIBLIOGRAPHY: ~/Documents/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis


** Purpose


** Contribution


** Relevance


** Methodology


** Results


** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
Abstract Financialization, expressing the growing importance of finance in the modus operandi of our capitalist system, has emerged as a key concept in various heterodox approaches over the last dozen years - be they Post-Keynesians (E. Stockhammer, E. Hein), American Radicals (G. Epstein, G. Krippner), Marxists (J. Bellamy Foster, G. Dumenil) or French R\'egulationists (M. Aglietta, R. Boyer). But until now those various analysts have each looked at this very complex phenomenon from one or the other specific angle. In this article, I am trying to provide a more comprehensive analysis of financialization by tracing its two primary drivers - structural changes making non-financial actors more dependent on debt-financing as well as financial-income sources (``financial centralization'') while also giving increased weight to the financial sector in the economy (``financial concentration''). The complex interaction between financial centralization and financial concentration has yielded a financialized growth dynamic fueling consecutive debt-financed asset bubbles in the center, the United States, that spurs export-led growth in the periphery. Framing this financialized growth dynamic in the R\'egulationist context as a historically conditioned accumulation regime, finance-led capitalism, I analyze its rise (1982 - 2007) in the wake of key changes in finance and its subsequent structural crisis (2007-2012) to provide a more complete approach to the crucial phenomenon of financialization.
#+END_ABSTRACT


* Specific notes


[cite/t:@guttmann_2017_Financialization] argue how some institutional changes in the US economy had boosted the financial sector, including the housing finance system. As consequence, those changes speed up the financial concentration of households, mainly XX.

* Annotations (zotero)

* Additional Backlinks

* References



#+print_bibliography:
