:PROPERTIES:
:ID:       669465fc-f4fb-4569-ae8c-6ff779c6b05c
:END:
#+title: IEE859 - Teoria do valor e preços (Prof. Franklin Serrano)
#+subtitle: Distribuição e Preços Relativos na Abordagem do Excedente
#+DATE: 2º Semestre de 2021
#+LANGUAGE: pt_br
#+OPTIONS: num:nil ^:{} toc:nil
#+SETUPFILE: ../themes/comfy_inline/comfy_inline.theme
#+INCLUDE: ../header.org
#+filetags: :UFRJ:Notas_de_Aula:Demanda_Efetiva:Modelos_de_crescimento_liderados_pela_demanda:Moderna_Abordagem_do_Excedente:SraffianTheory:ModenSurplusApproach:EffectiveDemand:LecturesNotes:
#+PROPERTY:header-args python :results output html :eval never-export :session sraffa :exports both



* Introdução ao curso <2021-09-30 qui>


 [[https://1drv.ms/u/s!AhhdMDsRteCzwEIDFAlWFdb145HV?e=OYUs4m][Pasta curso valor e preços - UFRJ]]

** Retomada da abordagem do excedente


O projeto de pesquisa proposto a partir da retomada da abordagem clássica do excedente proposta por Sraffa e Garegnani trata das relações entre distribuição e preços relativos.

- Para Marx e Sraffa, a definição de "Economia Política Clássica" é uma forma de análise que utiliza a noção de *excedente*.
  - Marx descreve isso em "Teoria da Mais-Valia", escrito antes, mas publicado postumamente
    - O trabalho é a fonte do valor de troca e não do valor de uso
  - Sraffa denominou de "Teoria objetiva do valor"
- O projeto de pesquisa de Sraffa parte da HPE ao mesmo tempo que torna a HPE mais clara


** Complementariedade dos fatores de produção

- Não é razoável supor que existe produtividade marginal. O produto só será produzido quando ambos os fatores serem utilizados
  - Como consequência, o conflito distributivo e determinação do poder de barganha e da estrutura salarial são relevantes
    - _Exemplo:_ Em um trabalho acadêmico dificilmente é possível atribuir quem contribuiu com o que (execução/ideia)
  - *Problema da redução:* Dificuldade de reduzir a uma medida de trabalho homogênea via coeficientes técnicos na teoria da distribuição
    - Seria um equivalente a uma "teoria do capital humana heterodoxa"
    - Maior qualificação da mão-de-obra não é suficiente para gerar os postos de trabalho, mas sim a Demanda Efetiva
      - Permitiria ter prioridade na contratação salarial, mas não ter mais emprego

** Preços e custos de produção

- Tanto na teoria clássica quanto na teoria neoclássica, os preços são iguais aos custos de produção
  - Uma das diferenças é que na teoria neoclássica, os preços refletem escassez dos fatores
  - Isso não é o mesmo que uma reapresentação da contabilidade nacional
  - Outra difrença é importante é em relação à teoria da *distribuição*
  - _Exemplo da metáfora do diamante e da água:_
    - Clássicos: Diamante é mais caro porque os custos de produção são maiores para extraí-lo do que água apesar de ser menos útil
      - Condições técnicas de produção e da distribuição determinam a forma como o excedente é distribuído
      - Quantidades produzidas tem que pagar estes preços de produção.
        Não é relevante os motivos/utilidade para gerar essa demanda
      - Adequa-se a produção à quem tem dinheiro para pagar.
        - Exemplo: Todos podem ter uma demanda (potencial) por bens de luxo, mas somente poucos podem pagar por este bem a preços que tornam essa produção rentável.
    - Neoclássicos: Nada impõe que o diamante não é útil. Além disso, a dotação relativo dos fatores é diferente.
      - Existe um leilão de uma quantidade fixa
  - Em resumo, a teoria dos preços relativos dependem necessariamente da teoria da *distribuição*

* Sraffa antes de 1960 <2021-09-30 qui> e <2021-10-07 qui>
:PROPERTIES:
:ID:       9610fd16-ec5c-472c-9cb0-9c6222156e32
:END:

** Referências

- Piero Sraffa, 1926 “The laws of returns under competitive conditions”, Economic Journal, Economic Journal, December , 1926
- Piero Sraffa, 1931 “D2/4 Lecture Notes on the Advanced Theory of Value, 1928-31”, Trinity College, Cambridge
- Saverio Fratini, 2016 “Sraffa on the Degeneration of the Notion of Cost” Centro Sraffa Working Papers, n. 21, August 2016
- Pierangelo Garegnani, 2005 "On a turning point in Sraffa's theoretical and interpretative position in the late 1920s ," European Journal of the History of Economic Thought, , vol. 12(3), pages 453-492, September.

** Equilíbrio geral e parcial

- Em um modelo de equilíbrio geral, a demanda de um bem depende da demanda dos outros bens também
  - Dominância diagonal :: A demanda de um bem depender principalmente do próprio preço
    - Achava-se que era suficiente supor dominância diagonal para poder existir um equilíbrio *parcial*
    - Atualmente, chama-se de axioma fraco das preferências reveladas (ou algo próximo disso)
    - Supõe-se que não há problemas no equilíbrio geral
  - No entanto, o aumento do preço relativo de um bem não implica necessariamente que o a demanda de outro bem irá aumentar.
    Isso porque é possível que possa afetar o custo de outro bem.
    - Em um modelo de equilíbrio parcial, na teoria neoclássica, há efeito substituição e renda.
      No entanto, em um modelo de equilíbrio *geral* (em que todos os que consomem necessariamente produzem algo), a renda de um agente também depende do que este agente produz.
      - Em equilíbrio geral, o efeito renda pode ter qualquer efeito

** Curva de oferta de longo prazo de concorrência perfeita

Em equilíbrio parcial, Sraffa concluiu que a curva de oferta de longo prazo (em concorrência perfeita) é horizontal e não *positivamente* inclinada.
- O custo é crescente dado um aumento da demanda uma vez que o estoque de capital (no curto prazo) é dado
  - Retorno decrescente
- No longo prazo, o estoque de capital não é mais constante.
  Portanto, os custos são constantes (para um setor individual).
- Para ter como resultado inequívoco que o aumento dos custos de fatores de setor só vai afetá-lo se supor que estes fatores são específicos
- Se houver retornos crescentes (e, por consequência custos decrescentes), haverá monopólio no longo prazo
  - A forma que Marshall superou essa questão é supor que *ao nível da firma* não há retornos de escala
    - Os retornos crescentes são *externos* (externalidades) à firma.
      Quando as empresas, de modo geral, aumentam a produção (por conta da indivisibilidade), haverá retornos crescentes.
      - _Exemplo:_ Quanto mais firmas utilizam um trem, maior será a economia
    - Sraffa afirma que essa alternativa é mais limitada
      - Pode existir economias de escala externas às empresas e ao *setor*
      - _Exemplo:_ Se outros setores usarem o mesmo trem, poderiam ser beneficiadas. Para a solução de Marshall ser válida, precisaria ser externa à firma e *interna* ao setor.
- A curva de longo prazo ser horizontal não implica preços deixarem de refletir escassez relativa
  - O motivo do porque isso ocorre na teoria neoclássica é que a dotação *total* (de equilíbrio geral) é limitada
  - A curva de longo prazo geral da economia é *positivamente* inclinada
- Se, em equilíbrio parcial, a curva de oferta é horizontal no longo prazo, a demanda determina a produção e a oferta determina os custos.
- Para conciliar custos decrescentes para a empresa sem incorrer em monopólio, Sraffa (1926) propõe *concorrência imperfeita* para reabilitar a teoria de equilíbrio parcial

** Equilíbrio parcial e predominância da teoria Marshalliana

- Houve uma certa noção de que o instrumental proposto por Marshall era uma forma neutra de se avaliar mercados isolados
- Sraffa passou a ser mais relevante porque era uma forma de tornar a saída de Marshall mais realista
- Posteriormente, Sraffa (1930) propõe que a teoria Marshalliana deveria ser abandonada
  - Concorrência imperfeita é insuficiente para incluir realismo a essa teoria

** Curva de demanda negativamente inclinada e a curva de demanda quebrada

- A demanda de um bem depende da reação dos concorrentes.
  Se não reagirem a uma redução do preço, será elástica; se reagirem será inelástica em relação à quantidade.
- Uma forma de resolver esse problema poderia ser via teoria dos jogos, mas não consegui-se
  - Isso seria para encontrar em que momento a curva de demanda seria quebrada
- O problema, portanto, não é a curva de demanda de mercado, mas sim a curva de demanda da *firma*
  - A demanda de cada firma depende da reação de cada um dos concorrentes
  - Alguns autores propuseram que poderia existir um cartel colusivo
  - Noção de concorrência neoclássica enquanto dependente do *número de firmas*
    - Não é razoável, no entanto, supor que o número de firmas é fixo
  - Existe um elemento de *indeterminação* na teoria de _organização industrial_ em que a curva de demanda da firma é subjetiva


** Preço limite e renda diferencial
:PROPERTIES:
:ID:       95c70823-73fa-4bcd-90bd-ba0d49d8b0c5
:END:


- A renda (lucro) de determinado agente é dado pelo entrante potencial
- O lucro extra-normal se dá não porque o preço deste produto é elevado, mas sim pelo custos (diferenciais) do produtor inframarginal é mais elevado
- Aumentar os preços induziria aumentar a entrada de concorrentes; mas uma vez definido o preço pelo produtor inframarginal, os lucros do produtor com a técnica dominante será maior
  - Mobilidade de capitais pode significar tanto mais firmas entrarem em determinado setor quanto capacidade de replicar a técnica superior.
  - _Exemplo:_ Demandante de um produto é indiferente se foi produzido com custos maiores ou não, mas toma a decisão em função do preço
    - O preço é alto porque os custos dos rivais é mais elevado e não os custos são elevados porque o preço é mais alto
    - Exemplo de Ricardo sobre renda da terra e preços
    - O que é relevante para determinar a margem de lucro são os custos e não os preços
- Alguns autores, sobretudo Kaleckianos, atribuem que a teoria do valor deixa de ser válida na medida que o capitalisto tornou-se mais desenvolvido (monopolista)

** Rumo a uma teoria objetiva dos preços relativos e custos de produção

- Sraffa percebeu que poderia apresentar os custos de produção a partir de uma medida física, sem precisar utilizar alguma forma subjetiva.
- Parte dessa mudança é a percepção de que o custo pode ser material (matéria-prima, bens salários) e não subjetivo (relacionado a sacrifício)


** Implicações desta discussão para as teorias de crescimento liderados pela demanda

- Não motivos para que --- dada a técnica produtiva relevante --- os retornos da produção não sejam constantes
  - Retornos decrescentes de escala ocorreriam na presença de "regresso técnico" ou que a está sendo usada uma técnica produtiva pouco usual (má especificação dos insumos)
  - Já retornos crescentes são bastante comuns uma vez que
    - Existe indivisibilidade
- Retomada aos clássicos:
  - Definição dos prazos teóricos:
    - Curto prazo é aquele que em que o preço que prevalesce é o de mercado
    - Longo prazo é aquele em que prevalesce o preço normal que refletem os custos de produção
      - Isso também ocorre na teoria neoclássica. Portanto, a diferença se dá principalmente no mercado de fatores e seus custos.
        - No entanto, Sraffa conclui que não existe equilíbrio parcial dos fatores e, portanto, seria necessário lançar mão de um modelo de equilíbrio parcial.
        - Para compreender os determinantes dos custos, é preciso compreender como se dá a distribuição do excedente.
  - Não há como especificar um preço de equilíbrio uma vez que não é possível especificar curvas de oferta e demanda
    - Exemplo de mercados perecíveis e possibilidade de armazenamento
    - Pode existir bolhas
      - Bolhas a partir de bens produzidos (que possuem custos de produção) tendem a estourar uma vez que haverá um excesso de produção


** Resumo

*** Críticas a teoria marshaliana do equilíbrio parcial

- Curva de oferta de longo prazo de concorrência perfeita em equilíbrio parcial é horizontal
- Custos crescentes:
  - Incompatível com equilíbrio parcial e com equilíbrio de longo prazo
  - Preço do fator: Incompatível com equilíbrio papcial
  - Coeficientes técnicos: Incompatível com equilíbrio de longo prazo
- Custos decrescentes:
  - Economias internas à firma, mas externas ao setor: incompatível com concorrência perfeita
  - Economias externa ao mercado: incompatível com equilíbrio parical
- Concorrência imperfeita: problema da curva de demanda da firma negativamente inclinada
  - Forma de conciliar os problemas anteriores com a teoria neoclássica
  - No limite, a teoria neoclássica requeria uma curva de custos constantes.
    Um dos motivos pelo qual Sraffa abandona a teoria marshaliana é tanto a subjetividade dos custos quanto a imposição de determinado comportamento dos custos (constantes).
    - Portanto, neste momento Sraffa rompe com a teoria neoclássica da oferta. Adiante romperá com a demanda.

*** As "primeiras equações" e mudança de interpretação da teoria do valor

**** Dois tipos de teoria do valor
- Ideia de dois tipos de teoria do valor: Trabalho ou utilidade
- Explicação dos preços relativos das mercadorias: equilíbrio parcial, custo de produção e retornos constantes

**** TODO Mudanças ao final de 1927 e as primeiras equações (VER Slides)

- As primeiras equações e o caminho para a produção

*** Degeneração da noção de custo (VER Slides)

- Fisiocratas:
- Valor se torna simétrico: iguala a utilidade (demanda) ao sacrifício (custo)
  - Em função desse caráter subjetivo, rejeita também o equilíbrio geral

**** Importância do princípio da substituição

*** Críticas externas à teoria marginalista em geral (Ver slide)

- Curva de oferta de fatores
  - Desutilidade marginal do trabalho
  - Parcimônia
- Curva de demanda por fatores
  - Depende de suposições sobre as técnicas


* Produção de mercadorias por meio de mercadorias: determinação da taxa de lucro e preços relativos em sistemas de capital circulante <2021-10-07 qui> e <2021-10-14 qui>
:PROPERTIES:
:ID:       8149d38f-b940-4d80-9a13-ebf1cc7fc2cb
:END:

** Sraffa e o livro

*Projeto:* Crítica a abordagem marginalista


** Um livro, dois gráficos


1. Relação inversa entre salário real e taxa de lucro
2. Relação complexa entre preços relativos e taxa de lucro
   1. Na teoria neoclássica, como os preços relativos também dependiam da taxa de lucro, isso gerava inconsistências internas
   2. Dificuldades de mensurar o excedente físico e, assim, calcular a taxa de lucro

** "Autosuficiência" e viabilidade

*** Produção de trigo por meio de trigo


- Economia muito simples que produz um único bem ($X_{1}$) o utiliza como insumo (capital circulante) ($A_{11}$)
  - Capital circulante não é sinônimo de consumo intermediário
    - A diferença é que o capital circulante pode ser usado uma única vez enquanto o capital fixo pode ser reutilizado
- É preciso que exista uma relação técnica ($a_{11}$) tecnicamente viável ($a_{11}<1$). No entanto, esta condição não é suficiente uma vez que é preciso remunerar o trabalho ($b_{1}\cdot l$). Portanto, há uma *condição social*: $a_{11}  + b_{1}\cdot l$
- Excedente mede o produto líquido da economia
  - Preços em Sraffa não garantem reposição uma vez quando se considera investimento líquido
  - Os preços que Sraffa descreve reflete os coeficientes técnicos
  - É o resíduo dos custos aproximados de repor a produção

#+BEGIN_latex
\begin{equation}
A_{11}, L_{1} \to X_{1}
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
a_{11}, l_{1} \to 1
\end{equation}
#+END_latex

Produzirá excedente se

#+BEGIN_latex
\begin{equation}
a_{11} + b_{1}\cdot l_{1} < 1
\end{equation}
#+END_latex
neste caso, será um excedente em trigo ou em trabalho.

Por outro lado, será uma economia de subsistência se
#+BEGIN_latex
\begin{equation}
a_{11} + b_{1}\cdot l_{1} = 1
\end{equation}
#+END_latex


A forma de mensuração do excedente não é o mais relevante, mas sim a representação do sistema econômico.
Dada uma técnica produtiva relevante e uma variável distributiva exógena, é possível indicar a existência do excedente.
O núcleo da teoria do excedente é indicar os elementos em comuns dos autores que partem da noção de excedente.


O excedente é uma condição necessária para:
- Divisão social do trabalho
- Acumulação de capital
  - Excedente permite existência de investimento líquido
  - Excedente é condição necessária, mas não suficiente
- Estratificação social
  - O que muda entre sistemas econômicos é a regra de divisão do excedente

*** Produção a partir de dois insumos e sem excedente

Sabendo os coeficientes técnicos (necessários), é possível obter os preços relativos sem precisar discutir formato de curvas de oferta e demanda.
Para uma economia de subsistência em que o coeficiente $a_{ij}$ já inclui salários (coeficiente aumentado):

#+BEGIN_latex
\begin{equation}
\begin{cases}
a_{11}\cdot p_{1} + a_{12}\cdot p_{2} = p_{1}\\
a_{21}\cdot p_{2} + a_{22}\cdot p_{2} = p_{2}
\end{cases}
\end{equation}
#+END_latex


Supondo que as relações técnicas são dadas, qual o preço relativo?
Por simplificação, é possível supor que um dos preços é unitário:

#+BEGIN_latex
\begin{equation}
p_{1} = 1
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
\frac{p_{2}}{p_{1}} = \frac{a_{12}}{1-a_{22}} = \frac{a_{21}}{1-a_{11}}
\end{equation}
#+END_latex
A implicação é que um setor não é independente do outro.
Por exemplo, supondo que o setor 2 remunera os trabalhadores a um salário mais alto.
Para este setor, pode não haver problemas.
No entanto, para o outro setor os custos de obter o produto produzido pelo setor 2 serão maiores.
O preço relativo precisa ser igual ao necessário para garantir a reprodução do sistema.
Os preços relativos são tal que tudo que o setor 2 não utilizou para a sua própria produção tem que ser suficiente para que o outro setor compre.
Dessa forma, é uma teoria objetiva e material das relações de troca.
Um sistema sem excedente não possui grau de liberdade.


#+BEGIN_latex
\begin{equation}
\frac{p_{2}}{p_{1}} = \frac{\text{Bens setor precisa de outro}}{\text{Excedente fisico deste setor}}
\end{equation}
#+END_latex
Para dois bens, os preços relativos refletem a interdependência física entre os setores.
Para mais de dois bens, esta relação não é tão direta.

** Produção com excedente

Se existir excedente, os preços não refletem apenas relações de troca, mas também distribuí-lo.
Nada garante que o excedente físico de um setor ficará contido nele.
Em um sistema econômico em que o excedente é distribuído via preços relativos, não há nenhuma garantia para onde o excedente irá ser deslocado.
Por exemplo, se o preço relativo do segundo setor for muito mais elevado, este setor irá se apropriar mais do excedente uma vez que os custos dos insumos deste segundo setor para o primeiro setor será maior.

Para a discussão da produtividade, é preciso incluir a discussão dos preços relativos.
Se um setor for mais produtivo em termos físicos, pode levar ao erro se a mensuração da produtividade for via valor adicionado/trabalhador.
Isso porque, se o preço relativo do outro setor for mais elevado, o valor adicionado será maior, mas a produtividade em termos físicos do outro setor é maior.

Para que esta economia continue produzindo todos os bens necessários, a taxa de lucro *precisa* ser uniforme.
Caso contrário e não havendo restrições, somente o bem com maiores taxas de lucro será produzido.


Se a soma vertical dos coeficientes for menor que um, a soma horizontal pode ser distinta de setor a setor.
Alguns setores serão superavitários enquanto outros deficitários (em termos físicos).


*** Relação entre excedente e taxa de lucro




** Produção com mais de um bem básico

*** O modelo

#+BEGIN_SRC python :results none
import sympy as sp
from sympy import pprint, latex, Eq, solve, solveset

def mytex(lhs, rhs):
    """
    lhs: left hand side (symbol)
    rhs: right hand side (expression)
    """
    import sympy as sp
    resul = sp.latex(
        sp.Eq(lhs, rhs),
        mode = 'equation*',
        mul_symbol = 'dot',
        # symbol_names = latex_names
    )
    return sp.pprint(resul)

p1, p2 = sp.symbols('p1, p2', positive = True) # Precos
w, v, V, r, R = sp.symbols('w v V r R', nonnegative = True)

a11, a12 = sp.symbols('a_11 a_12')
a21, a22 = sp.symbols('a_21 a_22')
l1, l2 = sp.symbols('l1 l2')
#+END_SRC


Considerando um modelo com dois bens básicos.
Um deles (bem 2, pão) serão utilizado como bem salário e numerário.
Supõe-se também que a cesta de bens dos trabalhadores é composta somente por este bem-salário.

#+BEGIN_SRC python :results html
a21 = a22 = 0
_w = p2*v
mytex(w, _w)
#+END_SRC

#+RESULTS:
#+begin_export html
\begin{equation*}w = p_{2} \cdot v\end{equation*}
#+end_export

Dadas as hipóteses, segue o conjunto de equações:
#+BEGIN_SRC python
_p1 = p1*a11*(1+r) + w*l1
mytex(p1, _p1)
_p2 = p1*a12*(1+r) + w*l2
mytex(p2, _p2)
mytex(w, _w)
mytex(p2, 1)
#+END_SRC

#+RESULTS:
#+begin_export html
\begin{equation*}p_{1} = a_{11} \cdot p_{1} \cdot \left(r + 1\right) + l_{1} \cdot
w\end{equation*}
\begin{equation*}p_{2} = a_{12} \cdot p_{1} \cdot \left(r + 1\right) + l_{2} \cdot
w\end{equation*}
\begin{equation*}w = p_{2} \cdot v\end{equation*}
\begin{equation*}p_{2} = 1\end{equation*}
#+end_export


*** Solução simultânea

Com isso, é possível escrever o preço do bem 1 como:

#+BEGIN_SRC python
tmp_p1 = solve(_p1 - p1, p1)[0].simplify()
mytex(tmp_p1, _p1)
#+END_SRC

#+RESULTS:
#+begin_export html
\begin{equation*}- \frac{l_{1} \cdot w}{a_{11} \cdot r + a_{11} - 1} = a_{11} \cdot
 p_{1} \cdot \left(r + 1\right) + l_{1} \cdot w\end{equation*}
#+end_export

rearrumando:
#+BEGIN_latex
\begin{equation}
p_{1} = \frac{v\cdot l_{1}}{1 - a_{11}\cdot (1 + r)}
\end{equation}
#+END_latex

nesta equação, utiliza-se trabalho direto ($l_{1}$) e indireto ($a_{11}$)[fn:: O coeficiente $a_{11}$ é o custo estritamente necessário para se produzir o bem $1$ mesmo que o salário seja zero.].
Além disso, um /mark-up/ positivo implica uma taxa de lucro positiva (e vice-versa).


Em um caso em que o salário é zero, a taxa de lucro máxima dessa economia é dada por:
#+BEGIN_latex
\begin{equation}
R_{v=0} = \frac{1 - a_{11}}{a_{11}}
\end{equation}
#+END_latex
Este caso deixa evidente que é dada como o produto líquido ($1 - a_{11}$, o que excede a quantidade estritamente necessária) divido pelo estoque de capital.
Também é possível expressar a produtividade do trabalho (valor adicionado/trabalhador) que, ao mesmo tempo, indica a taxa máxima de salário desta economia:
#+BEGIN_latex
\begin{equation}
V = \frac{1 - a_{11}}{l_{1}}
\end{equation}
#+END_latex

Estes casos indicam as possibilidades distributivas de determinada técnica produtiva.
Se a técnica produtiva mudar, pode aumentar tanto a taxa de lucro máxima quanto a produtividade do trabalho.

Continuando a substituição e deixando em função de $v$:
#+BEGIN_latex
\begin{equation}
v = \frac{1}{\frac{l_{1}a_{12}(1+r)}{1 - a_{11}(1+r)} - l_{2}}
\end{equation}
#+END_latex


*** Implicações


No caso em que a taxa de lucro é zero, os preços relativos refletirão os custos diretos e indiretos de produzir tais mercadorias (dada uma técnica produtiva).
Porém, se a taxa de lucro for positiva, os preços relativos *não* serão proporcionais aos uso de trabalho direto e indireto.
Caso sejam proporcionais, *não* será compatível com uma taxa de lucro uniforme.
A teoria do valor-trabalho não considerava a taxa de lucro como relevante para a determinação dos preços relativos.

**** Exemplo

Suponha um caso em que um produto (1) utiliza apenas trabalho direto e é finalizado em um período enquanto outro (2) utiliza trabalho direto e indireto e leva dois períodos para se concluir:

#+BEGIN_latex
\begin{equation}
\begin{cases}
p_{1} = l_{1}\cdot w\cdot (1+r)\\
p_{2} = l_{2}\cdot a_{2}\cdot w \cdot (1 + r) + l_{2}\cdot b\cdot w (1 + r)
\end{cases}
\end{equation}
#+END_latex

Para Ricardo, por exemplo, os preços relativos seriam:
#+BEGIN_latex
\begin{equation}
\frac{p_{1}}{p_{2}} = \frac{l_{1}}{l_{2}}
\end{equation}
#+END_latex
O problema é que o produtor do primeiro bem (que leva um período por hipótese) terá uma taxa de lucro sempre maior que o segundo.
A consequência é que a produção mais rápida terá uma taxa de retorno maior e o produto que utiliza trabalho indireto não será economicamente viável.

Para ser compatível com uma taxa de lucro uniforme:
#+BEGIN_latex
\begin{equation}
\begin{cases}
p_{1} = l_{1}\cdot w\cdot (1+r)\\
p_{2} = l_{2}\cdot a_{2}\cdot w \cdot (1 + r)^{2} + l_{2}\cdot b\cdot w (1 + r)
\end{cases}
\end{equation}
#+END_latex
Esse exemplo seria equivalente ao caso em que um dos insumo (trabalho indireto) é comprado de outro setor.
A intuição é que o preço de um dos insumo terá a taxa de lucro do produtor imbutido.
Ou seja, os preços relativos não são *independentes* da taxa de lucro.
Por essa razão, os preços de relativos deixam de ser proporcionais ao uso de trabalho direto e indireto.
Sendo assim, quando a taxa de lucro aumenta, o preço não será alterado igualmente entre os setores.

Para Marx, os preços relativos eram distintos do valor-trabalho[fn::A teoria do valor-trabalho propõe que os preços relativos são proporcionais ao uso de trabalho direto e indireto na produção.].
Como solução, aplicava o procedimento da transformação que iniciava estimando a taxa de lucro geral pela mais-valia e depois seguia-se imputando no cálculo dos preços.
Em resumo, Marx --- nem Ricardo e somente Smith para uma economia em estágio primitivo --- não se baseava na teoria do valor-trabalho.

*** De volta aos preços relativos

Por fim, substituindo a expressão para salário real, obtém-se o preço relativo do primeiro bem:

#+BEGIN_latex
\begin{equation}
p_{1} = \frac{\frac{1}{1 - a_{11}(1+r)}}{\frac{l_{1}a_{12}(1+r)}{1 - a_{11}(1+r)} - l_{2}}
\end{equation}
#+END_latex


Portanto, os preços relativos são não dependem da taxa de lucro se esta for zero:
#+BEGIN_latex
\begin{equation}
V_{r=0} = \frac{1}{l_{2} + \left(\frac{l_{1}}{1 - a_{11}}\right)a_{12}}
\end{equation}
#+END_latex
Por outro lado, só haverá taxa de lucro enquanto existir excedente.

** Preços relativos e distribuição de renda


O preço relativo do bem 1 quando a taxa de lucro é zero ($r=0$) é dado por:
#+BEGIN_latex
\begin{equation}
p_{1} = \frac{\frac{l_{1}}{1 - a_{11}}}{l_{2} + \left(\frac{l_{1}}{1 - a_{11}}\right)a_{12}}
\end{equation}
#+END_latex
Neste caso, temos:
#+BEGIN_latex
\begin{equation}
p_{1} = \frac{\text{Trabalho direta e indiretamente para produzir 1}}{\text{Trabalho direta e indiretamente para produzir 2}}
\end{equation}
#+END_latex

Já quando há uma taxa de lucro positiva,
#+BEGIN_latex
\begin{equation}
p_{1} = \frac{l_{1}}{(l_{1}a_{12} - l_{2}a_{11})(1+r) + l_{2}}
\end{equation}
#+END_latex
O preço relativo irá depender da taxa de lucro se
#+BEGIN_latex
\begin{equation}
l_{1}a_{12} \neq l_{2}a_{11}
\end{equation}
#+END_latex
Analisando cada caso,
#+BEGIN_latex
\begin{equation}
\frac{a_{12}}{l_{2}}
\begin{Bmatrix}
>\\=\\<
\end{Bmatrix}
\frac{a_{11}}{l_{1}}
\end{equation}
#+END_latex

A implicação da mudança do preço relativo

** A relação salário-lucros e os preços relativos

** Discussão de Sraffa (1960) (PCMC)
*** Capítulo 1
*** Capítulo 2

- A taxa máxima de lucro do Sraffa é a mesma que a taxa normal de lucro dos clássicos e de Marx

* A explicação monetária da distribuição
:PROPERTIES:
:ID:       9b80fea3-18f7-4b5f-88b9-7905f61cbff3
:END:

* Concorrência e gravitação


* Renda
:PROPERTIES:
:ID:       237ef9ec-3dfc-4814-946a-9f471f29f4cc
:END:

* Produção conjunta e capital fixo em Sraffa
:PROPERTIES:
:ID:       2d5e92fb-82b2-49f4-aea8-425a9ff157d4
:END:

* Fisiocratas & Smith
:PROPERTIES:
:ID:       2e53f53c-53ec-4a68-8e03-a4b752d3de72
:END:

* Ricardo
:PROPERTIES:
:ID:       00f9ac43-0729-4258-8cb0-1876c2cb50a7
:END:

* Mercadoria padrão
:PROPERTIES:
:ID:       8ea0b1ce-b7fc-4fd7-bd7c-93944168301e
:END:

* Marx depois de Sraffa
:PROPERTIES:
:ID:       a37fd324-12f2-4814-a90b-9093034ffa75
:END:
