:PROPERTIES:
:ID:       bde0d696-bb24-42c4-afdd-16a8355fcd91
:ROAM_REFS: @massenot_2018_Can
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Massenot, Pettinicchi: Can Firms See into the Future? Survey Evidence from Germany - (2018, J. Econ. Behav. Organ.)
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: J. Econ. Behav. Organ.
#+FILETAGS: Expectation formation,Firms,Learning,RESULTS
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis

- [[id:f19dc90a-2d72-4b4a-9319-f2ed35ebae47][Inatention Models]] and costly information update literature
  - Forecast errors are costly because it affects firm's profits and inventories

** Purpose and Contribution

- This paper aim to investigate the determinants of firms [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] and the role of [[id:f37ac1bb-3de3-40a8-9224-c713e9b2e2e6][Behavioral extrapolation]]

** Relevance

Considering the [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]] chapter, this paper can provide empirical evidence about how firms forms expectations.
This paper also address the issue of [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]] and [[id:65283fb0-edd5-4472-b9e2-0e32542305b8][Optmism bias]] regarding firms profits.
It is important to note that most literature focus on financial markets.

This paper also highlight the potential amplification effect of [[id:9326692f-7fa9-439b-8f3c-a7fa2d18aef8][Expectations]] on [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]]

** Methodology

- [[id:d0986877-a46e-4c2b-965a-a7bdf6aa952f][Survey Data]] of [[id:1deb2168-629b-4bae-b34c-a74a3ce9c52f][German]] firms of the manufacturing sector regarding its future business condition
- Estimate a forecast error considering the expected - realized values. If it is positive, firms have [[id:65283fb0-edd5-4472-b9e2-0e32542305b8][Optmism bias]]; [[id:bcc9f9e2-34dc-4e1c-b00f-47d5de24c0a5][Negative bias]] otherwise
- Analyze over-extrapolation in [[id:380b31ad-cdd5-4367-af2c-9ee199a085e7][Business Cycles]] peak and troughs in more detail
- Sample: Germany reunification period to access if firms' investment can antecipate reversals


** Results

- Expected and Realized variable move together
- Expectation errors are positively correlated with past experience. Thus, firms have a [[id:f37ac1bb-3de3-40a8-9224-c713e9b2e2e6][Behavioral extrapolation]] mechanism
  - Expectation lags business realization for about six months
- Firms extrapolate more negative values than positive ones
- Firms are optimistic before the downturn and pessimistic before the recovery
- Firms expected that sales and prices move in the same direction; thus, they forecast demand shocks more often than supply shocks
- More than seven centuries (!) to remove [[id:f37ac1bb-3de3-40a8-9224-c713e9b2e2e6][Behavioral extrapolation]] bias
- After a business improvement, firms become more optmistic and this result hold for both individual and aggregate shocks

** Interesting findings and not categorized stuff


** Critics


** Abstract

#+BEGIN_ABSTRACT
This paper presents new evidence on the expectation formation process of firms from a survey of the German manufacturing sector. First, firms become too optimistic after their business has improved, consistent with the over-extrapolation of their experience. Second, firms extrapolate improvements in their business more than deteriorations. Third, firms are more optimistic (pessimistic) than usual during business cycle peaks (troughs), suggesting that they do not anticipate reversals. Fourth, the German reunification provided a positive exogenous shock to the business of West German products. The industries most positively affected by the shock initially over-extrapolated the past downward trend just as much as the less affected industries, and thus failed to anticipate the reversal. Fifth, more overoptimistic firms subsequently report larger inventories and lower profits, suggesting that expectation errors entail (opportunity) costs. Sixth, older and larger firms show a smaller extrapolation bias, indicating that time and resources can alleviate the extrapolation bias. Seventh, firms that expect their business to improve tend to also expect their prices to increase, suggesting that firms mostly try to forecast demand shocks as opposed to supply shocks. Overall, these observations suggest that firms have a limited ability to anticipate changes in their activity and extrapolate their experience too much. © 2017 Elsevier B.V.
#+END_ABSTRACT


* Specific notes


* Additional Backlinks

- [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]]

* References



#+print_bibliography:
