:PROPERTIES:
:ID:       b7e5ba6b-66ba-44f8-9ed7-e8740a93d50d
:END:
#+title: Money, autonomous consumption and residential investment

* Maria Cristina Barbieri Goes (Rome Tre): A Tale of Three Prices: Monetary Policy and Autonomous Consumption in the US

** Questions

- Total final demand should not remove imports
- I would expect that there is a lag between house prices changes and rent changes, do you report this in your estimations?
- The second is an suggestion actually. The USA institutional arrangement provides some incentives to buy a house instead to rent one, so it would say that the rent mechanism on other countries would be stronger compared to USA. It you be interesting to estimate it as well




* Comments

** Mathia
** Alejandro

Hi Gabriel. Great paper! In case you are interested. - The critique of traditional cointegration methods is Elliot (1998), Econometrica. - To see alternatives that have more robust inference, look especially at Muller and Watson (2013). You can also look at 2008, 2015 for complements.
