:PROPERTIES:
:ID:       eabc64e1-d59c-4582-924d-fb12e4efabcc
:ROAM_REFS: @rzeszutek_2021_Managerial
:END:
#+title:
#+OPTIONS: num:nil ^:{} toc:nil
#+TITLE: Rzeszutek, Godin, Szyszka, Augier: Managerial Overconfidence in Capital Structure Decisions and Its Link to Aggregate Demand: An Agent-Based Model Perspective - (2021-08-19, PLOS ONE)
#+hugo_base_dir: ~/BrainDump/
#+hugo_section: notes
#+hugo_categories: "PLOS ONE"
#+FILETAGS: ABM Finance FinancialMarkets Macroeconomics MonetaryPolicy Banking
#+BIBLIOGRAPHY: ~/Org/zotero_refs.bib
#+cite_export: csl apa.csl



* FISH-5SS


** 5SS


** Background and motivation


** Supporting Ideas and hypothesis


** Purpose


** Contribution


** Relevance

For [[id:95265264-f61f-4cf5-8cdc-e590b2a47cb9][Innovation bubble ABM]] chapter, this paper provide some discussion regarding the effects of [[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]].
There is a possible dialogue between their model and mine.
Additionally, it provides some discussion on how to model capital goods sector.

** Methodology


** Results

- Overconfident firms outperform in terms of investment and size, but become more financially fragile

** Interesting findings and not categorized stuff


** Critics

- As the authors point out, there is no innovation

** Abstract

#+BEGIN_ABSTRACT
Objective This study aims to connect two strands of the psychology and economics literature, i.e., behavioural finance and agent-based macroeconomics, to assess the impact of managerial overconfidence at the micro and macro levels of the economy as a whole. Method We build a macroeconomic stock-flow consistent agent-based model that is calibrated for the specific case of Poland to explore whether the overconfidence of top corporate managers in the context of their initial capital structure decisions is detrimental for the firms being managed in this way, the financial market dynamics, and the selected macroeconomic indicators. We model heterogeneous firms with different capital structure decision criteria depending on their degree of managerial overconfidence. Our model also includes a complete macroeconomic closure with aggregated households, capital producers, banking, and a public sector. Results We find that firms with overconfident managers outperform in terms of investment and size but are also more fragile, thereby making them more likely to default. Finally, we run policy shocks and show that while investors’ flight to liquidity creates financial turmoil and increases the probability of default. Conclusions This paper contributes to the knowledge base by linking behavioural corporate finance and agent-based macroeconomics. In general, the excess overconfidence on the micro level, either an increase in the proportion of overconfident firms or a higher degree of overconfidence among managers, has a strong destabilizing impact on the economy as a whole on the macro level.
#+END_ABSTRACT


* Specific notes

* Annotations (zotero)

* Additional Backlinks

[[id:053144da-4f34-4a23-97cb-c5af4b600164][Behavioral Finance]]

[[id:9789613e-f409-4593-b958-a2c9c8283bb6][Agent Based Models]]

[[id:5901b2ed-90d0-4b76-bafd-2e82d26e0388][Overinvestment]]


* References



#+print_bibliography:
