name: Org to readme
on:
  push:
    branches: [ master ]

jobs:
  docit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copy the Readmes
      run: cp "index.org" "README.org"
